Repository crate/crate, pull requests merged in 2018-10, with the labels that each got.

#7714 Fix gradle `run` and `runDebug` tasks.
  app/build.gradle
  devs/docs/basics.rst
Labels: ready-to-merge

#7717 Add the generate_series table function
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/table-functions.rst
  sql/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  sql/src/main/java/io/crate/expression/tablefunctions/TableFunctionModule.java
  sql/src/test/java/io/crate/expression/tablefunctions/GenerateSeriesTest.java
Labels: ready-to-merge

#7720 Throw a sensible error if table function is used in WHERE
  sql/src/main/java/io/crate/analyze/where/WhereClauseValidator.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge

#7722 Handle _fetchId correctly in the ProjectSet operator
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPoints.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/test/groovy/io/crate/integrationtests/TableFunctionITest.groovy
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge

#7727 ci: Increase request timeout for azure pipelines
  azure-pipelines.yml
Labels: ready-to-merge

#7726 Allow mixing aggregations and table functions
  blackbox/docs/general/builtins/table-functions.rst
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPoints.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/test/groovy/io/crate/integrationtests/TableFunctionITest.groovy
  sql/src/test/java/io/crate/execution/dsl/projection/builder/SplitPointsTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#7728 Keep original stacktrace if possible
  sql/src/main/java/io/crate/exceptions/SQLExceptions.java
Labels: ready-to-merge

#7729 Remove TODO about reference nesting and simplify logic
  sql/src/main/java/io/crate/analyze/relations/AbstractTableRelation.java
  sql/src/main/java/io/crate/analyze/relations/DocTableRelation.java
Labels: ready-to-merge

#7666 change to "on conflict do update set"
  blackbox/docs/general/dml.rst
  blackbox/docs/sql/statements/insert.rst
Labels: ready-to-merge

#7730 Allow ANY = on object columns
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/dql/selects.rst
  sql/src/main/java/io/crate/expression/operator/any/AnyOperator.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/expression/operator/any/AnyEqOperatorTest.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#7723 Do not recurse into function arguments on group by semantics validation
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/relations/GroupByScalarAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#7733 ci: Don't run tests in parallel on azure pipelines
  azure-pipelines.yml
Labels: ready-to-merge

#7731 Enforce setting the streamers to retrieve rows from DistributedResultRequest
  sql/src/main/java/io/crate/execution/engine/distribution/DistributedResultRequest.java
  sql/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
  sql/src/test/java/io/crate/execution/engine/distribution/DistributedResultRequestTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
Labels: ready-to-merge

#7736 Amend 3.0.7 notes with notice about changes to CREATE REPOSITORY
  blackbox/docs/appendices/release-notes/3.0.7.rst
Labels: ready-to-merge

#7745 Re-work comparison operators to use composition
  sql/src/main/java/io/crate/expression/operator/CmpOperator.java
  sql/src/main/java/io/crate/expression/operator/EqOperator.java
  sql/src/main/java/io/crate/expression/operator/GtOperator.java
  sql/src/main/java/io/crate/expression/operator/GteOperator.java
  sql/src/main/java/io/crate/expression/operator/LtOperator.java
  sql/src/main/java/io/crate/expression/operator/LteOperator.java
Labels: ready-to-merge

#7746 Replace travis badge with azure pipelines badge in README
  README.rst
Labels: ready-to-merge

#7735 gradle: Update shadow plugin to 2.0.4
  build.gradle
Labels: ready-to-merge

#7739 Move TransportAction bindings in TransportExecutorModule
  sql/src/main/java/io/crate/execution/TransportExecutorModule.java
  sql/src/main/java/io/crate/plugin/SQLModule.java
Labels: ready-to-merge

#7749 Added basic passphrase crypto support.
  licensing/src/main/java/io/crate/license/Cryptos.java
  licensing/src/test/java/io/crate/license/CryptosTest.java
Labels: ready-to-merge

#7748 Tests: Add test utils to simplify writing lucene query tests
  sql/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  sql/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#7751 Set CORS headers if cors is enabled on blob endpoints
  blackbox/docs/appendices/release-notes/unreleased.rst
  blob/src/main/java/io/crate/blob/BlobService.java
  blob/src/main/java/io/crate/protocols/http/HttpBlobHandler.java
  blob/src/test/java/io/crate/integrationtests/BlobHttpIntegrationTest.java
  blob/src/test/java/io/crate/integrationtests/BlobIntegrationTest.java
  blob/src/test/java/io/crate/integrationtests/BlobIntegrationTestBase.java
Labels: ready-to-merge, v/3.1, v/3.2

#7750 Fix parsing of pg array literal single char elements
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge, v/3.1

#7761 Tests: Remove TestingTableInfo usage from GroupByPlannerTest
  sql/src/test/java/io/crate/analyze/TableDefinitions.java
  sql/src/test/java/io/crate/planner/consumer/GroupByPlannerTest.java
Labels: ready-to-merge

#7762 Fix implicit->explicit join condition conversion.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/join/JoinOperations.java
  sql/src/test/java/io/crate/execution/engine/join/JoinOperationsTest.java
Labels: ready-to-merge, v/3.1

#7764 Implement set license 'licenseKey'
  licensing/src/main/java/io/crate/license/LicenseMetaData.java
  licensing/src/main/java/io/crate/license/TransportSetLicenseAction.java
  licensing/src/test/java/io/crate/license/LicenseMetaDataTest.java
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/SetLicenseAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/SetStatementAnalyzer.java
  sql/src/main/java/io/crate/planner/statement/SetLicensePlan.java
  sql/src/test/java/io/crate/analyze/SetAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/SetLicenseIntegrationTest.java
Labels: ready-to-merge

#7766 Rename LicenseMetaData to License (and drop previous, duplicate, License)
  licensing/src/main/java/io/crate/license/License.java
  licensing/src/main/java/io/crate/license/LicenseMetaData.java
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/main/java/io/crate/license/SetLicenseRequest.java
  licensing/src/main/java/io/crate/license/TransportSetLicenseAction.java
  licensing/src/main/java/io/crate/plugin/LicensePlugin.java
  licensing/src/test/java/io/crate/license/LicenseTest.java
  sql/src/main/java/io/crate/planner/statement/SetLicensePlan.java
  sql/src/test/java/io/crate/integrationtests/SetLicenseIntegrationTest.java
Labels: ready-to-merge

#7767 Tests: Close IndexService on QueryTester.close
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#7770 Switch to psycopg2-binary
  blackbox/requirements.txt
Labels: ready-to-merge

#7768 Make sure CORS preflight requests are handled before auth checks
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  http/src/main/java/io/crate/protocols/http/CrateNettyHttpServerTransport.java
Labels: ready-to-merge, v/3.1, v/3.2

#7752 Update guava to 26.0
  gradle/version.properties
Labels: ready-to-merge

#7771 Fix array_length query generation for >=
  sql/src/main/java/io/crate/lucene/ArrayLengthQuery.java
Labels: ready-to-merge

#7774 Filter out archived settings on table altering.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/metadata/upgrade/IndexTemplateUpgrader.java
  sql/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  sql/src/test/java/io/crate/metadata/upgrade/IndexTemplateUpgraderTest.java
Labels: ready-to-merge, v/3.1

#7779 Expose the current license information in the `sys.cluster` table.
  blackbox/docs/admin/system-information.rst
  licensing/src/main/java/io/crate/license/DecryptedLicenseData.java
  licensing/src/main/java/io/crate/license/LicenseKey.java
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
  sql/src/main/java/io/crate/expression/reference/sys/cluster/ClusterLicenseExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/cluster/SysClusterExpressionModule.java
  sql/src/main/java/io/crate/metadata/sys/SysClusterTableInfo.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#7776 Remove partition unrelated alias handling
  sql/src/main/java/io/crate/exceptions/AlterTableAliasException.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/execution/ddl/tables/DropTableTask.java
  sql/src/main/java/io/crate/metadata/Schemas.java
  sql/src/main/java/io/crate/metadata/doc/DocIndexMetaData.java
  sql/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  sql/src/main/java/io/crate/metadata/doc/DocTableInfoBuilder.java
  sql/src/main/java/io/crate/metadata/doc/InternalDocTableInfoFactory.java
  sql/src/main/java/io/crate/metadata/shard/ShardReferenceResolver.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/test/java/io/crate/analyze/DropTableAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/InsertFromValuesAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
  sql/src/test/java/io/crate/integrationtests/TableAliasIntegrationTest.java
  sql/src/test/java/io/crate/metadata/SchemasITest.java
  sql/src/test/java/io/crate/metadata/SchemasTest.java
  sql/src/test/java/io/crate/metadata/doc/DocIndexMetaDataTest.java
  sql/src/test/java/io/crate/metadata/doc/DocTableInfoBuilderTest.java
  sql/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  sql/src/test/java/io/crate/metadata/table/TestingTableInfo.java
Labels: ready-to-merge

#7786 Store current versions on new table partition
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/metadata/IndexMappings.java
  sql/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge, v/3.1

#7782 move MQTT settings to the config section of the docs
  blackbox/docs/admin/ingestion/sources/mqtt.rst
  blackbox/docs/config/node.rst
Labels: ready-to-merge

#7794 Fix hashCode implementation of MergeCountProjection
  sql/src/main/java/io/crate/execution/dsl/projection/MergeCountProjection.java
  sql/src/test/java/io/crate/execution/dsl/projection/MergeCountProjectionTest.java
Labels: ready-to-merge

#7793 Prepare release 3.1.2
  blackbox/docs/appendices/release-notes/3.1.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#7791 Add sys checks to signal when the license is close to expiry.
  blackbox/docs/admin/system-information.rst
  licensing/src/main/java/io/crate/license/DecryptedLicenseData.java
  licensing/src/main/java/io/crate/license/LicenseExpiryNotification.java
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/test/java/io/crate/license/LicenseExpiryNotificationTest.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
  sql/src/main/java/io/crate/expression/reference/sys/check/AbstractSysCheck.java
  sql/src/main/java/io/crate/expression/reference/sys/check/SysChecksModule.java
  sql/src/main/java/io/crate/expression/reference/sys/check/cluster/LicenseExpiryCheck.java
  sql/src/main/java/io/crate/expression/reference/sys/check/cluster/TablesNeedUpgradeSysCheck.java
  sql/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseExpiryCheckTest.java
  sql/src/test/java/io/crate/integrationtests/SysCheckerIntegrationTest.java
Labels: ready-to-merge

#7798 Bump Version to 3.1.3-snapshot
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#7797 Register trial license (for 30 days) only if enterprise is enabled.
  licensing/build.gradle
  licensing/src/main/java/io/crate/license/LicenseKey.java
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/test/java/io/crate/license/LicenseKeyTest.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
Labels: ready-to-merge

#7796 Reflect CrateDB 3.1.2 release
  blackbox/docs/appendices/release-notes/3.1.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#7801 Fix privilege check in case table aliases are present
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/main/java/io/crate/auth/user/StatementPrivilegeValidator.java
  enterprise/users/src/test/java/io/crate/auth/user/StatementPrivilegeValidatorTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#7758 Implement License verification method
  licensing/src/main/java/io/crate/license/CryptoUtils.java
  licensing/src/main/java/io/crate/license/Cryptos.java
  licensing/src/main/java/io/crate/license/DecodedLicense.java
  licensing/src/main/java/io/crate/license/DecryptedLicenseData.java
  licensing/src/main/java/io/crate/license/EnterpriseLicense.java
  licensing/src/main/java/io/crate/license/LicenseKey.java
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/main/java/io/crate/license/SelfGeneratedLicense.java
  licensing/src/main/java/io/crate/license/TrialLicense.java
  licensing/src/test/java/io/crate/license/CryptoUtilsTest.java
  licensing/src/test/java/io/crate/license/DecryptedLicenseDataTest.java
  licensing/src/test/java/io/crate/license/LicenseExpiryNotificationTest.java
  licensing/src/test/java/io/crate/license/LicenseKeyTest.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
  licensing/src/test/java/io/crate/license/LicenseTest.java
  licensing/src/test/resources/private.key
  licensing/src/test/resources/public.key
Labels: ready-to-merge

#7755 Deprecate mqtt
  blackbox/docs/admin/ingestion/sources/mqtt.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/mqtt/src/main/java/io/crate/mqtt/netty/Netty4MqttServerTransport.java
  enterprise/mqtt/src/test/java/io/crate/mqtt/netty/MqttNettyNetworkConfigTest.java
Labels: ready-to-merge

#7804 Update t-digest to 3.2
  blackbox/docs/general/builtins/aggregation.rst
  es/es-server/build.gradle
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
Labels: ready-to-merge

#7807 Remove BytesRef conversion logic from js udf layer
  enterprise/lang-js/src/main/java/io/crate/operation/language/JavaScriptUserDefinedFunction.java
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
  sql/src/test/java/io/crate/executor/BytesRefUtilsTest.java
  sql/src/test/java/io/crate/testing/BytesRefUtils.java
Labels: ready-to-merge

#7814 Disable total hits tracking in OrderedDocCollector
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollector.java
Labels: ready-to-merge

#7815 Minor cleanups.
  licensing/src/main/java/io/crate/license/CryptoUtils.java
  licensing/src/main/java/io/crate/license/EnterpriseLicense.java
  licensing/src/main/java/io/crate/license/TrialLicense.java
  licensing/src/test/java/io/crate/license/CryptoUtilsTest.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
Labels: ready-to-merge

#7816 Remove some unused declarations
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToByteSizeValueVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToTimeValueVisitor.java
  sql/src/main/java/io/crate/exceptions/TableAliasSchemaException.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/IdFromUidCollectorExpression.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/metadata/RelationName.java
  sql/src/test/java/io/crate/metadata/table/TestingTableInfo.java
  sql/src/test/java/io/crate/testing/SqlExpressions.java
  sql/src/test/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#7812 Replace RowTransformingBatchIterator with a function + map
  sql/src/main/java/io/crate/execution/engine/pipeline/InputRowProjector.java
  sql/src/main/java/io/crate/execution/engine/pipeline/MapRowUsingInputs.java
  sql/src/test/java/io/crate/execution/engine/pipeline/MapRowUsingInputsTest.java
Labels: ready-to-merge

#7810 Create results list with correct size in CompletableFutures
  shared/src/main/java/io/crate/concurrent/CompletableFutures.java
Labels: ready-to-merge

#7818 Flush channel periodically when sending data to clients via pg
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  sql/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#7823 Add ability to inject the crate public key in the distribution at build time.
  licensing/build.gradle
Labels: ready-to-merge

#7819 Fix ClassCastException on sys.allocations queries
  sql/src/main/java/io/crate/metadata/sys/SysAllocationsTableInfo.java
Labels: ready-to-merge

#7813 Replace LiteralNestableInput with constant
  sql/src/main/java/io/crate/expression/reference/LiteralNestableInput.java
  sql/src/main/java/io/crate/expression/reference/sys/cluster/ClusterLoggingOverridesExpression.java
  sql/src/main/java/io/crate/metadata/shard/ShardReferenceResolver.java
  sql/src/test/java/io/crate/analyze/EvaluatingNormalizerTest.java
Labels: ready-to-merge

#7824 Document the trial, enterprise and community license behaviour.
  blackbox/docs/enterprise/index.rst
Labels: ready-to-merge

#7826 Deprecate setting: 'license.ident'
  app/src/main/dist/config/crate.yml
  blackbox/docs/admin/system-information.rst
  core/src/main/java/io/crate/module/CrateCoreModule.java
  core/src/main/java/io/crate/settings/SharedSettings.java
  sql/src/main/java/io/crate/expression/reference/sys/check/SysChecksModule.java
  sql/src/main/java/io/crate/expression/reference/sys/check/cluster/LicenseEnterpriseChecks.java
  sql/src/main/java/io/crate/expression/reference/sys/check/cluster/LicenseExpiryCheck.java
  sql/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseEnterpriseChecksTest.java
  sql/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseExpiryCheckTest.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterSettingsExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/SysCheckerIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
  udc/src/main/java/io/crate/udc/ping/PingTask.java
  udc/src/test/java/io/crate/udc/ping/PingTaskTest.java
Labels: ready-to-merge

#7829 Display null if there isn't any license present.
  sql/src/main/java/io/crate/expression/reference/sys/cluster/ClusterLicenseExpression.java
Labels: ready-to-merge

#7831 Fix a ByteBuf leak when sending rows to pg clients that contain failing expressions
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/protocols/postgres/Messages.java
  sql/src/test/java/io/crate/protocols/postgres/MessagesTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#7834 Fix ByteBuf leak in MqttIngestService
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/mqtt/src/main/java/io/crate/mqtt/operations/MqttIngestService.java
Labels: ready-to-merge, v/3.1, v/3.2
