Repository crate/crate, pull requests merged in 2018-12, with the labels that each got.

#7943 Move type validation for grouping columns into executor
  sql/src/main/java/io/crate/analyze/validator/GroupBySymbolValidator.java
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#7950 Fix an error handling issue that led to sys.jobs leaks
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/protocols/postgres/SimplePortal.java
  sql/src/test/java/io/crate/integrationtests/PostgresJobsLogsITest.java
Labels: ready-to-merge, v/3.1, v/3.2

#7951 Move distinct handling into the planner
  sql/src/main/java/io/crate/analyze/CopyAnalyzer.java
  sql/src/main/java/io/crate/analyze/MultiSourceSelect.java
  sql/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  sql/src/main/java/io/crate/analyze/QueriedTable.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  sql/src/main/java/io/crate/analyze/relations/OrderedLimitedRelation.java
  sql/src/main/java/io/crate/analyze/relations/QueriedRelation.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationNormalizer.java
  sql/src/main/java/io/crate/analyze/relations/UnionSelect.java
  sql/src/main/java/io/crate/planner/consumer/SemiJoins.java
  sql/src/main/java/io/crate/planner/operators/Distinct.java
  sql/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/Order.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/ShowStatementsAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/TableFunctionITest.java
  sql/src/test/java/io/crate/planner/SubQueryPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/SelectDistinctLogicalPlannerTest.java
Labels: ready-to-merge

#7925 reword CrateDB licensing documentation
  LICENSE
  NOTICE
  app/src/main/dist/config/crate.yml
  blackbox/docs/enterprise/index.rst
  enterprise/LICENSE
Labels: ready-to-merge

#7954 Fix an error handling issue that led to sys.jobs leaks
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/protocols/postgres/SimplePortal.java
  sql/src/test/java/io/crate/integrationtests/PostgresJobsLogsITest.java
Labels: ready-to-merge

#7958 Rename `indexName` on RelationName to `indexNameOrAlias`
  sql/src/main/java/io/crate/analyze/AbstractDropTableAnalyzedStatement.java
  sql/src/main/java/io/crate/execution/ddl/RerouteActions.java
  sql/src/main/java/io/crate/execution/ddl/SnapshotRestoreDDLDispatcher.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportDropTableAction.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportOpenCloseTableOrPartitionAction.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportRenameTableAction.java
  sql/src/main/java/io/crate/execution/ddl/views/TransportCreateViewAction.java
  sql/src/main/java/io/crate/execution/dml/ShardRequestExecutor.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexNameResolver.java
  sql/src/main/java/io/crate/execution/engine/pipeline/TableSettingsResolver.java
  sql/src/main/java/io/crate/expression/reference/sys/shard/ShardRowContext.java
  sql/src/main/java/io/crate/metadata/RelationName.java
  sql/src/main/java/io/crate/metadata/Routing.java
  sql/src/main/java/io/crate/metadata/blob/BlobTableInfo.java
  sql/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  sql/src/main/java/io/crate/metadata/cluster/DropTableClusterStateTaskExecutor.java
  sql/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  sql/src/main/java/io/crate/metadata/doc/DocTableInfoBuilder.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/test/java/io/crate/analyze/TableDefinitions.java
  sql/src/test/java/io/crate/execution/ddl/RerouteActionsTest.java
  sql/src/test/java/io/crate/execution/dml/delete/TransportShardDeleteActionTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  sql/src/test/java/io/crate/metadata/RelationNameTest.java
  sql/src/test/java/io/crate/metadata/table/TestingTableInfo.java
  sql/src/test/java/io/crate/testing/QueryTester.java
  sql/src/test/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#7962 Allow other outputs next to window functions in the select list.
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/execution/dsl/projection/WindowAggProjection.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/execution/dsl/projection/WindowAggProjectionSerialisationTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#7966 Optimize no-op check in UserManagerService
  enterprise/users/src/main/java/io/crate/auth/user/UserManagerService.java
Labels: ready-to-merge

#7965 Tests: Make RamBlockSizeCalculatorTest deterministic
  sql/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  sql/src/main/java/io/crate/execution/engine/join/NestedLoopOperation.java
  sql/src/main/java/io/crate/execution/engine/join/RamBlockSizeCalculator.java
  sql/src/test/java/io/crate/execution/engine/join/RamBlockSizeCalculatorTest.java
Labels: ready-to-merge

#7971 Drop the requirement to close tables for rename
  blackbox/docs/sql/statements/alter-table.rst
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportRenameTableAction.java
  sql/src/main/java/io/crate/execution/support/ActionListeners.java
  sql/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  sql/src/test/java/io/crate/execution/ddl/tables/TransportRenameTableActionTest.java
  sql/src/test/java/io/crate/integrationtests/RenameTableIntegrationTest.java
Labels: ready-to-merge

#7978 Drop the RenameTableResponse
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/execution/ddl/tables/RenameTableResponse.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportRenameTableAction.java
Labels: ready-to-merge

#7928 Implement shard shrinking
  sql/src/main/java/io/crate/execution/TransportExecutorModule.java
  sql/src/main/java/io/crate/execution/ddl/index/BulkRenameIndexRequest.java
  sql/src/main/java/io/crate/execution/ddl/index/TransportRenameIndexNameAction.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/metadata/cluster/RenameIndexClusterStateExecutor.java
  sql/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge

#7984 Remove the logger argument from CumulativePageBucketReceiver
  sql/src/main/java/io/crate/execution/engine/collect/collectors/RemoteCollector.java
  sql/src/main/java/io/crate/execution/jobs/CumulativePageBucketReceiver.java
  sql/src/main/java/io/crate/execution/jobs/JobSetup.java
  sql/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  sql/src/test/java/io/crate/execution/jobs/DistResultRXTaskTest.java
  sql/src/test/java/io/crate/execution/jobs/RootTaskTest.java
Labels: ready-to-merge

#7985 Make table health computation lazy
  sql/src/main/java/io/crate/metadata/sys/TableHealth.java
  sql/src/main/java/io/crate/metadata/sys/TableHealthService.java
  sql/src/test/java/io/crate/metadata/sys/TableHealthServiceTest.java
Labels: ready-to-merge

#7983 Update `renaming tables` documentation related to close/open removement.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/alter-table.rst
Labels: ready-to-merge

#7986 Filter out temporary indices from DB catalog
  sql/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  sql/src/main/java/io/crate/expression/reference/sys/shard/SysAllocations.java
  sql/src/main/java/io/crate/metadata/IndexParts.java
  sql/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysShardsTableInfo.java
  sql/src/test/java/io/crate/integrationtests/DanglingIndicesIntegrationTest.java
  sql/src/test/java/io/crate/metadata/IndexPartsTest.java
Labels: ready-to-merge

#7990 Separate Shrink Integration test
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/DDLShardResizeIntegrationTest.java
Labels: ready-to-merge

#7897 doc: add initial doc for shard shrinking
  blackbox/docs/general/ddl/alter-table.rst
  blackbox/docs/general/ddl/partitioned-tables.rst
  blackbox/docs/general/ddl/sharding.rst
  blackbox/docs/sql/statements/alter-table.rst
  blackbox/docs/sql/statements/create-table.rst
Labels: ready-to-merge

#7991 Implement analyzer changes to support table and table-partition shard shrinking
  sql/src/main/java/io/crate/analyze/AlterTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/TableParameterInfo.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/test/java/io/crate/analyze/CreateAlterPartitionedTableAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge

#7996 Fix documentation of table routing allocation parameters.
  blackbox/docs/sql/statements/create-table.rst
Labels: ready-to-merge, v/3.1

#7995 Add support for per-table shard allocation filtering.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/index.rst
  blackbox/docs/general/ddl/shard-allocation.rst
  blackbox/docs/sql/statements/create-table.rst
  sql/src/main/java/io/crate/analyze/GenericPropertiesConverter.java
  sql/src/main/java/io/crate/analyze/TableParameterInfo.java
  sql/src/main/java/io/crate/analyze/TablePropertiesAnalyzer.java
  sql/src/main/java/io/crate/expression/reference/information/TablesSettingsExpression.java
  sql/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#7977 Add a ALTER CLUSTER GC DANGLING ARTIFACTS statement
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/alter-cluster.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/GCDanglingArtifacts.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/AnalyzedGCDanglingArtifacts.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/metadata/IndexParts.java
  sql/src/main/java/io/crate/planner/GCDangingArtifactsPlan.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  sql/src/test/java/io/crate/integrationtests/GCDanglingArtifactsITest.java
Labels: ready-to-merge

#7881 simplify requirements.txt and document docs dir in LICENSE
  LICENSE
  blackbox/requirements.txt
Labels: ready-to-merge

#7999 Make sure errors are propagated to the RowConsumer (sys.jobs leaks)
  sql/src/main/java/io/crate/planner/CreateViewPlan.java
  sql/src/main/java/io/crate/planner/DropViewPlan.java
  sql/src/main/java/io/crate/planner/GCDangingArtifactsPlan.java
  sql/src/main/java/io/crate/planner/MultiPhasePlan.java
  sql/src/main/java/io/crate/planner/NoopPlan.java
  sql/src/main/java/io/crate/planner/Plan.java
  sql/src/main/java/io/crate/planner/SwapTablePlan.java
  sql/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  sql/src/main/java/io/crate/planner/node/dcl/GenericDCLPlan.java
  sql/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
  sql/src/main/java/io/crate/planner/node/ddl/DeleteAllPartitions.java
  sql/src/main/java/io/crate/planner/node/ddl/DeletePartitions.java
  sql/src/main/java/io/crate/planner/node/ddl/DropTablePlan.java
  sql/src/main/java/io/crate/planner/node/ddl/ESClusterUpdateSettingsPlan.java
  sql/src/main/java/io/crate/planner/node/ddl/GenericDDLPlan.java
  sql/src/main/java/io/crate/planner/node/dml/DeleteById.java
  sql/src/main/java/io/crate/planner/node/dml/LegacyUpsertById.java
  sql/src/main/java/io/crate/planner/node/dml/UpdateById.java
  sql/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  sql/src/main/java/io/crate/planner/node/management/KillPlan.java
  sql/src/main/java/io/crate/planner/node/management/ShowCreateTablePlan.java
  sql/src/main/java/io/crate/planner/node/management/ShowSessionParameterPlan.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlan.java
  sql/src/main/java/io/crate/planner/statement/CopyStatementPlanner.java
  sql/src/main/java/io/crate/planner/statement/DeletePlanner.java
  sql/src/main/java/io/crate/planner/statement/SetLicensePlan.java
  sql/src/main/java/io/crate/planner/statement/SetSessionPlan.java
  sql/src/main/java/io/crate/protocols/postgres/SimplePortal.java
  sql/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  sql/src/test/java/io/crate/protocols/postgres/BatchPortalTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8001 Remove shard allocation restriction from the table shrink flow
  blackbox/docs/general/ddl/alter-table.rst
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
Labels: ready-to-merge

#8003 Allow casts from geo_shape to object
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/types/DataTypes.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge

#8004 Fix array_unique for nested arrays
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/types/ArrayType.java
  core/src/main/java/io/crate/types/DataType.java
  sql/src/main/java/io/crate/expression/scalar/ArrayUniqueFunction.java
  sql/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#7981 Window functions: support ORDER BY inside the OVER clause.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/window-functions.rst
  sql/src/main/java/io/crate/analyze/FrameBoundDefinition.java
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/execution/dsl/projection/WindowAggProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFrameState.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunction.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/analyze/SelectWindowFunctionAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/WindowAggProjectionSerialisationTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#8011 Log possible dangling indices at node startup
  sql/src/main/java/io/crate/metadata/DanglingArtifactsService.java
  sql/src/main/java/io/crate/plugin/SQLModule.java
  sql/src/main/java/io/crate/plugin/SQLPlugin.java
Labels: ready-to-merge

#8012 Remove unused method AlterTableOperation::getNodeForResize
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
Labels: ready-to-merge

#8015 Account for the memory used by the WindowBatchIterator.
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge

#8014 upgrade admin ui to 1.11.3
  app/build.gradle
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8016 Make orderByIndexes non-nullable.
  sql/src/main/java/io/crate/execution/dsl/projection/WindowAggProjection.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/execution/dsl/projection/WindowAggProjectionSerialisationTest.java
Labels: ready-to-merge

#8018 Prepare 3.1.4 release
  blackbox/docs/appendices/release-notes/3.1.4.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8021 Reflect 3.1.4 release
  blackbox/docs/appendices/release-notes/3.1.4.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8020 Bump version to 3.1.5-SNAPSHOT
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8022 Rename InputColumn from* methods to map* to signal the outcome.
  sql/src/main/java/io/crate/execution/dsl/projection/TopNProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  sql/src/main/java/io/crate/expression/symbol/InputColumn.java
Labels: ready-to-merge

#8017 Prepare 3.2.0 release
  blackbox/docs/appendices/release-notes/3.2.0.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8024 Changed gradle writing folders using outputs.file to outputs.dir
  app/build.gradle
Labels: ready-to-merge

#8023 Use random PSQL port for blackbox tests
  blackbox/docs/src/doc_tests/tests.py
  blackbox/hdfs/src/tests.py
  blackbox/monitoring/src/tests.py
Labels: ready-to-merge, v/3.1

#8027 Bump version to 3.2.1-snapshot
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8026 Remove the DirectFallbackExecutor
  sql/src/main/java/io/crate/execution/engine/InterceptingRowConsumer.java
  sql/src/main/java/io/crate/execution/engine/PhasesTaskFactory.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  sql/src/main/java/io/crate/execution/support/ThreadPools.java
Labels: ready-to-merge
