Repository crate/crate, pull requests merged in 2018-09, with the labels that each got.

#7653 Fix table creation with generated columns inside objects
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  sql/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  sql/src/main/java/io/crate/metadata/GeneratedReference.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/UpdateSourceGenTest.java
  sql/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: v/3.1

#7639 Optimize obj = {} expressions to utilize the index if possible
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/lucene/EqQuery.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  sql/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
Labels: v/3.2

#7670 Inline createUnknownFunctionException
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/metadata/Functions.java
Labels: ready-to-merge

#7673 Mergify: set automated backport labels
  .mergify.yml
Labels: ready-to-merge

#7676 Remove a SessionContext constructor overload
  sql/src/main/java/io/crate/action/sql/SQLOperations.java
  sql/src/main/java/io/crate/action/sql/SessionContext.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  sql/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
  sql/src/test/java/io/crate/testing/SQLExecutor.java
  sql/src/test/java/io/crate/testing/SqlExpressions.java
Labels: ready-to-merge

#7680 Encapsulate function lookup logic within Functions
  app/src/test/java/io/crate/plugin/PluginLoaderTest.java
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/AggregateCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/GroupingBytesRefCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/GroupingLongCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationBenchmark.java
  enterprise/hll/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/test/java/io/crate/analyze/EvaluatingNormalizerTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationtest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  sql/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  sql/src/test/java/io/crate/expression/InputFactoryTest.java
  sql/src/test/java/io/crate/expression/scalar/AbstractScalarFunctionsTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/AddFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/LogFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/RandomFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/systeminformation/CurrentSchemaFunctionTest.java
  sql/src/test/java/io/crate/expression/tablefunctions/AbstractTableFunctionsTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  sql/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  sql/src/test/java/io/crate/operation/aggregation/AggregationTest.java
Labels: ready-to-merge

#7682 Remove unused isRawSourceInsert from ShardUpsertRequest
  sql/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
Labels: ready-to-merge

#7692 Drop redunant schema check (if table's missing we report it)
  sql/src/main/java/io/crate/metadata/Schemas.java
Labels: ready-to-merge

#7696 Remove Value symbol
  sql/src/main/java/io/crate/analyze/TableIdentsExtractor.java
  sql/src/main/java/io/crate/execution/dsl/projection/AbstractIndexWriterProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/DMLProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/MergeCountProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/WriterProjection.java
  sql/src/main/java/io/crate/expression/symbol/SymbolType.java
  sql/src/main/java/io/crate/expression/symbol/SymbolVisitor.java
  sql/src/main/java/io/crate/expression/symbol/Value.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationtest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  sql/src/test/java/io/crate/executor/transport/SymbolSerializerTest.java
  sql/src/test/java/io/crate/expression/scalar/AbstractScalarFunctionsTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/AddFunctionTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  sql/src/test/java/io/crate/planner/node/RoutedCollectPhaseTest.java
Labels: ready-to-merge

#7698 Reflect releases of 3.0.7 and 3.1.1
  blackbox/docs/appendices/release-notes/3.0.7.rst
  blackbox/docs/appendices/release-notes/3.1.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#7697 Add licensing module
  licensing/build.gradle
  licensing/src/main/java/io/crate/license/License.java
  settings.gradle
  sql/build.gradle
Labels: ready-to-merge

#7683 add synopsis for 'set license' statement
  blackbox/docs/config/index.rst
  blackbox/docs/config/license.rst
  blackbox/docs/config/session.rst
  blackbox/docs/sql/statements/set.rst
Labels: documentation, ready-to-merge

#7694 correct order of sys.shards columns
  blackbox/docs/admin/system-information.rst
Labels: ready-to-merge

#7705 Re-integrate NullEliminator into query-building
  sql/src/main/java/io/crate/analyze/WhereClause.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/test/java/io/crate/analyze/WhereClauseTest.java
  sql/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge

#7700 Tests: Replace TestingTableInfo usage with addTable in LuceneQueryBuilderTest
  sql/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
Labels: ready-to-merge

#7704 Make SymbolToTrueVisitor a singleton
  sql/src/main/java/io/crate/analyze/ScalarsAndRefsToTrue.java
  sql/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  sql/src/test/java/io/crate/analyze/ScalarsAndRefsToTrueTest.java
Labels: ready-to-merge

#7712 Update netty to 4.1.30
  gradle/version.properties
Labels: ready-to-merge
