Repository crate/crate, pull requests merged in 2019-01, with the labels that each got.

#8041 Revert information_schema.columns changes
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  sql/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  sql/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8042 Added example of using double quotes for nested table parameters
  blackbox/docs/sql/statements/create-table.rst
Labels: ready-to-merge

#8047 Undo of every chained action must only be called once.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/support/ChainableActions.java
  sql/src/test/java/io/crate/execution/support/ChainableActionsTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8045 Fix parameter type detection for nested relations
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/action/sql/Session.java
  sql/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8046 Add support for casts to nested arrays
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/DataTypeAnalyzer.java
  sql/src/test/java/io/crate/analyze/DataTypeAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8050 WindowFunction interface extends FunctionImplementation
  sql/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunction.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge

#8051 Allow reads on table functions even if license is expired
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/IsStatementExecutionAllowed.java
  sql/src/test/java/io/crate/planner/ExpiredLicensePlannerTest.java
Labels: ready-to-merge, v/3.2

#8058 Fix FailureOnlyResponseListener to propagate failures correctly
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/FailureOnlyResponseListener.java
  sql/src/test/java/io/crate/execution/engine/FailureOnlyResponseListenerTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8062 Inline CreateAnalyzerTask into CreateAnalyzerPlan
  sql/src/main/java/io/crate/execution/ddl/tables/CreateAnalyzerTask.java
  sql/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
Labels: ready-to-merge

#8060 Remove UpdateByIdTask indirection
  sql/src/main/java/io/crate/execution/dml/upsert/UpdateByIdTask.java
  sql/src/main/java/io/crate/planner/node/dml/UpdateById.java
Labels: ready-to-merge

#8063 Inline DropTableTask into DropTablePlan
  sql/src/main/java/io/crate/execution/ddl/tables/DropTableTask.java
  sql/src/main/java/io/crate/planner/node/ddl/DropTablePlan.java
Labels: ready-to-merge

#8019 Docs: Mention window functions under the `sql` section.
  blackbox/docs/sql/general/value-expressions.rst
Labels: ready-to-merge

#8069 Rename enterprise:hll to enterprise:functions as it'll hold multiple functions.
  app/build.gradle
  benchmarks/build.gradle
  benchmarks/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationBenchmark.java
  enterprise/functions/build.gradle
  enterprise/functions/src/main/java/io/crate/module/EnterpriseFunctionsModule.java
  enterprise/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  enterprise/functions/src/main/java/io/crate/plugin/EnterpriseFunctionsPlugin.java
  enterprise/functions/src/main/resources/META-INF/services/io.crate.Plugin
  enterprise/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  enterprise/hll/src/main/resources/META-INF/services/io.crate.Plugin
  settings.gradle
Labels: ready-to-merge

#8068 Extend range of expressions supported in the CASE operand
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
Labels: ready-to-merge

#8072 improve doc notes for superuser
  blackbox/docs/admin/user-management.rst
Labels: ready-to-merge

#8084 upgraded admin-ui to 1.10.5
  app/build.gradle
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8070 Add a pg_catalog.pg_description table
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgDescriptionTable.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#8071 Change support probot message to refer to discourse instead of slack
  .github/support.yml
Labels: ready-to-merge

#8059 Remove DeleteByIdTask indirection
  sql/src/main/java/io/crate/execution/dml/delete/DeleteByIdTask.java
  sql/src/main/java/io/crate/planner/node/dml/DeleteById.java
Labels: ready-to-merge

#8095 Remove ES Index API usage from ArrayMapperTest
  sql/src/test/java/io/crate/integrationtests/ArrayMapperITest.java
  sql/src/test/java/io/crate/metadata/doc/array/ArrayMapperTest.java
Labels: ready-to-merge

#8094 prepare release 3.2.1
  blackbox/docs/appendices/release-notes/3.2.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8093 prepare release 3.1.5
  blackbox/docs/appendices/release-notes/3.1.5.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8101 update version to 3.1.6-snapshot
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8099 update version to 3.2.2-snapshot
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8104 Fix a NPE on to-inner-join rewritable outer joins
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/Rewriter.java
  sql/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/3.1, v/3.2

#8102 reflect release 3.2.1
  blackbox/docs/appendices/release-notes/3.2.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8111 Remove ES GetSettings API usages in tests
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#8110 WindowFrameState holds all the rows in the frame.
  sql/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
Labels: ready-to-merge

#8117 Fix flaky sys.nodes time out test.
  sql/src/test/java/io/crate/integrationtests/SysNodeResiliencyIntegrationTest.java
Labels: ready-to-merge, v/3.2

#8127 Rename outputTypes to standaloneInputTypes used for memory row accounting
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
Labels: ready-to-merge

#8124 Tests: Change ColumnReference tests to avoid createIndex usage
  sql/src/test/java/io/crate/expression/reference/doc/BooleanColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/ByteColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  sql/src/test/java/io/crate/expression/reference/doc/DoubleColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/FloatColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/IntegerColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/IpColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/LongColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/ShortColumnReferenceTest.java
  sql/src/test/java/io/crate/expression/reference/doc/StringColumnReferenceTest.java
  sql/src/test/java/io/crate/testing/IndexEnv.java
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#8131 Replace usages of ES search API in tests
  sql/src/test/java/io/crate/executor/transport/task/elasticsearch/DocRefResolverTest.java
  sql/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#8133 Update CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: ready-to-merge

#8123 Remove usage of ES client at the crate node settings test
  app/build.gradle
  app/src/test/java/io/crate/node/NodeSettingsTest.java
Labels: ready-to-merge

#8139 Upgrade gradle to 5.1.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge

#8140 Doc update: unsupported section
  blackbox/docs/appendices/compatibility.rst
  blackbox/docs/general/builtins/window-functions.rst
Labels: ready-to-merge

#8148 Prepare release 3.2.2
  blackbox/docs/appendices/release-notes/3.2.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8149 hard wrap comments
  blackbox/docs/conf.py
Labels: ready-to-merge

#8150 Mark ingest framework as deprecated
  blackbox/docs/admin/ingestion/index.rst
  blackbox/docs/admin/ingestion/rules.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/create-ingest-rule.rst
  blackbox/docs/sql/statements/drop-ingest-rule.rst
Labels: ready-to-merge

#8152 Add Jenkinsfile
  Jenkinsfile
Labels: ready-to-merge, v/3.1, v/3.2

#8143 Update the 'Writing Documentation' for developer docs
  blackbox/build.gradle
  devs/docs/write_docs.rst
Labels: ready-to-merge

#8155 Expose pg_type.typlen column
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8157 Ensure the license tool jar name contains no classifier suffix.
  licensing/build.gradle
Labels: ready-to-merge

#8164 Expose column pg_type.typnamespace
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8172 Re-enable the annotation processor for jmh (disabled by default with gradle 5+)
  benchmarks/build.gradle
Labels: ready-to-merge

#8175 Avoid int truncation in QueryStats avgDurationInMs calculation
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/QueryStats.java
  enterprise/jmx-monitoring/src/test/java/io/crate/beans/QueryStatsTest.java
Labels: ready-to-merge

#8178 docs: Clarify that sys checks won't be disabled with the fs allocation decider
  blackbox/docs/admin/system-information.rst
  blackbox/docs/config/cluster.rst
Labels: ready-to-merge

#8179 Fix null argument handling in unnest
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  sql/src/test/java/io/crate/expression/tablefunctions/UnnestFunctionTest.java
Labels: ready-to-merge, v/3.2

#8163 Node decommission using sql statement
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/alter-cluster.rst
  blackbox/docs/src/doc_tests/process_test.py
  integration-testing/src/main/java/io/crate/test/integration/CrateDummyClusterServiceUnitTest.java
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/DecommissionNodeStatement.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/AnalyzedDecommissionNodeStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/DecommissionNodeAnalyzer.java
  sql/src/main/java/io/crate/cluster/decommission/DecommissionNodeRequest.java
  sql/src/main/java/io/crate/cluster/decommission/TransportDecommissionNodeAction.java
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
  sql/src/main/java/io/crate/execution/TransportActionProvider.java
  sql/src/main/java/io/crate/execution/TransportExecutorModule.java
  sql/src/main/java/io/crate/planner/DecommissionNodePlan.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/test/java/io/crate/analyze/DecommissionNodeAnalyzerTest.java
  sql/src/test/java/io/crate/planner/DecommissionNodePlanTest.java
Labels: ready-to-merge

#8185 Update README.rst
  README.rst
Labels: ready-to-merge
