Repository crate/crate, pull requests merged in 2019-07, with the labels that each got.

#8881 Change TablesNeedUpgradeSysCheck to check for re-index requirement
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/reference/sys/check/cluster/TablesNeedUpgradeSysCheck.java
  sql/src/test/java/io/crate/integrationtests/SysCheckerIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/TablesNeedUpgradeSysCheckTest.java
Labels: ready-to-merge, v/3.3

#8883 Bump version to 4.1.0-SNAPSHOT
  .mergify.yml
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#8885 Add support for the lead window function.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/editions.rst
  blackbox/docs/general/builtins/window-functions.rst
  enterprise/functions/src/main/java/io/crate/module/EnterpriseFunctionsModule.java
  enterprise/functions/src/main/java/io/crate/window/OffsetValueFunctions.java
  enterprise/functions/src/test/java/io/crate/window/OffsetValueFunctionsTest.java
Labels: ready-to-merge, v/4.1

#8886 Update the ``sql_features`` table with supported features.
  sql/src/main/resources/sql_features.tsv
Labels: ready-to-merge

#8887 Extend the write.wait_for_active_shards docs
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/create-table.rst
Labels: ready-to-merge

#8888 Add promote replica sub-command to alter table
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/alter-table.rst
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocateStalePrimaryAllocationCommand.java
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/PromoteReplica.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/AlterTableRerouteAnalyzer.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/PromoteReplicaStatement.java
  sql/src/main/java/io/crate/execution/ddl/DDLStatementDispatcher.java
  sql/src/main/java/io/crate/execution/ddl/RerouteActions.java
  sql/src/test/java/io/crate/analyze/AlterTableRerouteAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/PromoteStaleReplicaITest.java
Labels: ready-to-merge

#8891 Docs: Cross-ref from wait_for_active_shards to promote replica
  blackbox/docs/sql/statements/alter-table.rst
  blackbox/docs/sql/statements/create-table.rst
Labels: ready-to-merge

#8895 Update some dependencies and remove mocksocket
  es/es-testing/build.gradle
  es/es-testing/src/main/java/org/elasticsearch/transport/MockTcpTransport.java
  gradle/version.properties
Labels: ready-to-merge

#8894 Use partition instead of frame end in getRowInPartitionAtIndexOrNull.
  enterprise/functions/src/test/java/io/crate/window/OffsetValueFunctionsTest.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFrameState.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFrameStateTest.java
Labels: ready-to-merge

#8896 Link lead and lag function docs in the changelog entry.
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8893 Add support for ROWS window frames.
  benchmarks/src/test/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/window-functions.rst
  enterprise/functions/src/test/java/io/crate/window/NthValueFunctionsTest.java
  enterprise/functions/src/test/java/io/crate/window/OffsetValueFunctionsTest.java
  sql-parser/src/main/java/io/crate/sql/tree/FrameBound.java
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/analyze/SelectWindowFunctionAnalyzerTest.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/AggregationWindowFunctionsTest.java
  sql/src/test/java/io/crate/execution/engine/window/CurrentRowFrameBoundTest.java
  sql/src/test/java/io/crate/execution/engine/window/UnboundedFollowingFrameBoundTest.java
  sql/src/test/java/io/crate/execution/engine/window/UnboundedPrecedingFrameBoundTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowDefinitionTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
Labels: ready-to-merge, v/4.1

#8897 Docs: Correct promote replica synopsis and rename node_id → node
  blackbox/docs/sql/statements/alter-table.rst
Labels: ready-to-merge

#8899 Fix the CURRENT_ROW end index in ROWS mode to yield an exclusive bound.
  enterprise/functions/src/test/java/io/crate/window/NthValueFunctionsTest.java
  enterprise/functions/src/test/java/io/crate/window/OffsetValueFunctionsTest.java
  sql-parser/src/main/java/io/crate/sql/tree/FrameBound.java
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/AggregationWindowFunctionsTest.java
  sql/src/test/java/io/crate/execution/engine/window/CurrentRowFrameBoundTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge

#8901 Don't use doc lookup in insert from sys-tables
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/test/java/io/crate/planner/InsertPlannerTest.java
  sql/src/test/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#8900 Remove subQuery planning logic from RelationBoundary
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/MultiPhase.java
  sql/src/main/java/io/crate/planner/operators/RelationBoundary.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#8903 Prepare release 3.3.5
  blackbox/docs/appendices/release-notes/3.3.5.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8904 Bump version to 3.3.6-SNAPSHOT
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8905 Prepare release 4.0.1
  blackbox/docs/appendices/release-notes/4.0.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#8907 Reflect 3.3.5 and 4.0.1 releases
  blackbox/docs/appendices/release-notes/3.3.5.rst
  blackbox/docs/appendices/release-notes/4.0.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#8906 Bump version to 4.0.2-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#8902 Add support for the named window definition.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/window-functions.rst
  blackbox/docs/sql/statements/select.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/QuerySpecification.java
  sql-parser/src/main/java/io/crate/sql/tree/Window.java
  sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql-parser/src/test/java/io/crate/sql/tree/WindowTest.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalysisContext.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/test/java/io/crate/analyze/SelectWindowFunctionAnalyzerTest.java
Labels: ready-to-merge

#8908 Fixed broken reference
  blackbox/docs/general/builtins/window-functions.rst
Labels: ready-to-merge

#8917 Fix version handling for unknown future versions
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/test/java/org/elasticsearch/VersionTest.java
Labels: ready-to-merge, v/4.0

#8912 Push filters beneath ProjectSet if they target `standalone` outputs.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge

#8919 Bump version of admin-ui to 1.15.1
  blackbox/docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.0

#8922 Prepare release 4.0.2
  blackbox/docs/appendices/release-notes/4.0.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#8923 Bump version to 4.0.3-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#8924 Reflect release 4.0.2
  blackbox/docs/appendices/release-notes/4.0.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#8929 Merge CollectionType and ArrayType
  common/src/main/java/io/crate/types/ArrayType.java
  common/src/main/java/io/crate/types/CollectionType.java
  common/src/main/java/io/crate/types/DataTypes.java
  sql/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  sql/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  sql/src/main/java/io/crate/analyze/CopyAnalyzer.java
  sql/src/main/java/io/crate/analyze/MetaDataToASTNodeResolver.java
  sql/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  sql/src/main/java/io/crate/expression/operator/EqOperator.java
  sql/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  sql/src/main/java/io/crate/expression/operator/any/AnyOperator.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  sql/src/main/java/io/crate/expression/scalar/ArrayBoundFunctionResolver.java
  sql/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  sql/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  sql/src/main/java/io/crate/expression/scalar/cast/CastFunction.java
  sql/src/main/java/io/crate/expression/symbol/Function.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  sql/src/main/java/io/crate/expression/udf/UserDefinedFunctionMetaData.java
  sql/src/main/java/io/crate/lucene/AbstractAnyQuery.java
  sql/src/main/java/io/crate/lucene/AnyEqQuery.java
  sql/src/main/java/io/crate/lucene/ArrayLengthQuery.java
  sql/src/main/java/io/crate/lucene/EqQuery.java
  sql/src/main/java/io/crate/lucene/IsNullQuery.java
  sql/src/main/java/io/crate/lucene/LikeQuery.java
  sql/src/main/java/io/crate/lucene/SubscriptQuery.java
  sql/src/main/java/io/crate/metadata/functions/params/Param.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  sql/src/main/java/io/crate/metadata/table/ColumnRegistrar.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  sql/src/main/java/io/crate/rest/action/ResultToXContentBuilder.java
Labels: ready-to-merge

#8931 Migrate GeoPointType to use Point and map points to oid 600
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/interfaces/postgres.rst
  common/src/main/java/io/crate/types/DataTypes.java
  common/src/main/java/io/crate/types/GeoPointType.java
  common/src/test/java/io/crate/types/GeoPointTypeTest.java
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
  es/es-server/src/main/java/org/elasticsearch/common/xcontent/XContentElasticsearchExtension.java
  sql/src/main/java/io/crate/execution/engine/collect/files/SummitsContext.java
  sql/src/main/java/io/crate/execution/engine/collect/files/SummitsIterable.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/GeoPointColumnReference.java
  sql/src/main/java/io/crate/expression/scalar/geo/CoordinateFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/DistanceFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/GeoHashFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/lucene/DistanceQuery.java
  sql/src/main/java/io/crate/metadata/sys/SysSummitsTableInfo.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  sql/src/main/java/io/crate/protocols/postgres/types/PointType.java
  sql/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  sql/src/test/java/io/crate/expression/symbol/LiteralTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  sql/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  sql/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  sql/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
  sql/src/test/java/io/crate/testing/DataTypeTesting.java
  sql/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#8934 Fix java version parsing for EA builds
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheck.java
  sql/src/test/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheckTest.java
Labels: ready-to-merge, v/4.0

#8940 Jenkins: Update openjdk 12 version
  Jenkinsfile
Labels: ready-to-merge

#8943 Unify drop blob table and drop table analyzers
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  sql/src/main/java/io/crate/analyze/AbstractDropTableAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/DropBlobTableAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/DropBlobTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/DropTableAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/DropTableAnalyzer.java
  sql/src/main/java/io/crate/execution/ddl/DDLStatementDispatcher.java
  sql/src/main/java/io/crate/metadata/Schemas.java
  sql/src/main/java/io/crate/metadata/table/Operation.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/node/ddl/DropTablePlan.java
  sql/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/DropBlobTableAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/DropTableAnalyzerTest.java
  sql/src/test/java/io/crate/planner/DropTablePlannerTest.java
Labels: ready-to-merge

#8944 Remove some remaining set type artifacts
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/CollectionColumnType.java
  sql-parser/src/main/java/io/crate/sql/tree/ColumnType.java
  sql-parser/src/main/java/io/crate/sql/tree/ObjectColumnType.java
  sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  sql/src/main/java/io/crate/analyze/MetaDataToASTNodeResolver.java
  sql/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
Labels: ready-to-merge

#8946 Remove the orphans handling from create table
  shared/src/main/java/io/crate/exceptions/Exceptions.java
  sql/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  sql/src/test/java/io/crate/executor/transport/DependencyCarrierDDLTest.java
Labels: ready-to-merge

#8947 Update netty to 4.1.38 and Lucene to 8.2.0
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
  sql/src/test/java/io/crate/expression/reference/sys/shard/ShardMinLuceneVersionExpressionTest.java
Labels: ready-to-merge

#8952 Inline AstVisitor.process
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/Extract.java
  sql-parser/src/test/java/io/crate/sql/parser/TreeAssertions.java
  sql/src/main/java/io/crate/analyze/AlterTableRerouteAnalyzer.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/CreateAnalyzerStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/DataTypeAnalyzer.java
  sql/src/main/java/io/crate/analyze/ExplainStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/OutputNameFormatter.java
  sql/src/main/java/io/crate/analyze/SetStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/SubscriptValidator.java
  sql/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  sql/src/main/java/io/crate/analyze/UnboundAnalyzer.java
  sql/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalysisContext.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToColumnIdentVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToNumberVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToObjectVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToStringVisitor.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/select/SelectAnalyzer.java
Labels: ready-to-merge

#8953 Fix calculation of the mid index in binary search code of List2 methods.
  shared/src/main/java/io/crate/common/collections/Lists2.java
Labels: ready-to-merge

#8956 Remove unsupported table settings from default config
  app/src/main/dist/config/crate.yml
Labels: ready-to-merge, v/3.3, v/4.0

#8948 Remove SettingsFilter in favour of masked settings
  app/src/test/java/io/crate/node/UnsafeBootstrapAndDetachCommandIT.java
  azure-discovery/src/main/java/io/crate/azure/management/AzureComputeService.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/Setting.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/Settings.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/SettingsFilter.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/SettingsModule.java
  es/es-server/src/main/java/org/elasticsearch/node/Node.java
  es/es-server/src/main/java/org/elasticsearch/plugins/Plugin.java
  es/es-server/src/main/java/org/elasticsearch/plugins/PluginsService.java
  es/es-server/src/test/java/org/elasticsearch/common/settings/SettingsFilterTests.java
  es/es-server/src/test/java/org/elasticsearch/common/settings/SettingsModuleTests.java
  es/es-testing/src/main/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#8963 Remove the offset start/end value from window function test framework
  sql/src/main/java/io/crate/analyze/WindowFrameDefinition.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/AggregationWindowFunctionsTest.java
Labels: ready-to-merge

#8964 Make offset symbol in FrameBoundDefinition non-nullable
  shared/src/main/java/io/crate/common/collections/Lists2.java
  sql/src/main/java/io/crate/analyze/FrameBoundDefinition.java
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
  sql/src/main/java/io/crate/analyze/WindowFrameDefinition.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupBySingleNumberCollector.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/analyze/WindowDefinitionSerialisationTest.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
Labels: ready-to-merge

#8962 Jenkins: Update openjdk 12 version (bp #8940)
  Jenkinsfile
Labels: ready-to-merge

#8968 Fix time zone offset parsing for value `+0000`
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/types/TimestampType.java
  common/src/test/java/io/crate/types/TimestampTypesTest.java
Labels: ready-to-merge, v/4.0
