Repository crate/crate, pull requests merged in 2019-03, with the labels that each got.

#8303 Fix odering of MetaDataIndexUpgrader
  sql/src/main/java/io/crate/metadata/upgrade/MetaDataIndexUpgrader.java
  sql/src/test/java/io/crate/integrationtests/TablesNeedUpgradeSysCheckTest.java
Labels: ready-to-merge

#8304 Remove TypeFieldMapper
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesModule.java
Labels: ready-to-merge

#8299 Set log level for ignored set session statements to info
  sql/src/main/java/io/crate/planner/statement/SetSessionPlan.java
Labels: ready-to-merge

#8307 Remove the node ingest setting
  es/es-server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java
  es/es-server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  es/es-server/src/main/java/org/elasticsearch/node/Node.java
  es/es-testing/src/main/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#8297 copy edit
  blackbox/docs/config/session.rst
Labels: ready-to-merge

#8315 Fix template upgrade logic to handle templates in custom schemas
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/IndexParts.java
  sql/src/main/java/io/crate/metadata/upgrade/IndexTemplateUpgrader.java
  sql/src/test/java/io/crate/metadata/upgrade/IndexTemplateUpgraderTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8318 Restructure blackbox tests and switch to built-in python unittest
  blackbox/bin/test-all
  blackbox/bin/test-decommission
  blackbox/bin/test-docs
  blackbox/bin/test-hdfs
  blackbox/bin/test-jmx
  blackbox/build.gradle
  blackbox/requirements.txt
  blackbox/shared/src/testutils/__init__.py
  blackbox/test_decommission.py
  blackbox/test_dns_discovery.py
  blackbox/test_docs.py
  blackbox/test_hdfs.py
  blackbox/test_jmx.py
  blackbox/testdata/articles.json
  blackbox/testdata/colors.json
  blackbox/testdata/countries.json
  blackbox/testdata/departments.json
  blackbox/testdata/employees.json
  blackbox/testdata/locations.json
  blackbox/testdata/locations_import_summary1.json
  blackbox/testdata/locations_import_summary2.json
  blackbox/testdata/photos.json
  blackbox/testdata/uservisits.json
  blackbox/testutils/__init__.py
  blackbox/testutils/paths.py
  blackbox/testutils/ports.py
Labels: ready-to-merge

#8321 fix formatting
  blackbox/docs/admin/privileges.rst
Labels: ready-to-merge

#8320 Remove more unused components
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/forcemerge/ForceMergeResponse.java
  es/es-server/src/main/java/org/elasticsearch/bootstrap/SystemCallFilter.java
  es/es-server/src/main/java/org/elasticsearch/common/io/FileSystemUtils.java
  es/es-server/src/main/java/org/elasticsearch/index/analysis/FieldNameAnalyzer.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/Engine.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/main/java/org/elasticsearch/index/flush/FlushStats.java
  es/es-server/src/main/java/org/elasticsearch/index/refresh/RefreshStats.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  es/es-server/src/main/java/org/elasticsearch/index/translog/Translog.java
  es/es-server/src/main/java/org/elasticsearch/index/translog/TranslogStats.java
Labels: ready-to-merge

#8324 Fix java version parsing for JDK 12 variants
  sql/src/main/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheck.java
  sql/src/test/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheckTest.java
Labels: ready-to-merge, v/3.3

#8314 Char sequence `\\'` in Escaped String Literals result in ParsingException
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/Literals.java
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
Labels: ready-to-merge, v/3.3

#8323 Make PARTITIONED_TABLE_PART package private
  sql/src/main/java/io/crate/metadata/IndexParts.java
  sql/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
Labels: ready-to-merge

#8329 Remove PortPool from blackbox tests
  blackbox/test_decommission.py
  blackbox/test_dns_discovery.py
  blackbox/test_docs.py
  blackbox/test_hdfs.py
  blackbox/test_jmx.py
  blackbox/testutils/ports.py
Labels: ready-to-merge

#8319 Add a gradle task to release a CrateDB Community Edition distribution.
  app/build.gradle
  app/src/bin/crate.bat
  app/src/bin/crate.in.sh
  devs/docs/basics.rst
Labels: ready-to-merge, v/3.3

#8325 Apply a timeout to blackbox tests
  Jenkinsfile
Labels: ready-to-merge

#8334 Remove CollectorFieldsVisitor
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  sql/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/CollectorFieldsVisitor.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  sql/src/main/java/io/crate/execution/engine/sort/FieldsVisitorInputFieldComparator.java
  sql/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/CollectorContext.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/RawCollectorExpression.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/SourceLookup.java
  sql/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#8339 Remove enterprise enabled distinction in PrivilegesMetaDataUpgrader
  enterprise/users/src/main/java/io/crate/metadata/PrivilegesMetaDataUpgrader.java
  enterprise/users/src/test/java/io/crate/metadata/PrivilegesMetaDataUpgraderTest.java
Labels: ready-to-merge, v/3.3

#8341 Fix exception handling in SysSnapshots
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshot.java
  sql/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshots.java
  sql/src/test/java/io/crate/expression/reference/sys/snapshot/SysSnapshotsTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8342 Implement and expose 'pg_type.typarray' column
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/main/java/io/crate/protocols/postgres/types/BigIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/BooleanType.java
  sql/src/main/java/io/crate/protocols/postgres/types/CharType.java
  sql/src/main/java/io/crate/protocols/postgres/types/DoubleType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntegerType.java
  sql/src/main/java/io/crate/protocols/postgres/types/JsonType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGType.java
  sql/src/main/java/io/crate/protocols/postgres/types/RealType.java
  sql/src/main/java/io/crate/protocols/postgres/types/SmallIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/TimestampType.java
  sql/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8336 Backport community edition gradle task
  app/build.gradle
  app/src/bin/crate.bat
  app/src/bin/crate.in.sh
  devs/docs/basics.rst
Labels: ready-to-merge

#8354 Add number of available processors to UDC pings
  blackbox/docs/admin/udc.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  udc/src/main/java/io/crate/udc/ping/PingTask.java
  udc/src/test/java/io/crate/udc/ping/PingTaskTest.java
Labels: ready-to-merge, v/3.3

#8356 By-pass license validation on development instances
  licensing/src/main/java/io/crate/license/LicenseService.java
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
Labels: ready-to-merge, v/3.3

#8357 Allow decommission statement when license is expired
  blackbox/docs/editions/enterprise.rst
  licensing/src/test/java/io/crate/license/LicenseServiceTest.java
  sql/src/main/java/io/crate/planner/IsStatementExecutionAllowed.java
  sql/src/test/java/io/crate/planner/ExpiredLicensePlannerTest.java
Labels: ready-to-merge, v/3.3

#8358 Fix memory accounting of window functions
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8369 Log the license once when it is first initialized
  licensing/src/main/java/io/crate/license/LicenseService.java
Labels: ready-to-merge, v/3.3

#8370 Implement and expose 'pg_type.typnotnull' column
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge, v/3.3

#8350 Add subscript expression support on sub-relation columns.
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/types/DataTypes.java
  common/src/main/java/io/crate/types/ObjectType.java
  common/src/test/java/io/crate/types/ObjectTypeTest.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/collections/Lists2.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  sql/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  sql/src/test/java/io/crate/expression/scalar/SubscriptObjectFunctionTest.java
  sql/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/ViewsITest.java
Labels: ready-to-merge

#8373 Backport of #8342
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/main/java/io/crate/protocols/postgres/types/BigIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/BooleanType.java
  sql/src/main/java/io/crate/protocols/postgres/types/CharType.java
  sql/src/main/java/io/crate/protocols/postgres/types/DoubleType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntegerType.java
  sql/src/main/java/io/crate/protocols/postgres/types/JsonType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGType.java
  sql/src/main/java/io/crate/protocols/postgres/types/RealType.java
  sql/src/main/java/io/crate/protocols/postgres/types/SmallIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/TimestampType.java
  sql/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8375 Remove the deprecated USR2 signal handling
  app/src/main/dist/config/crate.yml
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/run.rst
  blackbox/test_decommission.py
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
Labels: ready-to-merge

#8365 Remove the deprecated license.ident setting
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/settings/SharedSettings.java
  sql/src/main/java/io/crate/metadata/settings/CrateSettings.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterSettingsExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8378 Change default column policy to strict
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/column-policy.rst
  blackbox/docs/general/ddl/show-create-table.rst
  blackbox/docs/general/dml.rst
  blackbox/docs/general/dql/geo.rst
  blackbox/docs/sql/statements/create-table.rst
  sql/src/main/java/io/crate/analyze/TableParameterInfo.java
  sql/src/main/java/io/crate/metadata/doc/DocIndexMetaData.java
  sql/src/main/java/io/crate/metadata/table/ColumnPolicy.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
  sql/src/test/java/io/crate/analyze/TableDefinitions.java
  sql/src/test/java/io/crate/integrationtests/BulkInsertOnClientNodeTest.java
  sql/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableConcurrentIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  sql/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#8381 mention graceful stop in run documentation
  blackbox/docs/run.rst
Labels: ready-to-merge

#8383 Fix order-by push down on sub-select queries
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/RelationBoundary.java
  sql/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8376 Run documentation integration tests for community edition.
  Jenkinsfile
  app/build.gradle
  blackbox/bin/test-ce-docs
  blackbox/build.gradle
  blackbox/test_docs.py
Labels: ready-to-merge, v/3.3

#8380 Remove some setting default overrides
  app/src/main/java/org/elasticsearch/node/internal/CrateSettingsPreparer.java
  app/src/test/java/io/crate/node/NodeSettingsTest.java
  app/src/test/java/org/elasticsearch/node/internal/CrateSettingsPreparerTest.java
  common/src/main/java/io/crate/Constants.java
  es/es-server/src/main/java/org/elasticsearch/cluster/ClusterName.java
  es/es-server/src/main/java/org/elasticsearch/http/HttpTransportSettings.java
  es/es-server/src/main/java/org/elasticsearch/search/SearchModule.java
  es/es-server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  sql/src/main/java/io/crate/plugin/SQLPlugin.java
Labels: ready-to-merge

#8388 Make clusteredBy and partitionedBy concrete on CreateTable
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/ClusteredBy.java
  sql-parser/src/main/java/io/crate/sql/tree/CrateTableOption.java
  sql-parser/src/main/java/io/crate/sql/tree/CreateTable.java
  sql-parser/src/main/java/io/crate/sql/tree/PartitionedBy.java
  sql/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/MetaDataToASTNodeResolver.java
Labels: ready-to-merge

#8390 Replace columnPolicy string attributes with the ColumnPolicy enum
  blackbox/docs/general/ddl/show-create-table.rst
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/tree/ColumnPolicy.java
  sql-parser/src/main/java/io/crate/sql/tree/ObjectColumnType.java
  sql/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  sql/src/main/java/io/crate/analyze/MetaDataToASTNodeResolver.java
  sql/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  sql/src/main/java/io/crate/analyze/TableParameterInfo.java
  sql/src/main/java/io/crate/analyze/expressions/ValueNormalizer.java
  sql/src/main/java/io/crate/expression/symbol/DynamicReference.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/main/java/io/crate/metadata/GeneratedReference.java
  sql/src/main/java/io/crate/metadata/IndexReference.java
  sql/src/main/java/io/crate/metadata/Reference.java
  sql/src/main/java/io/crate/metadata/doc/DocIndexMetaData.java
  sql/src/main/java/io/crate/metadata/doc/DocSysColumns.java
  sql/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  sql/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  sql/src/main/java/io/crate/metadata/table/ColumnPolicies.java
  sql/src/main/java/io/crate/metadata/table/ColumnRegistrar.java
  sql/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/InsertFromValuesAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
  sql/src/test/java/io/crate/analyze/TableDefinitions.java
  sql/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  sql/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  sql/src/test/java/io/crate/metadata/GeneratedReferenceTest.java
  sql/src/test/java/io/crate/metadata/ReferenceTest.java
  sql/src/test/java/io/crate/metadata/doc/DocIndexMetaDataTest.java
  sql/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  sql/src/test/java/io/crate/metadata/table/TestingTableInfo.java
Labels: ready-to-merge

#8392 Docs: Remove example that implies dynamic column_policy default
  blackbox/docs/general/ddl/column-policy.rst
Labels: ready-to-merge

#8382 Clarify new USR2 behavior in release notes
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8397 Correct documentation of the `processor` node setting
  blackbox/docs/config/node.rst
Labels: ready-to-merge

#8393 Update `license check` documentation.
  blackbox/docs/admin/system-information.rst
Labels: ready-to-merge

#8402 Remove special BytesRef handling from TestingHelpers
  sql/src/test/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#8384 Implement 'trim()' scalar string function
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/scalar.rst
  blackbox/docs/sql/general/lexical-structure.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/TrimMode.java
  sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  sql/src/test/java/io/crate/expression/scalar/string/TrimFunctionTest.java
Labels: ready-to-merge

#8405 Return NULL for unlimited license expiry date.
  sql/src/main/java/io/crate/expression/reference/sys/cluster/ClusterLicenseExpression.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterLicenseExpressionTest.java
Labels: ready-to-merge, v/3.3

#8406 Fix the gradle run command
  app/src/main/java/io/crate/bootstrap/CrateDB.java
Labels: ready-to-merge

#8398 Fix license cluster check to warn in case of expiration
  enterprise/licensing/src/main/java/io/crate/expression/reference/sys/check/cluster/LicenseCheck.java
  enterprise/licensing/src/main/java/io/crate/license/EnterpriseLicenseService.java
  enterprise/licensing/src/main/java/io/crate/license/LicenseExpiryNotification.java
  enterprise/licensing/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseCheckTest.java
  enterprise/licensing/src/test/java/io/crate/license/LicenseExpiryNotificationTest.java
  enterprise/licensing/src/test/java/io/crate/license/LicenseServiceTest.java
Labels: ready-to-merge, v/3.3

#8407 Make small adjustements to the developer docs
  devs/docs/basics.rst
Labels: ready-to-merge

#8404 made spacing in the release notes consistent
  blackbox/docs/appendices/release-notes/3.0.0.rst
Labels: ready-to-merge

#8411 Dispatch only 1 or 3 args trim function from parser.
  blackbox/docs/general/builtins/scalar.rst
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  sql/src/test/java/io/crate/expression/scalar/string/TrimFunctionTest.java
Labels: ready-to-merge

#8413 Fix flaky license check unit test
  enterprise/licensing/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseCheckTest.java
Labels: ready-to-merge

#8414 Make sure we don't utilize FieldNamesFieldMapper.termQuery
  es/es-server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
Labels: ready-to-merge

#8412 Drop support for BytesRef conversion in data types.
  common/src/main/java/io/crate/types/BooleanType.java
  common/src/main/java/io/crate/types/ByteType.java
  common/src/main/java/io/crate/types/DoubleType.java
  common/src/main/java/io/crate/types/FloatType.java
  common/src/main/java/io/crate/types/GeoPointType.java
  common/src/main/java/io/crate/types/GeoShapeType.java
  common/src/main/java/io/crate/types/IntegerType.java
  common/src/main/java/io/crate/types/LongType.java
  common/src/main/java/io/crate/types/ShortType.java
  common/src/main/java/io/crate/types/TimestampType.java
  common/src/test/java/io/crate/common/collections/MapComparatorTest.java
  common/src/test/java/io/crate/types/LongTypeTest.java
Labels: ready-to-merge

#8416 Add SQL syntax documetation for COMMIT and BEGIN statements.
  blackbox/docs/appendices/compatibility.rst
  blackbox/docs/interfaces/postgres.rst
  blackbox/docs/sql/statements/begin.rst
  blackbox/docs/sql/statements/commit.rst
  blackbox/docs/sql/statements/index.rst
Labels: ready-to-merge, v/3.3

#8419 Upgrade Admin-UI to v1.12.0
  app/build.gradle
  gradle/version.properties
Labels: ready-to-merge, v/3.3

#8417 Handle SimpleCaseExpression conversion separate from SearchedCaseExpression
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
Labels: ready-to-merge

#8408 Remove document re-ordering logic
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java
Labels: ready-to-merge

#8423 Remove duplicate setting defaults definitions
  app/src/main/java/org/elasticsearch/node/internal/CrateSettingsPreparer.java
  app/src/test/java/org/elasticsearch/node/internal/CrateSettingsPreparerTest.java
Labels: ready-to-merge

#8420 Add intellij codeStyle defaults that are closer to our style
  idea/codeStyle.xml
Labels: ready-to-merge

#8426 Avoid NPE if a window is ordered over a column that has null values.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8428 Remove HTTP pipelining code
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpChannel.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/pipelining/HttpPipelinedRequest.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/pipelining/HttpPipelinedResponse.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/pipelining/HttpPipeliningHandler.java
  sql/src/main/java/io/crate/rest/action/SqlHttpHandler.java
Labels: ready-to-merge

#8433 Upgrade Admin-UI to 1.13.0
  gradle/version.properties
Labels: ready-to-merge, v/3.3

#8429 Make window order by symbols part of the statement outputs and replace/map them.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/symbol/DefaultTraversalSymbolVisitor.java
  sql/src/main/java/io/crate/expression/symbol/FunctionCopyVisitor.java
  sql/src/test/java/io/crate/planner/operators/JoinTest.java
  sql/src/test/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge, v/3.2, v/3.3

#8432 Add timeouts to all tests run on jenkins
  Jenkinsfile
Labels: ready-to-merge

#8438 Expose _docid
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/system-columns.rst
  sql/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  sql/src/main/java/io/crate/expression/reference/Doc.java
  sql/src/main/java/io/crate/expression/reference/DocRefResolver.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/DocIdCollectorExpression.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  sql/src/main/java/io/crate/metadata/doc/DocSysColumns.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/GeneratedColumnsTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/UpdateSourceGenTest.java
  sql/src/test/java/io/crate/executor/transport/task/elasticsearch/DocRefResolverTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/metadata/doc/DocIndexMetaDataTest.java
Labels: ready-to-merge

#8418 Clarification Select Multi Value Fields
  blackbox/docs/general/builtins/table-functions.rst
  blackbox/docs/general/dql/selects.rst
Labels: ready-to-merge

#8442 Upgrade Admin-UI to 1.14.0
  gradle/version.properties
Labels: ready-to-merge, v/3.3

#8443 Fix gradle tasks to build javadoc + source JAR files.
  app/build.gradle
Labels: ready-to-merge, v/3.2, v/3.3

#8435 Removed deprecated `license.enterprise` setting.
  blackbox/bin/test-ce-no-enterprise
  blackbox/build.gradle
  blackbox/docs/admin/monitoring.rst
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/2.0.0.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/config/node.rst
  blackbox/test_ce_no_enterprise.py
  blackbox/test_docs.py
  blackbox/test_jmx.py
  blackbox/test_licensing.py
  common/src/main/java/io/crate/settings/SharedSettings.java
  enterprise/functions/src/main/java/io/crate/plugin/EnterpriseFunctionsPlugin.java
  enterprise/functions/src/test/java/io/crate/window/EnterpriseFunctionsProxyTestPlugin.java
  enterprise/functions/src/test/java/io/crate/window/NthValueFunctionIntegrationTest.java
  enterprise/jmx-monitoring/src/main/java/io/crate/plugin/CrateMonitoringPlugin.java
  enterprise/lang-js/src/main/java/io/crate/plugin/JavaScriptLanguagePlugin.java
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavaScriptUDFIntegrationTest.java
  enterprise/licensing/src/main/java/io/crate/expression/reference/sys/check/cluster/LicenseCheck.java
  enterprise/licensing/src/main/java/io/crate/license/EnterpriseLicenseComponent.java
  enterprise/licensing/src/main/java/io/crate/license/EnterpriseLicenseService.java
  enterprise/licensing/src/main/java/io/crate/license/LicenseExpiryNotification.java
  enterprise/licensing/src/test/java/io/crate/expression/reference/sys/check/cluster/LicenseCheckTest.java
  enterprise/licensing/src/test/java/io/crate/license/LicenseServiceTest.java
  enterprise/ssl-impl/src/test/java/io/crate/protocols/http/CrateHttpsTransportIntegrationTest.java
  enterprise/ssl-impl/src/test/java/io/crate/protocols/postgres/SslReqHandlerIntegrationTest.java
  enterprise/users/src/main/java/io/crate/auth/user/UserManagerService.java
  enterprise/users/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  enterprise/users/src/test/java/io/crate/auth/user/StatementPrivilegeValidatorTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/BaseUsersIntegrationTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/SysPrivilegesIntegrationTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/UserSessionIntegrationTest.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java
  sandbox/crate/config/crate.yml
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/auth/user/UserManager.java
  sql/src/main/java/io/crate/metadata/settings/CrateSettings.java
  sql/src/main/java/io/crate/plugin/SQLPlugin.java
  sql/src/test/java/io/crate/analyze/PrivilegesDCLAnalyzerTest.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterSettingsExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
  sql/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  sql/src/test/java/io/crate/testing/DummyUserManager.java
  sql/src/test/java/io/crate/testing/SQLExecutor.java
  sql/src/test/java/io/crate/testing/SQLTransportExecutor.java
  ssl/src/main/java/io/crate/protocols/ssl/SslConfigSettings.java
  udc/src/main/java/io/crate/udc/ping/PingTask.java
  udc/src/test/java/io/crate/udc/ping/PingTaskTest.java
Labels: ready-to-merge

#8450 Add missing PG mapping for ``array(ip)``
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  sql/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge

#8439 Make attributes in WriterProjection final
  sql/src/main/java/io/crate/execution/dsl/projection/WriterProjection.java
Labels: ready-to-merge

#8455 Remove unused TransportGetSettingsAction
  es/es-server/src/main/java/org/elasticsearch/action/ActionModule.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsAction.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsRequestBuilder.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/settings/get/TransportGetSettingsAction.java
  es/es-server/src/main/java/org/elasticsearch/client/IndicesAdminClient.java
  es/es-server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
Labels: ready-to-merge

#8451 Remove the supported enpoints check in CrateRestMainAction
  http/src/main/java/io/crate/plugin/HttpTransportPlugin.java
  http/src/main/java/io/crate/rest/CrateRestMainAction.java
Labels: ready-to-merge

#8456 Reflect 3.2.6 release
  blackbox/docs/appendices/release-notes/3.2.6.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8347 Update netty to 4.1.34
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  gradle/version.properties
Labels: ready-to-merge

#8458 docs: minor improvements
  blackbox/docs/admin/system-information.rst
  blackbox/docs/config/node.rst
  devs/docs/basics.rst
Labels: ready-to-merge

#8445 improve docs for COPY FROM
  blackbox/docs/general/dml.rst
  blackbox/docs/sql/statements/copy-from.rst
Labels: ready-to-merge

#8462 Quote identifiers that contain leading digits or whitespace.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql-parser/src/main/java/io/crate/sql/Identifiers.java
  sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  sql/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8461 Remove most of the rest-layer infrastructure logic
  enterprise/ssl-impl/src/test/java/io/crate/protocols/http/CrateHttpsTransportTest.java
  enterprise/users/src/main/java/io/crate/protocols/http/HttpAuthUpstreamHandler.java
  es/es-server/src/main/java/org/elasticsearch/action/ActionModule.java
  es/es-server/src/main/java/org/elasticsearch/action/support/IndicesOptions.java
  es/es-server/src/main/java/org/elasticsearch/common/network/NetworkModule.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/SettingsFilter.java
  es/es-server/src/main/java/org/elasticsearch/http/HttpServerTransport.java
  es/es-server/src/main/java/org/elasticsearch/node/Node.java
  es/es-server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java
  es/es-server/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
  es/es-server/src/main/java/org/elasticsearch/rest/AbstractRestChannel.java
  es/es-server/src/main/java/org/elasticsearch/rest/BytesRestResponse.java
  es/es-server/src/main/java/org/elasticsearch/rest/MethodHandlers.java
  es/es-server/src/main/java/org/elasticsearch/rest/RestChannel.java
  es/es-server/src/main/java/org/elasticsearch/rest/RestController.java
  es/es-server/src/main/java/org/elasticsearch/rest/RestHandler.java
  es/es-server/src/main/java/org/elasticsearch/rest/RestRequest.java
  es/es-server/src/main/java/org/elasticsearch/rest/RestResponse.java
  es/es-server/src/main/java/org/elasticsearch/rest/package-info.java
  es/es-testing/src/main/java/org/elasticsearch/http/NullDispatcher.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpChannel.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  es/es-transport/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
  http/src/main/java/io/crate/plugin/HttpTransportPlugin.java
  http/src/main/java/io/crate/protocols/http/CrateNettyHttpServerTransport.java
  http/src/main/java/io/crate/protocols/http/Headers.java
  http/src/main/java/io/crate/protocols/http/MainAndStaticFileHandler.java
  http/src/main/java/io/crate/protocols/http/Responses.java
  http/src/main/java/io/crate/protocols/http/StaticSite.java
  http/src/main/java/io/crate/rest/CrateRestMainAction.java
  http/src/test/java/io/crate/protocols/http/HeadersTest.java
  sql/src/main/java/io/crate/rest/action/SqlHttpHandler.java
Labels: ready-to-merge

#8467 Remove undocumented netty settings
  es/es-transport/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  es/es-transport/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
Labels: ready-to-merge

#8463 Added quote_ident scalar string function.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/string/QuoteIdentFunction.java
  sql/src/test/java/io/crate/expression/scalar/string/QuoteIdentFunctionTest.java
Labels: ready-to-merge

#8470 Limit HEAP of license blackbox test instances to 256MB
  blackbox/test_licensing.py
Labels: ready-to-merge, v/3.3

#8471 Fix jenkins `test jar jdk11` step
  Jenkinsfile
Labels: ready-to-merge

#8474 Do not quote identifiers that contain digits between characters.
  blackbox/docs/general/builtins/scalar.rst
  sql-parser/src/main/java/io/crate/sql/Identifiers.java
  sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
Labels: ready-to-merge

#8424 Migrate to lucene 8.0.0
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/dql/fulltext.rst
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/EdgeNGramTokenFilterFactory.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/LowerCaseTokenizerFactory.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/NGramTokenFilterFactory.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/SnowballAnalyzer.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/SnowballAnalyzerProvider.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/StandardHtmlStripAnalyzer.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/XLowerCaseTokenizer.java
  es/es-server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
  es/es-server/src/main/java/org/apache/lucene/queries/ExtendedCommonTermsQuery.java
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/MinimumScoreCollector.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/search/Queries.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/analysis/StopAnalyzerProvider.java
  es/es-server/src/main/java/org/elasticsearch/index/analysis/StopTokenFilterFactory.java
  es/es-server/src/main/java/org/elasticsearch/index/cache/bitset/BitsetFilterCache.java
  es/es-server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  es/es-server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicy.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexSearcherWrapper.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  es/es-server/src/main/java/org/elasticsearch/indices/analysis/PreBuiltAnalyzers.java
  es/es-server/src/main/java/org/elasticsearch/search/profile/query/ProfileScorer.java
  es/es-server/src/main/java/org/elasticsearch/search/profile/query/QueryTimingType.java
  es/es-testing/src/main/java/org/elasticsearch/index/analysis/MyFilterTokenFilterFactory.java
  es/es-testing/src/main/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java
  es/es-testing/src/main/java/org/elasticsearch/test/engine/MockEngineSupport.java
  gradle/version.properties
  sql/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/DummyScorer.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollector.java
  sql/src/main/java/io/crate/execution/engine/sort/InputFieldComparator.java
  sql/src/main/java/io/crate/execution/engine/sort/NullFieldComparatorSource.java
  sql/src/main/java/io/crate/execution/jobs/InstrumentedIndexSearcher.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/LuceneCollectorExpression.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/ScoreCollectorExpression.java
  sql/src/main/java/io/crate/lucene/ArrayLengthQuery.java
  sql/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/expression/reference/sys/shard/ShardMinLuceneVersionExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  sql/src/test/java/io/crate/integrationtests/TablesNeedUpgradeSysCheckTest.java
  sql/src/test/java/org/apache/lucene/index/AssertingLeafReader.java
Labels: ready-to-merge

#8481 Extract used columns from received symbols (as ordering can be on functions)
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8479 Rename column information_schema.table_partitions.schema_name to table_schema
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/partitioned-tables.rst
  blackbox/docs/general/information-schema.rst
  sql/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  sql/src/test/java/io/crate/integrationtests/DanglingIndicesIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#8484 Update guava to 27.1
  gradle/version.properties
Labels: ready-to-merge

#8489 Fix limit application in nested window agg operators
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
Labels: ready-to-merge, v/3.2, v/3.3
