Repository crate/crate, pull requests merged in 2019-02, with the labels that each got.

#8188 Enable jobs counter throttling for IO iterators regardless of partition creation.
  sql/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
Labels: ready-to-merge, v/3.1, v/3.2

#8196 Reflect 3.1.6 release
  blackbox/docs/appendices/release-notes/3.1.6.rst
  blackbox/docs/appendices/release-notes/index.rst
Labels: ready-to-merge

#8197 Bump version to 3.1.7-SNAPSHOT
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8193 Change node decommission statement to blocking
  sql/src/main/java/io/crate/cluster/decommission/TransportDecommissionNodeAction.java
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
Labels: ready-to-merge

#8198 Add a node check that checks the JVM version
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheck.java
  sql/src/main/java/io/crate/expression/reference/sys/check/node/SysNodeChecksModule.java
  sql/src/test/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheckTest.java
  sql/src/test/java/io/crate/integrationtests/SysNodeCheckerIntegrationTest.java
Labels: ready-to-merge

#8200 Mark the node decommissioning using USR2 as deprecated
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
Labels: ready-to-merge

#8202 Run tests with jdk12
  Jenkinsfile
Labels: ready-to-merge

#8203 Prepare 3.2.3 release
  blackbox/docs/appendices/release-notes/3.2.3.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8204 Fix parsing of 12-ea java version strings in node check
  sql/src/main/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheck.java
  sql/src/test/java/io/crate/expression/reference/sys/check/node/JvmVersionNodeCheckTest.java
Labels: ready-to-merge

#8209 Reflect 3.2.3 release
  blackbox/docs/appendices/release-notes/3.2.3.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8208 Update gradle to 5.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge

#8206 Force Pygments to 2.3.1 for rtd builds
  blackbox/docs/requirements.txt
Labels: ready-to-merge, v/3.1, v/3.2

#8205 Fix 'availability:none' case for node decommission
  blackbox/docs/src/doc_tests/process_test.py
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
Labels: ready-to-merge

#8207 The ChainableActions undo mechanism doesn't work for a one action chain.
  sql/src/main/java/io/crate/execution/support/ChainableActions.java
  sql/src/test/java/io/crate/execution/support/ChainableActionsTest.java
Labels: ready-to-merge

#8210 Remove Mqtt mentions from dev docs
  devs/docs/architecture.rst
Labels: ready-to-merge

#8219 Inline logic from DeleteAllPartitionsTask into plan
  sql/src/main/java/io/crate/execution/dml/delete/DeleteAllPartitionsTask.java
  sql/src/main/java/io/crate/planner/node/ddl/DeleteAllPartitions.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#8218 Expose sum_of_durations in sys.jobs_metric
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/stats/JobsLogService.java
  sql/src/main/java/io/crate/execution/engine/collect/stats/JobsLogs.java
  sql/src/main/java/io/crate/metadata/sys/ClassifiedHistograms.java
  sql/src/main/java/io/crate/metadata/sys/ClassifiedMetrics.java
  sql/src/main/java/io/crate/metadata/sys/SysMetricsTableInfo.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/MetricsITest.java
  sql/src/test/java/io/crate/metadata/sys/ClassifiedMetricsTest.java
Labels: ready-to-merge

#8220 Move ESClusterUpdateSettingsTask logic into plan
  sql/src/main/java/io/crate/execution/ddl/ESClusterUpdateSettingsTask.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/node/ddl/UpdateSettingsPlan.java
  sql/src/test/java/io/crate/executor/transport/DependencyCarrierDDLTest.java
  sql/src/test/java/io/crate/planner/PlannerTest.java
  sql/src/test/java/io/crate/planner/node/ddl/UpdateSettingsPlanTest.java
Labels: ready-to-merge

#8217 Fixed an issue that caused the basic auth prompt to fail in safari
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/main/java/io/crate/protocols/http/HttpAuthUpstreamHandler.java
Labels: ready-to-merge, v/3.2

#8225 Build the main enterprise:functions module under a test configuration.
  benchmarks/build.gradle
  enterprise/functions/build.gradle
Labels: ready-to-merge

#8215 Run blackbox tests also on each PR
  Jenkinsfile
  blackbox/docs/src/doc_tests/process_test.py
Labels: ready-to-merge

#8226 Query stats are exposing the metrics based on the sys.metrics measurements.
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/QueryStats.java
  enterprise/jmx-monitoring/src/test/java/io/crate/beans/QueryStatsTest.java
  sql/src/main/java/io/crate/metadata/sys/ClassifiedMetrics.java
Labels: ready-to-merge

#8234 Mention try_cast in value-expressions documentation
  blackbox/docs/sql/general/value-expressions.rst
Labels: ready-to-merge

#8238 Andrei/jenkins agents
  Jenkinsfile
Labels: ready-to-merge

#8236 Handle dynamic property and _meta version changes in template schema updates
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/collections/Lists2.java
  sql/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java
  sql/src/test/java/io/crate/collections/Lists2Test.java
  sql/src/test/java/io/crate/execution/ddl/TransportSchemaUpdateActionTest.java
Labels: ready-to-merge, v/3.2

#8235 Add window batch iterator benchmark
  benchmarks/src/test/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  enterprise/functions/src/main/java/io/crate/window/NthValueFunctions.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
Labels: ready-to-merge

#8232 Expose the totalCount and sumOfDurations query stats.
  blackbox/docs/admin/monitoring.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/QueryStats.java
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/QueryStatsMBean.java
  enterprise/jmx-monitoring/src/test/java/io/crate/beans/QueryStatsTest.java
Labels: ready-to-merge

#8239 Mark setting 'cluster.graceful_stop.reallocate' as deprecated
  app/src/main/dist/config/crate.yml
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/config/cluster.rst
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterSettingsExpressionTest.java
Labels: ready-to-merge

#8229 Clarified the casting documentation on changes shipped with 3.2.
  blackbox/docs/general/ddl/data-types.rst
Labels: ready-to-merge

#8245 Fix null constraints check for partitioned columns
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  sql/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge, v/3.2

#8249 idea: Change unused import inspection level to error
  idea/codeInspection.xml
Labels: ready-to-merge

#8255 Remove more unused ES components
  azure-discovery/src/test/java/io/crate/azure/AbstractAzureComputeServiceTestCase.java
  es/es-server/src/main/java/org/apache/lucene/queries/BinaryDocValuesRangeQuery.java
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/main/java/org/elasticsearch/action/ActionModule.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/NodeInfo.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/NodesInfoAction.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/NodesInfoRequestBuilder.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/NodesInfoResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/TransportNodesInfoAction.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/settings/ClusterGetSettingsRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/UpgradeRequestBuilder.java
  es/es-server/src/main/java/org/elasticsearch/action/support/ActionFilterChain.java
  es/es-server/src/main/java/org/elasticsearch/action/support/WriteRequestBuilder.java
  es/es-server/src/main/java/org/elasticsearch/action/support/master/info/ClusterInfoRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/support/master/info/ClusterInfoRequestBuilder.java
  es/es-server/src/main/java/org/elasticsearch/client/ClusterAdminClient.java
  es/es-server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  es/es-server/src/main/java/org/elasticsearch/cluster/MergableCustomMetaData.java
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/ClusterNameExpressionResolver.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocationCommand.java
  es/es-server/src/main/java/org/elasticsearch/common/geo/GeoDistance.java
  es/es-server/src/main/java/org/elasticsearch/common/inject/PreProcessModule.java
  es/es-server/src/main/java/org/elasticsearch/common/inject/internal/ErrorHandler.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/search/XMoreLikeThis.java
  es/es-server/src/main/java/org/elasticsearch/common/util/AbstractBigArray.java
  es/es-server/src/main/java/org/elasticsearch/common/xcontent/ObjectParserHelper.java
  es/es-server/src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java
  es/es-server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/AbstractSortingNumericDocValues.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/DocValueBits.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/GeoPointValues.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/SingletonMultiGeoPointValues.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractAtomicGeoPointFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/NonEstimatingEstimator.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/Uid.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/AbstractIndexShardComponent.java
  es/es-server/src/main/java/org/elasticsearch/indices/AbstractIndexShardCacheEntity.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesService.java
  es/es-server/src/main/java/org/elasticsearch/node/Node.java
  es/es-server/src/main/java/org/elasticsearch/node/NodeService.java
  es/es-server/src/main/java/org/elasticsearch/plugins/spi/NamedXContentProvider.java
  es/es-server/src/main/java/org/elasticsearch/transport/TaskAwareTransportRequestHandler.java
  es/es-server/src/main/java/org/elasticsearch/transport/TransportInfo.java
  es/es-server/src/main/java/org/elasticsearch/transport/TransportStats.java
  es/es-testing/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java
  es/es-testing/src/test/java/org/elasticsearch/test/test/InternalTestClusterTests.java
Labels: ready-to-merge

#8254 Bump java version to 11
  Jenkinsfile
  azure-pipelines.yml
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/hdfs/src/tests.py
  blackbox/monitoring/src/tests.py
  build.gradle
  devs/docs/basics.rst
  enterprise/lang-js/src/main/java/io/crate/operation/language/JavaScriptUserDefinedFunction.java
  gradle/javaModule.gradle
Labels: ready-to-merge

#8263 Remove BWC error handling from SettingsModule
  es/es-server/src/main/java/org/elasticsearch/common/settings/SettingsModule.java
Labels: ready-to-merge

#8268 Create a new stream every time we request the iterator of a stream backed iterable.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupBySingleNumberCollector.java
  sql/src/main/java/io/crate/execution/engine/join/RamBlockSizeCalculator.java
  sql/src/test/java/io/crate/execution/engine/aggregation/GroupBySingleNumberCollectorTest.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8274 JoinIntegrationTest: reset table stats and circuit breaker after tests that alter them.
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#8273 upgrade admin-ui to 1.11.4
  app/build.gradle
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8272 Exit with a more friendly error if there is no java installation
  app/src/bin/crate.in.sh
Labels: ready-to-merge

#8269 Remove more unused ES components
  es/es-server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
  es/es-server/src/main/java/org/elasticsearch/action/ActionFuture.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/settings/ClusterUpdateSettingsResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/support/AdapterActionFuture.java
  es/es-server/src/main/java/org/elasticsearch/action/support/broadcast/BroadcastShardResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/support/master/AcknowledgedResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/support/master/ShardsAcknowledgedResponse.java
  es/es-server/src/main/java/org/elasticsearch/action/support/nodes/BaseNodesRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/support/nodes/BaseNodesResponse.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocateUnassignedDecision.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocationCommands.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/common/unit/DistanceUnit.java
  es/es-server/src/main/java/org/elasticsearch/index/cache/bitset/BitsetFilterCache.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/AtomicDoubleFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/BinaryFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/BooleanFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentFieldMappers.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/IpFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/DocsStats.java
  es/es-server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java
  es/es-server/src/main/java/org/elasticsearch/indices/breaker/AllCircuitBreakerStats.java
  es/es-server/src/main/java/org/elasticsearch/indices/breaker/BreakerSettings.java
  es/es-server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  es/es-server/src/main/java/org/elasticsearch/rest/BytesRestResponse.java
  es/es-server/src/main/java/org/elasticsearch/search/DocValueFormat.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#8276 Remove deprecated ON DUPLICATE KEY syntax
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/statements/insert.rst
  blackbox/docs/src/doc_tests/process_test.py
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/Insert.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzer.java
  sql/src/main/java/io/crate/analyze/InsertFromValuesAnalyzer.java
  sql/src/main/java/io/crate/analyze/ValuesAwareExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/ValuesResolver.java
  sql/src/main/java/io/crate/analyze/relations/ExcludedFieldProvider.java
  sql/src/test/java/io/crate/action/sql/SessionTest.java
  sql/src/test/java/io/crate/analyze/InsertFromSubQueryAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/InsertFromValuesAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/relations/ExcludedFieldProviderTest.java
  sql/src/test/java/io/crate/integrationtests/ConcurrencyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  sql/src/test/java/io/crate/planner/InsertPlannerTest.java
Labels: ready-to-merge

#8279 NestedLoopJoin: don't switch tables if order by was pushed down.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  sql/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  sql/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8280 Move most ReadOnlyNodeIntegrationTest test cases into a unit test
  sql/src/test/java/io/crate/analyze/IsWriteOperationTest.java
  sql/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java
Labels: ready-to-merge

#8278 Prepare 3.2.4 release
  blackbox/docs/appendices/release-notes/3.2.4.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  core/src/main/java/io/crate/Version.java
Labels: v/3.3

#8286 Ignore .gradletasknamecache file
  .gitignore
Labels: ready-to-merge

#8288 Reflect 3.2.4 release
  blackbox/docs/appendices/release-notes/3.2.4.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/3.3

#8289 Remove unused nested field related code
  es/es-server/src/main/java/org/elasticsearch/index/IndexSortConfig.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/IndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/UidIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractLatLonPointDVIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/BinaryDVIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/BytesBinaryDVIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/ConstantIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/PagedBytesIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/SortedNumericDVIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/fielddata/plain/SortedSetDVOrdinalsIndexFieldData.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/TypeFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/UidFieldMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  sql/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
Labels: ready-to-merge

#8252 Support string literals with c-style character espaces
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/sql/general/lexical-structure.rst
  blackbox/docs/src/doc_tests/tests.py
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/Literals.java
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/EscapedCharStringLiteral.java
  sql-parser/src/test/java/io/crate/sql/LiteralsTest.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
Labels: ready-to-merge, v/3.3

#8211 Remove unused Setting: 'cluster.graceful_stop.reallocate'
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/config/cluster.rst
  sql/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
  sql/src/main/java/io/crate/metadata/settings/CrateSettings.java
  sql/src/test/java/io/crate/expression/reference/sys/cluster/ClusterSettingsExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8281 Make error more user friendly if a user attempts to decommission a node
  enterprise/users/src/main/java/io/crate/auth/user/StatementPrivilegeValidator.java
  enterprise/users/src/test/java/io/crate/auth/user/StatementPrivilegeValidatorTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/UserManagementIntegrationTest.java
  enterprise/users/src/test/java/io/crate/protocols/http/HttpAuthUpstreamHandlerTest.java
  sql/src/main/java/io/crate/user/StubUserManager.java
Labels: ready-to-merge, v/3.3

#8295 Support '\\' and '\'' in Escaped String Literals
  blackbox/docs/sql/general/lexical-structure.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/Literals.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/test/java/io/crate/sql/LiteralsTest.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
Labels: ready-to-merge, v/3.3

#8298 Make reads against the metrics histogram thread-safe.
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/QueryStats.java
  enterprise/jmx-monitoring/src/test/java/io/crate/beans/QueryStatsTest.java
  sql/src/main/java/io/crate/execution/engine/collect/stats/JobsLogs.java
  sql/src/main/java/io/crate/metadata/sys/ClassifiedMetrics.java
  sql/src/main/java/io/crate/metadata/sys/MetricsView.java
  sql/src/main/java/io/crate/metadata/sys/SysMetricsTableInfo.java
  sql/src/test/java/io/crate/execution/engine/collect/stats/JobsLogsTest.java
  sql/src/test/java/io/crate/integrationtests/MetricsITest.java
  sql/src/test/java/io/crate/metadata/sys/ClassifiedMetricsTest.java
Labels: ready-to-merge, v/3.2, v/3.3
