Repository crate/crate, pull requests merged in 2019-09, with the labels that each got.

#9094 Port the InternalEngine testing layers and tests.
  es/es-server/src/main/java/org/elasticsearch/index/engine/Segment.java
  es/es-server/src/test/java/org/elasticsearch/common/TriFunction.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/EngineSearcherTotalHitsMatcher.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  es/es-server/src/test/java/org/elasticsearch/index/translog/SnapshotMatchers.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#9099 Always fail engine if delete operation fails.
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#9101 Adds replication operation tests ported over from ES.
  es/es-server/src/test/java/org/elasticsearch/action/support/replication/ClusterStateCreationUtils.java
  es/es-server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java
Labels: ready-to-merge

#9079 Make alter table operation atomic
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataUpdateSettingsService.java
  sql/src/main/java/io/crate/execution/TransportExecutorModule.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableRequest.java
  sql/src/main/java/io/crate/execution/ddl/tables/TransportAlterTableAction.java
  sql/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  sql/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  sql/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
Labels: ready-to-merge

#9102 Improve resiliency of alter table add
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  sql/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  sql/src/main/java/io/crate/metadata/cluster/DDLClusterStateHelpers.java
  sql/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  sql/src/test/java/io/crate/metadata/cluster/DDLClusterStateHelpersTest.java
Labels: ready-to-merge

#9104 Add a rule to rewrite Collect to Get
  sql/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  sql/src/main/java/io/crate/planner/WhereClauseOptimizer.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/optimizer/Optimizer.java
  sql/src/main/java/io/crate/planner/optimizer/Rule.java
  sql/src/main/java/io/crate/planner/optimizer/rule/DeduplicateOrder.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MergeAggregateAndCollectToCount.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MergeFilterAndCollect.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MergeFilters.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathBoundary.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathFetchOrEval.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathGroupBy.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathHashJoin.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathNestedLoop.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathOrder.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathUnion.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathWindowAgg.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathBoundary.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathFetchOrEval.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathUnion.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RemoveRedundantFetchOrEval.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RewriteCollectToGet.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/optimizer/rule/MergeFiltersTest.java
Labels: ready-to-merge

#9105 Use separate translog dir in testDeleteWithFatalError.
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#9106 Flush engine after big merge.
  es/es-server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/IndexSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/main/java/org/elasticsearch/index/merge/OnGoingMerge.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#9096 Introduce new circuit breaker to limit requests cardinality and upser…
  benchmarks/src/test/java/io/crate/execution/jobs/CheckFreeMemoryAlternativeMethodsBenchmark.java
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/breaker/EstimateRowSize.java
  sql/src/main/java/io/crate/breaker/TypeGuessEstimateRowSize.java
  sql/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/test/java/io/crate/execution/engine/indexing/BulkShardCreationLimiterTest.java
Labels: ready-to-merge

#9088 Use cause to determine if node with primary is closing.
  es/es-server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java
  es/es-server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java
Labels: ready-to-merge

#9109 Move sync translog operation outside writeLock to improve performance.
  es/es-server/src/main/java/org/elasticsearch/index/translog/Translog.java
Labels: ready-to-merge

#9108 Simplify code by using java.lang.Math's available methods
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
Labels: ready-to-merge

#9110 Re-use EstimateRowSize in RowAccountingWithEstimators
  sql/src/main/java/io/crate/breaker/RowAccountingWithEstimators.java
Labels: ready-to-merge

#9098 Fail engine if hit document failure on replicas.
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#9111 Fix column’s ordinal being NULL on tables created < 4.0.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  sql/src/test/java/io/crate/execution/engine/collect/sources/ColumnsIterableTest.java
Labels: ready-to-merge, v/4.0

#9112 Assert cluster state size in intergration test layer.
  es/es-testing/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
Labels: ready-to-merge

#9107 Update gradle to 5.6.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge

#9115 Assert number of version lookup only if assertions are enabled.
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#9114 De-couple param binding from WhereClauseAnalyzer
  sql/src/main/java/io/crate/analyze/WhereClause.java
  sql/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/main/java/io/crate/planner/operators/Count.java
Labels: ready-to-merge

#9117 Do not add hidden settings to table default settings.
  blackbox/docs/general/ddl/show-create-table.rst
  sql/src/main/java/io/crate/analyze/GenericPropertiesConverter.java
  sql/src/main/java/io/crate/analyze/TableParameters.java
  sql/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
Labels: ready-to-merge, v/4.0

#9116 Move FrameBound tests into the package of the FrameBound class
  sql-parser/src/test/java/io/crate/sql/tree/CurrentRowFrameBoundTest.java
  sql-parser/src/test/java/io/crate/sql/tree/OffsetFollowingFrameBoundTest.java
  sql-parser/src/test/java/io/crate/sql/tree/OffsetPrecedingFrameBoundTest.java
  sql-parser/src/test/java/io/crate/sql/tree/UnboundedFollowingFrameBoundTest.java
  sql-parser/src/test/java/io/crate/sql/tree/UnboundedPrecedingFrameBoundTest.java
Labels: ready-to-merge

#9118 Remove partition tie break restriction
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  sql/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#9119 Optimize size estimation for arrays of fixed size elements
  sql/src/main/java/io/crate/breaker/ArraySizeEstimator.java
  sql/src/main/java/io/crate/breaker/ConstSizeEstimator.java
  sql/src/main/java/io/crate/breaker/SizeEstimatorFactory.java
Labels: ready-to-merge

#9122 Fix InternalEngineTests#assertOpsOnPrimary.
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#9123 Extract more details of frame bound calculations out of WindowFunctionBatchIterator
  benchmarks/src/test/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  sql/src/main/java/io/crate/analyze/SymbolEvaluator.java
  sql/src/main/java/io/crate/execution/engine/window/ComputeFrameBoundary.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
Labels: ready-to-merge

#9126 Handle delete document level failures.
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#8740 Adding elasticsearch phonetic analyzer / tokenizer
  app/build.gradle
  app/src/main/java/io/crate/node/CrateNode.java
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/analyzers.rst
  blackbox/docs/general/dql/fulltext.rst
  blackbox/docs/general/information-schema.rst
  es/es-analysis-phonetic/build.gradle
  es/es-analysis-phonetic/licenses/commons-codec-1.11.jar.sha1
  es/es-analysis-phonetic/licenses/commons-codec-LICENSE.txt
  es/es-analysis-phonetic/licenses/commons-codec-NOTICE.txt
  es/es-analysis-phonetic/licenses/lucene-LICENSE.txt
  es/es-analysis-phonetic/licenses/lucene-NOTICE.txt
  es/es-analysis-phonetic/licenses/lucene-analyzers-phonetic-8.2.0.jar.sha1
  es/es-analysis-phonetic/src/main/java/org/elasticsearch/index/analysis/PhoneticTokenFilterFactory.java
  es/es-analysis-phonetic/src/main/java/org/elasticsearch/index/analysis/phonetic/HaasePhonetik.java
  es/es-analysis-phonetic/src/main/java/org/elasticsearch/index/analysis/phonetic/KoelnerPhonetik.java
  es/es-analysis-phonetic/src/main/java/org/elasticsearch/index/analysis/phonetic/Nysiis.java
  es/es-analysis-phonetic/src/main/java/org/elasticsearch/plugin/analysis/AnalysisPhoneticPlugin.java
  es/es-analysis-phonetic/src/test/java/org/elasticsearch/index/analysis/AnalysisPhoneticFactoryTests.java
  es/es-analysis-phonetic/src/test/java/org/elasticsearch/index/analysis/SimplePhoneticAnalysisTests.java
  es/es-analysis-phonetic/src/test/resources/org/elasticsearch/index/analysis/phonetic-1.yml
  es/es-testing/src/main/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java
  settings.gradle
Labels: ready-to-merge

#9130 Fix some spelling mistakes
  app/src/main/java/io/crate/bootstrap/CrateDB.java
  app/src/main/java/io/crate/plugin/PluginLoaderPlugin.java
  blob/src/main/java/io/crate/blob/BlobService.java
  common/src/test/java/io/crate/interval/IntervalParserTest.java
  common/src/test/java/io/crate/types/TypeConversionTest.java
  sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/NegativeExpression.java
  sql-parser/src/main/java/io/crate/sql/tree/Update.java
  sql/src/main/java/io/crate/analyze/UpdateAnalyzer.java
Labels: ready-to-merge

#9136 Exclude `node.store.allow_mmap` from table/partition defaults.
  sql/src/main/java/io/crate/analyze/TableParameters.java
Labels: ready-to-merge

#9144 Remove assertion about nodes in a request in AsyncAction
  es/es-server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java
Labels: ready-to-merge, v/4.0

#9139 Update admin ui to 1.15.2
  blackbox/docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.0

#9147 Prepare release 4.0.5
  blackbox/docs/appendices/release-notes/4.0.5.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9151 Reflect release 4.0.5.
  blackbox/docs/appendices/release-notes/4.0.5.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9152 Bump version to 4.0.6-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9154 Fix a NPE when client disconnects before responses are sent
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/rest/action/SqlHttpHandler.java
Labels: ready-to-merge, v/3.3, v/4.0

#9157 Fix regression in reroute logic when a node passes disk watermarks.
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/cluster/InternalClusterInfoService.java
  es/es-testing/src/main/java/org/elasticsearch/cluster/MockInternalClusterInfoService.java
  sql/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
Labels: ready-to-merge, v/4.0

#9163 Remove JVM version dependent GC setting handling
  app/src/bin/crate.bat
  app/src/bin/crate.in.sh
Labels: ready-to-merge

#9162 Add support for ILIKE in the where clause
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/config/node.rst
  blackbox/docs/general/dql/selects.rst
  blackbox/docs/sql/general/lexical-structure.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/ArrayLikePredicate.java
  sql-parser/src/main/java/io/crate/sql/tree/LikePredicate.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/expression/operator/LikeOperator.java
  sql/src/main/java/io/crate/expression/operator/LikeOperators.java
  sql/src/main/java/io/crate/expression/operator/Operator.java
  sql/src/main/java/io/crate/expression/operator/OperatorModule.java
  sql/src/main/java/io/crate/expression/operator/TriPredicate.java
  sql/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  sql/src/main/java/io/crate/lucene/AbstractAnyQuery.java
  sql/src/main/java/io/crate/lucene/AnyLikeQuery.java
  sql/src/main/java/io/crate/lucene/AnyNotLikeQuery.java
  sql/src/main/java/io/crate/lucene/LikeQuery.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  sql/src/test/java/io/crate/expression/operator/LikeOperatorTest.java
  sql/src/test/java/io/crate/expression/operator/any/AnyLikeOperatorTest.java
  sql/src/test/java/io/crate/expression/operator/any/AnyNotLikeOperatorTest.java
  sql/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  sql/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#9167 Add a node column to sys.jobs_log
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/stats/JobsLogService.java
  sql/src/main/java/io/crate/metadata/sys/SysJobsLogTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysJobsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  sql/src/test/java/io/crate/execution/engine/collect/stats/JobsLogsTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#9171 Move subquery paramers binding down to FetchOrEval#toInputColOrFetchRef.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/FetchOrEval.java
  sql/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge

#9174 Remove incorrect parenthesis from optimize synopsis
  blackbox/docs/sql/statements/optimize.rst
Labels: ready-to-merge

#9170 Upgrade Admin UI version to 1.15.3
  blackbox/docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#9172 Fix some spelling mistakes
  azure-discovery/src/test/java/io/crate/azure/discovery/AzureSeedHostsProviderTest.java
  dex/src/main/java/io/crate/data/join/JoinBatchIterator.java
  dex/src/test/java/io/crate/data/FlatMapBatchIteratorTest.java
  enterprise/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  enterprise/licensing/src/test/java/io/crate/license/LicenseConverterTest.java
Labels: ready-to-merge

#9176 Update netty to 4.1.42
  gradle/version.properties
Labels: ready-to-merge

#9175 Allow unsafe for netty
  app/src/bin/crate.bat
  app/src/bin/crate.in.sh
Labels: ready-to-merge

#9181 Use NON_RECYCLING_INSTANCE BigArrays for hyperloglog_distinct
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  enterprise/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
Labels: ready-to-merge, v/3.3, v/4.0

#9180 Remove unused circuitBreakingInstance from BigArrays
  es/es-server/src/main/java/org/elasticsearch/common/util/BigArrays.java
Labels: ready-to-merge

#9184 Release 3.3.6
  blackbox/docs/appendices/release-notes/3.3.6.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#9186 Bump version to 3.3.7-SNAPSHOT
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#9188 Only log create-table analyzer warnings once.
  sql/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  sql/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
Labels: ready-to-merge

#9192 [Jenkins] Pin adopt JDK to 1.12.0-2
  Jenkinsfile
Labels: ready-to-merge

#9190 Remove BigArrays argument to AggregationFunction.newState
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/AggregateCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/GroupingLongCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/aggregation/GroupingStringCollectorBenchmark.java
  benchmarks/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationBenchmark.java
  enterprise/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/AggregateCollector.java
  sql/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  sql/src/main/java/io/crate/execution/engine/aggregation/AggregationPipe.java
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupingCollector.java
  sql/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/AverageAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/PercentileAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/StringAgg.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
  sql/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/StringAggTest.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/operation/aggregation/AggregationTest.java
Labels: ready-to-merge

#9149 Expose segment information in sys.segments table
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  sql/src/main/java/io/crate/expression/reference/sys/shard/ShardSegment.java
  sql/src/main/java/io/crate/expression/reference/sys/shard/ShardSegments.java
  sql/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSegmentsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
  sql/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#9191 Remove some redundant != null checks
  es/es-server/src/main/java/org/elasticsearch/ElasticsearchException.java
  es/es-server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
Labels: ready-to-merge

#9160 Extract a ShardStateObserver from ShardStateAwareRemoteCollector
  sql/src/main/java/io/crate/execution/engine/collect/RemoteCollectorFactory.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/ShardStateAwareRemoteCollector.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/ShardStateObserver.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/ShardStateAwareRemoteCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/ShardStateObserverTest.java
Labels: ready-to-merge

#9189 Reflect release 3.3.6
  blackbox/docs/appendices/release-notes/3.3.6.rst
  blackbox/docs/appendices/release-notes/index.rst
Labels: ready-to-merge

#9193 Fix synchronization in LocalCheckpointTracker
  es/es-server/src/main/java/org/elasticsearch/index/seqno/LocalCheckpointTracker.java
Labels: ready-to-merge
