Repository crate/crate, pull requests merged in 2019-04, with the labels that each got.

#8490 Make orderBy processing in WindowAgg a bit less imperative
  sql/src/main/java/io/crate/analyze/OrderBy.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge

#8493 improve CrateDB editions docs
  blackbox/docs/admin/auth/hba.rst
  blackbox/docs/admin/auth/methods.rst
  blackbox/docs/admin/monitoring.rst
  blackbox/docs/admin/privileges.rst
  blackbox/docs/admin/system-information.rst
  blackbox/docs/admin/user-management.rst
  blackbox/docs/appendices/release-notes/3.3.0.rst
  blackbox/docs/config/node.rst
  blackbox/docs/editions.rst
  blackbox/docs/editions/community.rst
  blackbox/docs/editions/enterprise.rst
  blackbox/docs/editions/index.rst
  blackbox/docs/general/builtins/aggregation.rst
  blackbox/docs/general/builtins/scalar.rst
  blackbox/docs/general/builtins/window-functions.rst
  blackbox/docs/general/ddl/create-table.rst
  blackbox/docs/general/user-defined-functions.rst
  blackbox/docs/index.rst
  blackbox/docs/sql/statements/set-license.rst
  blackbox/editions.txt
Labels: ready-to-merge

#8495 Implement 'current_setting' scalar funtion
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/postgres/CurrentSettingFunction.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSetting.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  sql/src/main/java/io/crate/planner/node/management/ShowSessionParameterPlan.java
  sql/src/test/java/io/crate/expression/scalar/postgres/CurrentSettingFunctionTest.java
Labels: ready-to-merge

#8496 Remove indexsort configurations and related methods.
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/IndexService.java
  es/es-server/src/main/java/org/elasticsearch/index/IndexSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/IndexSortConfig.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/EngineConfig.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
  es/es-testing/src/main/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#8446 improve user privileges docs
  blackbox/docs/admin/privileges.rst
  blackbox/docs/admin/user-management.rst
Labels: ready-to-merge

#8464 Remove deprecated nGram, edgeNGram, htmlStrip Tokenfilters names in favour for ngram, edge_ngram, and html_strip
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java
  sql/src/test/java/io/crate/integrationtests/FulltextAnalyzerResolverTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#8494 Execute window functions with partitions distributed
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge

#8498 Drop the uploadArchives and related jars generating gradle tasks
  Jenkinsfile
  app/build.gradle
Labels: ready-to-merge

#8501 Tweak current_setting documentation
  blackbox/docs/config/session.rst
  blackbox/docs/general/builtins/scalar.rst
Labels: ready-to-merge

#8500 Don't stream WindowFrameDefinition as optional
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
Labels: ready-to-merge

#8502 Change deprecated RAMDirectory to ByteBufferDirectory
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  sql/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  sql/src/test/java/io/crate/testing/IndexEnv.java
Labels: ready-to-merge

#8504 Update antlr to 4.7.2.
  gradle/dependencies.gradle
  gradle/version.properties
  sql-parser/src/main/java/io/crate/sql/parser/SqlParser.java
  sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/test/java/io/crate/analyze/DecommissionNodeAnalyzerTest.java
Labels: ready-to-merge

#8505 Update the admin UI to 1.15.0
  gradle/version.properties
Labels: ready-to-merge

#8503 Fix handling of multiple window definitions
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/symbol/WindowFunction.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8507 Extend PR checklist with a note about breaking changes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-to-merge

#8513 Migrate blackbox tests to cr8 CrateNode
  blackbox/build.gradle
  blackbox/docs/admin/system-information.rst
  blackbox/requirements.txt
  blackbox/test_ce_no_enterprise.py
  blackbox/test_decommission.py
  blackbox/test_docs.py
  blackbox/test_hdfs.py
  blackbox/test_jmx.py
  blackbox/test_licensing.py
Labels: ready-to-merge

#8511 Fix logger.debug call to provide right number of arguments
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
Labels: ready-to-merge

#8515 class cast exception fix
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGType.java
  sql/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8516 Migrate test_dns_discovery to unittest and include on PR tests
  Jenkinsfile
  blackbox/bin/test-dns-discovery
  blackbox/test_dns_discovery.py
Labels: ready-to-merge

#8519 This fixes a few bugs on processing window functions over partitioned windows
  blackbox/docs/appendices/release-notes/unreleased.rst
  enterprise/functions/src/main/java/io/crate/window/NthValueFunctions.java
  enterprise/functions/src/test/java/io/crate/window/NthValueFunctionsTest.java
  sql/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  sql/src/main/java/io/crate/execution/engine/window/WindowBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunction.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/RowNumberWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/integrationtests/WindowFunctionsIntegrationTest.java
Labels: ready-to-merge, v/3.3

#8521 Run blackbox tests on medium jenkins slave
  Jenkinsfile
  blackbox/bootstrap.sh
  blackbox/test_decommission.py
  blackbox/test_hdfs.py
  blackbox/test_jmx.py
Labels: ready-to-merge

#8508 docs: Document all supported session settings
  blackbox/docs/config/session.rst
  blackbox/docs/general/builtins/scalar.rst
  blackbox/docs/general/dql/joins.rst
Labels: ready-to-merge

#8525 Implement the pg_catalog.pg_settings table.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/information-schema.rst
  blackbox/docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/execution/engine/collect/sources/SystemCollectSource.java
  sql/src/main/java/io/crate/expression/reference/StaticTableDefinition.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgSettingsTable.java
  sql/src/main/java/io/crate/metadata/settings/session/NamedSessionSetting.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSetting.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#8532 reflect release 3.3.1
  blackbox/docs/appendices/release-notes/3.3.1.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8531 bump upcoming version to 3.3.2-SNAPSHOT
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8533 Eagerly resolve the default for nullsFirst in OrderBy
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  sql/src/main/java/io/crate/analyze/OrderBy.java
  sql/src/main/java/io/crate/analyze/relations/OrderyByAnalyzer.java
  sql/src/main/java/io/crate/execution/dsl/projection/OrderedTopNProjection.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfter.java
  sql/src/main/java/io/crate/execution/engine/sort/OrderingByPosition.java
  sql/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
  sql/src/main/java/io/crate/planner/PositionalOrderBy.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/test/java/io/crate/analyze/OrderByTest.java
  sql/src/test/java/io/crate/analyze/WindowDefinitionSerialisationTest.java
  sql/src/test/java/io/crate/analyze/relations/OrderByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/relations/RelationSplitterTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/OrderedTopNProjectionTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/execution/engine/collect/sources/SystemCollectSourceTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/merge/SortedPagingIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  sql/src/test/java/io/crate/execution/engine/sort/OrderingByPositionTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  sql/src/test/java/io/crate/planner/PositionalOrderByTest.java
  sql/src/test/java/io/crate/planner/SubQueryPlannerTest.java
  sql/src/test/java/io/crate/planner/consumer/GroupByPlannerTest.java
  sql/src/test/java/io/crate/planner/consumer/SemiJoinsTest.java
  sql/src/test/java/io/crate/planner/node/RoutedCollectPhaseTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/testing/SQLPrinter.java
Labels: ready-to-merge

#8529 Change `show param` implementation to a rewrite to a select query.
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/ShowSessionParameterAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/ShowStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/UnboundAnalyzer.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/node/management/ShowSessionParameterPlan.java
Labels: ready-to-merge

#8535 Replace Ordering/Comparator chaining with a specific implementation
  benchmarks/src/test/java/io/crate/execution/engine/distribution/merge/SortedPagingIteratorBenchmark.java
  sql/src/main/java/io/crate/execution/engine/collect/RowsTransformer.java
  sql/src/main/java/io/crate/execution/engine/sort/BoundedSortingTopNCollector.java
  sql/src/main/java/io/crate/execution/engine/sort/NullAwareComparator.java
  sql/src/main/java/io/crate/execution/engine/sort/OrderingByPosition.java
  sql/src/main/java/io/crate/execution/engine/sort/SortingProjector.java
  sql/src/main/java/io/crate/execution/engine/sort/UnboundedSortingTopNCollector.java
  sql/src/test/java/io/crate/execution/engine/sort/OrderingByPositionTest.java
  sql/src/test/java/io/crate/execution/engine/sort/SortingProjectorTest.java
  sql/src/test/java/io/crate/execution/engine/sort/SortingTopNProjectorTest.java
  sql/src/test/java/io/crate/integrationtests/JoinGroupByIntegrationTests.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge

#8537 Make the `show all` statement display session description.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/ShowStatementAnalyzer.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#8536 Add the `max_index_keys` session setting.
  blackbox/docs/config/session.rst
  sql/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  sql/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#8538 Reflect 3.2.7 release
  blackbox/docs/appendices/release-notes/3.2.7.rst
  blackbox/docs/appendices/release-notes/index.rst
Labels: ready-to-merge

#8541 Add support for handling scalar functions as table functions
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/scalar.rst
  blackbox/docs/general/builtins/table-functions.rst
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalysisContext.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SubSelectAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/TableFunctionITest.java
Labels: ready-to-merge

#8547 Fix resource leak warning in MainAndStaticFileHandler
  http/src/main/java/io/crate/protocols/http/MainAndStaticFileHandler.java
Labels: ready-to-merge

#8553 Make nested subqueries ignore the limit of outer subqueries.
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/MultiPhasePlan.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/test/java/io/crate/planner/UpdatePlannerTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8555 Fix limit processing in queries of insert into statements
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  sql/src/main/java/io/crate/planner/operators/Insert.java
  sql/src/test/java/io/crate/planner/InsertPlannerTest.java
Labels: ready-to-merge, v/3.2, v/3.3

#8545 docs improvement
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/table-functions.rst
Labels: ready-to-merge

#8561 Use seqNo and primaryTerm for internal versioning on upserts.
  es/es-server/src/main/java/org/elasticsearch/index/engine/Engine.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  es/es-testing/src/main/java/org/elasticsearch/index/engine/TranslogHandler.java
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  sql/src/main/java/io/crate/expression/reference/Doc.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/main/java/io/crate/planner/operators/PKAndVersion.java
  sql/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#8554 Add support for type 'string' cast operator
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/data-types.rst
  blackbox/docs/sql/general/lexical-structure.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/ColumnType.java
  sql-parser/src/main/java/io/crate/sql/tree/DateLiteral.java
  sql-parser/src/main/java/io/crate/sql/tree/ObjectColumnType.java
  sql-parser/src/main/java/io/crate/sql/tree/TimeLiteral.java
  sql-parser/src/main/java/io/crate/sql/tree/TimestampLiteral.java
  sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  sql/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  sql/src/test/java/io/crate/metadata/doc/DocIndexMetaDataTest.java
Labels: ready-to-merge

#8562 Remove guava usage from udc module
  udc/build.gradle
  udc/src/main/java/io/crate/udc/ping/PingTask.java
Labels: ready-to-merge

#8558 Run sort phase in window function execution in parallel
  benchmarks/src/test/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/engine/sort/Comparators.java
  sql/src/main/java/io/crate/execution/engine/sort/Sort.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  sql/src/test/java/io/crate/execution/engine/collect/BlobShardCollectorProviderTest.java
  sql/src/test/java/io/crate/execution/engine/sort/SortTest.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
Labels: ready-to-merge

#8563 Move t-digest and HdrHistogram dependencies into sql module
  es/es-server/build.gradle
  sql/build.gradle
Labels: ready-to-merge

#8568 Make the window function computation phase lazy again
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
Labels: ready-to-merge

#8569 Optimize `findFirstNonPeer` to use a binary search approach
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
Labels: ready-to-merge

#8574 Prepare 3.3.2 release
  blackbox/docs/appendices/release-notes/3.3.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  common/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8576 Replace the LocalSysColReferenceResolver with MapBackedRefResolver
  sql/src/main/java/io/crate/execution/engine/collect/sources/NodeStatsCollectSource.java
  sql/src/main/java/io/crate/expression/reference/sys/cluster/SysClusterExpressionModule.java
  sql/src/main/java/io/crate/metadata/ClusterReferenceResolver.java
  sql/src/main/java/io/crate/metadata/LocalSysColReferenceResolver.java
  sql/src/main/java/io/crate/metadata/MapBackedRefResolver.java
  sql/src/main/java/io/crate/metadata/shard/ShardReferenceResolver.java
  sql/src/test/java/io/crate/analyze/EvaluatingNormalizerTest.java
  sql/src/test/java/io/crate/execution/engine/collect/sources/NodeStatsCollectSourceTest.java
  sql/src/test/java/io/crate/metadata/MapBackedRefResolverTest.java
Labels: ready-to-merge

#8572 Bump version to 3.2.9-SNAPSHOT
  core/src/main/java/io/crate/Version.java
Labels: ready-to-merge

#8567 Add minimum_index_compatibility_version, minimum_wire_compatibility_v…
  blackbox/docs/admin/system-information.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeVersionStatsExpression.java
  sql/src/main/java/io/crate/metadata/sys/SysNodesTableInfo.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/metadata/SysNodesTableInfoTest.java
Labels: ready-to-merge

#8577 Use java date/time parsers for crate timestamp types.
  blackbox/docs/general/ddl/data-types.rst
  common/src/main/java/io/crate/TimestampFormat.java
  common/src/main/java/io/crate/types/TimestampType.java
  common/src/test/java/io/crate/types/TimestampTypesTest.java
  sql/src/test/java/io/crate/expression/scalar/DateFormatFunctionTest.java
Labels: ready-to-merge

#8573 Add support for SQL standard timestamp format
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/ddl/data-types.rst
  common/src/main/java/io/crate/types/TimestampType.java
  common/src/test/java/io/crate/types/TimestampTypesTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge

#8578 Remove some unused declarations
  sql/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  sql/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/main/java/io/crate/metadata/FunctionIdent.java
  sql/src/main/java/io/crate/metadata/ReferenceIdent.java
  sql/src/main/java/io/crate/planner/PlannerContext.java
  sql/src/test/java/io/crate/expression/scalar/AbstractScalarFunctionsTest.java
Labels: ready-to-merge

#8582 Remove unused shard upsert request class.
  sql/src/main/java/io/crate/execution/engine/indexing/ShardUpsertRequestAndResponse.java
Labels: ready-to-merge

#8580 Drop the commons-lang3 dependency
  blob/src/test/java/io/crate/integrationtests/BlobIntegrationTest.java
  common/src/test/java/io/crate/types/DataTypesTest.java
  enterprise/ssl-impl/src/test/java/io/crate/protocols/http/CrateHttpsTransportIntegrationTest.java
  enterprise/users/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  integration-testing/build.gradle
Labels: ready-to-merge

#8579 Use names of registered data type to build cast functions.
  sql/src/main/java/io/crate/expression/scalar/cast/CastFunction.java
  sql/src/main/java/io/crate/expression/scalar/cast/CastFunctionResolver.java
  sql/src/main/java/io/crate/expression/scalar/cast/TryCastScalarFunction.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/InsertFromValuesAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  sql/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  sql/src/test/java/io/crate/planner/InsertPlannerTest.java
Labels: ready-to-merge

#8584 reflect release 3.3.2
  blackbox/docs/appendices/release-notes/3.3.2.rst
  blackbox/docs/appendices/release-notes/index.rst
  blackbox/docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#8581 Use java instead of guava collections in datatypes class.
  common/src/main/java/io/crate/types/DataTypes.java
Labels: ready-to-merge

#8587 Remove unused & deprecated routing preferences
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/Preference.java
Labels: ready-to-merge

#8590 Remove the IndicesRequestCache
  es/es-server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesRequestCache.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesService.java
  es/es-testing/src/main/java/org/elasticsearch/test/ESIntegTestCase.java
Labels: ready-to-merge

#8591 Use CopyOnWriteArrayList for killAllListeners
  sql/src/main/java/io/crate/execution/jobs/TasksService.java
Labels: ready-to-merge

#8593 Remove the shard limit enforcement logic
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaData.java
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
  es/es-server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataUpdateSettingsService.java
  es/es-server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesService.java
  es/es-server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge

#8583 Fix lgtm warnings
  es/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/NGramTokenFilterFactory.java
  es/es-discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/Ec2NameResolver.java
  es/es-server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/MoveAllocationCommand.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
  es/es-server/src/main/java/org/elasticsearch/common/compress/CompressedXContent.java
  es/es-server/src/main/java/org/elasticsearch/common/geo/GeoUtils.java
  es/es-server/src/main/java/org/elasticsearch/common/geo/builders/PolygonBuilder.java
  es/es-server/src/main/java/org/elasticsearch/common/geo/parsers/GeoJsonParser.java
  es/es-server/src/main/java/org/elasticsearch/common/io/stream/ByteBufferStreamInput.java
  es/es-server/src/main/java/org/elasticsearch/common/io/stream/FilterStreamInput.java
  es/es-server/src/main/java/org/elasticsearch/common/io/stream/InputStreamStreamInput.java
  es/es-server/src/main/java/org/elasticsearch/common/joda/Joda.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/store/InputStreamIndexInput.java
  es/es-server/src/main/java/org/elasticsearch/common/time/EpochMillisDateFormatter.java
  es/es-server/src/main/java/org/elasticsearch/common/util/concurrent/KeyedLock.java
  es/es-server/src/main/java/org/elasticsearch/discovery/zen/MasterFaultDetection.java
  es/es-server/src/main/java/org/elasticsearch/discovery/zen/MembershipAction.java
  es/es-server/src/main/java/org/elasticsearch/gateway/MetaDataStateFormat.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/ElasticsearchConcurrentMergeScheduler.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  es/es-server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java
  es/es-server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/RefreshListeners.java
  es/es-server/src/main/java/org/elasticsearch/index/translog/BufferedChecksumStreamInput.java
  es/es-server/src/main/java/org/elasticsearch/index/translog/Translog.java
  es/es-server/src/main/java/org/elasticsearch/indices/recovery/RecoveryState.java
  es/es-server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  es/es-server/src/main/java/org/elasticsearch/transport/NodeDisconnectedException.java
  es/es-server/src/main/java/org/elasticsearch/transport/NotSerializableTransportException.java
  es/es-server/src/main/java/org/elasticsearch/transport/RemoteTransportException.java
  es/es-server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
  es/es-testing/src/main/java/org/elasticsearch/transport/MockTcpTransport.java
  es/es-transport/src/main/java/org/elasticsearch/transport/netty4/ByteBufStreamInput.java
Labels: ready-to-merge

#8595 Enable Bulk-Merge if all source remains backport of https://github.co…
  es/es-server/build.gradle
  es/es-server/src/main/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicy.java
  es/es-server/src/test/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicyTests.java
Labels: ready-to-merge

#8596 Test sequence versioning under network partition.
  sql/src/test/java/io/crate/integrationtests/disruption/SequenceConsistencyIT.java
Labels: ready-to-merge

#8594 Remove deprecation logging fro index.shard.check_on_startup
  es/es-server/src/main/java/org/elasticsearch/index/IndexSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#8598 Remove duplicated code between OperationRouting and RoutingProvider
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java
  sql/src/main/java/io/crate/metadata/RoutingProvider.java
Labels: ready-to-merge

#8597 Remove analyzeGraphPhrase override in MatchQuery
  es/es-server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
Labels: ready-to-merge

#8599 Improve primary terms documentation.
  blackbox/docs/general/ddl/system-columns.rst
  blackbox/docs/general/occ.rst
Labels: ready-to-merge

#8600 Remove unused deprecated index.ttl.disable_purge setting
  es/es-server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  es/es-server/src/main/java/org/elasticsearch/index/IndexSettings.java
Labels: ready-to-merge

#8604 Update hamcrest to 2.1
  dex/build.gradle
  enterprise/functions/build.gradle
  enterprise/lang-js/build.gradle
  enterprise/users/build.gradle
  es/es-server/build.gradle
  es/es-testing/build.gradle
  gradle/dependencies.gradle
  gradle/version.properties
  integration-testing/src/main/java/io/crate/test/CauseMatcher.java
  shared/build.gradle
  sql-parser/build.gradle
  sql/build.gradle
Labels: ready-to-merge

#8601 Port ES snapshotting code.
  blackbox/docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/action/ActionListener.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/DeleteSnapshotRequest.java
  es/es-server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshotAction.java
  es/es-server/src/main/java/org/elasticsearch/cluster/RestoreInProgress.java
  es/es-server/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java
  es/es-server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  es/es-server/src/main/java/org/elasticsearch/snapshots/SnapshotInProgressException.java
  es/es-server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java
  es/es-server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  es/es-server/src/main/java/org/elasticsearch/transport/TransportRequestDeduplicator.java
Labels: ready-to-merge

#8608 Merge AnalyzedRelation with QueriedRelation
  enterprise/users/src/main/java/io/crate/auth/user/StatementPrivilegeValidator.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/CopyFromReturnSummaryAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/CreateViewAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateViewStmt.java
  sql/src/main/java/io/crate/analyze/ExplainAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzer.java
  sql/src/main/java/io/crate/analyze/MultiSourceSelect.java
  sql/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  sql/src/main/java/io/crate/analyze/QueriedTable.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/main/java/io/crate/analyze/Rewriter.java
  sql/src/main/java/io/crate/analyze/ShowCreateTableAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/UnboundAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/SubqueryAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/AbstractTableRelation.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedRelation.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedRelationVisitor.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  sql/src/main/java/io/crate/analyze/relations/OrderedLimitedRelation.java
  sql/src/main/java/io/crate/analyze/relations/QueriedRelation.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationNormalizer.java
  sql/src/main/java/io/crate/analyze/relations/RelationSplitter.java
  sql/src/main/java/io/crate/analyze/relations/UnionSelect.java
  sql/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  sql/src/main/java/io/crate/expression/symbol/SelectSymbol.java
  sql/src/main/java/io/crate/planner/IsStatementExecutionAllowed.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/SelectStatementPlanner.java
  sql/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  sql/src/main/java/io/crate/planner/consumer/OptimizingRewriter.java
  sql/src/main/java/io/crate/planner/consumer/SemiJoins.java
  sql/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/MultiPhase.java
  sql/src/main/java/io/crate/planner/operators/RelationBoundary.java
  sql/src/main/java/io/crate/planner/operators/Union.java
  sql/src/test/java/io/crate/analyze/ExplainAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/QuerySpecTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/ShowStatementsAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SingleRowSubselectAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SubSelectAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/relations/GroupByScalarAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/builder/SplitPointsTest.java
  sql/src/test/java/io/crate/planner/consumer/SemiJoinsTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/testing/DummyRelation.java
  sql/src/test/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#8610 Change InputColumns to be strict instead of lenient
  sql/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
Labels: ready-to-merge

#8592 Use Netty ByteBuf Bulk Operations for Faster Deserialization backport…
  es/es-server/src/main/java/org/elasticsearch/common/io/stream/ByteBufferStreamInput.java
  es/es-server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
  es/es-transport/src/main/java/org/elasticsearch/transport/netty4/ByteBufStreamInput.java
Labels: ready-to-merge

#8611 Replace deprecated mockito method calls
  blob/src/test/java/io/crate/BlobHeadRequestHandlerTests.java
  enterprise/ssl-impl/src/test/java/io/crate/protocols/ssl/SslContextProviderTest.java
  sql/src/test/java/io/crate/breaker/CrateCircuitBreakerServiceTest.java
  sql/src/test/java/io/crate/cluster/gracefulstop/DecommissionAllocationDeciderTest.java
  sql/src/test/java/io/crate/cluster/gracefulstop/DecommissioningServiceTest.java
  sql/src/test/java/io/crate/execution/dml/delete/TransportShardDeleteActionTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  sql/src/test/java/io/crate/execution/engine/collect/CollectTaskTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/RemoteCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/ShardStateAwareRemoteCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/files/S3FileInputTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
  sql/src/test/java/io/crate/execution/jobs/CountTaskTest.java
  sql/src/test/java/io/crate/execution/jobs/kill/TransportKillAllNodeActionTest.java
  sql/src/test/java/io/crate/execution/jobs/kill/TransportKillJobsNodeActionTest.java
  sql/src/test/java/io/crate/execution/support/TransportsTest.java
  sql/src/test/java/io/crate/expression/reference/sys/check/node/SysNodeChecksTest.java
  sql/src/test/java/io/crate/planner/TableStatsServiceTest.java
  sql/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  sql/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
Labels: ready-to-merge

#8613 Improve error msg for window definitions oredered/partitioned by arrays.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/builtins/window-functions.rst
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  sql/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
Labels: ready-to-merge, v/3.3

#8616 Document the `pg_get_expr` function.
  blackbox/docs/general/builtins/scalar.rst
Labels: ready-to-merge

#8618 Simplify (add)ColumnDefintion parser rules.
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
Labels: ready-to-merge

#8617 Register udfs against the pg_catalog schema.
  blackbox/docs/appendices/release-notes/unreleased.rst
  blackbox/docs/general/user-defined-functions.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  sql/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
Labels: ready-to-merge
