Repository crate/crate, pull requests merged in 2020-10, with the labels that each got.

#10600 Port over some of IndexSettingsTests.
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
Labels: ready-to-merge

#10605 Add DiskDisruptionIT to integration tests
  server/src/test/java/io/crate/integrationtests/disruption/discovery/DiskDisruptionIT.java
  server/src/test/java/org/elasticsearch/test/BackgroundIndexer.java
  server/src/test/java/org/elasticsearch/test/ESIntegTestCase.java
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10615 Use ProxyObject to represent map based data types in UDF.
  docs/appendices/release-notes/unreleased.rst
  enterprise/lang-js/src/main/java/io/crate/operation/language/JavaScriptUserDefinedFunction.java
  enterprise/lang-js/src/main/java/io/crate/operation/language/PolyglotValuesConverter.java
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
Labels: ready-to-merge, v/4.2

#10616 Add IndexBalanceTests back to es test suite
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/IndexBalanceTests.java
Labels: ready-to-merge

#10619 Make unknown node count in NodeJobsCounter thread safe
  server/src/main/java/io/crate/execution/jobs/NodeJobsCounter.java
Labels: ready-to-merge

#10614 Tune memory reservation for COPY/INSERT-FROM-QUERY
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/NoopCircuitBreaker.java
  server/src/test/java/io/crate/execution/engine/indexing/BulkShardCreationLimiterTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorUnitTest.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
  server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreaker.java
Labels: ready-to-merge, v/4.2

#10622 Fix subscript resolving inside views/aliases
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/main/java/io/crate/planner/operators/Filter.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
Labels: ready-to-merge, v/4.2

#10623 Fix implicit cast from double to float for the min-value
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/types/FloatType.java
  server/src/test/java/io/crate/types/FloatTypeTest.java
Labels: ready-to-merge, v/4.2

#10631 Allow double infinity to float infinity implicit casts
  server/src/main/java/io/crate/types/FloatType.java
  server/src/test/java/io/crate/types/FloatTypeTest.java
Labels: ready-to-merge, v/4.2

#10627 Fix the partitions deletion from the subquery expressions.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
Labels: ready-to-merge, v/4.2

#10634 Release 4.2.6.
  docs/appendices/release-notes/4.2.6.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10635 Fix flaky testResetEngine
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#10637 Reflect 4.2.6 release.
  docs/appendices/release-notes/4.2.6.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10636 Bump version to 4.2.7-SNAPSHOT.
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10640 Fix flaky testRetentionLeasesSyncOnRecovery
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseIT.java
Labels: ready-to-merge

#10639 Fix flaky test_update_by_query_returning_multiple_results
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#10638 Enable soft deletes by default for new tables
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/engine/Segment.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/operation/aggregation/AggregationTest.java
  server/src/test/java/org/elasticsearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#10641 Document soft_deletes.retention_lease.period
  docs/sql/statements/create-table.rst
Labels: ready-to-merge

#10643 Fix flaky testPrimaryTermIsIncreasedOnReplicaPromotion
  server/src/test/java/io/crate/integrationtests/disruption/seqno/SequenceConsistencyIT.java
Labels: ready-to-merge

#10644 Group unreleased release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10646 Fix flaky testSoftDeletesDefaultSetting
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
Labels: ready-to-merge

#10647 Update admin-ui to 1.17.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#10630 Add scalar function translate
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/string/TranslateFunction.java
  server/src/test/java/io/crate/expression/scalar/string/TranslateFunctionTest.java
Labels: ready-to-merge

#10652 Make global_checkpoint_sync.interval internal again
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/ClusterDisruptionIT.java
  server/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
Labels: ready-to-merge

#10654 Optimize PartitionInfos
  server/src/main/java/io/crate/metadata/PartitionInfos.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/PartitionedByMappingExtractor.java
Labels: ready-to-merge

#10656 Add shard limits per node
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  server/src/main/java/io/crate/execution/ddl/tables/TransportAlterTableAction.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/settings/CrateSettings.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/indices/ShardLimitValidator.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/ShardLimitsIT.java
  server/src/test/java/org/elasticsearch/cluster/shards/ShardCounts.java
  server/src/test/java/org/elasticsearch/indices/ShardLimitValidatorTests.java
Labels: ready-to-merge

#10651 Prevent dropping of a UDF used inside a generated col expression
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoBuilder.java
  server/src/test/java/io/crate/expression/udf/UdfUnitTest.java
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionServiceTest.java
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionsMetadataTest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
  server/src/test/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, v/4.2

#10660 Disallow creating self referencing views
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/CreateViewPlan.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
Labels: ready-to-merge, v/4.2

#10665 RetentionLeaseIT: Replace update setting client calls with alter table
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseIT.java
Labels: ready-to-merge

#10657 Remove ValidationException
  server/src/main/java/io/crate/exceptions/AmbiguousColumnAliasException.java
  server/src/main/java/io/crate/exceptions/AmbiguousColumnException.java
  server/src/main/java/io/crate/exceptions/AnalyzerInvalidException.java
  server/src/main/java/io/crate/exceptions/ColumnValidationException.java
  server/src/main/java/io/crate/exceptions/GroupByOnArrayUnsupportedException.java
  server/src/main/java/io/crate/exceptions/InvalidArgumentException.java
  server/src/main/java/io/crate/exceptions/InvalidColumnNameException.java
  server/src/main/java/io/crate/exceptions/InvalidRelationName.java
  server/src/main/java/io/crate/exceptions/InvalidSchemaNameException.java
  server/src/main/java/io/crate/exceptions/LicenseViolationException.java
  server/src/main/java/io/crate/exceptions/OperationOnInaccessibleRelationException.java
  server/src/main/java/io/crate/exceptions/RelationValidationException.java
  server/src/main/java/io/crate/exceptions/SQLParseException.java
  server/src/main/java/io/crate/exceptions/UnsupportedFeatureException.java
  server/src/main/java/io/crate/exceptions/ValidationException.java
  server/src/main/java/io/crate/exceptions/VersioninigValidationException.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BytesRefColumnReference.java
  server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java
Labels: ready-to-merge

#10667 Prepare release 4.2.7
  docs/appendices/release-notes/4.2.7.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10671 Reflect release 4.2.7
  docs/appendices/release-notes/4.2.7.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10670 Bump version to 4.2.8-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10672 Release 4.3.0
  docs/appendices/release-notes/4.3.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10673 Bump version to 4.3.1-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10676 Bump version to 4.4.0-SNAPSHOT.
  .mergify.yml
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10675 Share a single event loop group across netty servers
  enterprise/ssl-impl/src/test/java/io/crate/protocols/http/CrateHttpsTransportTest.java
  server/src/main/java/io/crate/netty/CrateChannelBootstrapFactory.java
  server/src/main/java/io/crate/netty/EventLoopGroups.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/org/elasticsearch/common/network/NetworkModule.java
  server/src/main/java/org/elasticsearch/http/HttpServerTransport.java
  server/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
  server/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/Transports.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresNettyPublishPortTest.java
  server/src/test/java/org/elasticsearch/transport/MockTcpTransportPlugin.java
Labels: ready-to-merge

#10678 Update gradle to 6.7
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.2, v/4.3

#10685 Reorder methods in BlobStoreRepository to match ES upstream
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge

#10686 Fix PgArray#encodeAsUTF8Text for escaped double quotes.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge, v/4.2, v/4.3

#10690 Limit workers used for snapshot operation
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge, v/4.2, v/4.3

#10695 Avoid byte array copy to parse SQL http request
  server/src/main/java/io/crate/action/sql/parser/SQLRequestParser.java
Labels: ready-to-merge

#10694 Fix a type inference error when using eclipse jdt
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
Labels: ready-to-merge

#10698 Prevent a IndexShardClosedException on sys.shards queries
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/sys/shard/ShardRowContext.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
Labels: ready-to-merge, v/4.3

#10702 Fix test_implicit_cast_ISO_formats_with_time_zone
  docs/general/ddl/data-types.rst
  server/src/test/java/io/crate/types/TimeTZTypeTest.java
Labels: ready-to-merge, v/4.3

#10703 Allow super users to drop corrupted tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AnalyzedDropTable.java
  server/src/main/java/io/crate/analyze/DropTableAnalyzer.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/node/ddl/DropTablePlan.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/planner/DropTablePlannerTest.java
Labels: ready-to-merge, v/4.3

#10706 Ensure TableInfo can be created for new indices
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/DropTableAnalyzer.java
  server/src/main/java/io/crate/plugin/SQLPlugin.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge, v/4.3

#10709 Update bundled JDK to 15.0.1+9
  gradle/version.properties
Labels: ready-to-merge, v/4.3

#10713 Ensure TableInfo can be created for altered tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/ddl/tables/TransportAlterTableAction.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge, v/4.3

#10674 Using Kahan summation algorithm for doubles and floats in SUM operation
  server/src/main/java/io/crate/execution/engine/aggregation/impl/KahanSummationForDouble.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/KahanSummationForFloat.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/KahanSummationForDoubleTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/KahanSummationForFloatTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
Labels: ready-to-merge

#10711 Fix functions resolution for text types with different limit lengths.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/types/TypeCompatibility.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
  server/src/test/java/io/crate/types/TypeCompatibilityTest.java
Labels: ready-to-merge, v/4.3

#10717 Release memory for sharded requests to avoid circuit breaker errors
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
Labels: ready-to-merge, v/4.3

#10719 Fix flaky testFloatSummationWithoutLosingPrecision
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArrayAggTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/operation/aggregation/AggregationTest.java
Labels: ready-to-merge

#10720 Release 4.3.1
  docs/appendices/release-notes/4.3.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10723 Reflect 4.3.1 release
  docs/appendices/release-notes/4.3.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10722 Bump version to 4.3.2-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10721 Use follow-tags in create_tag script
  devs/tools/create_tag.sh
Labels: ready-to-merge, v/4.3

#10725 Fix nested table function handling
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  server/src/main/java/io/crate/planner/operators/ProjectSet.java
  server/src/test/java/io/crate/integrationtests/TableFunctionITest.java
Labels: ready-to-merge, v/4.3

#10727 Broken link to `rolling_upgrade#step-2-graceful-stop` - #10447
  docs/sql/statements/alter-cluster.rst
Labels: ready-to-merge, v/4.3
