Repository crate/crate, pull requests merged in 2020-07, with the labels that each got.

#10156 Add SET TRANSACTION statement support
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/set-transaction.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/SetStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/SetTransactionStatement.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/AnalyzedSetTransaction.java
  server/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/planner/IsStatementExecutionAllowed.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/test/java/io/crate/analyze/SetAnalyzerTest.java
  server/src/test/java/io/crate/planner/PlannerTest.java
Labels: ready-to-merge

#10152 Resolve unnest and _values signature return type correctly.
  server/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  server/src/main/java/io/crate/expression/tablefunctions/ValuesFunction.java
  server/src/test/java/io/crate/expression/tablefunctions/AbstractTableFunctionsTest.java
  server/src/test/java/io/crate/expression/tablefunctions/UnnestFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
Labels: ready-to-merge

#10159 Make sure credentials for s3 repo plugin are masked
  blackbox/test_s3.py
  docs/appendices/release-notes/unreleased.rst
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RepositoryPlugin.java
Labels: ready-to-merge, v/4.1

#10160 Update admin-ui to 1.16.0
  gradle/version.properties
Labels: ready-to-merge

#10162 Fix flaky testQueryAllColumns
  server/src/test/java/io/crate/integrationtests/SysSnapshotsTest.java
Labels: ready-to-merge

#10168 Fix between handling in expression analyzer
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
Labels: ready-to-merge

#10169 Fix time measurement in SysSnapshotsTest
  server/src/test/java/io/crate/integrationtests/SysSnapshotsTest.java
Labels: ready-to-merge

#10172 Fix stuck query on pg-wire-fetch
  server/src/main/java/io/crate/action/sql/Session.java
Labels: ready-to-merge

#10173 Remove support probot config; Add issue template link to GH discussions
  .github/ISSUE_TEMPLATE/config.yml
  .github/support.yml
Labels: ready-to-merge

#10171 Replaced wrong word in allocation awareness docs
  docs/config/cluster.rst
Labels: ready-to-merge, v/4.1

#10177 Fix negate function registration for REAL type
  server/src/main/java/io/crate/expression/scalar/arithmetic/NegateFunctions.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
Labels: ready-to-merge

#10174 Add pretty printing for negate function
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: ready-to-merge

#10176 Do not create unused tables in GroupByPlannerTest
  server/src/test/java/io/crate/planner/consumer/GroupByPlannerTest.java
Labels: ready-to-merge

#10178 Make sure null returned by `not` predicate is typed as boolean
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/main/java/io/crate/planner/operators/Filter.java
  server/src/test/java/io/crate/expression/predicate/NotPredicateTest.java
Labels: ready-to-merge

#10179 Fix simple query channel delay handling
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
Labels: ready-to-merge

#10180 Release 4.1.8
  docs/appendices/release-notes/4.1.8.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10182 Bump version to 4.1.9-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#10167 Add missing functionality required to run crate-node tool
  app/build.gradle
  gradle/version.properties
  libs/cli/build.gradle
  libs/cli/src/main/java/org/elasticsearch/cli/Command.java
  libs/cli/src/main/java/org/elasticsearch/cli/ExitCodes.java
  libs/cli/src/main/java/org/elasticsearch/cli/MultiCommand.java
  libs/cli/src/main/java/org/elasticsearch/cli/SuppressForbidden.java
  libs/cli/src/main/java/org/elasticsearch/cli/Terminal.java
  libs/cli/src/main/java/org/elasticsearch/cli/UserException.java
  server/build.gradle
  server/src/test/java/org/elasticsearch/cli/MockTerminal.java
  settings.gradle
Labels: ready-to-merge

#10183 Reflect 4.1.8 release
  docs/appendices/release-notes/4.1.8.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10187 Bump version to 4.2.1-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10188 Exclude build-hash if releaseZip task is used
  server/build.gradle
Labels: ready-to-merge

#10191 Fix window function plan construction
  docs/appendices/release-notes/unreleased.rst
  enterprise/functions/src/test/java/io/crate/window/WindowFunctionsITest.java
  server/src/main/java/io/crate/Constants.java
  server/src/main/java/io/crate/execution/dsl/projection/WindowAggProjection.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  server/src/main/java/io/crate/expression/symbol/ScopedSymbol.java
  server/src/main/java/io/crate/expression/symbol/WindowFunctionContext.java
  server/src/main/java/io/crate/planner/operators/WindowAgg.java
  server/src/test/java/io/crate/execution/dsl/projection/WindowAggProjectionSerialisationTest.java
Labels: ready-to-merge

#10195 Update outdated entries in crate.yml
  app/src/main/dist/config/crate.yml
Labels: ready-to-merge

#10198 Prune changes released with 4.2.0 from unreleased
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10193 Docs: Fix COPY TO URI formatting example for windows
  docs/sql/statements/copy-to.rst
Labels: ready-to-merge

#10199 Update netty to 4.1.51
  gradle/version.properties
Labels: ready-to-merge

#10197 Fix support for subscript expressions in ON CONFLICT
  docs/appendices/release-notes/unreleased.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Insert.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge

#10202 Mention more contribution options in CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: ready-to-merge

#10205 Don't flush when sending row description
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge

#10206 Quote only base part of subscript expressions with `quote_ident`
  docs/appendices/release-notes/unreleased.rst
  libs/sql-parser/src/main/java/io/crate/sql/Identifiers.java
  libs/sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  server/src/main/java/io/crate/expression/scalar/string/QuoteIdentFunction.java
Labels: ready-to-merge

#10214 Release 4.2.1
  docs/appendices/release-notes/4.2.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10218 Bump version to 4.2.2-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10220 Bump version to 4.3.0-SNAPSHOT
  .mergify.yml
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10219 Change type in SessionSetting to DataType
  server/src/main/java/io/crate/metadata/pgcatalog/PgSettingsTable.java
  server/src/main/java/io/crate/metadata/settings/session/NamedSessionSetting.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSetting.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
Labels: ready-to-merge

#10221 Fix ADD COLUMN on tables with INDEX OFF primary key columns
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
Labels: ready-to-merge, v/4.2

#10223 Add an empty pg_role table
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgRolesTable.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#10225 Allow users to kill their own statements
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/kill.rst
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  enterprise/users/src/test/java/io/crate/auth/user/AccessControlMayExecuteTest.java
  server/src/main/java/io/crate/execution/engine/InterceptingRowConsumer.java
  server/src/main/java/io/crate/execution/engine/JobLauncher.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/RemoteCollector.java
  server/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/main/java/io/crate/execution/jobs/kill/KillAllRequest.java
  server/src/main/java/io/crate/execution/jobs/kill/KillJobsRequest.java
  server/src/main/java/io/crate/execution/jobs/kill/TransportKillAllNodeAction.java
  server/src/main/java/io/crate/execution/jobs/kill/TransportKillJobsNodeAction.java
  server/src/main/java/io/crate/execution/jobs/transport/NodeDisconnectJobMonitorService.java
  server/src/main/java/io/crate/execution/jobs/transport/TransportJobAction.java
  server/src/main/java/io/crate/planner/node/management/KillPlan.java
  server/src/test/java/io/crate/execution/jobs/RootTaskTest.java
  server/src/test/java/io/crate/execution/jobs/TasksServiceTest.java
  server/src/test/java/io/crate/execution/jobs/kill/KillJobsRequestTest.java
  server/src/test/java/io/crate/execution/jobs/kill/TransportKillAllNodeActionTest.java
  server/src/test/java/io/crate/execution/jobs/kill/TransportKillJobsNodeActionTest.java
  server/src/test/java/io/crate/execution/jobs/transport/NodeDisconnectJobMonitorServiceTest.java
  server/src/test/java/io/crate/planner/node/management/KillPlanTest.java
Labels: ready-to-merge

#10229 Remove unused ReferenceToLiteralConverter.
  server/src/main/java/io/crate/metadata/ReferenceToLiteralConverter.java
  server/src/test/java/io/crate/metadata/ReferenceToLiteralConverterTest.java
Labels: ready-to-merge

#10231 Upgrade lucene to 8.6.0
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/elasticsearch/index/engine/ElasticsearchConcurrentMergeScheduler.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/test/CorruptionUtils.java
Labels: ready-to-merge

#10235 Update JDK to 14.0.2+12
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.2

#10239 Increase stats.service.interval from 1h to 24h
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  server/src/main/java/io/crate/statistics/TableStatsService.java
Labels: ready-to-merge, v/4.2

#10237 Add new extensions for Lucene86 points codec
  server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java
  server/src/test/java/org/elasticsearch/index/store/FsDirectoryServiceTest.java
Labels: ready-to-merge

#10245 Add doc-value aggregator for min aggregation
  libs/shared/src/main/java/io/crate/common/MutableDouble.java
  libs/shared/src/main/java/io/crate/common/MutableLong.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
Labels: ready-to-merge

#10227 Extend REFRESH statement docs
  blackbox/test_docs.py
  docs/concepts/storage-consistency.rst
  docs/sql/statements/refresh.rst
Labels: ready-to-merge

#10236 Update gradle to 6.5.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.1, v/4.2

#10246 Allow all users to execute discard and set transaction
  docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  enterprise/users/src/test/java/io/crate/auth/user/AccessControlMayExecuteTest.java
Labels: ready-to-merge, v/4.2

#10252 Upgrade Sphinx dependency to match RTD default
  blackbox/requirements.txt
Labels: bug, build, documentation, ready-to-merge

#10244 Docs: Add a snippet to show how to escape s3 access keys
  docs/sql/statements/copy-from.rst
Labels: ready-to-merge

#10258 Avoid plan re-creation for no-op optimizer passes
  libs/shared/src/main/java/io/crate/common/collections/Lists2.java
  server/src/main/java/io/crate/planner/optimizer/Optimizer.java
Labels: ready-to-merge

#10260 Fix partitioned column value retrieval in query-then-fetch plans
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge, v/4.2

#10264 Fix fetch planning bug with aliased columns
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/Fetch.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge, v/4.2

#10265 Fix statement classification to include sources of fetch operators
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/StatementClassifier.java
  server/src/test/java/io/crate/planner/operators/StatementClassifierTest.java
Labels: ready-to-merge, v/4.2

#10268 Fix performance regression; execute ORDER BY w/o LIMIT with QTF
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  server/src/main/java/io/crate/planner/operators/Eval.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/PlanHint.java
  server/src/main/java/io/crate/planner/operators/Rename.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteToQueryThenFetch.java
  server/src/test/java/io/crate/integrationtests/ExplainAnalyzeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
  server/src/test/java/io/crate/planner/operators/StatementClassifierTest.java
Labels: ready-to-merge, v/4.2

#10257 Add table function generate_subscripts
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/table-functions.rst
  server/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  server/src/main/java/io/crate/expression/tablefunctions/GenerateSubscripts.java
  server/src/main/java/io/crate/expression/tablefunctions/RangeIterable.java
  server/src/main/java/io/crate/expression/tablefunctions/TableFunctionModule.java
  server/src/test/java/io/crate/expression/tablefunctions/GenerateSubscriptsTest.java
Labels: ready-to-merge

#10271 Fix regression that caused unknown key errors on ignored objects
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/4.2

#10273 Fix clustered-by column validation for inserts
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/4.2

#10275 Integrate LazyMapList into Lists2
  libs/shared/src/main/java/io/crate/common/collections/LazyMapList.java
  libs/shared/src/main/java/io/crate/common/collections/Lists2.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/analyze/where/DocKeys.java
  server/src/main/java/io/crate/execution/engine/collect/RemoteCollectorFactory.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
Labels: ready-to-merge

#10276 Initialize a single query profile per index searcher.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/ExplainStatementAnalyzer.java
  server/src/main/java/io/crate/execution/engine/JobLauncher.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
  server/src/main/java/io/crate/execution/jobs/transport/TransportJobAction.java
  server/src/main/java/io/crate/profile/ProfilingContext.java
  server/src/test/java/io/crate/execution/jobs/RootTaskTest.java
Labels: ready-to-merge, v/4.2

#10057 Remove guava some guava multi and immutable maps.
  libs/shared/src/main/java/io/crate/common/collections/MapBuilder.java
  server/src/main/java/io/crate/action/sql/parser/SQLRequestParser.java
  server/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  server/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  server/src/main/java/io/crate/analyze/MatchOptionsAnalysis.java
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalysisContext.java
  server/src/main/java/io/crate/analyze/where/WhereClauseValidator.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResultCollectors.java
  server/src/main/java/io/crate/expression/reference/doc/blob/BlobReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/file/FileLineReferenceResolver.java
  server/src/main/java/io/crate/lucene/SubscriptQuery.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocSysColumns.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/io/crate/metadata/shard/ShardReferenceResolver.java
  server/src/main/java/io/crate/metadata/sys/SysShardsTableInfo.java
  server/src/main/java/io/crate/planner/PlanPrinter.java
  server/src/test/java/io/crate/analyze/CompoundLiteralTest.java
  server/src/test/java/io/crate/analyze/MatchOptionsAnalyzedStatementTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/relations/FieldProviderTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/collect/BlobShardCollectorProviderTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/RemoteCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/sources/SystemCollectSourceTest.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  server/src/test/java/io/crate/expression/reference/sys/check/cluster/SysChecksTest.java
  server/src/test/java/io/crate/expression/scalar/DateFormatFunctionTest.java
  server/src/test/java/io/crate/expression/symbol/MappingSymbolVisitorTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GeoShapeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/metadata/RoutingTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/test/java/io/crate/metadata/view/ViewsMetadataTest.java
  server/src/test/java/io/crate/planner/PlanPrinterTest.java
  server/src/test/java/io/crate/testing/T3.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge

#10282 Release 4.2.2.
  docs/appendices/release-notes/4.2.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10283 Bump version to 4.2.3-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10284 Reflect 4.2.2 release.
  docs/appendices/release-notes/4.2.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10288 Backport implicit refresh removal & remove isRecovering check
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#10291 Debounce computations in TableHealthService
  server/src/main/java/io/crate/metadata/sys/TableHealthService.java
Labels: ready-to-merge

#10294 bp: Record Force Merges in Live Commit Data
  server/src/main/java/org/elasticsearch/action/admin/indices/forcemerge/ForceMergeRequest.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/store/StoreUtils.java
Labels: ready-to-merge

#10299 Add developer docs for ES backports
  devs/docs/es-backports.rst
Labels: ready-to-merge
