Repository crate/crate, pull requests merged in 2020-12, with the labels that each got.

#10839 Fix bytebuf leak in SrvUnicastHostsProvider
  docs/appendices/release-notes/unreleased.rst
  plugins/dns-discovery/src/main/java/io/crate/discovery/SrvUnicastHostsProvider.java
Labels: v/4.3

#10835 Add jmx shard relate information to node info
  blackbox/test_jmx.py
  docs/admin/monitoring.rst
  docs/appendices/release-notes/unreleased.rst
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/NodeInfo.java
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/NodeInfoMXBean.java
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/ShardInfo.java
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/ShardStats.java
  enterprise/jmx-monitoring/src/main/java/io/crate/plugin/CrateMonitor.java
  enterprise/jmx-monitoring/src/test/java/io/crate/beans/NodeInfoTest.java
Labels: ready-to-merge

#10844 Mute flaky SysSegmentsTableInfoTest test_retrieve_segment_information
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
Labels: ready-to-merge

#10846 bp: Remove non task-aware version of master and node operations (#43563)
  enterprise/licensing/src/main/java/io/crate/license/TransportSetLicenseAction.java
  enterprise/users/src/main/java/io/crate/auth/user/TransportAlterUserAction.java
  enterprise/users/src/main/java/io/crate/auth/user/TransportCreateUserAction.java
  enterprise/users/src/main/java/io/crate/auth/user/TransportDropUserAction.java
  enterprise/users/src/main/java/io/crate/auth/user/TransportPrivilegesAction.java
  server/src/main/java/io/crate/execution/ddl/AbstractDDLTransportAction.java
  server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java
  server/src/main/java/io/crate/execution/ddl/TransportSwapRelationsAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameTableAction.java
  server/src/main/java/io/crate/execution/ddl/views/TransportCreateViewAction.java
  server/src/main/java/io/crate/execution/ddl/views/TransportDropViewAction.java
  server/src/main/java/io/crate/expression/udf/TransportCreateUserDefinedFunctionAction.java
  server/src/main/java/io/crate/expression/udf/TransportDropUserDefinedFunctionAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/delete/TransportDeleteRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/TransportPutRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/tasks/TransportPendingClusterTasksAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/TransportDeleteIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/TransportPutMappingAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/delete/TransportDeleteIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/get/TransportGetIndexTemplatesAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/put/TransportPutIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/TransportUpgradeSettingsAction.java
  server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java
  server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/elasticsearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java
Labels: ready-to-merge

#10852 Add elasticsearch.cluster.routing package to es-backports
  devs/docs/es-backports.rst
Labels: ready-to-merge

#10850 Set shardId on blob requests
  server/src/main/java/io/crate/blob/BlobService.java
  server/src/main/java/io/crate/blob/BlobTransferRequest.java
  server/src/main/java/io/crate/blob/DeleteBlobRequest.java
  server/src/main/java/io/crate/blob/PutChunkRequest.java
  server/src/main/java/io/crate/blob/RemoteDigestBlob.java
  server/src/main/java/io/crate/blob/StartBlobRequest.java
  server/src/main/java/io/crate/blob/TransportDeleteBlobAction.java
  server/src/main/java/io/crate/blob/TransportPutChunkAction.java
  server/src/main/java/io/crate/blob/TransportStartBlobAction.java
  server/src/test/java/io/crate/blob/DeleteBlobRequestTest.java
  server/src/test/java/io/crate/integrationtests/RecoveryTests.java
Labels: ready-to-merge

#10853 bp: Check again on-going snapshots/restores of indices before closing
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/metadata/cluster/CloseTableClusterStateTaskExecutor.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
Labels: ready-to-merge

#10856 Update netty to 4.1.55
  gradle/version.properties
Labels: ready-to-merge

#10847 Add postgres syntax compatible parser for to_char scalarfunction for timestamps
  docs/general/builtins/scalar.rst
  libs/shared/src/main/java/io/crate/common/StringUtils.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/formatting/DateTimeFormatter.java
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionPostgresCompatabilityTest.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#10845 Fix handling of spaces in `$CRATE_HOME`
  app/src/bin/crate.in.sh
  app/src/main/dist/bin/crate
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/4.3

#10864 Use postgres compatible formatter for to_char with interval types
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/formatting/DateTimeFormatter.java
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#10867 Improvement: Make ``ITEST_FILE_NAME_FILTER`` documentation more visible
  devs/docs/tests.rst
  devs/docs/write_docs.rst
Labels: ready-to-merge, team: tech writing

#10860 Add an empty pg_catalog.pg_am table
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgAmTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#10862 Optimize fetch performance for sequential value retrieval
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/execution/engine/fetch/ReaderContext.java
  server/src/main/java/io/crate/execution/engine/sort/InputFieldComparator.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BooleanColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/ByteColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BytesRefColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/DoubleColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/FetchIdCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/FloatColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/GeoPointColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IdCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IntegerColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IpColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LongColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/PrimaryTermCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/RawCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SeqNoCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/ShortColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceLookup.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/VersionCollectorExpression.java
  server/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/org/elasticsearch/common/lucene/index/ElasticsearchLeafReader.java
  server/src/main/java/org/elasticsearch/common/lucene/index/SequentialStoredFieldsLeafReader.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchCollectorTest.java
  server/src/test/java/io/crate/expression/reference/doc/BooleanColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/DoubleColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/FloatColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/IpColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/LongColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/ShortColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/doc/StringColumnReferenceTest.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#10873 Optimize ReaderContext creation for LuceneCollectorExpressions
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
Labels: ready-to-merge

#10877 Correction: Clarify note about stock `crate.yml` file
  docs/admin/auth/hba.rst
Labels: team: tech writing

#10878 Fix output names of COPY TO statements
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
Labels: ready-to-merge, v/4.3

#10880 Correction: Fix old URLs still pointing to `guide`
  docs/admin/discovery.rst
  docs/appendices/release-notes/3.0.0.rst
  docs/cli-tools.rst
  docs/config/cluster.rst
  docs/config/environment.rst
  docs/general/ddl/partitioned-tables.rst
  docs/general/ddl/sharding.rst
Labels: ready-to-merge, team: tech writing

#10871 Docs: Fix typo in array function documentation
  docs/general/builtins/scalar.rst
Labels: ready-to-merge
