Repository crate/crate, pull requests merged in 2020-01, with the labels that each got.

#9480 Fix data type of `sys.jobs_metrics.classification['labels']`
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/sys/SysMetricsTableInfo.java
Labels: ready-to-merge, v/4.0

#9482 Always normalize the WHERE clause of relations
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/relations/RelationNormalizer.java
  sql/src/test/java/io/crate/integrationtests/ViewsITest.java
Labels: ready-to-merge, v/4.0

#9488 Update JaCoCo and forbidden-apis
  build.gradle
Labels: ready-to-merge

#9487 Update Lucene to 8.4
  docs/general/dql/fulltext.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  es/es-server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  es/es-server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  es/es-server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
  gradle/version.properties
  sql/src/test/java/io/crate/expression/reference/sys/shard/ShardMinLuceneVersionExpressionTest.java
  sql/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
Labels: ready-to-merge

#9486 Group unreleased changes
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#9490 Make sure describe/bind analysis errors result in sys.jobs_log entries
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/action/sql/Session.java
  sql/src/test/java/io/crate/integrationtests/JobLogIntegrationTest.java
Labels: ready-to-merge, v/4.0

#9489 Make ReadOnlyException error message more verbose
  sql/src/main/java/io/crate/action/sql/Session.java
  sql/src/main/java/io/crate/exceptions/ReadOnlyException.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
  sql/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java
Labels: ready-to-merge

#9494 Remove tableStats assertion from ANALYZE cmd itest
  sql/src/test/java/io/crate/integrationtests/AnalyzeITest.java
Labels: ready-to-merge

#9493 Add toString implementations to Transport.Connection
  es/es-server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  es/es-testing/src/main/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java
  es/es-testing/src/main/java/org/elasticsearch/test/transport/MockTransport.java
  es/es-testing/src/main/java/org/elasticsearch/test/transport/StubbableTransport.java
Labels: ready-to-merge

#9496 Fix flaky test failures due to open connection assertion
  es/es-testing/src/main/java/org/elasticsearch/test/transport/MockTransportService.java
Labels: ready-to-merge, v/4.0

#9495 Update outdated es/upstream reference in LICENSE file
  LICENSE
Labels: ready-to-merge

#9498 Reduce indirections for symbol casts
  sql/src/main/java/io/crate/analyze/InsertFromValuesAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ValueNormalizer.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/expression/scalar/geo/DistanceFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/IntersectsFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
  sql/src/main/java/io/crate/expression/symbol/Function.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/expression/symbol/ParameterSymbol.java
  sql/src/main/java/io/crate/expression/symbol/Symbol.java
Labels: ready-to-merge

#9499 gradle: Don't fail if tests filter doesn't match any tests
  es/build.gradle
  gradle/javaModule.gradle
Labels: ready-to-merge

#9492 Expose the merge.scheduler.max_thread_count setting for non-SSD type disks
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/show-create-table.rst
  docs/sql/statements/create-table.rst
  sql/src/main/java/io/crate/analyze/TableParameters.java
  sql/src/main/java/io/crate/expression/reference/information/TablesSettingsExpression.java
  sql/src/main/java/io/crate/expression/reference/partitioned/PartitionsSettingsExpression.java
  sql/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  sql/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  sql/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#9481 Add returning clause to update-by-id usecase to the storage engine
  sql/src/main/java/io/crate/action/sql/Session.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedUpdateStatement.java
  sql/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedRelation.java
  sql/src/main/java/io/crate/execution/dml/ShardRequestExecutor.java
  sql/src/main/java/io/crate/execution/dml/ShardResponse.java
  sql/src/main/java/io/crate/execution/dml/delete/TransportShardDeleteAction.java
  sql/src/main/java/io/crate/execution/dml/upsert/LegacyUpsertByIdTask.java
  sql/src/main/java/io/crate/execution/dml/upsert/ReturnValueGen.java
  sql/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/main/java/io/crate/execution/dml/upsert/UpdateSourceGen.java
  sql/src/main/java/io/crate/execution/dsl/projection/UpdateProjection.java
  sql/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  sql/src/main/java/io/crate/planner/node/dml/UpdateById.java
  sql/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dml/ShardResponseTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/ReturnValueGenTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/UpdateSourceGenTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/UpdateProjectionTest.java
  sql/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#9504 Add support for ALL in array/subquery comparisons
  blackbox/test_docs.py
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/array-comparisons.rst
  docs/general/builtins/subquery-expressions.rst
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/expression/operator/AllOperator.java
  sql/src/main/java/io/crate/expression/operator/OperatorModule.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/expression/operator/AllOperatorTest.java
Labels: ready-to-merge

#9506 tests: Make sure disrupted connections timeout eventually
  es/es-testing/src/main/java/org/elasticsearch/test/transport/MockTransportService.java
Labels: ready-to-merge

#9505 Update netty to 4.1.45
  gradle/version.properties
Labels: ready-to-merge

#9503 Remove arrays indirection for hash calculation
  sql/src/main/java/io/crate/execution/engine/join/HashInnerJoinBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  sql/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorMemoryTest.java
  sql/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorTest.java
Labels: ready-to-merge

#9507 tests: Use unique data for occ doctests
  blackbox/test_docs.py
  docs/general/occ.rst
Labels: ready-to-merge

#9467 Drop limitation from some copy integration tests.
  sql/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#9508 Support pg array value input notation
  common/build.gradle
  common/src/main/java/io/crate/types/ArrayType.java
  common/src/test/java/io/crate/types/ArrayTypeTest.java
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  pgwire/src/main/antlr/PgArray.g4
  pgwire/src/main/java/io/crate/protocols/postgres/parser/PgArrayASTVisitor.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge

#9512 Release 4.0.11
  docs/appendices/release-notes/4.0.11.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9514 Bump version to 4.0.12-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9515 Reflect release 4.0.11
  docs/appendices/release-notes/4.0.11.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9511 Make sure CoordinatorTests do not run OOM
  es/es-server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
  es/es-server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java
Labels: ready-to-merge

#9516 Release 4.1.0
  docs/appendices/release-notes/4.1.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9517 Fix sphinx dev command
  Jenkinsfile
  blackbox/bin/sphinx
  blackbox/requirements.txt
  devs/docs/write_docs.rst
  docs/appendices/compliance.rst
Labels: ready-to-merge

#9523 Fix system table type declarations
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysJobsLogTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysMetricsTableInfo.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge, v/4.0

#9521 Replaced unnest function for sample tables in the docs with VALUES
  docs/general/builtins/aggregation.rst
  docs/general/builtins/window-functions.rst
Labels: ready-to-merge

#9502 Add implementation for returning clause for update-by-query usecase to storage engine
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/main/java/io/crate/execution/dsl/projection/UpdateProjection.java
  sql/src/main/java/io/crate/execution/engine/indexing/DMLProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/expression/reference/Doc.java
  sql/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  sql/src/test/java/io/crate/execution/dsl/projection/UpdateProjectionTest.java
  sql/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#9528 Allow more lenient column type validation in VALUES.
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/values.rst
  shared/src/main/java/io/crate/common/collections/Lists2.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/test/java/io/crate/analyze/ValuesAnalyzerTest.java
Labels: ready-to-merge, v/4.1, v/4.2

#9527 Improve documentation regarding analyzers types
  docs/general/ddl/analyzers.rst
  docs/general/ddl/column-policy.rst
  docs/general/ddl/data-types.rst
  docs/general/ddl/fulltext-indices.rst
Labels: ready-to-merge, v/4.0

#9532 Fix varargs warnings in RamAccountingBatchIteratorTest
  sql/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
Labels: ready-to-merge

#9538 Allow more characters in unquoted string elements of pg arrays
  pgwire/src/main/antlr/PgArray.g4
  pgwire/src/test/java/io/crate/protocols/postgres/parser/PgArrayParserTest.java
Labels: ready-to-merge

#9541 Improve error message for CREATE VIEW
  sql/src/main/java/io/crate/analyze/ViewAnalyzer.java
  sql/src/test/java/io/crate/analyze/CreateViewAnalyzerTest.java
Labels: ready-to-merge

#9542 Bump version to 4.2.0-SNAPSHOT
  .mergify.yml
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9510 Add pg array type notation support
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge, v/4.2

#9535 Add `version()` system information function.
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/VersionFunction.java
  sql/src/test/java/io/crate/expression/scalar/postgres/VersionFunctionTest.java
Labels: ready-to-merge

#9543 Move generate_series to pg_catalog schema
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  sql/src/test/java/io/crate/expression/tablefunctions/GenerateSeriesTest.java
Labels: ready-to-merge

#9549 Add the `pg_catalog.obj_description` scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/ObjDescriptionFunction.java
  sql/src/test/java/io/crate/expression/scalar/systeminformation/ObjDescriptionFunctionTest.java
Labels: ready-to-merge

#9553 Exclude unreleased release notes from code owners
  .github/CODEOWNERS
Labels: ready-to-merge

#9547 Copyedit
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#9557 Make sure nested geo shape columns are not added as top-level columns
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/doc/DocIndexMetaData.java
  sql/src/test/java/io/crate/metadata/doc/DocIndexMetaDataTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9465 Deduplicate insert from values/subquery analyzer logic.
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  docs/general/ddl/generated-columns.rst
  docs/general/dml.rst
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/InsertFromValues.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/action/sql/Session.java
  sql/src/main/java/io/crate/analyze/AbstractInsertAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/AbstractInsertAnalyzer.java
  sql/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzer.java
  sql/src/main/java/io/crate/analyze/InsertFromValuesAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/InsertFromValuesAnalyzer.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/main/java/io/crate/analyze/SymbolEvaluator.java
  sql/src/main/java/io/crate/analyze/UnboundAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/StatementAnalysisContext.java
  sql/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  sql/src/main/java/io/crate/execution/dml/upsert/LegacyUpsertByIdTask.java
  sql/src/main/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjection.java
  sql/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardLocation.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/metadata/doc/DocIndexMetaData.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  sql/src/main/java/io/crate/planner/node/dml/LegacyUpsertById.java
  sql/src/main/java/io/crate/planner/operators/Insert.java
  sql/src/main/java/io/crate/planner/operators/InsertFromValues.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanVisitor.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/RewriteInsertFromSubQueryToInsertFromValues.java
  sql/src/main/java/io/crate/planner/operators/StatementClassifier.java
  sql/src/test/java/io/crate/analyze/InsertFromSubQueryAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/InsertFromValuesAnalyzerTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjectionTest.java
  sql/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
  sql/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  sql/src/test/java/io/crate/integrationtests/TableFunctionITest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  sql/src/test/java/io/crate/planner/InsertPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/StatementClassifierTest.java
Labels: ready-to-merge

#9562 Impove types incompatibility exception message in insert analyzer.
  sql/src/main/java/io/crate/analyze/InsertFromSubQueryAnalyzer.java
  sql/src/test/java/io/crate/analyze/InsertFromSubQueryAnalyzerTest.java
Labels: ready-to-merge

#9563 Rename InsertFromSubQueryAnalyzer → InsertAnalyzer
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/InsertAnalyzer.java
  sql/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge

#9569 Add a ascii scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/string/AsciiFunction.java
  sql/src/test/java/io/crate/expression/scalar/AsciiFunctionTest.java
Labels: ready-to-merge

#9540 Add encode and decode string functions
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  shared/src/main/java/io/crate/common/Hex.java
  shared/src/main/java/io/crate/common/Octal.java
  shared/src/test/java/io/crate/common/OctalTest.java
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/string/EncodeDecodeFunction.java
  sql/src/test/java/io/crate/expression/scalar/string/EncodeDecodeFunctionTest.java
Labels: ready-to-merge

#9550 Minor copyedit
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#9573 Add changelog entry for crate object[] -> pg json[] remapping.
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#9576 Replace object arrays with lists in SQL args parsers.
  sql/src/main/java/io/crate/action/sql/parser/SQLArgsParseElement.java
  sql/src/main/java/io/crate/action/sql/parser/SQLBulkArgsParseElement.java
  sql/src/main/java/io/crate/action/sql/parser/SQLRequestParseContext.java
  sql/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  sql/src/test/java/io/crate/action/sql/parser/SQLBulkArgsParseElementTest.java
Labels: ready-to-merge

#9577 Add ceiling alias for ceil scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/CeilFunction.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/CeilFunctionTest.java
Labels: ready-to-merge

#9586 Update gradle to 6.1.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.0, v/4.1

#9585 Add the pi scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/PiFunction.java
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/test/java/io/crate/expression/scalar/PiFunctionTest.java
Labels: ready-to-merge

#9572 Minor copyedit
  docs/general/builtins/scalar.rst
Labels: ready-to-merge

#9571 Do not store partition values, but include on select
  common/src/main/java/io/crate/common/collections/Maps.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  sql/src/main/java/io/crate/execution/engine/collect/BlobShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/count/InternalCountOperation.java
  sql/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  sql/src/main/java/io/crate/execution/engine/fetch/NodeFetchOperation.java
  sql/src/main/java/io/crate/execution/jobs/JobSetup.java
  sql/src/main/java/io/crate/expression/reference/DocRefResolver.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  sql/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  sql/src/main/java/io/crate/metadata/DocReferences.java
  sql/src/main/java/io/crate/statistics/ReservoirSampler.java
  sql/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  sql/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  sql/src/test/java/io/crate/execution/engine/fetch/FetchTaskTest.java
  sql/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  sql/src/test/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolverTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  sql/src/test/java/io/crate/testing/IndexEnv.java
  sql/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge, v/4.0, v/4.1

#9575 Improve BwC for returning clause for update
  integration-testing/src/main/java/io/crate/test/integration/CrateDummyClusterServiceUnitTest.java
  sql/src/main/java/io/crate/execution/dml/ShardResponse.java
  sql/src/main/java/io/crate/execution/dml/delete/TransportShardDeleteAction.java
  sql/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/main/java/io/crate/execution/dsl/projection/SysUpdateProjection.java
  sql/src/main/java/io/crate/execution/dsl/projection/UpdateProjection.java
  sql/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/planner/PlannerContext.java
  sql/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  sql/src/main/java/io/crate/planner/node/dml/UpdateById.java
  sql/src/main/java/io/crate/planner/operators/InsertFromValues.java
  sql/src/test/java/io/crate/execution/dml/ShardResponseTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  sql/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  sql/src/test/java/io/crate/execution/dsl/projection/UpdateProjectionTest.java
  sql/src/test/java/io/crate/planner/UpdatePlannerTest.java
Labels: ready-to-merge

#9587 Fix error handling while consuming a next batch
  benchmarks/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/sort/SortingTopNCollectorBenchmark.java
  dex/src/main/java/io/crate/data/AsyncOperationBatchIterator.java
  dex/src/main/java/io/crate/data/BatchIterator.java
  dex/src/main/java/io/crate/data/BatchIterators.java
  dex/src/main/java/io/crate/data/CloseAssertingBatchIterator.java
  dex/src/main/java/io/crate/data/CollectingBatchIterator.java
  dex/src/main/java/io/crate/data/CompositeBatchIterator.java
  dex/src/main/java/io/crate/data/FlatMapBatchIterator.java
  dex/src/main/java/io/crate/data/InMemoryBatchIterator.java
  dex/src/main/java/io/crate/data/LimitingBatchIterator.java
  dex/src/main/java/io/crate/data/MappedForwardingBatchIterator.java
  dex/src/main/java/io/crate/data/TopNDistinctBatchIterator.java
  dex/src/main/java/io/crate/data/join/JoinBatchIterator.java
  dex/src/main/java/io/crate/data/join/SemiJoinNLBatchIterator.java
  dex/src/test/java/io/crate/data/CollectingBatchIteratorTest.java
  dex/src/test/java/io/crate/testing/BatchIteratorTester.java
  dex/src/test/java/io/crate/testing/BatchSimulatingIterator.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/action/sql/RowConsumerToResultReceiver.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  sql/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  sql/src/main/java/io/crate/execution/engine/distribution/merge/BatchPagingIterator.java
  sql/src/main/java/io/crate/execution/engine/join/HashInnerJoinBatchIterator.java
  sql/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/merge/BatchPagingIteratorTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9590 Update AdminUI to 1.15.6
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.0, v/4.1

#9597 Prevent select on multiple relations with WHERE .. AND FALSE from matching rows
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/relations/QuerySplitter.java
  sql/src/main/java/io/crate/planner/consumer/QualifiedNameCollector.java
  sql/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  sql/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  sql/src/test/java/io/crate/analyze/relations/QuerySplitterTest.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9609 Use newer images on azure pipelines
  azure-pipelines.yml
Labels: ready-to-merge, v/4.0, v/4.1

#9604 Remove noMatch from WhereClause
  sql/src/main/java/io/crate/analyze/DeleteAnalyzer.java
  sql/src/main/java/io/crate/analyze/QueryClause.java
  sql/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  sql/src/main/java/io/crate/analyze/WhereClause.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  sql/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  sql/src/main/java/io/crate/expression/operator/Operator.java
  sql/src/main/java/io/crate/expression/predicate/NotPredicate.java
  sql/src/main/java/io/crate/expression/scalar/cast/CastFunction.java
  sql/src/main/java/io/crate/planner/statement/CopyToPlan.java
  sql/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/WhereClauseTest.java
  sql/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/JoinTest.java
  sql/src/test/java/io/crate/planner/operators/LimitTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/operators/SelectDistinctLogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
  sql/src/test/java/io/crate/testing/SQLPrinter.java
Labels: ready-to-merge

#9603 Replaced 'unnest' function for sample tables in the docs with 'values'
  docs/general/builtins/aggregation.rst
  docs/general/builtins/window-functions.rst
Labels: ready-to-merge

#9614 Merge InsertFromSubQuery into Insert
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/Insert.java
  sql-parser/src/main/java/io/crate/sql/tree/InsertFromSubquery.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Analyzer.java
  sql/src/main/java/io/crate/analyze/InsertAnalyzer.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge
