Repository crate/crate, pull requests merged in 2020-08, with the labels that each got.

#10307 Fix _id value computation for PK lookups
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/where/DocKeys.java
  server/src/main/java/io/crate/execution/engine/collect/RowShardResolver.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/4.2

#10308 Amend integer literal breaking changes entry with implications
  docs/appendices/release-notes/4.2.0.rst
Labels: ready-to-merge

#10314 Don't acquire searchers in prepare if FetchTask is done already
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
Labels: ready-to-merge

#10316 Add release notes entry for implicit refresh removal for optimize
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10321 bp: Core: Combine Action and GenericAction
  server/src/main/java/io/crate/blob/DeleteBlobAction.java
  server/src/main/java/io/crate/blob/PutChunkAction.java
  server/src/main/java/io/crate/blob/StartBlobAction.java
  server/src/main/java/org/elasticsearch/action/Action.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/ActionRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/GenericAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/AddVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/ClearVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/node/stats/NodesStatsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/delete/DeleteRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/PutRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/reroute/ClusterRerouteAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/settings/ClusterUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/DeleteSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/tasks/PendingClusterTasksAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/DeleteIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/SyncedFlushAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/forcemerge/ForceMergeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/recovery/RecoveryAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/refresh/RefreshAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/delete/DeleteIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/get/GetIndexTemplatesAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/UpgradeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/upgrade/post/UpgradeSettingsAction.java
  server/src/main/java/org/elasticsearch/action/support/broadcast/BroadcastOperationRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/support/master/AcknowledgedRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/support/master/MasterNodeOperationRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/support/master/MasterNodeReadOperationRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequestBuilder.java
  server/src/main/java/org/elasticsearch/client/ElasticsearchClient.java
  server/src/main/java/org/elasticsearch/client/node/NodeClient.java
  server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java
Labels: ready-to-merge

#10327 Mute testRegularSelectWithFewAvailableThreadsShouldNeverGetStuck
  server/src/test/java/io/crate/integrationtests/ThreadPoolsExhaustedIntegrationTest.java
Labels: ready-to-merge

#10329 Mute testAddOrRenewRetentionLease
  server/src/test/java/org/elasticsearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
Labels: ready-to-merge

#10334 Mute testReplicaIgnoresOlderRetentionLeasesVersion
  server/src/test/java/org/elasticsearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
Labels: ready-to-merge

#10318 Migrate tests with SQLActionException to assertThrows
  enterprise/users/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  enterprise/users/src/test/java/io/crate/integrationtests/UserManagementIntegrationTest.java
  plugins/es-analysis-common/src/test/java/io/crate/analysis/common/FulltextITest.java
  plugins/es-analysis-common/src/test/java/io/crate/integrationtests/FulltextAnalyzerResolverTest.java
  plugins/es-repository-url/src/test/java/org/elasticsearch/repositories/url/URLRepositoryITest.java
  server/src/main/java/io/crate/protocols/postgres/PGErrorStatus.java
  server/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CountStarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateBreakerTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/JobIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/OptimizeTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/integrationtests/QueryThenFetchIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RegexpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RepositoryIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/StaticInformationSchemaQueryTest.java
  server/src/test/java/io/crate/integrationtests/SysClusterTest.java
  server/src/test/java/io/crate/integrationtests/SysNodesITest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/TableBlocksIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/io/crate/testing/Asserts.java
  server/src/test/java/io/crate/testing/SQLErrorMatcher.java
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#10332 Remove unused MultiGeoPointValues
  server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/MultiGeoPointValues.java
Labels: ready-to-merge

#10341 bp: Use current term in initial leases in engine test
  devs/docs/es-backports.rst
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#10343 Revert removal of MatchQueryBuilder#newTermQuery.
  docs/appendices/release-notes/unreleased.rst
  plugins/es-analysis-common/src/test/java/io/crate/analysis/common/FulltextITest.java
  server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
Labels: ready-to-merge, v/4.2

#10352 Mute testAcquirePrimaryAllOperationsPermits
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#10348 Update gradle to 6.6
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.2

#10339 Remove ExpectedException from SQLTransportIntegrationTest
  enterprise/users/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  enterprise/users/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SwapTableITest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge

#10360 Supress tech writing notifications for es-backports.rst
  .github/CODEOWNERS
Labels: ready-to-merge, team: tech writing

#10363 Mute ConcurrentSeqNoVersioningIT#testSeqNoCASLinearizability
  server/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
Labels: ready-to-merge

#10359 Fix flaky GroupByAggregateTest#testGroupByUnknownGroupByColumn test
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#10367 Remove Repeat from tests
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#10368 Configure executable of the JavaExec type tasks in jdkRuntime plugin.
  app/build.gradle
  gradle/jdkRuntime.gradle
  server/build.gradle
Labels: ready-to-merge

#10347 Add doc-values aggregator for std deviation aggregation.
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
Labels: ready-to-merge

#10358 Add doc-values aggregator for the geometric mean aggregation.
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationtest.java
Labels: ready-to-merge

#10369 Add doc-values aggregator for the count(v) aggregation.
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
Labels: ready-to-merge

#10375 Use junit assertions in assertThrows
  server/src/test/java/io/crate/testing/Asserts.java
Labels: ready-to-merge

#10310 Update, expand, and re-organize Editions page
  docs/editions.rst
  docs/general/builtins/scalar.rst
Labels: ready-to-merge

#10377 Mute testDistributedPushSelectWithFewAvailableThreadsShouldNeverGetStuck
  server/src/test/java/io/crate/integrationtests/ThreadPoolsExhaustedIntegrationTest.java
Labels: ready-to-merge

#10378 Avoid wrapping errors in UnhandledServerException in ShardCollectSource
  docs/general/ddl/fulltext-indices.rst
  docs/general/occ.rst
  server/src/main/java/io/crate/exceptions/UnhandledServerException.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge

#10379 Add numeric and binary doc values aggregator base classes.
  server/src/main/java/io/crate/execution/engine/aggregation/impl/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/BinaryDocValueAggregator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SortedNumericDocValueAggregator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
Labels: ready-to-merge

#10388 Release 4.2.3
  docs/appendices/release-notes/4.2.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10389 Bump version to 4.2.4-SNAPSHOT.
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10384 Add doc-values aggregators for the arbitrary aggregation.
  libs/shared/src/main/java/io/crate/common/MutableObject.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/BinaryDocValueAggregator.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
Labels: ready-to-merge

#10390 Reflect 4.2.3 release.
  docs/appendices/release-notes/4.2.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10392 Expose blocks.read_only_allow_delete in information_schema tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#10398 Fix predicate evaluation for the sys.nodes table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/collectors/NodeStats.java
  server/src/test/java/io/crate/integrationtests/SysNodesITest.java
Labels: ready-to-merge, v/4.2

#10400 Fix serialization of DecomissionNodeRequest
  blackbox/test_decommission.py
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/cluster/decommission/DecommissionNodeRequest.java
  server/src/main/java/io/crate/cluster/decommission/TransportDecommissionNodeAction.java
  server/src/main/java/io/crate/planner/DecommissionNodePlan.java
  server/src/test/java/io/crate/cluster/decommission/DecommissionNodeRequestTest.java
Labels: v/4.2

#10419 Migrate sql-parser tests to assertThrows.
  libs/sql-parser/src/test/java/io/crate/sql/IntervalLiteralTest.java
  libs/sql-parser/src/test/java/io/crate/sql/LiteralsTest.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/UnboundedFollowingFrameBoundTest.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/UnboundedPrecedingFrameBoundTest.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/WindowTest.java
Labels: ready-to-merge

#10418 Avoid creating unused tables in analyzer tests
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge

#10426 Mute JdkDownloadPluginFunctionalTest.
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
Labels: ready-to-merge

#10421 Fix mixed cluster compatibility of MATCH predicates on geo shapes
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  server/src/main/java/io/crate/expression/predicate/MatchPredicate.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/metadata/FunctionInfo.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge, v/4.2

#10424 Prevent column prune logic from duplicating outputs
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/4.2

#10428 Migrate all crate tests in server module to assertThrows
  server/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/reference/doc/IpColumnReferenceTest.java
  server/src/test/java/io/crate/expression/reference/sys/node/NodeStatsContextFieldResolverTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/ArithmeticOverflowTest.java
  server/src/test/java/io/crate/expression/scalar/string/ChrFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/StringPaddingFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/timestamp/TimezoneFunctionTest.java
  server/src/test/java/io/crate/geo/GeoJSONUtilsTest.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
  server/src/test/java/io/crate/types/TimestampTypesTest.java
Labels: ready-to-merge

#10439 Integrate generated partition column expansion into Collect operator
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/4.2

#10434 Prevent JDK plugin functional tests from downloading real JDK artifacts.
  buildSrc/build.gradle
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
  buildSrc/src/test/resources/fake_artifacts/13.0.2+8/aarch64_linux.tar.gz
  buildSrc/src/test/resources/fake_artifacts/13.0.2+8/x64_linux.tar.gz
  buildSrc/src/test/resources/fake_artifacts/13.0.2+8/x64_mac.tar.gz
  buildSrc/src/test/resources/fake_artifacts/13.0.2+8/x64_windows.zip
  buildSrc/src/testKit/jdk-download/build.gradle
Labels: ready-to-merge

#10432 Release 4.2.4
  docs/appendices/release-notes/4.2.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10433 Add new close table transport using 3 step close
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableTarget.java
  server/src/main/java/io/crate/execution/ddl/tables/CloseTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/metadata/cluster/DDLClusterStateHelpers.java
  server/src/main/java/io/crate/metadata/cluster/DDLClusterStateService.java
  server/src/main/java/org/elasticsearch/action/admin/indices/close/TransportVerifyShardBeforeCloseAction.java
Labels: ready-to-merge

#10405 Clarify documentation of `ignored` object types
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#10374 Update jmh to 1.25
  benchmarks/build.gradle
Labels: ready-to-merge

#10441 bp: [Close Index API] Add unique UUID to ClusterBlock
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/org/elasticsearch/action/admin/indices/close/TransportVerifyShardBeforeCloseAction.java
Labels: ready-to-merge

#10444 Add RTD status check to mergify conditions
  .mergify.yml
Labels: ready-to-merge

#10448 Reflect 4.2.4 release.
  docs/appendices/release-notes/4.2.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10442 Avoid create partitions requests if there are no partitions to create
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
Labels: ready-to-merge, v/4.2

#10454 Map DuplicateKeyException to PG 23505 UNIQUE_VIOLATION error
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#10449 Change sitemap name to site.xml
  docs/_extra/robots.txt
Labels: ready-to-merge, v/4.2

#10456 Map RelationUnknown to PG 42P01 undefined_table error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/integrationtests/StaticInformationSchemaQueryTest.java
  server/src/test/java/io/crate/integrationtests/SwapTableITest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#10460 Map ColumnUnknownException to PG 42703 undefined_column error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CountStarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#10461 Map RelationAlreadyExists to PG 42P07 duplicate_table error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
Labels: ready-to-merge

#10446 Flesh out instructions for writing documentation
  devs/docs/write_docs.rst
Labels: ready-to-merge

#10463 Map AmbiguousColumnException to PG 42702 ambiguous_column error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
Labels: ready-to-merge

#10464 Update Lucene to 8.6.2
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge
