Repository crate/crate, pull requests merged in 2020-02, with the labels that each got.

#9601 Add returning clause for insert to grammar and parser
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/Insert.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
Labels: ready-to-merge

#9618 Add support for PostgreSQL record access syntax for objects
  common/src/main/java/io/crate/types/ObjectType.java
  docs/appendices/release-notes/unreleased.rst
  docs/sql/general/value-expressions.rst
  sql-parser/src/main/antlr/SqlBase.g4
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  sql-parser/src/main/java/io/crate/sql/tree/RecordSubscript.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge

#9621 Make sure planner errors don't cause queries to get stuck
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
Labels: ready-to-merge

#9620 Add returning for insert to analyzer
  sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  sql/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  sql/src/main/java/io/crate/analyze/InsertAnalyzer.java
  sql/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge

#9623 Using SortingProjector instead of SortingTopNProjector for testUsedMemoryIsAccountedFor test case
  sql/src/test/java/io/crate/execution/engine/sort/SortingProjectorTest.java
Labels: ready-to-merge

#9625 Make cast error message more verbose
  docs/general/builtins/aggregation.rst
  docs/general/ddl/data-types.rst
  sql/src/main/java/io/crate/analyze/expressions/ValueNormalizer.java
  sql/src/main/java/io/crate/exceptions/ConversionException.java
  sql/src/main/java/io/crate/expression/symbol/FuncArg.java
  sql/src/main/java/io/crate/metadata/functions/params/Param.java
  sql/src/test/java/io/crate/analyze/CompoundLiteralTest.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/ValuesAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayBoundFunctionResolverTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/SubstrFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/TypeInferenceTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/AbsFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/ArrayFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/Ignore3vlFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/LogFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/RoundFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/SquareRootFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/geo/IntersectsFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/regex/RegexpReplaceFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/timestamp/TimezoneFunctionTest.java
  sql/src/test/java/io/crate/integrationtests/CastIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
  sql/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  sql/src/test/java/io/crate/metadata/functions/params/FuncParamsTest.java
Labels: ready-to-merge

#9626 Remove createTableInfo from SRF in favor of a objectType
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/TableFunctionRelation.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/TableFunctionCollectSource.java
  sql/src/main/java/io/crate/expression/tablefunctions/EmptyRowTableFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  sql/src/main/java/io/crate/expression/tablefunctions/PgGetKeywordsFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
  sql/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/ValuesFunction.java
  sql/src/main/java/io/crate/metadata/tablefunctions/TableFunctionImplementation.java
  sql/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
Labels: ready-to-merge

#9631 Add the cotangent trigonometric scalar function.
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctionsTest.java
Labels: ready-to-merge

#9633 Improve error message in case parameter placeholders are used but no params given
  sql/src/main/java/io/crate/planner/operators/SubQueryAndParamBinder.java
  sql/src/test/java/io/crate/planner/operators/SubQueryAndParamBinderTest.java
Labels: ready-to-merge

#9629 Add support for JOIN USING statements
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/select.rst
  sql-parser/src/main/java/io/crate/sql/tree/JoinUsing.java
  sql-parser/src/test/java/io/crate/sql/tree/JoinUsingTests.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#9630 Replace Nashorn with GraalVM JS engine in UDF.
  app/build.gradle
  docs/appendices/release-notes/unreleased.rst
  docs/general/user-defined-functions.rst
  enterprise/lang-js/build.gradle
  enterprise/lang-js/src/main/java/io/crate/operation/language/JavaScriptLanguage.java
  enterprise/lang-js/src/main/java/io/crate/operation/language/JavaScriptUserDefinedFunction.java
  enterprise/lang-js/src/main/java/io/crate/operation/language/PolyglotValuesConverter.java
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
  gradle/version.properties
Labels: ready-to-merge

#9634 Add some missing columns to pg_catalog.pg_type.
  docs/appendices/release-notes/unreleased.rst
  docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  sql/src/main/java/io/crate/protocols/postgres/types/BaseTimestampType.java
  sql/src/main/java/io/crate/protocols/postgres/types/BigIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/BooleanType.java
  sql/src/main/java/io/crate/protocols/postgres/types/CharType.java
  sql/src/main/java/io/crate/protocols/postgres/types/DoubleType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntegerType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntervalType.java
  sql/src/main/java/io/crate/protocols/postgres/types/JsonType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PointType.java
  sql/src/main/java/io/crate/protocols/postgres/types/RealType.java
  sql/src/main/java/io/crate/protocols/postgres/types/SmallIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#9638 Add ``degrees`` and ``radians`` scalar functions.
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctions.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctionsTest.java
Labels: ready-to-merge

#9644 Improve PGType type saftey and fix record serialization
  sql/src/main/java/io/crate/protocols/postgres/types/BigIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/BooleanType.java
  sql/src/main/java/io/crate/protocols/postgres/types/CharType.java
  sql/src/main/java/io/crate/protocols/postgres/types/DoubleType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntegerType.java
  sql/src/main/java/io/crate/protocols/postgres/types/IntervalType.java
  sql/src/main/java/io/crate/protocols/postgres/types/JsonType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  sql/src/main/java/io/crate/protocols/postgres/types/PGType.java
  sql/src/main/java/io/crate/protocols/postgres/types/PointType.java
  sql/src/main/java/io/crate/protocols/postgres/types/RealType.java
  sql/src/main/java/io/crate/protocols/postgres/types/RecordType.java
  sql/src/main/java/io/crate/protocols/postgres/types/SmallIntType.java
  sql/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
  sql/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge

#9639 Add `exp` scalar function.
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/ExpFunctionTest.java
Labels: ready-to-merge

#9642 Update outdated RelationNormalizer docs
  sql/src/main/java/io/crate/analyze/relations/RelationNormalizer.java
Labels: ready-to-merge

#9645 Replace azure pipelines with github actions.
  .github/workflows/main.yml
  .mergify.yml
  README.rst
  azure-pipelines.yml
Labels: ready-to-merge

#9643 Add the ``atan2`` trigonometric scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctionsTest.java
Labels: ready-to-merge

#9640 Add ``mod`` alias for the ``modulus`` scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/arithmetic/ArithmeticFunctions.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/ModulusFunctionTest.java
Labels: ready-to-merge

#9647 Add a safeguard to the optimizer to prevent infinite loops
  sql/src/main/java/io/crate/planner/optimizer/Optimizer.java
Labels: ready-to-merge

#9648 Make mergify merge rule to wait for all github actions tests.
  .mergify.yml
Labels: ready-to-merge

#9649 Prevent join filter push down rule from matching infinitely
  sql/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#9619 Added system columns to output expression
  docs/sql/statements/update.rst
Labels: ready-to-merge

#9650 Terminate ordered lucene collector on cancel/kill
  shared/src/main/java/io/crate/concurrent/KillableCompletionStage.java
  shared/src/main/java/io/crate/data/Killable.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollector.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/OrderedDocCollector.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactory.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
  sql/src/main/java/io/crate/execution/engine/distribution/merge/BatchPagingIterator.java
  sql/src/main/java/io/crate/execution/jobs/CumulativePageBucketReceiver.java
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  sql/src/test/java/io/crate/execution/engine/distribution/merge/BatchPagingIteratorTest.java
Labels: ready-to-merge

#9659 Return `issued_to` value if license is loading
  common/src/main/java/io/crate/license/LicenseService.java
  docs/appendices/release-notes/unreleased.rst
  enterprise/licensing/src/main/java/io/crate/license/EnterpriseLicenseService.java
  sql/src/main/java/io/crate/expression/reference/sys/cluster/ClusterLicenseExpression.java
  sql/src/test/java/io/crate/metadata/sys/SysClusterTableInfoTest.java
Labels: ready-to-merge, v/4.1

#9658 Allow implicit casts from TEXT to OBJECT again
  common/src/main/java/io/crate/types/DataType.java
  common/src/main/java/io/crate/types/DataTypes.java
  common/src/main/java/io/crate/types/GeoPointType.java
  common/src/main/java/io/crate/types/ObjectType.java
  common/src/test/java/io/crate/types/TypeConversionTest.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/InsertAnalyzer.java
  sql/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9668 tests: Add Ignore annotation to flaky test
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#9664 Add a `now()` scalar
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/timestamp/NowFunction.java
  sql/src/test/java/io/crate/expression/scalar/timestamp/NowFunctionTest.java
Labels: ready-to-merge

#9670 Remove custom normalize from CurrentTimestampFunction
  sql/src/main/java/io/crate/expression/scalar/timestamp/CurrentTimestampFunction.java
Labels: ready-to-merge

#9671 Remove unused hasAggregates from AnalyzedRelation
  sql/src/main/java/io/crate/analyze/AnalyzedCopyFromReturnSummary.java
  sql/src/main/java/io/crate/analyze/AnalyzedShowCreateTable.java
  sql/src/main/java/io/crate/analyze/ExplainAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/MultiSourceSelect.java
  sql/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  sql/src/main/java/io/crate/analyze/QuerySpec.java
  sql/src/main/java/io/crate/analyze/relations/AbstractTableRelation.java
  sql/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedRelation.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/TableFunctionRelation.java
  sql/src/main/java/io/crate/analyze/relations/UnionSelect.java
  sql/src/main/java/io/crate/planner/statement/CopyToPlan.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/testing/DummyRelation.java
Labels: ready-to-merge

#9672 Fix `/ by zero` error in average row size calculation
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/statistics/Stats.java
  sql/src/test/java/io/crate/statistics/StatsTest.java
Labels: ready-to-merge, v/4.1

#9676 Enforce Literal returnType / dataType relationship with type system
  common/src/main/java/io/crate/types/DataTypes.java
  sql/src/main/java/io/crate/expression/scalar/ConcatFunction.java
  sql/src/main/java/io/crate/expression/scalar/cast/CastFunction.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/metadata/Scalar.java
  sql/src/main/java/io/crate/planner/operators/SubQueryAndParamBinder.java
  sql/src/main/java/io/crate/planner/operators/TableFunction.java
  sql/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  sql/src/main/java/io/crate/planner/statement/CopyToPlan.java
  sql/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/string/EncodeDecodeFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/string/StringLeftRightFunctionTest.java
  sql/src/test/java/io/crate/expression/symbol/LiteralTest.java
Labels: ready-to-merge

#9677 Release 4.1.2
  docs/appendices/release-notes/4.1.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9678 Bump version to 4.1.3-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9679 Reflect 4.1.2 release
  docs/appendices/release-notes/4.1.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9646 Add the ``trunc`` scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/TruncFunction.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/TruncFunctionTest.java
Labels: ready-to-merge

#9683 Pass thread-safe ram accounting to projectors also on joins
  sql/src/main/java/io/crate/execution/jobs/JobSetup.java
Labels: ready-to-merge

#9681 Fix flaky ordered lucene collector kill test
  sql/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#9682 Fix raw type warnings in symbol implementations
  dex/src/test/java/io/crate/data/SkippingBatchIteratorTest.java
  sql/src/main/java/io/crate/execution/dml/upsert/GeneratedColumns.java
  sql/src/main/java/io/crate/execution/dml/upsert/UpdateSourceGen.java
  sql/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  sql/src/main/java/io/crate/expression/symbol/Aggregation.java
  sql/src/main/java/io/crate/expression/symbol/FetchReference.java
  sql/src/main/java/io/crate/expression/symbol/Field.java
  sql/src/main/java/io/crate/expression/symbol/Function.java
  sql/src/main/java/io/crate/expression/symbol/InputColumn.java
  sql/src/main/java/io/crate/expression/symbol/MatchPredicate.java
  sql/src/main/java/io/crate/expression/symbol/ParameterSymbol.java
  sql/src/main/java/io/crate/expression/symbol/Symbol.java
  sql/src/main/java/io/crate/metadata/Reference.java
  sql/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
Labels: ready-to-merge

#9685 Add documentation for the `discovery.type` setting
  docs/config/cluster.rst
Labels: ready-to-merge

#9687 Make aggregation and group by semantic validation more readable
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/expression/symbol/GroupAndAggregateSemantics.java
  sql/src/main/java/io/crate/expression/symbol/GroupBySemantics.java
  sql/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
Labels: ready-to-merge

#9680 Docs: Update insert reference to reflect column ordering behavior
  docs/sql/statements/insert.rst
Labels: ready-to-merge

#9689 Fix rtrim to trim the right side in all cases
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  sql/src/test/java/io/crate/expression/scalar/string/TrimFunctionTest.java
Labels: ready-to-merge, v/4.1

#9688 Allow eager normalization of functions on non-literals
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/expression/symbol/Symbols.java
  sql/src/test/java/io/crate/analyze/relations/QuerySplitterTest.java
  sql/src/test/java/io/crate/analyze/where/NullEliminatorTest.java
  sql/src/test/java/io/crate/expression/scalar/AbstractScalarFunctionsTest.java
  sql/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
  sql/src/test/java/io/crate/planner/selectivity/SelectivityFunctionsTest.java
  sql/src/test/java/io/crate/testing/SqlExpressions.java
Labels: ready-to-merge

#9690 Removed initialisation of custom TrustStore
  app/src/main/java/io/crate/plugin/PluginLoaderPlugin.java
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/4.0, v/4.1

#9696 Remove Set/Object[] support recurse sorting from LiteralValueFormatter
  sql/src/main/java/io/crate/expression/symbol/LiteralValueFormatter.java
  sql/src/main/java/io/crate/expression/symbol/format/SymbolPrinter.java
  sql/src/test/java/io/crate/expression/symbol/LiteralValueFormatterTest.java
  sql/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: ready-to-merge

#9697 [Test] Return local sql response var to ensure thread safety.
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9653 Add sequence and version tests
  es/es-testing/src/main/java/org/elasticsearch/cluster/coordination/LinearizabilityChecker.java
  sql/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  sql/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
  sql/src/test/java/io/crate/integrationtests/disruption/seqno/SimpleVersioningIT.java
Labels: ready-to-merge

#9695 Update gradle to 6.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.1

#9700 Tests: Disable automatic rebalancing on manual reallocation test
  sql/src/test/java/io/crate/integrationtests/PartitionedTableConcurrentIntegrationTest.java
Labels: ready-to-merge, v/4.0, v/4.1

#9702 Add support for GROUP BY on analyzed columns
  docs/appendices/release-notes/unreleased.rst
  docs/general/dql/selects.rst
  sql/src/main/java/io/crate/planner/node/dql/GroupByConsumer.java
  sql/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  sql/src/test/java/io/crate/planner/consumer/GroupByPlannerTest.java
Labels: ready-to-merge

#9705 Make subscript expression behavior more consistent
  sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  sql-parser/src/main/java/io/crate/sql/tree/SubscriptExpression.java
  sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  sql/src/main/java/io/crate/analyze/OutputNameFormatter.java
  sql/src/main/java/io/crate/analyze/SubscriptValidator.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToColumnIdentVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToObjectVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToStringVisitor.java
  sql/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  sql/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/SubscriptValidatorTest.java
  sql/src/test/java/io/crate/expression/scalar/SubscriptFunctionTest.java
  sql/src/test/java/io/crate/testing/SqlExpressions.java
Labels: ready-to-merge

#9706 Change optimizer to re-try rules after children have been optimized
  sql/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  sql/src/main/java/io/crate/planner/optimizer/Optimizer.java
  sql/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge

#9708 Update gradle to 6.2.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.1

#9713 Fix negative free disk handling in DiskThresholdDecider
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  es/es-server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  es/es-server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  es/es-server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderUnitTests.java
Labels: ready-to-merge, v/4.1

#9711 Add type safe and less verbose SystemTable builder
  es/es-server/src/main/java/org/elasticsearch/monitor/fs/FsInfo.java
  es/es-server/src/main/java/org/elasticsearch/threadpool/ThreadPoolStats.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/NodeStats.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/NodeStatsCollectSource.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeHeapStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeLoadStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeMemoryStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeNetworkStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeNetworkTCPStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeOsCgroupStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeOsCpuStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeOsInfoStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeOsJvmStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeOsStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodePortStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeProcessStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeStatsThreadPoolExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeThreadPoolsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeVersionStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/SimpleNodeStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/fs/NodeFsStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/fs/NodeFsTotalStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/fs/NodeStatsFsArrayExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/fs/NodeStatsFsDataExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/fs/NodeStatsFsDisksExpression.java
  sql/src/main/java/io/crate/metadata/ColumnIdent.java
  sql/src/main/java/io/crate/metadata/SystemTable.java
  sql/src/main/java/io/crate/metadata/information/InformationTableInfo.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgClassTable.java
  sql/src/main/java/io/crate/metadata/sys/SysHealth.java
  sql/src/main/java/io/crate/metadata/sys/SysHealthTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysNodesTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  sql/src/test/java/io/crate/execution/engine/collect/sources/NodeStatsCollectSourceTest.java
  sql/src/test/java/io/crate/expression/reference/sys/node/NodeStatsContextFieldResolverTest.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/NodeStatsTest.java
  sql/src/test/java/io/crate/integrationtests/SysNodeResiliencyIntegrationTest.java
  sql/src/test/java/io/crate/metadata/SysNodesTableInfoTest.java
  sql/src/test/java/io/crate/metadata/SystemTableTest.java
Labels: ready-to-merge
