Repository crate/crate, pull requests merged in 2020-11, with the labels that each got.

#10708 Add support for PK lookup if additional filters are combined by AND
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/WhereClause.java
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/main/java/io/crate/analyze/where/WhereClauseValidator.java
  server/src/main/java/io/crate/planner/WhereClauseOptimizer.java
  server/src/main/java/io/crate/planner/operators/Get.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteCollectToGet.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/io/crate/planner/DeletePlannerTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
  server/src/test/java/io/crate/testing/Asserts.java
Labels: ready-to-merge

#10738 Bump JNA
  gradle/version.properties
Labels: ready-to-merge

#10743 Fix flaky ShuffleForcedMergePolicyTests#testDiagnostics
  server/src/main/java/org/apache/lucene/index/ShuffleForcedMergePolicy.java
  server/src/test/java/org/apache/lucene/index/ShuffleForcedMergePolicyTests.java
Labels: ready-to-merge

#10742 Fix parameter placeholder handling for insert from query with fetch
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/Fetch.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/4.3

#10747 Fix flaky FilteringAllocationIT
  server/src/test/java/org/elasticsearch/cluster/allocation/FilteringAllocationIT.java
Labels: ready-to-merge

#10744 Add the `sys.snapshot_restore` table.
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshotRestoreInProgress.java
  server/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  server/src/main/java/io/crate/metadata/sys/SysSnapshotRestoreTableInfo.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/metadata/sys/SysSnapshotRestoreTableInfoTest.java
Labels: ready-to-merge

#10749 Run linkcheck in GHA instead of Jenkins
  .github/workflows/main.yml
  Jenkinsfile
Labels: ready-to-merge

#10748 Fix IS NULL and IS NOT NULL handling on ignored objects
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/lucene/IsNullQuery.java
  server/src/main/java/io/crate/lucene/NotQuery.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
Labels: ready-to-merge, v/4.3

#10751 Try to fix flaky testShrinkShardsOfPartition
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
Labels: ready-to-merge

#10756 Mute testAutoExpandReplicasToFilteredNodes in FilteringAllocationIT
  server/src/test/java/org/elasticsearch/cluster/allocation/FilteringAllocationIT.java
Labels: ready-to-merge

#10754 Mention sys.snapshot_restore table in snapshots documentation.
  docs/admin/snapshots.rst
Labels: ready-to-merge

#10760 Fix link to `Crash` inside SSL documentation
  docs/admin/ssl.rst
Labels: ready-to-merge

#10759 Fix usage of regexp_matches wrapped inside subscript as GROUB BY
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/validator/GroupBySymbolValidator.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPoints.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/planner/GroupByScalarPlannerTest.java
Labels: ready-to-merge, v/4.3

#10765 Fix "REPRODUCE WITH" output
  gradle/javaModule.gradle
Labels: ready-to-merge

#10609 Add last-reviewed metadata to some docs
  CONTRIBUTING.rst
  devs/docs/basics.rst
  devs/docs/benchmarks.rst
  devs/docs/es-backports.rst
  devs/docs/index.rst
  devs/docs/logging.rst
  devs/docs/plugins.rst
  devs/docs/release.rst
  devs/docs/tests.rst
  docs/appendices/compatibility.rst
  docs/editions.rst
Labels: area: infra, ready-to-merge, team: tech writing

#10767 Update netty to 4.1.54
  gradle/version.properties
Labels: ready-to-merge

#10757 Add the empty_string_as_null option for ``COPY FROM``.
  benchmarks/src/test/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/test/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/analyze/CopyFromParserProperties.java
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/execution/dsl/phases/FileUriCollectPhase.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/files/LineParser.java
  server/src/main/java/io/crate/execution/engine/collect/files/LineProcessor.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/io/crate/operation/collect/files/CSVLineParser.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/execution/dsl/phases/FileUriCollectPhaseTest.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/LineProcessorTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
Labels: ready-to-merge

#10775 Added the ``delimiter`` option for copy fromm CSV files.
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/analyze/CopyFromParserProperties.java
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/operation/collect/files/CSVLineParser.java
  server/src/test/java/io/crate/execution/dsl/phases/FileUriCollectPhaseTest.java
  server/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
Labels: ready-to-merge

#10770 Added ``rank`` window function
  docs/appendices/release-notes/unreleased.rst
  docs/editions.rst
  docs/general/builtins/window-functions.rst
  enterprise/functions/src/main/java/io/crate/module/EnterpriseFunctionsModule.java
  enterprise/functions/src/main/java/io/crate/window/RankFunctions.java
  enterprise/functions/src/test/java/io/crate/window/RankFunctionIntegrationTest.java
  enterprise/functions/src/test/java/io/crate/window/RankFunctionTest.java
Labels: ready-to-merge

#10778 Added dense_rank window function
  docs/appendices/release-notes/unreleased.rst
  docs/editions.rst
  docs/general/builtins/window-functions.rst
  enterprise/functions/src/main/java/io/crate/window/RankFunctions.java
  enterprise/functions/src/test/java/io/crate/window/RankFunctionsIntegrationTest.java
  enterprise/functions/src/test/java/io/crate/window/RankFunctionsTest.java
Labels: ready-to-merge

#10782 Adjust HEAP recommendation to 25% inside the shipped crate.yml
  app/src/main/dist/config/crate.yml
Labels: ready-to-merge, v/4.3

#10783 Try to fix flaky ResizeShardsITest
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
Labels: ready-to-merge

#10780 Ensure pg_proc.oid and pg_type.typreceive can be joined
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/OidHash.java
  server/src/main/java/io/crate/types/Regproc.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/protocols/postgres/types/RegprocTypeTest.java
  server/src/test/java/io/crate/types/RegprocTypeTest.java
Labels: ready-to-merge, v/4.3

#10789 Compute tables health, exposed via sys.health, based on cluster state
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/sys/MetadataSysModule.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/metadata/sys/TableHealth.java
  server/src/main/java/io/crate/metadata/sys/TableHealthService.java
  server/src/test/java/io/crate/metadata/sys/TableHealthServiceTest.java
Labels: ready-to-merge

#10790 bp: Fail allocation of new primaries in empty cluster
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java
Labels: ready-to-merge

#10793 Fix flaky testDisablingAllocationFiltering
  server/src/test/java/org/elasticsearch/cluster/allocation/FilteringAllocationIT.java
Labels: ready-to-merge

#10791 Print the query symbol on GET logical plans
  docs/sql/statements/refresh.rst
  server/src/main/java/io/crate/planner/operators/Get.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge

#10795 Fix FilteringAllocationIT
  server/src/test/java/org/elasticsearch/cluster/allocation/FilteringAllocationIT.java
Labels: ready-to-merge

#10796 Update graal vm to 20.3.0
  gradle/version.properties
Labels: ready-to-merge

#10797 Fix peer recovery request handling, don't sent response twice
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
Labels: ready-to-merge, v/4.3

#10801 Set SSL client auth value depending on HBA settings
  docs/appendices/release-notes/unreleased.rst
  enterprise/ssl-impl/src/main/java/io/crate/protocols/ssl/SslConfiguration.java
  server/src/main/java/io/crate/auth/AuthSettings.java
  server/src/test/java/io/crate/auth/AuthSettingsTest.java
Labels: ready-to-merge, v/4.3

#10805 Release 4.3.2
  docs/appendices/release-notes/4.3.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10807 Bump version to 4.3.3-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10799 Add scalar function split_part
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/string/StringSplitPartFunction.java
  server/src/test/java/io/crate/expression/scalar/string/StringSplitPartFunctionTest.java
Labels: ready-to-merge

#10808 Reflect 4.3.2 release
  docs/appendices/release-notes/4.3.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10813 Mute CoordinatorTests
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
Labels: ready-to-merge

#10810 Fixed spelling error in 4.3.2 release notes
  docs/appendices/release-notes/4.3.2.rst
Labels: ready-to-merge

#10809 Update gradle to 6.7.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.3

#10729 Broken link in primitive types list - #10445
  blackbox/bootstrap.sh
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#10817 Fix flaky testSeqNoCASLinearizability
  server/src/test/java/io/crate/integrationtests/disruption/discovery/AbstractDisruptionTestCase.java
Labels: ready-to-merge

#10819 Increase SQL request timeout on Github actions
  .github/workflows/main.yml
Labels: ready-to-merge

#10812 Fix testRecentPrimaryInformation
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge

#10823 Generate fromId mapping in Version
  enterprise/licensing/src/main/java/io/crate/license/LicenseKey.java
  enterprise/users/src/main/java/io/crate/metadata/UsersMetadata.java
  enterprise/users/src/main/java/io/crate/metadata/UsersPrivilegesMetadata.java
  plugins/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/LegacyDelimitedPayloadTokenFilterFactory.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionsMetadata.java
  server/src/main/java/io/crate/metadata/view/ViewsMetadata.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/cluster/SnapshotDeletionsInProgress.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/store/Store.java
  server/src/main/java/org/elasticsearch/plugins/PluginInfo.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/metadata/upgrade/MetadataIndexUpgraderTest.java
Labels: ready-to-merge

#10806 Fix changing of "cluster.info.update.interval" global setting
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
Labels: ready-to-merge, v/4.3

#10830 Increase timeouts in MasterDisruptionIT
  server/src/test/java/io/crate/integrationtests/disruption/discovery/AbstractDisruptionTestCase.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
Labels: ready-to-merge
