Repository crate/crate, pull requests merged in 2020-03, with the labels that each got.

#9716 Make sure undefined type can be streamed as text to clients
  sql/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
  sql/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge

#9715 Update netty to 4.1.46
  gradle/version.properties
Labels: ready-to-merge

#9718 Re-use subscript lookupByName method in subscript_obj
  sql/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  sql/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
Labels: ready-to-merge

#9719 Adapt the start of ordinal_position for columns to 1 in SystemTable
  sql/src/main/java/io/crate/metadata/SystemTable.java
Labels: ready-to-merge

#9720 Port latest hybridfs configuration from ES
  es/es-server/src/main/java/org/elasticsearch/index/store/FsDirectoryService.java
  es/es-server/src/test/java/org/elasticsearch/index/store/IndexStoreTests.java
Labels: ready-to-merge

#9722 Improve table recreation sys check docs
  docs/admin/system-information.rst
Labels: ready-to-merge

#9726 Fix doctests (nail crash to <0.25.0)
  blackbox/requirements.txt
Labels: ready-to-merge, v/4.0, v/4.1

#9729 Fix ON CONFLICT (..) UPDATE SET with CASE statements
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/InsertFromValuesAnalyzer.java
  sql/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge

#9730 Fix a NPE that occurred on GROUP BY nested partition column
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/metadata/MapBackedRefResolver.java
  sql/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#9731 Change doctests setup and require crash >= 0.25
  blackbox/requirements.txt
  blackbox/test_docs.py
Labels: ready-to-merge

#9733 Implement proper formatting for window functions
  sql/src/main/java/io/crate/analyze/OrderBy.java
  sql/src/main/java/io/crate/execution/dsl/projection/OrderedTopNProjection.java
  sql/src/main/java/io/crate/expression/symbol/WindowFunction.java
  sql/src/main/java/io/crate/planner/operators/ExplainLogicalPlan.java
  sql/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge

#9737 Remove process method from AnalyzedRelationVisitor
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  sql/src/main/java/io/crate/analyze/AnalyzedShowCreateTable.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/main/java/io/crate/analyze/TableIdentsExtractor.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedRelationVisitor.java
  sql/src/main/java/io/crate/planner/IsStatementExecutionAllowed.java
Labels: ready-to-merge

#9736 Make sure that aliased literals are not de-duplicated
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#9734 Release 4.1.3
  docs/appendices/release-notes/4.1.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9738 Bump version to 4.1.4-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9739 Remove unused declarations
  enterprise/users/src/test/java/io/crate/scalar/systeminformation/UserFunctionTest.java
  es/es-server/src/main/java/org/elasticsearch/common/collect/MapBuilder.java
  sql/src/main/java/io/crate/action/sql/RowConsumerToResultReceiver.java
  sql/src/main/java/io/crate/analyze/AbstractDDLAnalyzedStatement.java
  sql/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  sql/src/main/java/io/crate/analyze/AlterTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/AlterTableRerouteAnalyzer.java
  sql/src/main/java/io/crate/analyze/Analysis.java
  sql/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  sql/src/main/java/io/crate/analyze/CopyAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateAnalyzerStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateBlobTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateFunctionAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateRepositoryAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateSnapshotAnalyzer.java
  sql/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/ExplainStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/InsertAnalyzer.java
  sql/src/main/java/io/crate/analyze/KillAnalyzer.java
  sql/src/main/java/io/crate/analyze/OptimizeTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/ParameterContext.java
  sql/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java
  sql/src/main/java/io/crate/analyze/RefreshTableAnalyzer.java
  sql/src/main/java/io/crate/analyze/RestoreSnapshotAnalyzer.java
  sql/src/main/java/io/crate/analyze/ShowStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/UserAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  sql/src/main/java/io/crate/analyze/relations/StatementAnalysisContext.java
  sql/src/main/java/io/crate/analyze/relations/select/SelectAnalysis.java
  sql/src/main/java/io/crate/execution/dml/upsert/CheckConstraints.java
  sql/src/main/java/io/crate/execution/dsl/projection/Projection.java
  sql/src/main/java/io/crate/expression/symbol/Literal.java
  sql/src/main/java/io/crate/metadata/table/ColumnRegistrar.java
  sql/src/main/java/io/crate/planner/ExplainNode.java
  sql/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  sql/src/main/java/io/crate/statistics/Samples.java
  sql/src/test/java/io/crate/analyze/ParameterContextTest.java
  sql/src/test/java/io/crate/analyze/PartitionPropertiesAnalyzerTest.java
  sql/src/test/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  sql/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  sql/src/test/java/io/crate/testing/QueryTester.java
  sql/src/test/java/io/crate/testing/SqlExpressions.java
  sql/src/test/java/io/crate/testing/T3.java
Labels: ready-to-merge

#9740 Reflect 4.1.3 release
  docs/appendices/release-notes/4.1.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9717 Add primary keys to pg_class and pg_index
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  sql/src/main/java/io/crate/metadata/pgcatalog/OidHash.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgClassTable.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgIndexTable.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge

#9744 Fix array_agg return type declaration
  sql/src/main/java/io/crate/execution/engine/aggregation/impl/ArrayAgg.java
  sql/src/test/java/io/crate/execution/engine/aggregation/impl/ArrayAggTest.java
Labels: ready-to-merge

#9742 Add server_version_num and server_version session setting
  docs/appendices/release-notes/unreleased.rst
  docs/config/session.rst
  sql/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  sql/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#9752 Fix top-n-distinct for cases where the group columns are a sub-set of the source
  dex/src/main/java/io/crate/data/TopNDistinctBatchIterator.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/TopNDistinct.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/4.1

#9750 Add the `pg_catalog.pg_proc` table.
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  sql/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/main/java/io/crate/metadata/pgcatalog/OidHash.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgDatabaseTable.java
  sql/src/main/java/io/crate/metadata/pgcatalog/PgProcTable.java
  sql/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  sql/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  sql/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#9751 Update netty to 4.1.47
  gradle/version.properties
Labels: ready-to-merge

#9755 Fix top-n-distinct for cases where the group columns are a sub-set of the source
  dex/src/main/java/io/crate/data/TopNDistinctBatchIterator.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/TopNDistinct.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#9745 Add column pruning
  sql/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  sql/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  sql/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/main/java/io/crate/planner/operators/Count.java
  sql/src/main/java/io/crate/planner/operators/Eval.java
  sql/src/main/java/io/crate/planner/operators/Filter.java
  sql/src/main/java/io/crate/planner/operators/ForwardingLogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  sql/src/main/java/io/crate/planner/operators/HashAggregate.java
  sql/src/main/java/io/crate/planner/operators/HashJoin.java
  sql/src/main/java/io/crate/planner/operators/Insert.java
  sql/src/main/java/io/crate/planner/operators/InsertFromValues.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  sql/src/main/java/io/crate/planner/operators/Order.java
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/main/java/io/crate/planner/operators/Rename.java
  sql/src/main/java/io/crate/planner/operators/TableFunction.java
  sql/src/main/java/io/crate/planner/operators/Union.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RewriteCollectToGet.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
  sql/src/test/java/io/crate/planner/SubQueryPlannerTest.java
  sql/src/test/java/io/crate/planner/UnionPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/operators/SelectDistinctLogicalPlannerTest.java
Labels: ready-to-merge

#9753 Make sure inserts from lazy table functions are throttled
  dex/src/main/java/io/crate/data/AsyncOperationBatchIterator.java
  dex/src/main/java/io/crate/data/BatchIterator.java
  dex/src/main/java/io/crate/data/CloseAssertingBatchIterator.java
  dex/src/main/java/io/crate/data/CollectingBatchIterator.java
  dex/src/main/java/io/crate/data/CompositeBatchIterator.java
  dex/src/main/java/io/crate/data/FlatMapBatchIterator.java
  dex/src/main/java/io/crate/data/ForwardingBatchIterator.java
  dex/src/main/java/io/crate/data/InMemoryBatchIterator.java
  dex/src/main/java/io/crate/data/MappedForwardingBatchIterator.java
  dex/src/main/java/io/crate/data/TopNDistinctBatchIterator.java
  dex/src/main/java/io/crate/data/join/JoinBatchIterator.java
  dex/src/main/java/io/crate/data/join/SemiJoinNLBatchIterator.java
  dex/src/test/java/io/crate/testing/BatchSimulatingIterator.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/TableFunctionCollectSource.java
  sql/src/main/java/io/crate/execution/engine/distribution/merge/BatchPagingIterator.java
  sql/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/DMLProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/main/java/io/crate/expression/tablefunctions/EmptyRowTableFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  sql/src/main/java/io/crate/expression/tablefunctions/PgExpandArray.java
  sql/src/main/java/io/crate/expression/tablefunctions/PgGetKeywordsFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
  sql/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/ValuesFunction.java
  sql/src/main/java/io/crate/metadata/tablefunctions/TableFunctionImplementation.java
Labels: ready-to-merge, v/4.1

#9756 Make sure inserts from lazy table functions are throttled
  dex/src/main/java/io/crate/data/AsyncOperationBatchIterator.java
  dex/src/main/java/io/crate/data/BatchIterator.java
  dex/src/main/java/io/crate/data/CloseAssertingBatchIterator.java
  dex/src/main/java/io/crate/data/CollectingBatchIterator.java
  dex/src/main/java/io/crate/data/CompositeBatchIterator.java
  dex/src/main/java/io/crate/data/FlatMapBatchIterator.java
  dex/src/main/java/io/crate/data/ForwardingBatchIterator.java
  dex/src/main/java/io/crate/data/InMemoryBatchIterator.java
  dex/src/main/java/io/crate/data/MappedForwardingBatchIterator.java
  dex/src/main/java/io/crate/data/TopNDistinctBatchIterator.java
  dex/src/main/java/io/crate/data/join/JoinBatchIterator.java
  dex/src/main/java/io/crate/data/join/SemiJoinNLBatchIterator.java
  dex/src/test/java/io/crate/testing/BatchSimulatingIterator.java
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  sql/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/TableFunctionCollectSource.java
  sql/src/main/java/io/crate/execution/engine/distribution/merge/BatchPagingIterator.java
  sql/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/DMLProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  sql/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  sql/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  sql/src/main/java/io/crate/expression/tablefunctions/EmptyRowTableFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  sql/src/main/java/io/crate/expression/tablefunctions/PgGetKeywordsFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
  sql/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  sql/src/main/java/io/crate/expression/tablefunctions/ValuesFunction.java
  sql/src/main/java/io/crate/metadata/tablefunctions/TableFunctionImplementation.java
Labels: ready-to-merge

#9746 Use bundled JDK instead of host system JDK.
  .github/workflows/main.yml
  Jenkinsfile
  app/build.gradle
  app/src/bin/crate.bat
  app/src/main/dist/bin/crate
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/io/crate/gradle/OS.java
  buildSrc/src/main/java/io/crate/gradle/plugins/jdk/Jdk.java
  buildSrc/src/main/java/io/crate/gradle/plugins/jdk/JdkDownloadPlugin.java
  buildSrc/src/main/java/io/crate/gradle/plugins/jdk/SymbolicLinkPreservingUntarTask.java
  buildSrc/src/main/resources/META-INF/gradle-plugins/jdk-download.properties
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkTest.java
  buildSrc/src/testKit/jdk-download/build.gradle
  buildSrc/src/testKit/jdk-download/fake_repos/jdk_repo_adoptopenjdk_13.0.2+8/linux.tar.gz
  buildSrc/src/testKit/jdk-download/fake_repos/jdk_repo_adoptopenjdk_13.0.2+8/mac.tar.gz
  buildSrc/src/testKit/jdk-download/fake_repos/jdk_repo_adoptopenjdk_13.0.2+8/windows.zip
  buildSrc/src/testKit/jdk-download/settings.gradle
  buildSrc/src/testKit/jdk-download/sub/build.gradle
  docs/appendices/release-notes/unreleased.rst
  es/build.gradle
  es/es-server/build.gradle
  gradle/version.properties
Labels: ready-to-merge

#9758 Remove process from AnalyzedStatementVisitor
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  sql/src/main/java/io/crate/action/sql/DCLStatementDispatcher.java
  sql/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  sql/src/main/java/io/crate/analyze/Relations.java
  sql/src/main/java/io/crate/planner/Planner.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
Labels: ready-to-merge

#9759 Change EXPLAIN to print the logical plan
  build.gradle
  sql/src/main/java/io/crate/analyze/ExplainAnalyzedStatement.java
  sql/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/main/java/io/crate/planner/operators/Count.java
  sql/src/main/java/io/crate/planner/operators/ExplainLogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/Filter.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  sql/src/main/java/io/crate/planner/operators/HashJoin.java
  sql/src/main/java/io/crate/planner/operators/Limit.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/MultiPhase.java
  sql/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  sql/src/main/java/io/crate/planner/operators/Order.java
  sql/src/main/java/io/crate/planner/operators/PrintContext.java
  sql/src/main/java/io/crate/planner/operators/Rename.java
  sql/src/main/java/io/crate/planner/operators/RootRelationBoundary.java
  sql/src/main/java/io/crate/planner/operators/TableFunction.java
  sql/src/main/java/io/crate/planner/operators/TopNDistinct.java
  sql/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  sql/src/test/java/io/crate/integrationtests/SysClusterTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  sql/src/test/java/io/crate/planner/ExplainPlannerTest.java
  sql/src/test/java/io/crate/planner/SelectPlannerTest.java
  sql/src/test/java/io/crate/planner/UnionPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/JoinTest.java
  sql/src/test/java/io/crate/planner/operators/LimitTest.java
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/operators/SelectDistinctLogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge

#9760 gradle: Remove pmd, update checkstyle
  common/src/main/java/io/crate/interval/IntervalParser.java
  dex/src/main/java/io/crate/data/SentinelRow.java
  enterprise/ssl-impl/src/main/java/io/crate/protocols/ssl/SslConfiguration.java
  gradle/javaModule.gradle
  shared/src/main/java/io/crate/common/Octal.java
  sql/src/main/java/io/crate/analyze/DataTypeAnalyzer.java
  sql/src/main/java/io/crate/execution/dml/ShardResponse.java
  sql/src/main/java/io/crate/execution/engine/FirstColumnConsumers.java
  sql/src/main/java/io/crate/metadata/DanglingArtifactsService.java
  ssl/src/main/java/io/crate/protocols/ssl/SslConfigSettings.java
Labels: ready-to-merge

#9761 Update docker run instructions in README
  README.rst
Labels: ready-to-merge

#9768 Tests: Update hadoop version to 2.8.5
  blackbox/test_hdfs.py
Labels: ready-to-merge

#9767 Extend PR template with reminder about sql_features table
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-to-merge

#9773 CI: Kill stale CrateDB processes before itest run
  Jenkinsfile
  blackbox/kill_4200.py
Labels: ready-to-merge

#9772 Update netty to 4.1.48
  gradle/version.properties
Labels: ready-to-merge

#9769 Migrate SysOperationsLogTableInfo, SysSummitsTableInfo and SysSnapshotsTableInfo to SystemTable
  sql/src/main/java/io/crate/metadata/SystemTable.java
  sql/src/main/java/io/crate/metadata/sys/SysJobsLogTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysJobsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysMetricsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysOperationsLogTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSnapshotsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysSummitsTableInfo.java
  sql/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  sql/src/test/java/io/crate/expression/reference/information/TablesSettingsExpressionTest.java
Labels: ready-to-merge

#9774 Update graalvm to 20.0.0
  gradle/version.properties
Labels: ready-to-merge

#9778 Fix WindowAgg column pruning
  sql/src/main/java/io/crate/breaker/EstimateRowSize.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#9781 Release 4.1.4
  docs/appendices/release-notes/4.1.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9783 Bump version to 4.1.5-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#9784 Reflect 4.1.4 release
  docs/appendices/release-notes/4.1.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#9779 Update minimum wire compat version to 4.1
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/test/java/org/elasticsearch/VersionTest.java
Labels: ready-to-merge

#9791 Use small block size if table stats are not available
  sql/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  sql/src/main/java/io/crate/execution/engine/join/NestedLoopOperation.java
  sql/src/main/java/io/crate/execution/engine/join/RamBlockSizeCalculator.java
  sql/src/test/java/io/crate/execution/engine/join/RamBlockSizeCalculatorTest.java
  sql/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#9792 Revert "Update minimum wire compat version to 4.1"
  es/es-server/src/main/java/org/elasticsearch/Version.java
  es/es-server/src/test/java/org/elasticsearch/VersionTest.java
Labels: ready-to-merge

#9793 Fix exact matches of function signatures
  sql/src/main/java/io/crate/expression/scalar/arithmetic/AbsFunction.java
  sql/src/main/java/io/crate/metadata/FuncResolver.java
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/main/java/io/crate/metadata/functions/Signature.java
  sql/src/test/java/io/crate/expression/scalar/DateFormatFunctionTest.java
Labels: ready-to-merge

#9789 Use postgresql jdbc client instead of crate jdbc
  app/build.gradle
  enterprise/functions/build.gradle
  enterprise/lang-js/build.gradle
  enterprise/licensing/build.gradle
  enterprise/ssl-impl/build.gradle
  enterprise/users/build.gradle
  enterprise/users/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  enterprise/users/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  es/es-server/src/main/java/org/elasticsearch/common/Numbers.java
  es/es-x-content/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java
  gradle/version.properties
  sql/build.gradle
  sql/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/PostgresITest.java
  sql/src/test/java/io/crate/integrationtests/PostgresJobsLogsITest.java
  sql/src/test/java/io/crate/integrationtests/RenameTableIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  sql/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  sql/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#9794 Remove unused ExpressionToXYVisitor
  sql/src/main/java/io/crate/analyze/NumberOfShards.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToNumberVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToObjectVisitor.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionToStringVisitor.java
  sql/src/main/java/io/crate/metadata/settings/session/SessionSetting.java
  sql/src/test/java/io/crate/analyze/NumberOfShardsTest.java
  sql/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#9798 Add an assertion to limit allocated bytes for current thread
  sql/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  sql/src/test/java/io/crate/planner/operators/PushDownTest.java
  sql/src/test/java/io/crate/planner/operators/WindowAggTest.java
  sql/src/test/java/io/crate/testing/MemoryLimits.java
Labels: ready-to-merge

#9787 Migrate to junit5 / JUnitPlatform
  blob/build.gradle
  build.gradle
  common/build.gradle
  dex/build.gradle
  dex/src/test/java/io/crate/data/BatchIteratorsTest.java
  es/build.gradle
  es/es-testing/build.gradle
  gradle/javaModule.gradle
  gradle/version.properties
  pgwire/build.gradle
  shared/build.gradle
  sql-parser/build.gradle
Labels: ready-to-merge

#9790 Update admonition to link to tutorials section
  docs/index.rst
Labels: ready-to-merge

#9803 Update gradle to 6.3
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.1

#9808 Refactor UDF scalars to use new function registry.
  enterprise/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
  sql/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/test/java/io/crate/expression/udf/UserDefinedFunctionsTest.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
Labels: ready-to-merge

#9811 Refactor most arithmetic scalars to new function registry
  sql/src/main/java/io/crate/analyze/NegateLiterals.java
  sql/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/ArrayFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/CeilFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/FloorFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/LogFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/NegateFunctions.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctions.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/RandomFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/RoundFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/SquareRootFunction.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/TruncFunction.java
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/main/java/io/crate/metadata/functions/Signature.java
  sql/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
Labels: ready-to-merge

#9815 Early return if no global checkpoint listeners
  es/es-server/src/main/java/org/elasticsearch/index/shard/GlobalCheckpointListeners.java
Labels: ready-to-merge

#9816 Fix testConcurrentFunctionRegistering
  sql/src/main/java/io/crate/metadata/Functions.java
  sql/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
Labels: ready-to-merge

#9818 Avoid HashMap creation for CSV to JSON conversion
  .gitignore
  sql/src/main/java/io/crate/execution/engine/collect/files/LineParser.java
  sql/src/main/java/io/crate/execution/engine/collect/files/LineProcessor.java
  sql/src/main/java/io/crate/operation/collect/files/CSVLineParser.java
  sql/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
Labels: ready-to-merge

#9813 Update estimated row size of Collect after prune or fetch rewrite
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/main/java/io/crate/planner/operators/Count.java
  sql/src/main/java/io/crate/planner/operators/Eval.java
  sql/src/main/java/io/crate/planner/operators/Fetch.java
  sql/src/main/java/io/crate/planner/operators/Filter.java
  sql/src/main/java/io/crate/planner/operators/ForwardingLogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/Get.java
  sql/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  sql/src/main/java/io/crate/planner/operators/HashAggregate.java
  sql/src/main/java/io/crate/planner/operators/HashJoin.java
  sql/src/main/java/io/crate/planner/operators/Insert.java
  sql/src/main/java/io/crate/planner/operators/InsertFromValues.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlan.java
  sql/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  sql/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  sql/src/main/java/io/crate/planner/operators/Order.java
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/main/java/io/crate/planner/operators/Rename.java
  sql/src/main/java/io/crate/planner/operators/TableFunction.java
  sql/src/main/java/io/crate/planner/operators/Union.java
  sql/src/main/java/io/crate/planner/operators/WindowAgg.java
  sql/src/main/java/io/crate/planner/optimizer/rule/RewriteToQueryThenFetch.java
  sql/src/test/java/io/crate/planner/operators/CollectTest.java
  sql/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
Labels: ready-to-merge

#9821 Use source lookup in fetch operations
  sql/src/main/java/io/crate/planner/operators/Collect.java
  sql/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
Labels: ready-to-merge

#9820 Remove unused declarations
  sql/src/main/java/io/crate/analyze/WhereClause.java
  sql/src/main/java/io/crate/analyze/WindowDefinition.java
  sql/src/main/java/io/crate/analyze/relations/JoinPair.java
  sql/src/main/java/io/crate/analyze/relations/RelationPrinter.java
  sql/src/main/java/io/crate/execution/engine/collect/BlobShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/CollectSourceResolver.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  sql/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectorProviderFactory.java
  sql/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  sql/src/main/java/io/crate/execution/jobs/JobSetup.java
  sql/src/main/java/io/crate/execution/support/Transports.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NestedNodeStatsExpression.java
  sql/src/main/java/io/crate/expression/reference/sys/node/NodeStatsArrayTypeExpression.java
  sql/src/test/java/io/crate/execution/engine/collect/BlobShardCollectorProviderTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  sql/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
Labels: ready-to-merge

#9824 Refactor all postgres scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/postgres/CurrentSettingFunction.java
  sql/src/main/java/io/crate/expression/scalar/postgres/PgBackendPidFunction.java
  sql/src/main/java/io/crate/expression/scalar/postgres/PgGetUserByIdFunction.java
Labels: ready-to-merge

#9823 Refactor all geo scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/geo/CoordinateFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/DistanceFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/GeoHashFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/IntersectsFunction.java
  sql/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
  sql/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
Labels: ready-to-merge

#9825 Refactor all regex scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/regex/MatchesFunction.java
  sql/src/main/java/io/crate/expression/scalar/regex/RegexpReplaceFunction.java
  sql/src/test/java/io/crate/expression/scalar/regex/RegexpReplaceFunctionTest.java
Labels: ready-to-merge

#9826 Refactor all string scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/string/AsciiFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/EncodeDecodeFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/HashFunctions.java
  sql/src/main/java/io/crate/expression/scalar/string/InitCapFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/LengthFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/QuoteIdentFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/ReplaceFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/StringCaseFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/StringLeftRightFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/StringPaddingFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/StringRepeatFunction.java
  sql/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
Labels: ready-to-merge

#9828 Refactor all time/date scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/DateFormatFunction.java
  sql/src/main/java/io/crate/expression/scalar/DateTruncFunction.java
  sql/src/main/java/io/crate/expression/scalar/ExtractFunctions.java
  sql/src/main/java/io/crate/expression/scalar/timestamp/CurrentTimestampFunction.java
  sql/src/main/java/io/crate/expression/scalar/timestamp/NowFunction.java
  sql/src/main/java/io/crate/expression/scalar/timestamp/TimezoneFunction.java
Labels: ready-to-merge

#9817 Allow the definition of check constraints in ALTER ADD COLUMN statements
  sql/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  sql/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  sql/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  sql/src/main/java/io/crate/analyze/expressions/TableReferenceResolver.java
  sql/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  sql/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  sql/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  sql/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: feature: sql: ddl

#9830 Use BlockBasedRamAccounting for nested loop & hash join
  sql/src/main/java/io/crate/execution/jobs/JobSetup.java
Labels: ready-to-merge

#9832 Fix NPE with COPY TO .. WHERE pk_column = ...
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  sql/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#9775 Update JDK to 14
  .github/workflows/main.yml
  .lgtm.yml
  gradle/version.properties
Labels: ready-to-merge

#9827 Refactor all system information scalars to new function registry
  sql/src/main/java/io/crate/expression/scalar/CurrentDatabaseFunction.java
  sql/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  sql/src/main/java/io/crate/expression/scalar/arithmetic/NegateFunctions.java
  sql/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/CurrentSchemaFunction.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/CurrentSchemasFunction.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/ObjDescriptionFunction.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/PgGetExpr.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/PgTypeofFunction.java
  sql/src/main/java/io/crate/expression/scalar/systeminformation/VersionFunction.java
  sql/src/main/java/io/crate/metadata/functions/Signature.java
Labels: ready-to-merge

#9829 Refactor all array scalars to new function registry
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  sql/src/main/java/io/crate/expression/scalar/ArrayBoundFunctionResolver.java
  sql/src/main/java/io/crate/expression/scalar/ArrayCatFunction.java
  sql/src/main/java/io/crate/expression/scalar/ArrayDifferenceFunction.java
  sql/src/main/java/io/crate/expression/scalar/ArrayLowerFunction.java
  sql/src/main/java/io/crate/expression/scalar/ArrayUniqueFunction.java
  sql/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  sql/src/main/java/io/crate/expression/scalar/CollectionAverageFunction.java
  sql/src/main/java/io/crate/expression/scalar/CollectionCountFunction.java
  sql/src/main/java/io/crate/expression/scalar/ConcatFunction.java
  sql/src/main/java/io/crate/expression/scalar/StringToArrayFunction.java
  sql/src/main/java/io/crate/expression/scalar/array/ArrayArgumentValidators.java
  sql/src/test/java/io/crate/expression/scalar/ArrayBoundFunctionResolverTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayCatFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayDifferenceFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayLowerFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ArrayUpperFunctionTest.java
  sql/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
Labels: ready-to-merge

#9834 Refactor format, ignore3vl, pi, substr to new function registry
  sql/src/main/java/io/crate/expression/scalar/FormatFunction.java
  sql/src/main/java/io/crate/expression/scalar/Ignore3vlFunction.java
  sql/src/main/java/io/crate/expression/scalar/PiFunction.java
  sql/src/main/java/io/crate/expression/scalar/SubstrFunction.java
  sql/src/main/java/io/crate/metadata/functions/Signature.java
Labels: ready-to-merge
