Repository crate/crate, pull requests merged in 2020-09, with the labels that each got.

#10466 bp: Make ChannelActionListener a top-level class
  server/src/main/java/org/elasticsearch/action/support/HandledTransportAction.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
Labels: ready-to-merge

#10467 bp: Peer recovery should flush at the end
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
Labels: ready-to-merge

#10469 Remove uneeded imports from JoinIntegrationTest
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#10471 Simplify bash script to make more readable
  blackbox/bin/sphinx
Labels: ready-to-merge

#10473 Move error mapping for clients closer to the border
  libs/shared/src/main/java/io/crate/exceptions/Exceptions.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/exceptions/SQLExceptions.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  server/src/main/java/io/crate/protocols/postgres/RowCountReceiver.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#10475 Improve assertion errors for SQLError codes
  server/src/test/java/io/crate/testing/SQLErrorMatcher.java
Labels: ready-to-merge

#10472 Fix primary key lookup with parameter placeholders requiring casts
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/SymbolEvaluator.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/planner/node/ddl/UpdateSettingsPlanTest.java
Labels: ready-to-merge, v/4.2

#10479 Make JobKilledException serializable to fix flaky KillIntegrationTest
  server/src/main/java/io/crate/exceptions/JobKilledException.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
Labels: ready-to-merge

#10480 Update checkstyle to 8.36
  gradle/javaModule.gradle
Labels: ready-to-merge

#10474 Map InvalidSchemaNameException to PG 3F000 error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
Labels: ready-to-merge

#10478 Map AmbiguousColumnAliasException to PG 42P09 error code
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
Labels: ready-to-merge

#10486 Map UserDefinedFunctionUnknownException to PG 42883 error
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
Labels: ready-to-merge

#10490 Return non-null ordinal_position for object sub-cols
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/test/java/io/crate/execution/engine/collect/sources/ColumnsIterableTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge

#10491 Fix usage of quoted subscript expr as an alias
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/test/java/io/crate/analyze/SubSelectAnalyzerTest.java
Labels: ready-to-merge, tool: PowerBI

#10492 Match all Exception types in KillIntegrationTest to fix flakiness
  server/src/main/java/io/crate/exceptions/TaskMissing.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/integrationtests/KillIntegrationTest.java
Labels: ready-to-merge

#10305 Add scalar function pg_get_function_result required by conn.getMetaData().getFunctions()
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/PgGetFunctionResultFunction.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgProcTable.java
  server/src/test/java/io/crate/expression/scalar/systeminformation/PgGetFunctionResultFunctionTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
Labels: ready-to-merge

#10200 Improve error messages on repository creation
  docs/appendices/release-notes/unreleased.rst
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  plugins/es-repository-s3/build.gradle
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryIntegrationTest.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge

#10481 Use doc values aggregators in the group by iterator.
  server/src/main/java/io/crate/breaker/MultiSizeEstimator.java
  server/src/main/java/io/crate/execution/engine/aggregation/GroupingCollector.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/operation/aggregation/AggregationTest.java
Labels: ready-to-merge

#10502 Add codeql analysis Github action
  .github/workflows/codeql-analysis.yml
Labels: ready-to-merge

#10514 Fix the join condition hash symbols ordering in the HashJoin.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/HashJoinConditionSymbolsExtractor.java
  server/src/test/java/io/crate/planner/operators/HashJoinConditionSymbolsExtractorTest.java
Labels: ready-to-merge, v/4.2

#10500 Improve error handling when group by with an undefined type
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/GroupAndAggregateSemantics.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#10512 Clarify indexing/tokenization schemes with dynamic object columns
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#10520 Fix aggregation plan building when inputs contain params
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  server/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  server/src/main/java/io/crate/planner/operators/HashAggregate.java
  server/src/test/java/io/crate/planner/consumer/GlobalAggregatePlannerTest.java
  server/src/test/java/io/crate/testing/SymbolMatchers.java
Labels: ready-to-merge, v/4.2

#10525 Do not close index searchers outside of the CollectTask.
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
Labels: ready-to-merge

#10527 Also pause insert-from-query on high memory usage
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/indexing/BatchIteratorBackpressureExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/test/java/io/crate/execution/engine/indexing/BatchIteratorBackpressureExecutorTest.java
Labels: ready-to-merge, v/4.2

#10530 Update httpclient and httpcore
  gradle/version.properties
Labels: ready-to-merge

#10532 Remove obsolete Ignore annotation for subscript on object literal
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge

#10533 Fix division by 0 if debug logging is enabled on engine.indexing
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
Labels: ready-to-merge

#10534 bp: Do not block transport thread on startup
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
Labels: ready-to-merge

#10539 Fix testRestartNodeWhileIndexing
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10540 Fix flaky testTrimUnreferencedTranslogFiles
  server/src/test/java/org/elasticsearch/index/engine/NoOpEngineTests.java
Labels: ready-to-merge

#10541 Add a .vscode/launch.json
  .vscode/launch.json
Labels: ready-to-merge

#10535 Deprecate fielddata circuit breaker setting
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  enterprise/jmx-monitoring/src/main/java/io/crate/beans/CircuitBreakers.java
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/elasticsearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreaker.java
  server/src/test/java/org/elasticsearch/common/settings/MemorySizeSettingsTests.java
  server/src/test/java/org/elasticsearch/indices/breaker/NoneCircuitBreakerService.java
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10544 Increase assertBusy timeout for testMappingNewFieldsTimeoutDoesntAffectCheckpoints
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
Labels: ready-to-merge

#10546 Remove lgtm artifacts
  .lgtm.yml
  README.rst
Labels: ready-to-merge

#10536 Account for memory used and adapt size in insert-from-query operations
  server/src/main/java/io/crate/execution/engine/collect/BlobShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/sources/CollectSourceResolver.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectorProviderFactory.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/NoopCircuitBreaker.java
  server/src/test/java/io/crate/execution/engine/collect/BlobShardCollectorProviderTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorUnitTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
  server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreaker.java
Labels: ready-to-merge, v/4.2

#10551 Remove two ignored planner tests
  server/src/test/java/io/crate/planner/consumer/GlobalAggregatePlannerTest.java
  server/src/test/java/io/crate/planner/consumer/GroupByPlannerTest.java
Labels: ready-to-merge

#10552 Remove some unnecessary testing code
  server/src/test/java/org/elasticsearch/test/ESIntegTestCase.java
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10554 Update bundled JDK to 15+36
  build.gradle
  buildSrc/src/main/java/io/crate/gradle/plugins/jdk/Jdk.java
  gradle/version.properties
Labels: ready-to-merge

#10555 Always close searchers via CollectTask
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
Labels: ready-to-merge

#10556 Fix "Searcher for reader with id X not found" flaky tests
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
Labels: ready-to-merge

#10549 Deprecate the overhead circuit breaker setting
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  server/src/main/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/NoopCircuitBreaker.java
  server/src/main/java/org/elasticsearch/indices/breaker/BreakerSettings.java
  server/src/main/java/org/elasticsearch/indices/breaker/CircuitBreakerStats.java
  server/src/main/java/org/elasticsearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/io/crate/breaker/CrateCircuitBreakerServiceTest.java
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateBreakerTest.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
  server/src/test/java/org/elasticsearch/common/breaker/MemoryCircuitBreaker.java
Labels: ready-to-merge

#10523 Update developer guides
  CONTRIBUTING.rst
  devs/docs/architecture.rst
  devs/docs/architecture.svg
  devs/docs/basics.rst
  devs/docs/benchmarks.rst
  devs/docs/es-backports.rst
  devs/docs/index.rst
  devs/docs/logging.rst
  devs/docs/plugins.rst
  devs/docs/release.rst
  devs/docs/tests.rst
Labels: ready-to-merge

#10557 Fix BWC issue with aggregation func resolving
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  server/src/main/java/io/crate/expression/symbol/Aggregation.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/test/java/io/crate/expression/symbol/AggregationTest.java
Labels: ready-to-merge, v/4.2

#10493 ES backports related to ShardLock error details
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
  server/src/main/java/org/elasticsearch/env/ShardLock.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/store/Store.java
Labels: ready-to-merge

#10558 Remove duplicated registerRequestHandler overloads
  server/src/main/java/io/crate/blob/transfer/BlobHeadRequestHandler.java
  server/src/main/java/io/crate/cluster/decommission/TransportDecommissionNodeAction.java
  server/src/main/java/io/crate/execution/engine/collect/stats/TransportNodeStatsAction.java
  server/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
  server/src/main/java/io/crate/execution/engine/fetch/TransportFetchNodeAction.java
  server/src/main/java/io/crate/execution/engine/profile/TransportCollectProfileNodeAction.java
  server/src/main/java/io/crate/execution/jobs/kill/TransportKillNodeAction.java
  server/src/main/java/io/crate/execution/jobs/transport/TransportJobAction.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java
  server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/elasticsearch/cluster/action/index/NodeMappingRefreshAction.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/elasticsearch/gateway/LocalAllocateDangledIndices.java
  server/src/main/java/org/elasticsearch/indices/flush/SyncedFlushService.java
  server/src/main/java/org/elasticsearch/indices/recovery/BlobRecoveryTarget.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/elasticsearch/indices/store/IndicesStore.java
  server/src/main/java/org/elasticsearch/repositories/VerifyNodeRepositoryAction.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
Labels: ready-to-merge

#10561 Make completionFuture mandatory in CapturingRowConsumer
  libs/dex/src/main/java/io/crate/data/CapturingRowConsumer.java
Labels: ready-to-merge

#10565 Acquire indexService eagerly in SharedShardContext(s)
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContext.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
Labels: ready-to-merge

#10566 Port over ES OpenCloseIndexIT tests.
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
Labels: ready-to-merge

#10562 Remove Guava ImmutableList from some server module tests
  server/src/main/java/io/crate/analyze/Id.java
  server/src/test/java/io/crate/analyze/IdTest.java
  server/src/test/java/io/crate/analyze/OrderByTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/where/DocKeysTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
  server/src/test/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge

#10570 Fix CIDR range check in host based authentication
  docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/main/java/io/crate/auth/HostBasedAuthentication.java
  enterprise/users/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
Labels: ready-to-merge, v/4.2

#10567 Improve "is still locked" errors in test layer
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10572 Release 4.2.5.
  docs/appendices/release-notes/4.2.5.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10569 Add more context to source of acquireSearcher calls
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
Labels: ready-to-merge

#10568 Avoid wrapping AssertionError in RuntimeExceptions in test layer
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#10574 Bump version to 4.2.6-SNAPSHOT.
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10575 Reflect 4.2.5 release.
  docs/appendices/release-notes/4.2.5.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10573 Remove bogus code from innerNoOp
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
Labels: ready-to-merge

#10577 Deduplicate CircuitBreakerException
  server/src/main/java/io/crate/exceptions/CircuitBreakingException.java
  server/src/main/java/io/crate/exceptions/SQLExceptions.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/PercentileAggregation.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#10578 Make memory reservation based on free bytes in insert-from-query
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
Labels: ready-to-merge, v/4.2

#10580 Port over some of ReadOnlyEngineTests.
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
Labels: ready-to-merge

#10584 Don't pass DistributingConsumer logger around unnecessarily
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumerFactory.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
Labels: ready-to-merge

#10553 Fix flaky ThreadPoolsExhaustedIntegrationTest
  server/src/main/java/io/crate/common/collections/RefCountedItem.java
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContext.java
  server/src/test/java/io/crate/execution/engine/collect/CollectTaskTest.java
  server/src/test/java/io/crate/integrationtests/ThreadPoolsExhaustedIntegrationTest.java
Labels: ready-to-merge

#10587 Expose IndexSearcher instead of Engine.Searcher in SharedShardContext
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContext.java
  server/src/test/java/io/crate/execution/engine/collect/CollectTaskTest.java
Labels: ready-to-merge

#10588 Add optimizer rule for count(*) on aliased table
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/main/java/io/crate/planner/optimizer/rule/MergeAggregateRenameAndCollectToCount.java
  server/src/test/java/io/crate/integrationtests/CountStarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#10581 Port over some of IndexShardTests.
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryState.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTestCase.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/shard/RestoreOnlyRepository.java
Labels: ready-to-merge

#10593 Fix sys.cluster usage in joins
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/SystemCollectSource.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/4.2

#10595 Remove unused reader-wrapper hook
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/operation/aggregation/AggregationTest.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTestCase.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#10599 Fix searcher double-release race condition
  server/src/main/java/io/crate/common/collections/RefCountedItem.java
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContext.java
Labels: ready-to-merge

#10601 bp: Use correct global checkpoint sync interval
  server/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
Labels: ready-to-merge

#10560 Ensure searchers are always closed
  libs/dex/src/main/java/io/crate/data/CapturingRowConsumer.java
  server/src/main/java/io/crate/execution/engine/InterceptingRowConsumer.java
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/test/java/io/crate/execution/engine/collect/CollectTaskTest.java
Labels: ready-to-merge

#10606 Fix null handling in SubscriptObjectFunction
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  server/src/test/java/io/crate/expression/scalar/SubscriptObjectFunctionTest.java
Labels: ready-to-merge, v/4.2

#10597 Update compatibility notes
  docs/appendices/compatibility.rst
Labels: ready-to-merge

#10592 Extend heap size bootstrap check with more information
  server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
Labels: ready-to-merge

#10608 Remove remaining Ignore annotations
  server/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge
