Repository crate/crate, pull requests merged in 2020-06, with the labels that each got.

#10029 Implement explicit and implicit casts for array and object types.
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/ObjectType.java
Labels: ready-to-merge

#10030 Fallback to last applied settings when updating settings with dependencies
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/test/java/org/elasticsearch/common/settings/ScopedSettingsTests.java
Labels: ready-to-merge, v/4.1

#10032 Remove FieldData leftovers
  server/src/main/java/org/elasticsearch/common/cache/Cache.java
  server/src/main/java/org/elasticsearch/common/cache/CacheBuilder.java
  server/src/main/java/org/elasticsearch/common/cache/CacheLoader.java
  server/src/main/java/org/elasticsearch/common/cache/RemovalListener.java
  server/src/main/java/org/elasticsearch/common/cache/RemovalNotification.java
  server/src/main/java/org/elasticsearch/index/fielddata/AbstractBinaryDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/AbstractNumericDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/AbstractSortedDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/AbstractSortedNumericDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/AbstractSortedSetDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/NumericDoubleValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/MultiOrdinals.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/Ordinals.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/OrdinalsBuilder.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/SinglePackedOrdinals.java
  server/src/main/java/org/elasticsearch/search/MultiValueMode.java
Labels: ready-to-merge

#10034 Remove unused PathTrie
  server/src/main/java/org/elasticsearch/common/path/PathTrie.java
  server/src/main/java/org/elasticsearch/rest/RestUtils.java
Labels: ready-to-merge

#10035 Remove unused ShardBitsetFilterCache
  server/src/main/java/io/crate/execution/engine/collect/DocInputFactory.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/org/elasticsearch/index/cache/bitset/ShardBitsetFilterCache.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#10036 Eagerly resolve PGType when sending data to clients
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  server/src/test/java/io/crate/protocols/postgres/MessagesTest.java
  server/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
Labels: ready-to-merge

#10038 Base data type comparison on its IDs in relevant places.
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/types/DataTypesTest.java
Labels: ready-to-merge

#10039 Fix ssl keystore/truststore change detection if there are symlinks
  docs/appendices/release-notes/unreleased.rst
  enterprise/ssl-impl/build.gradle
  enterprise/ssl-impl/src/main/java/io/crate/protocols/ssl/FilesWatcher.java
  enterprise/ssl-impl/src/main/java/io/crate/protocols/ssl/SslContextProviderService.java
  enterprise/ssl-impl/src/test/java/io/crate/protocols/ssl/SslContextProviderServiceTest.java
Labels: ready-to-merge, v/4.1

#10042 Fix flaky test_optimized_iterator_stop_processing_on_kill
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
Labels: ready-to-merge

#10044 Increase SSL trust/keystore poll interval to 5m by default
  docs/appendices/release-notes/unreleased.rst
  docs/config/node.rst
  server/src/main/java/io/crate/protocols/ssl/SslConfigSettings.java
Labels: ready-to-merge

#10049 Update gradle to 6.5
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.1

#10050 Add character_maximum_length to the columns table.
  docs/general/information-schema.rst
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#10052 Update jackson to 2.11.0
  gradle/version.properties
Labels: ready-to-merge

#10054 Release 4.1.6
  docs/appendices/release-notes/4.1.6.rst
  docs/appendices/release-notes/index.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10053 Add a tables column to sys.snapshots
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshot.java
  server/src/main/java/io/crate/metadata/sys/SysSnapshotsTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/SysSnapshotsTest.java
Labels: ready-to-merge

#10056 Reflect 4.1.6 release
  docs/appendices/release-notes/4.1.6.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10055 Bump version to 4.1.7-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#10059 Add azure snapshot integration test
  gradle/version.properties
  plugins/es-repository-azure/build.gradle
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureHttpHandler.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
Labels: ready-to-merge

#10062 Add test reports for submodules
  Jenkinsfile
Labels: ready-to-merge

#10026 Add Ability to List Child Containers to BlobContainer
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobContainer.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepository.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageService.java
  plugins/es-repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsBlobContainer.java
  plugins/es-repository-hdfs/src/main/java/org/elasticsearch/repositories/hdfs/HdfsRepository.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3BlobContainer.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
  plugins/es-repository-url/src/main/java/org/elasticsearch/common/blobstore/url/URLBlobContainer.java
  plugins/es-repository-url/src/main/java/org/elasticsearch/repositories/url/URLRepository.java
  server/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobContainer.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java
  server/src/test/java/org/elasticsearch/repositories/BlobStoreRepositoryTest.java
Labels: ready-to-merge

#10073 Move arithmetic floating point changes entry
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10074 Remove duplicate word in documentation
  docs/config/cluster.rst
Labels: ready-to-merge, v/4.1

#10077 Fix NPE in createTableStats that occurred on primitive array types.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/statistics/TransportAnalyzeActionTest.java
  server/src/test/java/io/crate/types/ArrayTypeTest.java
Labels: ready-to-merge, v/4.1

#10076 Add query optimizer incl. rules for cast optimizations
  server/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/main/java/io/crate/analyze/where/WhereClauseValidator.java
  server/src/main/java/io/crate/expression/operator/any/AnyOperators.java
  server/src/main/java/io/crate/expression/scalar/cast/CastFunctionResolver.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/lucene/NotQuery.java
  server/src/main/java/io/crate/metadata/functions/params/Param.java
  server/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/main/java/io/crate/planner/optimizer/symbol/FunctionSymbolResolver.java
  server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java
  server/src/main/java/io/crate/planner/optimizer/symbol/Rule.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveArrayLengthOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveReferenceCastToLiteralCastOnAnyOperatorsWhenLeftIsReference.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveReferenceCastToLiteralCastOnAnyOperatorsWhenRightIsReference.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveSubscriptOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SubSelectAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/relations/QuerySplitterTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/execution/dsl/projection/builder/SplitPointsTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/LikeQueryBuilderTest.java
  server/src/test/java/io/crate/metadata/functions/params/FuncParamsTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
  server/src/test/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#10080 Update test cheatsheet to new module structure
  devs/docs/tests.rst
Labels: ready-to-merge

#10083 Allow users with AL privileges to execute RESET statements
  docs/appendices/release-notes/unreleased.rst
  enterprise/users/src/main/java/io/crate/auth/user/AccessControlImpl.java
  enterprise/users/src/test/java/io/crate/auth/user/AccessControlMayExecuteTest.java
Labels: ready-to-merge, v/4.1

#9915 New TimeTZType to be returned by scalar function current_time
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  docs/interfaces/http.rst
  docs/interfaces/postgres.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/protocols/postgres/types/TimeTZType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DataTypeXContentExtension.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/TimeTZ.java
  server/src/main/java/io/crate/types/TimeTZParser.java
  server/src/main/java/io/crate/types/TimeTZType.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/protocols/postgres/types/TimeTZTypeTest.java
  server/src/test/java/io/crate/types/TimeTZParserTest.java
  server/src/test/java/io/crate/types/TimeTZTypeTest.java
  server/src/test/java/io/crate/types/TypeConversionTest.java
Labels: feature: sql: type system, ready-to-merge

#10085 Fix flaky TypeConversionTest
  server/src/test/java/io/crate/types/TypeConversionTest.java
Labels: ready-to-merge

#10090 Add missing signatures to Aggregation, Window, Table functions
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregation.java
  server/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  server/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
Labels: ready-to-merge

#10091 Ensure GroupByOptimizedIterator can be used in insert-from-query cases
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/test/java/io/crate/planner/InsertPlannerTest.java
Labels: ready-to-merge, v/4.1

#10089 Convert all operators to new signature based function registry
  server/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/main/java/io/crate/expression/operator/AllOperator.java
  server/src/main/java/io/crate/expression/operator/AndOperator.java
  server/src/main/java/io/crate/expression/operator/CIDROperator.java
  server/src/main/java/io/crate/expression/operator/CmpOperator.java
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/expression/operator/GtOperator.java
  server/src/main/java/io/crate/expression/operator/GteOperator.java
  server/src/main/java/io/crate/expression/operator/LikeOperator.java
  server/src/main/java/io/crate/expression/operator/LikeOperators.java
  server/src/main/java/io/crate/expression/operator/LtOperator.java
  server/src/main/java/io/crate/expression/operator/LteOperator.java
  server/src/main/java/io/crate/expression/operator/Operator.java
  server/src/main/java/io/crate/expression/operator/OperatorModule.java
  server/src/main/java/io/crate/expression/operator/Operators.java
  server/src/main/java/io/crate/expression/operator/OrOperator.java
  server/src/main/java/io/crate/expression/operator/RegexpMatchCaseInsensitiveOperator.java
  server/src/main/java/io/crate/expression/operator/RegexpMatchOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyOperators.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/planner/WhereClauseOptimizer.java
  server/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteCollectToGet.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/EvaluatingNormalizerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/execution/dsl/projection/FilterProjectionTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  server/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  server/src/test/java/io/crate/expression/operator/AndOperatorTest.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
  server/src/test/java/io/crate/expression/operator/RegexpMatchCaseInsensitiveOperatorTest.java
  server/src/test/java/io/crate/expression/operator/RegexpMatchOperatortest.java
  server/src/test/java/io/crate/expression/operator/any/AnyEqOperatorTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
  server/src/test/java/io/crate/planner/node/dql/JoinPhaseTest.java
  server/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
Labels: ready-to-merge

#10094 De-duplicate aggregation functions used with GROUP BY
  server/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#10092 Adapt exception handling in repository creation
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge

#10096 Remove the SslResourcePollIntervalParser
  server/src/main/java/io/crate/protocols/ssl/SslConfigSettings.java
  server/src/main/java/io/crate/protocols/ssl/SslResourcePollIntervalParser.java
  server/src/test/java/io/crate/ssl/SslResourcePollIntervalParserTest.java
Labels: ready-to-merge

#10086 Fix some typos in concepts docs
  docs/concepts/shared-nothing.rst
Labels: ready-to-merge

#10097 Limit line_numbers to 50 in the presence of errors when using COPY FROM RETURN SUMMARY
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResults.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#10048 Add optimized global aggregates using doc-values
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/DocValueAggregator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
Labels: ready-to-merge

#10106 Remove unused BlobStoreFormat
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreFormat.java
Labels: ready-to-merge

#10109 Allow ORDER BY on aggregations shadowed by alias
  server/src/main/java/io/crate/planner/consumer/OrderByWithAggregationValidator.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge

#10107 Remove obsolete IncompatibleSnapshots Logic
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/io/crate/expression/reference/sys/snapshot/SysSnapshotsTest.java
Labels: ready-to-merge

#10111 Fix flaky test_copy_from_return_summary_with_failed_rows_line_numers_limitted_to_50
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#10115 Exclude warmer.enabled setting from new tables
  docs/admin/system-information.rst
  docs/general/ddl/show-create-table.rst
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/test/java/io/crate/analyze/MetaDataToASTNodeResolverTest.java
Labels: ready-to-merge

#10112 Execute select queries on execute instead of deferring them to sync.
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge

#10114 Clarify array_unique change in release notes
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#10120 Fix use of parameter symbols in join conditions
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#10118 Improve unknown function error for operators
  enterprise/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/metadata/FunctionName.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationtest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayCatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayDifferenceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayLowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUpperFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/StringToArrayFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/MapFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/PowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/CoordinateFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/GeoHashFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/postgres/PgBackendPidFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/regex/MatchesFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/regex/RegexpReplaceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/ChrFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/QuoteIdentFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
  server/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
Labels: ready-to-merge

#10124 Delay writes on channel until execute is finished
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/protocols/postgres/DelayableWriteChannel.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge

#10123 Add SnapshotsInProgressTests
  server/src/test/java/org/elasticsearch/cluster/SnapshotsInProgressTests.java
Labels: ready-to-merge

#10125 Add information_schema.character_sets table
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/metadata/information/InformationCharacterSetsTable.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#10127 Fix ORDER BY handling on table functions
  docs/appendices/release-notes/unreleased.rst
  sql/src/main/java/io/crate/planner/operators/ProjectSet.java
  sql/src/test/java/io/crate/integrationtests/TableFunctionITest.java
Labels: ready-to-merge

#10126 Remove unused code from Repository
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge

#10129 Fix DataType generics
  server/src/main/java/io/crate/analyze/AnalyzedDropFunction.java
  server/src/main/java/io/crate/analyze/FunctionArgumentDefinition.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/exceptions/UserDefinedFunctionUnknownException.java
  server/src/main/java/io/crate/execution/dsl/phases/AbstractProjectionsPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/HashJoinPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/MergePhase.java
  server/src/main/java/io/crate/execution/dsl/phases/NestedLoopPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/PKLookupPhase.java
  server/src/main/java/io/crate/execution/dsl/projection/TopNProjection.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/join/NestedLoopOperation.java
  server/src/main/java/io/crate/expression/AbstractFunctionModule.java
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/main/java/io/crate/expression/scalar/ArrayCatFunction.java
  server/src/main/java/io/crate/expression/scalar/ArrayDifferenceFunction.java
  server/src/main/java/io/crate/expression/scalar/ArrayUniqueFunction.java
  server/src/main/java/io/crate/expression/scalar/DateFormatFunction.java
  server/src/main/java/io/crate/expression/scalar/DateTruncFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/ArrayFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/IntervalTimestampArithmeticScalar.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/MapFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/TruncFunction.java
  server/src/main/java/io/crate/expression/scalar/array/ArrayArgumentValidators.java
  server/src/main/java/io/crate/expression/scalar/geo/DistanceFunction.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/FormatTypeFunction.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/ObjDescriptionFunction.java
  server/src/main/java/io/crate/expression/symbol/InputColumn.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/expression/tablefunctions/GenerateSeries.java
  server/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  server/src/main/java/io/crate/expression/tablefunctions/ValuesFunction.java
  server/src/main/java/io/crate/expression/udf/DropUserDefinedFunctionRequest.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionMetaData.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionsMetaData.java
  server/src/main/java/io/crate/metadata/FunctionIdent.java
  server/src/main/java/io/crate/metadata/FunctionInfo.java
  server/src/main/java/io/crate/metadata/FunctionProvider.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/planner/Merge.java
  server/src/main/java/io/crate/planner/ResultDescription.java
  server/src/main/java/io/crate/planner/UnionExecutionPlan.java
  server/src/main/java/io/crate/planner/node/StreamerVisitor.java
  server/src/main/java/io/crate/planner/node/dql/Collect.java
  server/src/main/java/io/crate/planner/node/dql/CountPlan.java
  server/src/main/java/io/crate/planner/node/dql/join/Join.java
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/main/java/io/crate/statistics/ColumnStats.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerFactoryTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
  server/src/test/java/io/crate/planner/node/MergeNodeTest.java
Labels: ready-to-merge

#10130 Release 4.1.7
  docs/appendices/release-notes/4.1.7.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  es/es-server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10134 Reflect 4.1.7 release
  docs/appendices/release-notes/4.1.7.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10133 Bump version to 4.1.8-SNAPSHOT
  es/es-server/src/main/java/org/elasticsearch/Version.java
  gradle/version.properties
Labels: ready-to-merge

#10137 Add an oidvector type for use in pg_proc
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  docs/interfaces/http.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/breaker/SizeEstimatorFactory.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgProcTable.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/protocols/postgres/types/PgOidVectorType.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/OidVectorType.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#10121 Update @crate/tech-writing team name
  .github/CODEOWNERS
Labels: documentation, enhancement, ready-to-merge

#10143 Keep gradle test kit artefacts under buildSrc/build.
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
Labels: ready-to-merge

#10144 Fix simple query handling with delayed channels
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
Labels: ready-to-merge

#10147 Make sure there is an entry in pg_proc for each pg_type typreceive
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  server/src/main/java/io/crate/protocols/postgres/types/AnyType.java
  server/src/main/java/io/crate/protocols/postgres/types/PGType.java
  server/src/main/java/io/crate/types/Regproc.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/protocols/postgres/types/AnyTypeTest.java
Labels: ready-to-merge

#10149 Add oid type to pg_type table
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/protocols/postgres/types/OidType.java
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/protocols/postgres/types/PgOidVectorType.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge

#10150 Check if Snapshot files are correctly deleted
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#10013 Fix contribution attribution (mailcap)
  .mailmap
Labels: ready-to-merge

#9948 Update netty to 4.1.50
  enterprise/users/src/test/java/io/crate/auth/ClientCertAuthTest.java
  enterprise/users/src/test/java/io/crate/protocols/http/HttpAuthUpstreamHandlerTest.java
  gradle/version.properties
Labels: ready-to-merge

#10128 Track Shard-Snapshot Index Generation at Repository Root
  server/src/main/java/org/elasticsearch/action/ActionListener.java
  server/src/main/java/org/elasticsearch/action/ActionRunnable.java
  server/src/main/java/org/elasticsearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataDeleteIndexService.java
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/repositories/ShardGenerations.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/io/crate/expression/reference/sys/snapshot/SysSnapshotsTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/org/elasticsearch/cluster/SnapshotsInProgressTests.java
  server/src/test/java/org/elasticsearch/repositories/RepositoryDataTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/test/java/org/elasticsearch/snapshots/SnapshotsInProgressSerializationTests.java
Labels: ready-to-merge

#10155 Expose text and _text in pg_type table
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
Labels: ready-to-merge

#10141 Add consistent anchors to all configuration settings
  docs/appendices/release-notes/4.0.0.rst
  docs/config/cluster.rst
  docs/config/node.rst
  docs/general/dql/selects.rst
  docs/sql/statements/create-repository.rst
Labels: documentation, enhancement
