Repository crate/crate, pull requests merged in 2021-02, with the labels that each got.

#10973 Slightly improve the README
  README.rst
Labels: ready-to-merge

#10979 Fix `ReadyForQuery` message ordering on explicit flush
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/4.4

#10976 Update basics.rst
  devs/docs/basics.rst
Labels: ready-to-merge, team: tech writing

#10982 Disable internal paging for PK lookup operations
  docs/appendices/release-notes/unreleased.rst
  libs/dex/src/main/java/io/crate/data/Paging.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/4.4

#10984 Rework docs for inserting objects, add subsection for JSON strings
  docs/general/ddl/data-types.rst
  docs/sql/general/value-expressions.rst
Labels: ready-to-merge, team: tech writing

#10987 Fix flaky testSetResetGlobalSetting
  server/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
Labels: ready-to-merge

#10990 Link create/drop table mentions to sql reference for these statements
  docs/general/ddl/create-table.rst
Labels: ready-to-merge

#10991 Release 4.4.1
  docs/admin/system-information.rst
  docs/appendices/release-notes/4.4.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10994 Reflect 4.4.1 release
  docs/appendices/release-notes/4.4.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10993 Bump version to 4.4.2-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10996 Replace ImmutableList usages
  app/src/main/java/io/crate/plugin/PluginLoader.java
  benchmarks/src/test/java/io/crate/execution/engine/sort/SortingTopNCollectorBenchmark.java
  extensions/jmx-monitoring/src/main/java/io/crate/plugin/CrateMonitoringPlugin.java
  extensions/jmx-monitoring/src/test/java/io/crate/beans/QueryStatsTest.java
  extensions/lang-js/src/test/java/io/crate/operation/language/JavaScriptUDFIntegrationTest.java
  extensions/users/src/test/java/io/crate/auth/user/TransportPrivilegesActionTest.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/execution/engine/collect/BlobShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/files/LocalFsFileInput.java
  server/src/main/java/io/crate/execution/engine/distribution/merge/PassThroughPagingIterator.java
  server/src/main/java/io/crate/execution/engine/distribution/merge/RecordingSortedMergeIterator.java
  server/src/main/java/io/crate/execution/engine/join/JoinOperations.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/main/java/io/crate/execution/support/ChainableActions.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
Labels: ready-to-merge

#10992 Remove license custom metadata for bwc
  server/src/main/java/io/crate/license/LicenseCustomMetadataUpgrader.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/main/resources/META-INF/services/io.crate.metadata.CustomMetadataUpgrader
  server/src/test/java/io/crate/license/LicenseCustomMetadataUpgraderTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
Labels: ready-to-merge

#11000 Update hadoop version to existing version
  blackbox/test_hdfs.py
Labels: ready-to-merge

#11003 Ensure (string → array) parsing error lead to clear errors
  server/src/main/java/io/crate/exceptions/ConversionException.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/SubQueryAndParamBinder.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/planner/PlannerTest.java
Labels: ready-to-merge

#11004 Support full timestamp formats in pg wire
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/types/TimestampType.java
  server/src/main/java/io/crate/types/TimestampType.java
  server/src/test/java/io/crate/protocols/postgres/types/TimestampTypeTest.java
Labels: ready-to-merge, v/4.4

#11006 Update netty to 4.1.59
  gradle/version.properties
Labels: ready-to-merge

#11002 Reduce replicas configured in testHealthWithClosedIndices
  server/src/test/java/org/elasticsearch/cluster/ClusterHealthIT.java
Labels: ready-to-merge

#11005 Don't create unused tables in each test case in TransportSQLActionClassLifecycleTest
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
Labels: ready-to-merge

#10997 Improve aggregation documentation
  docs/appendices/release-notes/4.0.0.rst
  docs/appendices/release-notes/4.1.0.rst
  docs/appendices/release-notes/4.2.0.rst
  docs/general/builtins/aggregation.rst
  docs/general/builtins/window-functions.rst
  docs/general/dql/selects.rst
Labels: ready-to-merge, team: tech writing

#11009 Add License serialization back for bwc
  server/src/main/java/io/crate/license/License.java
  server/src/main/java/io/crate/license/LicenseCustomMetadataUpgrader.java
  server/src/main/java/io/crate/plugin/SQLPlugin.java
  server/src/test/java/io/crate/license/LicenseCustomMetadataUpgraderTest.java
Labels: ready-to-merge

#11011 Move method in RecoverySourceHandler to mirror upstream order
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
Labels: ready-to-merge

#11012 bp: Remove String interning from `o.e.index.Index`.
  server/src/main/java/org/elasticsearch/index/Index.java
Labels: ready-to-merge

#11008 Infer requiresRepeat from RowConsumer
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
Labels: ready-to-merge

#11018 Fix keystore path in sandbox crate.yml
  sandbox/crate/config/crate.yml
Labels: ready-to-merge

#11023 Fix type-aware source parsing on string encoded source values
  server/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge

#11024 io related backports
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java
  server/src/main/java/org/elasticsearch/transport/OutboundMessage.java
Labels: ready-to-merge

#11028 Optimize pgwire varchar/text serialization
  server/src/main/java/io/crate/protocols/postgres/types/VarCharType.java
Labels: ready-to-merge

#11029 Remove unused test_licensing.py
  blackbox/test_licensing.py
Labels: ready-to-merge

#11010 Improve path settings documentation
  app/src/main/dist/config/crate.yml
  docs/config/node.rst
Labels: ready-to-merge, team: tech writing

#11027 Support digits in unquoted pg array strings
  docs/appendices/release-notes/unreleased.rst
  libs/pgwire/src/main/antlr/PgArray.g4
  libs/pgwire/src/test/java/io/crate/protocols/postgres/parser/PgArrayParserTest.java
  server/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge, v/4.4

#11031 Remove TestLogging from MasterDisruptionIT
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
Labels: ready-to-merge

#11030 Fix flaky test_window_function_use_mixed_with_joins
  extensions/functions/src/test/java/io/crate/window/WindowFunctionsITest.java
Labels: ready-to-merge

#11037 Avoid boxing in PGArray.encodeAsUTF8Text
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
Labels: ready-to-merge

#11036 Fix NullPointerException in AsyncFlatMapBatchIterator
  docs/appendices/release-notes/unreleased.rst
  libs/dex/src/main/java/io/crate/data/AsyncFlatMapBatchIterator.java
  libs/dex/src/test/java/io/crate/data/AsyncFlatMapBatchIteratorTest.java
Labels: ready-to-merge, v/4.4

#11042 Accept all inbound messages in PostgresWireProtocol
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
Labels: ready-to-merge

#11040 Set initial loaded left batches to 0 in HashInnerJoinBatchIterator
  server/src/main/java/io/crate/execution/engine/join/HashInnerJoinBatchIterator.java
Labels: ready-to-merge

#11045 Fix flaky `testQueryBreakerIsUpdatedWhenSettingIsChanged`
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
Labels: ready-to-merge

#11046 Fix flaky `testQueryBreakerIsDecrementedWhenQueryCompletes`
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
Labels: ready-to-merge

#11044 bp: Migrate peer recovery from translog to retention lease
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/elasticsearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/shard/PrimaryReplicaSyncer.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseIT.java
  server/src/test/java/org/elasticsearch/index/shard/PrimaryReplicaSyncerTests.java
Labels: ready-to-merge

#11051 Fix pg array parsing regressions
  libs/pgwire/src/main/antlr/PgArray.g4
  libs/pgwire/src/main/java/io/crate/protocols/postgres/parser/PgArrayASTVisitor.java
  libs/pgwire/src/main/java/io/crate/protocols/postgres/parser/PgArrayParser.java
  libs/pgwire/src/test/java/io/crate/protocols/postgres/parser/PgArrayParserTest.java
Labels: ready-to-merge, v/4.4

#10700 Implement "CREATE TABLE AS"
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table-as.rst
  docs/sql/statements/index.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateTable.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateTableAs.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateTableAs.java
  server/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/CreateTableAsAnalyzer.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/analyze/SymbolToColumnDefinitionConverter.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlanner.java
  server/src/test/java/io/crate/analyze/CreateTableAsAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SymbolToColumnDefinitionConverterTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableAsIntegrationTest.java
  server/src/test/java/io/crate/testing/NodeMatchers.java
Labels: ready-to-merge

#11043 Release delayed messages on close channel
  server/src/main/java/io/crate/protocols/postgres/DelayableWriteChannel.java
  server/src/test/java/io/crate/protocols/postgres/DelayableWriteChannelTest.java
Labels: ready-to-merge

#11065 Reorganize InternalEngineTests to be in same order with upstream
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#11067 Fix fetch rewrite on Eval operators
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/EvalProjection.java
  server/src/main/java/io/crate/planner/operators/MapBackedSymbolReplacer.java
  server/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
  server/src/test/java/io/crate/planner/operators/MapBackedSymbolReplacerTest.java
Labels: ready-to-merge, v/4.4

#11070 Add reasons for skipping backports
  devs/docs/es-backports.rst
Labels: ready-to-merge
