Repository crate/crate, pull requests merged in 2021-03, with the labels that each got.

#11077 Fix repository verification error handling
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge, v/4.4

#11082 Increase default SQL request timeout in tests
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#11081 Preserve kill reason in CountTask
  server/src/main/java/io/crate/execution/jobs/CountTask.java
Labels: ready-to-merge

#11084 Fix flaky testPreferCopyCanPerformNoopRecovery
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge

#11085 bp: Avoid StackOverflowError if write circular reference exception
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java
Labels: ready-to-merge

#11086 Release 4.4.2
  docs/appendices/release-notes/4.4.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11087 Fix UncaughtExceptionError in testRestartNodeWhileIndexing
  server/src/test/java/io/crate/integrationtests/disruption/discovery/ClusterDisruptionIT.java
Labels: ready-to-merge, v/4.4

#11090 Bump version to 4.4.3-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11093 Improve object cast error messages
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/exceptions/ConversionException.java
  server/src/main/java/io/crate/expression/scalar/cast/ExplicitCastFunction.java
  server/src/main/java/io/crate/expression/scalar/cast/ImplicitCastFunction.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge

#11094 bp: Remove close method in PageCacheRecycler/Recycler
  server/src/main/java/org/elasticsearch/common/recycler/AbstractRecycler.java
  server/src/main/java/org/elasticsearch/common/recycler/ConcurrentDequeRecycler.java
  server/src/main/java/org/elasticsearch/common/recycler/DequeRecycler.java
  server/src/main/java/org/elasticsearch/common/recycler/FilterRecycler.java
  server/src/main/java/org/elasticsearch/common/recycler/NoneRecycler.java
  server/src/main/java/org/elasticsearch/common/recycler/Recycler.java
  server/src/main/java/org/elasticsearch/common/recycler/Recyclers.java
  server/src/main/java/org/elasticsearch/common/util/PageCacheRecycler.java
  server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge

#11097 Update checkstyle to 8.41
  gradle/javaModule.gradle
  server/src/main/java/io/crate/execution/dml/TransportShardAction.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
Labels: ready-to-merge

#11095 Add a release notes entry for the license changes
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#11103 Allow allocation of shards on nodes with lower HOTFIX version
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeVersionAllocationDecider.java
  server/src/test/java/org/elasticsearch/cluster/routing/TestShardRouting.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
Labels: ready-to-merge, v/4.4

#11106 Change VersionUtils.getPreviousVersion() to return previous MAJOR.MINOR
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/org/elasticsearch/test/VersionUtils.java
Labels: ready-to-merge

#11114 Update netty to 4.1.60
  gradle/version.properties
Labels: ready-to-merge

#11115 Fix hash join execution plan with empty sys.shards table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/4.4

#11112 Exclude keys with null value from source
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  server/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
Labels: ready-to-merge

#11118 Fix flaky NodeVersionAllocationDeciderTest
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
Labels: ready-to-merge

#11120 Fix trace logging of negative byte values in ChildMemoryCircuitBreaker
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
  server/src/test/java/org/elasticsearch/common/unit/ByteSizeValueTest.java
Labels: ready-to-merge, v/4.4

#11073 Clarify how the routing column works
  docs/appendices/glossary.rst
  docs/concepts/storage-consistency.rst
  docs/general/ddl/sharding.rst
  docs/sql/statements/create-table.rst
Labels: ready-to-merge, team: tech writing

#11126 Fix flaky testPrepareIndexForPeerRecovery
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java
Labels: ready-to-merge

#11123 Stop sampling on CircuitBreakingException instead of failing
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
Labels: ready-to-merge, v/4.4

#11127 Jf/fix kill npe for normal users
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/test/java/io/crate/execution/jobs/TasksServiceTest.java
Labels: ready-to-merge, v/4.4

#11130 bp: Fix testCancelRecoveryDuringPhase1
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
Labels: ready-to-merge

#11128 Remove AwaitsFix from CoordinatorTests
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
Labels: ready-to-merge

#11132 bp: Async IO Processor release before notify
  server/src/main/java/org/elasticsearch/common/util/concurrent/AsyncIOProcessor.java
  server/src/test/java/org/elasticsearch/common/util/concurrent/AsyncIOProcessorTests.java
Labels: ready-to-merge

#11133 bp: Ensure no circular reference in translog tragic exception
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/ExceptionsHelper.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/translog/TragicExceptionHolder.java
  server/src/main/java/org/elasticsearch/index/translog/Translog.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
Labels: ready-to-merge

#11134 Revert "Remove AwaitsFix from CoordinatorTests"
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
Labels: ready-to-merge

#11135 bp: Remove pre 6.0.0 support from InternalEngine
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
Labels: ready-to-merge

#11136 Prevent invalid version creation for default and empty versions
  extensions/jmx-monitoring/src/test/java/io/crate/beans/NodeInfoTest.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/test/java/org/elasticsearch/common/settings/SettingTests.java
Labels: ready-to-merge

#11138 Rework the partitioned table introduction
  docs/general/ddl/partitioned-tables.rst
Labels: ready-to-merge

#11143 tests: Dump active tasks on SQL request timeout
  server/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/test/java/io/crate/integrationtests/SQLTransportIntegrationTest.java
  server/src/test/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#11145 Update bundled JDK to 16+36
  build.gradle
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
  server/build.gradle
Labels: ready-to-merge

#11151 [Tests] Fix self-signed SSL Certification generation
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/protocols/http/HttpsTransportKeyStoreReloadIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerTest.java
Labels: ready-to-merge

#11153 Fix self-sign certificate generation at the ClientCertAuthTest
  server/src/test/java/io/crate/auth/ClientCertAuthTest.java
Labels: ready-to-merge

#11140 JMX Monitoring documentation improvements
  docs/admin/monitoring.rst
Labels: ready-to-merge

#11155 Upgrade AdminUI to 1.18.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#11101 Adjust "crate-node" auxiliary program to use the bundled Java runtime
  app/build.gradle
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/4.4

#11146 Deprecate soft_deletes.enabled setting
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/test/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#11147 Deprecate translog.retention.age and translog.retention.size settings
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/test/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#11158 Avoid NPE if a channel is closed
  server/src/main/java/io/crate/protocols/postgres/DelayableWriteChannel.java
Labels: ready-to-merge

#11159 Fix a JDT compile error in DocValuesGroupByOptimizedIterator
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
Labels: ready-to-merge

#10978 9651 scalar current date
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  docs/general/ddl/data-types.rst
  docs/interfaces/http.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/expression/scalar/CurrentDateFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/protocols/postgres/types/DateType.java
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/DateType.java
  server/src/main/resources/sql_features.tsv
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/CurrentDateFunctionTest.java
  server/src/test/java/io/crate/protocols/postgres/types/DateTypeTest.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
  server/src/test/java/io/crate/testing/DataTypeTesting.java
  server/src/test/java/io/crate/types/DateTypeTest.java
Labels: ready-to-merge

#11149 Add support to restore metadata and settings from snapshots
  docs/admin/snapshots.rst
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/restore-snapshot.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/RestoreSnapshot.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/AnalyzedRestoreSnapshot.java
  server/src/main/java/io/crate/analyze/BoundRestoreSnapshot.java
  server/src/main/java/io/crate/analyze/RestoreSnapshotAnalyzer.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/user/UserManagerService.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/analyze/SnapshotRestoreAnalyzerTest.java
  server/src/test/java/io/crate/expression/tablefunctions/PgGetKeywordsFunctionTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#11164 Clean up up backport file
  devs/docs/es-backports.rst
Labels: ready-to-merge

#11165 Add a `gen_random_text_uuid` scalar
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/GenRandomTextUUIDFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/test/java/io/crate/expression/scalar/GenRandomTextUUIDFunctionTest.java
Labels: ready-to-merge

#11166 bp: Relax translog assertion in testRestoreLocalHistoryFromTranslog
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#11169 Release 4.4.3
  docs/appendices/release-notes/4.4.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11170 Bump version to 4.4.4-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11171 Reflect 4.4.3 release
  docs/appendices/release-notes/4.4.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11174 Release 4.5.0
  docs/appendices/release-notes/4.5.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11175 Add animated GIF for the Admin UI in CrateDB 4.5
  crate-admin.gif
Labels: ready-to-merge, team: tech writing

#11163 Cross-link uses of the word "subquery" and "subselect" in the docs
  docs/appendices/release-notes/1.0.0.rst
  docs/appendices/release-notes/1.0.3.rst
  docs/appendices/release-notes/1.1.0.rst
  docs/appendices/release-notes/1.1.3.rst
  docs/appendices/release-notes/1.1.5.rst
  docs/appendices/release-notes/2.0.0.rst
  docs/appendices/release-notes/2.0.4.rst
  docs/appendices/release-notes/2.1.0.rst
  docs/appendices/release-notes/2.1.6.rst
  docs/appendices/release-notes/2.1.7.rst
  docs/appendices/release-notes/2.1.8.rst
  docs/appendices/release-notes/2.1.9.rst
  docs/appendices/release-notes/2.2.0.rst
  docs/appendices/release-notes/2.2.1.rst
  docs/appendices/release-notes/2.2.5.rst
  docs/appendices/release-notes/2.2.6.rst
  docs/appendices/release-notes/2.3.2.rst
  docs/appendices/release-notes/2.3.3.rst
  docs/appendices/release-notes/2.3.8.rst
  docs/appendices/release-notes/3.2.0.rst
  docs/appendices/release-notes/3.2.4.rst
  docs/appendices/release-notes/3.2.6.rst
  docs/appendices/release-notes/3.2.8.rst
  docs/appendices/release-notes/3.3.2.rst
  docs/appendices/release-notes/3.3.3.rst
  docs/appendices/release-notes/4.1.0.rst
  docs/appendices/release-notes/4.3.3.rst
  docs/general/builtins/subquery-expressions.rst
  docs/general/dql/selects.rst
  docs/sql/general/value-expressions.rst
  docs/sql/statements/select.rst
Labels: ready-to-merge, team: tech writing

#11176 Cross-link uses of the word "expression" in the docs
  docs/appendices/release-notes/1.0.4.rst
  docs/appendices/release-notes/1.1.5.rst
  docs/appendices/release-notes/2.0.6.rst
  docs/appendices/release-notes/2.2.6.rst
  docs/appendices/release-notes/3.2.0.rst
  docs/appendices/release-notes/3.2.8.rst
  docs/appendices/release-notes/3.3.2.rst
  docs/appendices/release-notes/3.3.4.rst
  docs/appendices/release-notes/4.0.0.rst
  docs/appendices/release-notes/4.0.7.rst
  docs/appendices/release-notes/4.1.0.rst
  docs/config/cluster.rst
  docs/config/session.rst
  docs/general/builtins/array-comparisons.rst
  docs/general/builtins/scalar-functions.rst
  docs/general/builtins/subquery-expressions.rst
  docs/general/builtins/table-functions.rst
  docs/general/builtins/window-functions.rst
  docs/general/ddl/generated-columns.rst
  docs/general/ddl/partitioned-tables.rst
  docs/general/dql/joins.rst
  docs/general/dql/selects.rst
  docs/interfaces/postgres.rst
  docs/sql/general/value-expressions.rst
  docs/sql/statements/copy-from.rst
  docs/sql/statements/copy-to.rst
  docs/sql/statements/create-table.rst
  docs/sql/statements/select.rst
Labels: ready-to-merge, team: tech writing

#11177 Remove materialize from Buckets
  libs/dex/src/main/java/io/crate/data/Buckets.java
  server/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
Labels: ready-to-merge

#11185 Set tableOid in RowDescription only if all result columns have positions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge, v/4.4

#11187 Update netty to 4.1.62
  gradle/version.properties
Labels: ready-to-merge

#11188 Remove ConcurrentMapLong
  server/src/main/java/org/elasticsearch/common/util/concurrent/ConcurrentCollections.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/ConcurrentHashMapLong.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/ConcurrentMapLong.java
  server/src/main/java/org/elasticsearch/tasks/TaskManager.java
Labels: ready-to-merge

#11190 Bump version to 4.5.1-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge
