Repository crate/crate, pull requests merged in 2021-07, with the labels that each got.

#11524 Group release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#11525 Use long-rtt in insert back-off policy
  libs/shared/src/main/java/io/crate/concurrent/limits/ConcurrencyLimit.java
  server/src/main/java/io/crate/action/LimitedExponentialBackoff.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/org/elasticsearch/action/bulk/BackoffPolicy.java
Labels: ready-to-merge

#11527 fixed description of scalar function array_avg
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#11526 Revert to Lucene 8.8.2
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/index/engine/NoOpEngine.java
Labels: ready-to-merge

#11530 Automatically add PRs to project board
  .github/workflows/project.yml
Labels: ready-to-merge

#11534 bp: Better logging for TLS message on non-secure transport channel
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTest.java
Labels: ready-to-merge

#11541 Add missing generic value streaming implementations
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
  server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java
  server/src/test/java/io/crate/types/UndefinedTypeTest.java
Labels: ready-to-merge, v/4.5

#11548 Release 4.5.4
  docs/appendices/release-notes/4.5.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11550 Sync 4.5.4 release notes
  docs/appendices/release-notes/4.5.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11549 Bump version to 4.5.5-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11547 Remove dual mode support
  docs/admin/auth/hba.rst
  docs/admin/ssl.rst
  docs/config/node.rst
  server/src/main/java/io/crate/protocols/ssl/ConnectionTest.java
  server/src/main/java/io/crate/protocols/ssl/SslSettings.java
  server/src/main/java/org/elasticsearch/transport/netty4/DualModeSSLHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/io/crate/integrationtests/SSLDualModeTransportITest.java
  server/src/test/java/io/crate/integrationtests/SSLTransportITest.java
  server/src/testFixtures/java/io/crate/test/utils/ConnectionTest.java
Labels: ready-to-merge

#11551 Update admin console to 1.19.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#11553 Release 4.6.0
  docs/appendices/release-notes/4.6.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11555 Bump version to 4.6.1-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11554 Bump version to 4.7.0-SNAPSHOT
  .mergify.yml
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11556 Remove pip `--use-feature` option for blackbox bootstrap
  blackbox/bootstrap.sh
Labels: ready-to-merge, v/4.5, v/4.6

#11564 Fix COPY FROM CSV import into partitioned tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/file/ColumnExtractingLineExpression.java
  server/src/main/java/io/crate/expression/reference/file/FileLineReferenceResolver.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge, v/4.5, v/4.6

#11560 Minor docs improvements
  docs/appendices/compatibility.rst
  docs/appendices/compliance.rst
  docs/appendices/release-notes/4.0.0.rst
  docs/concepts/joins.rst
  docs/interfaces/index.rst
  docs/sql/index.rst
Labels: ready-to-merge

#11579 Always prefer doc-values for ORDER BY operations
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/4.5, v/4.6

#11569 Add Snapshot integration tests back to test suite
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureRepositorySettingsTests.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryTests.java
  server/src/main/java/org/elasticsearch/common/blobstore/BlobPath.java
  server/src/main/java/org/elasticsearch/common/io/Streams.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/test/java/org/elasticsearch/snapshots/BlobStoreFormatIT.java
  server/src/testFixtures/java/org/elasticsearch/repositories/BlobStoreTestUtil.java
  server/src/testFixtures/java/org/elasticsearch/repositories/blobstore/BlobStoreTestUtil.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/mockstore/BlobContainerWrapper.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/mockstore/BlobStoreWrapper.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
  server/src/testFixtures/java/org/elasticsearch/test/ESIntegTestCase.java
Labels: ready-to-merge, v/4.6

#11573 Fix issue causing node with default config fail on startup
  docs/appendices/release-notes/unreleased.rst
  docs/config/node.rst
  server/src/main/java/io/crate/protocols/ssl/SslSettings.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/io/crate/integrationtests/DefaultTransportITest.java
Labels: ready-to-merge, v/4.6

#11586 Release 4.6.1
  docs/appendices/release-notes/4.6.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11587 Bump version to 4.5.6-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11590 Bump version to 4.6.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11588 Sync 4.5.5 release notes
  docs/appendices/release-notes/4.5.5.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11593 Sync 4.6.1 release notes
  docs/appendices/release-notes/4.6.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#11591 Update netty to 4.1.66
  gradle/version.properties
Labels: ready-to-merge

#11589 Update GraalVM to 21.2.0
  gradle/version.properties
Labels: ready-to-merge

#11595 Add a missing backtick to cross-reference
  docs/config/cluster.rst
Labels: ready-to-merge

#11599 Adjust test_jmx for updated sjk.jar output
  blackbox/test_jmx.py
Labels: ready-to-merge

#11598 Fix disk threshold setting monkey patching in blackbox setup
  blackbox/build.gradle
  blackbox/test_decommission.py
Labels: ready-to-merge

#11577 Implement date_bin scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/DateBinFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/test/java/io/crate/expression/scalar/DateBinFunctionTest.java
Labels: ready-to-merge

#11606 Documentation: Satisfy link checker
  docs/appendices/compliance.rst
  docs/appendices/release-notes/4.0.0.rst
  docs/appendices/release-notes/4.0.1.rst
  docs/appendices/release-notes/4.0.10.rst
  docs/appendices/release-notes/4.0.11.rst
  docs/appendices/release-notes/4.0.12.rst
  docs/appendices/release-notes/4.0.2.rst
  docs/appendices/release-notes/4.0.3.rst
  docs/appendices/release-notes/4.0.4.rst
  docs/appendices/release-notes/4.0.5.rst
  docs/appendices/release-notes/4.0.6.rst
  docs/appendices/release-notes/4.0.7.rst
  docs/appendices/release-notes/4.0.8.rst
  docs/appendices/release-notes/4.0.9.rst
  docs/concepts/joins.rst
  docs/general/ddl/alter-table.rst
  docs/general/ddl/create-table.rst
  docs/general/dql/selects.rst
  docs/interfaces/postgres.rst
  docs/sql/index.rst
  docs/sql/statements/copy-from.rst
  docs/sql/statements/copy-to.rst
  docs/sql/statements/start-transaction.rst
Labels: ready-to-merge, v/4.6

#11610 Docs: Add VIEW to ON clause for GRANT/REVOKE
  docs/sql/statements/grant.rst
  docs/sql/statements/revoke.rst
Labels: ready-to-merge, v/4.6
