Repository crate/crate, pull requests merged in 2021-01, with the labels that each got.

#10882 Fix streaming of target columns of the ColumnIndexWriterProjection
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjection.java
  server/src/test/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjectionTest.java
Labels: ready-to-merge, v/4.3

#10885 Rewrite order by symbols to source lookups if collect symbols are rewritten
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/test/java/io/crate/planner/consumer/InsertFromSubQueryPlannerTest.java
Labels: ready-to-merge, v/4.3

#10887 Ensure param types can be resolved correctly in bind
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/PreparedStmt.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/4.3

#10890 Release 4.3.3
  docs/appendices/release-notes/4.3.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10892 Reflect 4.3.3 release
  docs/appendices/release-notes/4.3.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10891 Bump version to 4.3.4-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10894 Update gradle to 6.8.0
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge

#10895 Fix typo in backport guide
  devs/docs/es-backports.rst
Labels: ready-to-merge

#10896 Fix broken result ordering for selects with QTF
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchMapper.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchOperation.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchOperation.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchRequest.java
  server/src/main/java/io/crate/execution/engine/fetch/ReaderBucket.java
  server/src/main/java/io/crate/execution/engine/fetch/ReaderBuckets.java
  server/src/main/java/io/crate/execution/engine/fetch/TransportFetchOperation.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchCollectorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchRowsTest.java
  server/src/test/java/io/crate/execution/engine/fetch/NodeFetchRequestTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#10899 Fix default traversal of match predicate
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/DefaultTraversalSymbolVisitor.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/4.3

#10898 Remove unnecessary doGetSequentialStoredFieldsReader
  server/src/main/java/org/elasticsearch/common/lucene/index/ElasticsearchLeafReader.java
  server/src/main/java/org/elasticsearch/common/lucene/index/SequentialStoredFieldsLeafReader.java
Labels: ready-to-merge

#10902 Update netty to 4.1.57
  gradle/version.properties
Labels: ready-to-merge

#10903 Change format_type to return array type names using pg notation
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/systeminformation/FormatTypeFunction.java
  server/src/test/java/io/crate/expression/scalar/systeminformation/FormatTypeFunctionTest.java
Labels: ready-to-merge

#10901 Require parameterTypes in PreparedStmt
  server/src/main/java/io/crate/action/sql/PreparedStmt.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/analyze/AnalyzedCopyTo.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateFunction.java
  server/src/main/java/io/crate/analyze/AnalyzedPromoteReplica.java
  server/src/main/java/io/crate/analyze/AnalyzedRerouteMoveShard.java
  server/src/main/java/io/crate/analyze/AnalyzedSwapTable.java
  server/src/main/java/io/crate/analyze/CreateViewStmt.java
  server/src/main/java/io/crate/analyze/RerouteAnalyzedStatement.java
  server/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge

#10907 Fix flaky CommonAnalyzerITest / add visitSymbols to create analyzer stmt
  server/src/main/java/io/crate/analyze/AnalyzedCreateAnalyzer.java
Labels: ready-to-merge

#10906 Log connection reset errors on info instead of error
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
Labels: ready-to-merge

#10908 Ensure all types returned via `pg_type` table can be looked up by oid
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge, v/4.3

#10909 Update netty to 4.1.58
  gradle/version.properties
Labels: ready-to-merge

#10910 Add support for `numeric` data type arguments on `to_char` and `negate`
  server/src/main/java/io/crate/expression/scalar/arithmetic/NegateFunctions.java
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#10866 Improvement: Overhaul arrays and objects DQL docs
  blackbox/test_docs.py
  blackbox/testdata/locations.json
  blackbox/testdata/locations_import_summary1.json
  blackbox/testdata/locations_import_summary2.json
  docs/general/builtins/table-functions.rst
  docs/general/dml.rst
  docs/general/dql/fulltext.rst
  docs/general/dql/selects.rst
  docs/general/information-schema.rst
  docs/interfaces/http.rst
  docs/sql/general/value-expressions.rst
Labels: ready-to-merge, team: tech writing

#10917 Remove to_char(number, text) scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#10919 Made stmt.visitSymbol impl mandatory, add missing implementations
  server/src/main/java/io/crate/analyze/AnalyzedAlterBlobTable.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableAddColumn.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableDropCheckConstraint.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableOpenClose.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableRename.java
  server/src/main/java/io/crate/analyze/AnalyzedAnalyze.java
  server/src/main/java/io/crate/analyze/AnalyzedBegin.java
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/analyze/AnalyzedCommit.java
  server/src/main/java/io/crate/analyze/AnalyzedDeallocate.java
  server/src/main/java/io/crate/analyze/AnalyzedDiscard.java
  server/src/main/java/io/crate/analyze/AnalyzedDropAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedDropFunction.java
  server/src/main/java/io/crate/analyze/AnalyzedDropRepository.java
  server/src/main/java/io/crate/analyze/AnalyzedDropSnapshot.java
  server/src/main/java/io/crate/analyze/AnalyzedDropTable.java
  server/src/main/java/io/crate/analyze/AnalyzedDropUser.java
  server/src/main/java/io/crate/analyze/AnalyzedDropView.java
  server/src/main/java/io/crate/analyze/AnalyzedGCDanglingArtifacts.java
  server/src/main/java/io/crate/analyze/AnalyzedPrivileges.java
  server/src/main/java/io/crate/analyze/AnalyzedRefreshTable.java
  server/src/main/java/io/crate/analyze/AnalyzedRerouteRetryFailed.java
  server/src/main/java/io/crate/analyze/AnalyzedResetStatement.java
  server/src/main/java/io/crate/analyze/AnalyzedSetSessionAuthorizationStatement.java
  server/src/main/java/io/crate/analyze/AnalyzedSetTransaction.java
  server/src/main/java/io/crate/analyze/AnalyzedStatement.java
Labels: ready-to-merge

#10920 Add release notes item about the JNA version bump
  docs/appendices/release-notes/unreleased.rst
Labels: v/4.3

#10923 Add compile support to ToChar function
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/main/java/org/elasticsearch/common/TriFunction.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#10905 Include real table_oid and attr_num in RowDescription message
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/DescribeResult.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge

#10929 Fix ECMAScript 2019 reference
  docs/general/user-defined-functions.rst
Labels: ready-to-merge

#10926 bp: Added wait_for_metadata_version parameter to cluster state api
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateResponse.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/ClusterStateApiTests.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/ClusterStateResponseTests.java
Labels: ready-to-merge

#10927 Group unreleased release notes by topic
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar.rst
Labels: ready-to-merge

#10924 Adjust versions checks on node joins to allow hotfix version differences
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: ready-to-merge, v/4.3

#10931 Deprecate zen 1 Discovery Settings
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/discovery/DiscoverySettings.java
Labels: ready-to-merge

#10934 Fix join executor test case, expecting it to fail with previous version
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: ready-to-merge

#10935 Release 4.3.4
  docs/appendices/release-notes/4.3.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10937 Bump version to 4.3.5-SNAPSHOT
  docs/admin/system-information.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10938 Reflect 4.3.4 release
  docs/appendices/release-notes/4.3.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10939 Extend filtered source parsing to object columns
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge

#10932 Move discovery.initial_state_timeout from DiscoverySettings to Node
  app/src/test/java/io/crate/node/UnsafeBootstrapAndDetachCommandIT.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/discovery/DiscoverySettings.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
  server/src/test/java/org/elasticsearch/test/transport/MockTransportService.java
Labels: ready-to-merge

#10940 Release 4.4.0
  docs/appendices/release-notes/4.4.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#10942 Add InternalTestClusterTests back to test-suite
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
  server/src/test/java/org/elasticsearch/test/test/InternalTestClusterTests.java
Labels: ready-to-merge

#10904 Remove AwaitsFix from test_retrieve_segment_information
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
Labels: ready-to-merge

#10946 Update antlr to 4.9.1
  gradle/version.properties
Labels: ready-to-merge

#10945 Make sure master node is never stopped in InternalTestCluster
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10947 Add restart callback back to InternalTestCluster to fix DiskDisruptionIT
  server/src/test/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#10951 Correction: Fix spelling of "Lucene"
  docs/general/dql/selects.rst
Labels: ready-to-merge, team: tech writing

#10953 Update JDK to 15.0.2+7
  gradle/version.properties
Labels: ready-to-merge

#10954 Remove the LoadingCache from BlobSchemaInfo
  server/src/main/java/io/crate/metadata/blob/BlobSchemaInfo.java
Labels: ready-to-merge

#10952 Fix `GraalVM Security Guide` missing link
  docs/general/user-defined-functions.rst
Labels: ready-to-merge

#10955 Remove dead code from TransportAction
  server/src/main/java/org/elasticsearch/action/support/TransportAction.java
Labels: ready-to-merge

#10956 Enable slow tests for jenkins java tests
  Jenkinsfile
Labels: ready-to-merge

#10962 Fix flaky create_azure_snapshot_and_restore_it
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
Labels: ready-to-merge

#10941 Make source parsing eagerly type aware
  server/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceLookup.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge

#10968 Correction: Fix explanation of unusual nested structures syntax and array limitations
  docs/general/dql/selects.rst
Labels: ready-to-merge, team: tech writing

#10969 Fix parameter type extraction for joins
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/4.4

#10972 Fix nested joins with primary key lookups which require scroll
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/4.4

#10959 Improvement: Copyedit LIKE/ILIKE performance note
  docs/general/dql/selects.rst
Labels: ready-to-merge, team: tech writing
