Repository crate/crate, pull requests merged in 2022-10, with the labels that each got.

#13083 Replace deprecated NO_MORE_ORDS checks with docValueCount
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BitStringColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IpColumnReference.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java
  server/src/main/java/org/elasticsearch/search/MultiValueMode.java
Labels: ready-to-merge

#13084 Avoid string conversion in bool doc-value lookup
  server/src/main/java/io/crate/expression/reference/doc/lucene/BooleanColumnReference.java
  server/src/main/java/org/elasticsearch/index/fielddata/FieldData.java
Labels: ready-to-merge

#13095 Remove wrong Nullable annotations in BatchIteratorBackpressureExecutor
  server/src/main/java/io/crate/execution/engine/indexing/BatchIteratorBackpressureExecutor.java
Labels: ready-to-merge

#13092 Fix warnings in ColumnIdent.get
  server/src/main/java/io/crate/metadata/ColumnIdent.java
Labels: ready-to-merge

#13088 New tests for tryParseLong
  libs/shared/src/test/java/io/crate/common/StringUtilsTest.java
Labels: ready-to-merge

#13093 Revert "bp: Add Caching for RepositoryData in BlobStoreRepository"
  devs/docs/es-backports.rst
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepository.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
Labels: ready-to-merge

#13086 Don't create intermediate list to add indexable fields
  server/src/main/java/org/elasticsearch/index/mapper/ArrayMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/BitStringFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/SeqNoFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/VersionFieldMapper.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
Labels: ready-to-merge

#13081 Explain how users are backed up and restored
  docs/admin/user-management.rst
Labels: v/5.0

#13099 Document silent skipping of rows on failed type casting during INSERT
  docs/general/dml.rst
  docs/sql/statements/insert.rst
Labels: v/5.0

#13109 Release 5.0.2
  docs/appendices/release-notes/5.0.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13114 Bump version to 5.0.3-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13118 Add SymbolMatchers assertj migration to git-blame-ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#13119 Add left out sql features changes
  server/src/main/resources/sql_features.tsv
Labels: ready-to-merge

#13116 Add validation of the COPY FROM `compression` parameter
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
Labels: ready-to-merge

#13122 Bump version to 5.1.1-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13094 Avoid multiple evaluation of same expression in GroupRowsByShard
  libs/shared/src/main/java/io/crate/data/Row.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
Labels: ready-to-merge

#13130 Update netty to 4.1.84
  gradle/version.properties
Labels: ready-to-merge

#13131 Include allowed values in error message of settings using stringValidator
  server/src/main/java/io/crate/metadata/settings/Validators.java
  server/src/test/java/io/crate/metadata/settings/ValidatorsTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
Labels: ready-to-merge

#13127 Add `max_by` and `min_by` aggregation functions
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/AggregationImplModule.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CompareByType.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CmpByAggregationTest.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#13138 Add recent assertj migrations to git-blame-ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#13137 Add recent assertj migrations to git-blame-ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#13106 Ensure IS NULL does not match empty object arrays or empty objects
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/expression/predicate/IsNullQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.1

#13141 Do not check pause condition again after resume (fix infinite loop)
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/indexing/BatchIteratorBackpressureExecutor.java
Labels: ready-to-merge, v/5.1

#13145 tests: Fix flaky SysSegmentsTableInfoTest
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
Labels: ready-to-merge, v/5.1

#13144 Fix: Allow omitting pk column generated from a col with default
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge, v/5.1

#13153 Fix: Allow omitting pk column generated from a col with default (backport #13144)
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge

#13156 Release 5.0.3
  docs/appendices/release-notes/5.0.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13157 Reflect release 5.0.3
  docs/appendices/release-notes/5.0.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13159 Reflect release 5.0.3
  docs/appendices/release-notes/5.0.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13160 Bump version to 5.0.4-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13161 Update bundled JDK to 19
  gradle/version.properties
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
Labels: ready-to-merge

#13163 bp: Handle IOException while checking translog corruption
  server/src/testFixtures/java/org/elasticsearch/index/translog/TestTranslog.java
Labels: ready-to-merge

#13164 tests: Fix flaky testTransientErrorsDuringRecoveryAreRetried
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge, v/5.1

#13169 Document the effect of BEGIN END and COMMIT on CURSORs
  docs/sql/statements/begin.rst
  docs/sql/statements/commit.rst
  docs/sql/statements/end.rst
Labels: ready-to-merge, docs, v/5.1

#13170 tests: Fix flaky `PartitionedTableIntegrationTest`
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge, v/5.1

#13171 tests: Fix flaky SysShardsTest.testInsertFromClosedTableNotAllowed
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
Labels: ready-to-merge, v/5.1

#13173 Fix IllegalIndexShardStateException handling in count operation
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/count/InternalCountOperation.java
  server/src/test/java/io/crate/execution/engine/collect/count/InternalCountOperationTest.java
Labels: ready-to-merge, v/5.1

#13178 Avoid boxing for ReaderContext#visitDocument
  server/src/main/java/io/crate/execution/engine/fetch/ReaderContext.java
Labels: ready-to-merge

#13180 bp: Add voting-only master node
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/ElectionStrategy.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PreVoteCollector.java
  server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java
  server/src/main/java/org/elasticsearch/plugins/DiscoveryPlugin.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinationStateTestCluster.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PreVoteCollectorTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTests.java
  server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodesTests.java
Labels: ready-to-merge

#13182 Remove fixed seed from LuceneQueryBuilderIntegrationTest
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
Labels: ready-to-merge

#13186 bp: Remove nodes with read-only filesystems
  devs/docs/es-backports.rst
  libs/shared/src/main/java/org/elasticsearch/common/io/PathUtils.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/elasticsearch/cluster/coordination/NodeHealthCheckFailureException.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PreVoteCollector.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java
  server/src/main/java/org/elasticsearch/monitor/NodeHealthService.java
  server/src/main/java/org/elasticsearch/monitor/StatusInfo.java
  server/src/main/java/org/elasticsearch/monitor/fs/FsHealthService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/LeaderCheckerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PreVoteCollectorTests.java
  server/src/test/java/org/elasticsearch/monitor/fs/FsHealthServiceTests.java
Labels: ready-to-merge

#13181 Fix EqOperator applied to empty arrays for IP, GEO_SHAPE, OBJECT and BIT types
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  server/src/test/java/io/crate/testing/DataTypeTestingTest.java
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge, v/5.1

#13191 Update GraalVM to 22.3.0
  gradle/version.properties
Labels: ready-to-merge

#13190 Fix source decoding of bit string values, add additional base64 decoding step
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/5.1

#13193 bp: Fix node health-check-related test failures
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/elasticsearch/monitor/fs/FsHealthService.java
  server/src/test/java/org/elasticsearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/elasticsearch/monitor/fs/FsHealthServiceTests.java
Labels: ready-to-merge

#13194 Add some more unit tests for cursors
  server/src/test/java/io/crate/action/sql/CursorTest.java
Labels: ready-to-merge

#13195 Remove IndexCache
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/cache/IndexCache.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#13200 Replace `indices.breaker.fielddata.limit` ref in 4.3 release notes
  docs/appendices/release-notes/4.3.0.rst
Labels: ready-to-merge

#13199 Fix handling of BitString in undefined type serialization
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
  server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java
  server/src/test/java/io/crate/types/UndefinedTypeTest.java
Labels: ready-to-merge, v/5.1
