Repository crate/crate, pull requests merged in 2022-09, with the labels that each got.

#12953 Fix for #12754: BWC compatibility with nodes < 5.1
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
Labels: ready-to-merge, v/4.8, v/5.0

#12950 Release 4.8.3
  docs/appendices/release-notes/4.8.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12963 Add support for SET TIME ZONE as no-op
  docs/appendices/release-notes/unreleased.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/SetStatement.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/test/java/io/crate/planner/PlannerTest.java
Labels: ready-to-merge

#12957 bp: Move Snapshot Status Related Method to Appropriate Places
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
  server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotInfo.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#12962 Remaining BWC for #12754
  server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataMappingService.java
Labels: ready-to-merge, v/4.8, v/5.0

#12970 Update release date for 4.8.3
  docs/appendices/release-notes/4.8.3.rst
Labels: ready-to-merge

#12971 Release 5.0.1
  docs/appendices/release-notes/5.0.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12972 Increase assertBusy maxWaitTime for test_subscription_state_order
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
Labels: ready-to-merge

#12974 Bump version to 4.8.4-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12911 Always close BatchIterator in BatchIterators.collect
  libs/dex/src/main/java/io/crate/data/BatchIterators.java
  libs/dex/src/main/java/io/crate/data/CollectingRowConsumer.java
  libs/dex/src/testFixtures/java/io/crate/testing/BatchIteratorTester.java
  libs/dex/src/testFixtures/java/io/crate/testing/TestingRowConsumer.java
  server/src/main/java/io/crate/execution/engine/distribution/SingleBucketBuilder.java
  server/src/main/java/io/crate/execution/jobs/DistResultRXTask.java
Labels: ready-to-merge

#12958 bp: Remove Redundant Cluster State during Snapshot INIT + Master Failover
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#12959 bp: Make Snapshot Deletes Less Racy
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshotAction.java
  server/src/main/java/org/elasticsearch/cluster/SnapshotDeletionsInProgress.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#12978 Fix typo in checkstyle cmd
  devs/docs/basics.rst
Labels: ready-to-merge, v/5.0

#12983 Fix pgJDBC documentation links
  docs/admin/ssl.rst
  docs/appendices/release-notes/4.1.0.rst
  docs/interfaces/postgres.rst
Labels: ready-to-merge, v/4.8, v/5.0

#12982 Turn off translog retention only when shard started
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge, v/5.0

#12960 bp: Fix Race in Snapshot Abort
  devs/docs/es-backports.rst
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/RestoreOnlyRepository.java
Labels: ready-to-merge

#12961 bp: Voting config exclusions should work with absent nodes
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequest.java
  server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequestTests.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsActionTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NodeJoinTests.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge

#12987 bp: Add RepositoriesService to createComponents() args
  devs/docs/es-backports.rst
  plugins/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/CommonAnalysisPlugin.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/Plugin.java
  server/src/main/java/org/elasticsearch/plugins/RepositoryPlugin.java
  server/src/main/java/org/elasticsearch/repositories/RepositoriesModule.java
  server/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
Labels: ready-to-merge

#12993 bp: Ensure not to open directory reader on transport thread
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java
Labels: ready-to-merge

#12988 bp: Exclude Snapshot Shard Status Update Requests from Circuit Breaker
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java
Labels: ready-to-merge

#12994 Make comma separator of successive BEGIN transaction_modes optional
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/begin.rst
  docs/sql/statements/start-transaction.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
Labels: ready-to-merge

#12998 bp: Fix NPE in Partial Snapshot Without Global State
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#13002 Fix `ExplainPlan` to utilize cast optimization on sub plans.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  server/src/test/java/io/crate/planner/ExplainPlannerTest.java
Labels: ready-to-merge, v/5.0

#13006 tests: Add assertj migrations to git blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#13007 Use assertj for assertions in `buildSrc` (partial backport #12846)
  buildSrc/build.gradle
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkTest.java
Labels: ready-to-merge

#13001 Fix error handling in FetchTask.start
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
Labels: ready-to-merge, v/5.0

#13010 Update gradle wrapper scripts and jar
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: ready-to-merge, v/5.0

#13012 Reflect release 4.8.3
  docs/appendices/release-notes/4.8.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13009 tests: Add assertj migrations to git blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#13018 remove mentions of enterprise and mqtt from the schema
  devs/docs/architecture.svg
Labels: ready-to-merge, v/5.0

#13023 bp: Fix TransportAddVotingConfigExclusionsActionTests Leaking CS Observers
  server/src/test/java/org/elasticsearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsActionTests.java
Labels: ready-to-merge, v/5.0

#12981 Optimize some of the common helpers in AstBuilder
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
Labels: ready-to-merge

#12996 implement Drop Constraint in dedicated request and action
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/DropConstraintRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropConstraintAction.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropCheckConstraintPlan.java
  server/src/test/java/io/crate/analyze/AlterTableDropCheckConstraintAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13021 Fix race that could lead to pg wire messages being out-of-order
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/DelayableWriteChannel.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  server/src/main/java/io/crate/protocols/postgres/RowCountReceiver.java
  server/src/test/java/io/crate/protocols/postgres/DelayableWriteChannelTest.java
  server/src/test/java/io/crate/protocols/postgres/MessagesTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge

#13029 Fix fd leak in getCgroupHierarchy
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java
Labels: ready-to-merge, v/5.0

#13039 Update to Admin UI 1.23.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#13040 Release 4.8.4
  docs/appendices/release-notes/4.8.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13041 bp: Fix Broken Numeric Shard Generations in RepositoryData
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/repositories/ShardGenerations.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/elasticsearch/repositories/RepositoryDataTests.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/testFixtures/java/org/elasticsearch/repositories/blobstore/BlobStoreTestUtil.java
Labels: ready-to-merge

#13042 bump version to 4.8.5-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13047 ES backport: fix test
  server/src/test/java/org/elasticsearch/indices/recovery/RecoveryRequestTrackerTests.java
Labels: ready-to-merge

#13037 Fix issue with LEFT join and subquery in WHERE
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/SymbolEvaluator.java
  server/src/main/java/io/crate/planner/optimizer/rule/NullSymbolEvaluator.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
Labels: ready-to-merge, v/5.0

#13050 Add parser support for DECLARE, FETCH and CLOSE
  docs/general/builtins/table-functions.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Close.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Declare.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Fetch.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/expression/tablefunctions/PgGetKeywordsFunctionTest.java
  server/src/test/java/io/crate/integrationtests/TableFunctionITest.java
Labels: ready-to-merge

#13054 tests: Fix an issue causing ClassCastException when planning
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, v/5.0

#13058 Remove stream usage from JoinPlanBuilder for correlated subqueries
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
Labels: ready-to-merge

#13062 Add teardown assertion to ensure sessions get closed
  server/src/main/java/io/crate/action/sql/Cursors.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BaseUsersIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DefaultSchemaIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/JobLogIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLHttpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/ScalarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysNodeResiliencyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysPrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UserSessionIntegrationTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13071 Enable watermarks on single nodes without escape hatch
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
Labels: ready-to-merge

#13068 Upgrade jackson
  gradle/version.properties
Labels: ready-to-merge, v/5.0

#13072 Documentation: Fix table of available data types for the HTTP interface
  docs/interfaces/http.rst
Labels: ready-to-merge, v/5.0

#13059 Fix: also get from translog when query matching on `_id`
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/WhereClauseOptimizer.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/5.0

#13077 Group release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#13046 Add a setting allowing to throttle ANALYZE
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  docs/sql/statements/analyze.rst
  server/src/main/java/io/crate/breaker/RowCellsAccountingWithEstimators.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/main/java/io/crate/statistics/TableStats.java
  server/src/main/java/io/crate/statistics/TableStatsService.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/planner/node/ddl/ResetSettingsPlanTest.java
  server/src/test/java/io/crate/statistics/ReservoirSamplerTest.java
Labels: ready-to-merge

#13076 Upgrade to Admin UI 1.23.1
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#13078 remove portals and cursors from Session.toString
  server/src/main/java/io/crate/action/sql/Session.java
Labels: ready-to-merge

#13079 Remove invalid deprecation note of `indices.breaker.query.limit`
  docs/config/cluster.rst
Labels: ready-to-merge

#13063 reuse running ANALYZE result
  server/src/main/java/io/crate/statistics/FetchSampleRequest.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
Labels: ready-to-merge
