Repository crate/crate, pull requests merged in 2022-04, with the labels that each got.

#12288 Proofreading of logical replication docs
  docs/admin/logical-replication.rst
  docs/admin/system-information.rst
  docs/sql/statements/alter-publication.rst
  docs/sql/statements/alter-subscription.rst
  docs/sql/statements/create-publication.rst
  docs/sql/statements/create-subscription.rst
Labels: ready-to-merge

#12291 Retrieve remote client once per poll in metadata tracker
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#12290 set default port to 5432 if creating a subscription with pg_tunnel mode
  docs/sql/statements/create-subscription.rst
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/test/java/io/crate/replication/logical/metadata/ConnectionInfoTest.java
Labels: ready-to-merge

#12280 Migrate some TransportAction ActionListener usages to prefer CompletableFuture
  server/src/main/java/io/crate/blob/v2/BlobAdminClient.java
  server/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
  server/src/main/java/io/crate/execution/ddl/RepositoryService.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/planner/CreateViewPlan.java
  server/src/main/java/io/crate/planner/DropViewPlan.java
  server/src/main/java/io/crate/planner/GCDangingArtifactsPlan.java
  server/src/main/java/io/crate/planner/SwapTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateBlobTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateFunctionPlan.java
  server/src/main/java/io/crate/planner/node/ddl/OptimizeTablePlan.java
  server/src/main/java/io/crate/user/UserManagerService.java
  server/src/main/java/org/elasticsearch/action/support/TransportAction.java
  server/src/test/java/org/elasticsearch/action/support/ActionTestUtils.java
Labels: ready-to-merge

#12229 COPY FROM should fail gracefully in case of illegal data in CSV
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dsl/projection/SourceIndexWriterReturnSummaryProjection.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/files/LineProcessor.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResultContext.java
  server/src/main/java/io/crate/expression/reference/file/FileLineReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/file/LineContext.java
  server/src/main/java/io/crate/expression/reference/file/SourceParsingFailureExpression.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge, v/4.7

#12208 implement cancellation portion of Postgres wire protocol
  docs/appendices/release-notes/unreleased.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/execution/jobs/kill/KillJobsRequest.java
  server/src/main/java/io/crate/execution/jobs/kill/TransportKillNodeAction.java
  server/src/main/java/io/crate/protocols/postgres/ClientMessages.java
  server/src/main/java/io/crate/protocols/postgres/KeyData.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/protocols/postgres/PgSessions.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresNettyPublishPortTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerTest.java
Labels: ready-to-merge

#12306 RemoteClusters must reconnect if previous connection fails
  server/src/main/java/org/elasticsearch/transport/RemoteClusters.java
  server/src/test/java/org/elasticsearch/transport/RemoteClustersTest.java
Labels: ready-to-merge

#12302 Use hosts as seed nodes at `sniff` remote connection mode
  docs/sql/statements/create-subscription.rst
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/org/elasticsearch/transport/RemoteCluster.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
  server/src/main/java/org/elasticsearch/transport/SniffConnectionStrategy.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/replication/logical/metadata/ConnectionInfoTest.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterConnectionTests.java
Labels: ready-to-merge

#12308 Print server logs on doc-test ConnectionError
  blackbox/test_docs.py
Labels: ready-to-merge

#12247 Update license notes for dependency packages
  3RD-PARTY-NOTICES.md
Labels: ready-to-merge

#12307 Merge PgDecoder with SslReqHandler and extract from PostgresWireProtocol
  server/src/main/java/io/crate/protocols/postgres/ClientMessages.java
  server/src/main/java/io/crate/protocols/postgres/PgDecoder.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/SslReqHandler.java
  server/src/main/java/io/crate/protocols/ssl/SslContextProvider.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerTest.java
Labels: ready-to-merge

#12315 Send rst/don't linger on channel close in tests
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpChannel.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#12310 Remove unused accessControl from session
  server/src/main/java/io/crate/action/sql/SQLOperations.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/protocols/postgres/BatchPortalTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge

#12303 fix curly braces within `ILIKE` operands to be treated as a normal character
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/operator/LikeOperators.java
  server/src/test/java/io/crate/expression/operator/LikeOperatorTest.java
Labels: ready-to-merge, v/4.7

#12316 Ignore coverage of benchmarks
  codecov.yml
Labels: ready-to-merge

#12292 Add implementation/support for ALTER PUBLICATION
  libs/sql-parser/src/main/java/io/crate/sql/tree/AlterPublication.java
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/planner/DependencyCarrier.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/replication/logical/action/TransportAlterPublicationAction.java
  server/src/main/java/io/crate/replication/logical/plan/AlterPublicationPlan.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/replication/logical/action/TransportAlterPublicationActionTest.java
Labels: ready-to-merge

#12318 clean up unreleased doc
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#12326 Revert "Update bundled JDK to 18+36"
  .github/workflows/codeql-analysis.yml
  build.gradle
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12325 Raise user friendly error on invalid subscription connection mode
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/org/elasticsearch/transport/RemoteCluster.java
  server/src/test/java/io/crate/replication/logical/metadata/ConnectionInfoTest.java
Labels: ready-to-merge

#12322 don't forget to handle routing columns when merging index mappings
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
Labels: ready-to-merge, v/4.7

#12328 Update to Admin UI 1.21.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12336 Don't wrap exceptions into RuntimeException/handle ConnectException
  libs/shared/src/main/java/io/crate/exceptions/Exceptions.java
  server/src/main/java/io/crate/execution/support/NodeActionRequestHandler.java
  server/src/main/java/io/crate/execution/support/Transports.java
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/TransportCreateSubscriptionAction.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#12335 Fix failed connectionFuture handling in PgClient.ensureConnected
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
Labels: ready-to-merge

#12337 use default trust store if not configured
  server/src/main/java/io/crate/protocols/ssl/SslContextProvider.java
  server/src/test/java/io/crate/protocols/ssl/SslContextProviderTest.java
Labels: ready-to-merge

#12338 Ensure MetadataTracker schedule loop doesn't stop on some conditions
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#12320 Minor proofreading fixes for documentation
  docs/general/ddl/analyzers.rst
  docs/general/ddl/data-types.rst
  docs/interfaces/postgres.rst
Labels: ready-to-merge, docs

#12329 implement `union [distinct]`
  docs/appendices/release-notes/unreleased.rst
  docs/general/dql/union.rst
  docs/sql/statements/select.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/UnionSelect.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/UnionIntegrationTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
Labels: ready-to-merge

#12360 add checkstyle command to the dev docs
  devs/docs/basics.rst
Labels: ready-to-merge

#12366 Ensure close of ShardReplicationChangesTracker takes effect
  server/src/main/java/io/crate/replication/logical/ShardReplicationChangesTracker.java
Labels: ready-to-merge

#12367 Update netty to 4.1.76
  gradle/version.properties
Labels: ready-to-merge

#12362 Add max_line_length for rst to editorconfig
  .editorconfig
Labels: ready-to-merge

#12365 added test case: drop_publication_stops_the_replication_on_subscriber
  docs/sql/statements/drop-publication.rst
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/integrationtests/disruption/replication/logical/SubscriptionDisruptionIT.java
Labels: ready-to-merge

#12375 Ensure the MetadataTracker reacts to master changes
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#12374 Retrieve index/template metadata with PublicationsStateAction
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/metadata/RelationMetadata.java
  server/src/test/java/io/crate/integrationtests/disruption/replication/logical/SubscriptionDisruptionIT.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
Labels: ready-to-merge

#12377 tests: Try to include jobs-log information in stuck tasks assertion error
  server/src/testFixtures/java/io/crate/integrationtests/SQLIntegrationTestCase.java
Labels: ready-to-merge

#12378 Require only metadata for concreteIndices retrieval
  server/src/main/java/io/crate/execution/ddl/SwapRelationsOperation.java
  server/src/main/java/io/crate/execution/ddl/TransportSwapRelationsAction.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableTarget.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropTableAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameTableAction.java
  server/src/main/java/io/crate/metadata/blob/InternalBlobTableInfoFactory.java
  server/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/DropTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoBuilder.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/TransportDropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/metadata/RelationMetadata.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/elasticsearch/indices/flush/SyncedFlushService.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
Labels: ready-to-merge

#12380 Fix deadlock when closing EventLoopGroup in PgClient
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
Labels: ready-to-merge

#12382 Handle IllegalIndexShardStateException in getFutureOrderedCollector
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/OrderedDocCollector.java
Labels: ready-to-merge

#12385 Ensure closing SniffRemoteClient closes pending connection
  server/src/main/java/org/elasticsearch/transport/SniffRemoteClient.java
Labels: ready-to-merge

#12342 Handle case when cluster can subscribe to existing tables
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
Labels: ready-to-merge

#12386 Minor LogicalReplicationService cleanup
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
Labels: ready-to-merge

#12346 Disable renaming of tables included in a publication
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoBuilder.java
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/test/java/io/crate/analyze/AlterTableRenameAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/table/OperationTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
  server/src/test/java/io/crate/planner/consumer/InsertFromSubQueryPlannerTest.java
  server/src/testFixtures/java/io/crate/test/integration/CrateDummyClusterServiceUnitTest.java
Labels: ready-to-merge

#12379 Update bundled JDK to 17.0.3+7
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.7

#12388 Detect updated engineFactories on index setting changes
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/planner/DependencyCarrier.java
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/action/TransportDropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/plan/DropSubscriptionPlan.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationAllPermitsAcquisitionTests.java
  server/src/test/java/org/elasticsearch/index/engine/NoOpEngineRecoveryTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardRetentionLeaseTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/indices/IndexingMemoryControllerTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#12393 Stop the ShardReplicationTracker if index switched to normal index
  server/src/main/java/io/crate/replication/logical/ShardReplicationService.java
  server/src/main/java/org/elasticsearch/index/CompositeIndexEventListener.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexEventListener.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#12389 Wait for restore before next poll in MetadataTracker
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
Labels: ready-to-merge

#12397 Move RetentionLeaserHelper loggers to debug level
  server/src/main/java/io/crate/replication/logical/seqno/RetentionLeaseHelper.java
Labels: ready-to-merge

#12396 Try to fix thread leak in PgClientTest
  server/src/main/java/io/crate/netty/NettyBootstrap.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
Labels: ready-to-merge

#12399 Re-use acquired remote client in LogicalReplicationRepository
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
Labels: ready-to-merge

#12395 Turn tables dropped or excluded from the publication into normal tables
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#12392 Make AckedClusterStateUpdateTask CompletionListenable
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/org/elasticsearch/cluster/AckedClusterStateUpdateTask.java
  server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java
Labels: ready-to-merge

#12404 remove outdated test and adjust docs for DROP/ALTER PUBLICATION
  docs/sql/statements/alter-publication.rst
  docs/sql/statements/drop-publication.rst
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#12408 Fix flaky test_subscription_metadata_tracker_retries_on_publisher_disconnect
  server/src/test/java/io/crate/integrationtests/disruption/replication/logical/SubscriptionDisruptionIT.java
Labels: ready-to-merge

#12406 remove SYNCHRONIZED state from subscribtion table docs
  docs/admin/system-information.rst
Labels: ready-to-merge

#12369 Subscription to multiple publications should not stop after dropping one of the publications
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
Labels: ready-to-merge

#12413 Fix broken AD application guide link
  docs/admin/discovery.rst
  docs/config/cluster.rst
Labels: ready-to-merge

#12410 Revert "implement drop subscription in 3 requests"
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/CloseTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/OpenCloseTableOrPartitionRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportOpenCloseTableOrPartitionAction.java
  server/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/CloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableOpenClosePlan.java
Labels: ready-to-merge

#12415 Reflect 4.7.2 release
  docs/appendices/release-notes/4.7.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12416 Bump version to 4.7.3-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12418 Mark UNION DISTINCT as supported at sql_features
  server/src/main/resources/sql_features.tsv
Labels: ready-to-merge

#12420 Release 4.8.0
  docs/appendices/release-notes/4.8.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12422 add decimal type as alias to numeric type
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/types/DataTypesTest.java
Labels: ready-to-merge
