Repository crate/crate, pull requests merged in 2022-06, with the labels that each got.

#12553 Implement has_schema_privilege scalar function
  benchmarks/src/main/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  extensions/lang-js/src/main/java/io/crate/operation/language/JavaScriptUserDefinedFunction.java
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/expression/BaseImplementationSymbolVisitor.java
  server/src/main/java/io/crate/expression/operator/LikeOperator.java
  server/src/main/java/io/crate/expression/scalar/ArrayDifferenceFunction.java
  server/src/main/java/io/crate/expression/scalar/DateBinFunction.java
  server/src/main/java/io/crate/expression/scalar/DateTruncFunction.java
  server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/cast/ImplicitCastFunction.java
  server/src/main/java/io/crate/expression/scalar/formatting/ToCharFunction.java
  server/src/main/java/io/crate/expression/scalar/regex/RegexpReplaceFunction.java
  server/src/main/java/io/crate/expression/scalar/string/TranslateFunction.java
  server/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  server/src/main/java/io/crate/expression/tablefunctions/MatchesFunction.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/NodeContext.java
  server/src/main/java/io/crate/metadata/Scalar.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/user/User.java
  server/src/main/java/io/crate/user/UserLookup.java
  server/src/main/java/io/crate/user/UserLookupService.java
  server/src/main/java/io/crate/user/UserManagerService.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorTest.java
  server/src/test/java/io/crate/expression/scalar/HasSchemaPrivilegeFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/AbstractTableFunctionsTest.java
  server/src/test/java/io/crate/planner/node/ddl/ResetSettingsPlanTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/user/UserActionsTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
  server/src/testFixtures/java/io/crate/testing/SqlExpressions.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
  server/src/testFixtures/java/io/crate/user/StubUserManager.java
Labels: ready-to-merge

#12577 Avoid array copy operation to generate streamers
  server/src/main/java/io/crate/execution/dml/ShardResponse.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
Labels: ready-to-merge

#12588 Fix/allow handling of null literals in UNION and GROUP BY
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  server/src/main/java/io/crate/expression/symbol/GroupAndAggregateSemantics.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/UnionIntegrationTest.java
Labels: ready-to-merge, v/4.8

#12583 Update Admin UI to 1.22.0, including the new logo and colors
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12590 Fix ssl documentation for self-signed certifications
  docs/admin/ssl.rst
Labels: ready-to-merge, v/4.8

#12600 tests: Fix sql-parser tests regarding assertThrows
  libs/sql-parser/src/test/java/io/crate/sql/IntervalLiteralTest.java
  libs/sql-parser/src/test/java/io/crate/sql/LiteralsTest.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  libs/sql-parser/src/test/java/io/crate/sql/testing/Asserts.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/BitStringTest.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/UnboundedFollowingFrameBoundTest.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/UnboundedPrecedingFrameBoundTest.java
  libs/sql-parser/src/test/java/io/crate/sql/tree/WindowTest.java
Labels: ready-to-merge, v/4.8

#12602 Try to fix flaky IndexRecoveryIT.testRerouteRecovery
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#12601 Update netty to 4.1.77
  gradle/version.properties
Labels: ready-to-merge

#12606 Remove stats from IndicesQueryCache
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
Labels: ready-to-merge

#12609 Include statement in timeout exceptions in tests
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#12608 Wait for pending logical replication operations on test teardown
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
Labels: ready-to-merge

#12616 Remove unused properties from IndexService
  server/src/main/java/org/elasticsearch/index/IndexService.java
Labels: ready-to-merge

#12618 parser: Fix grammar warning
  libs/sql-parser/src/main/antlr/SqlBase.g4
Labels: ready-to-merge

#12622 Add `SUBSTRING` to non-reserved SQL keywords
  docs/appendices/release-notes/unreleased.rst
  docs/sql/general/lexical-structure.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/expression/scalar/SubstrFunction.java
  server/src/test/java/io/crate/expression/scalar/SubstrFunctionTest.java
Labels: ready-to-merge

#12619 Add `pg_catalog.pg_tables` and `pg_catalog.pg_views` tables
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgTablesTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgViewsTable.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#12617 Remove assertions from ReadOnlyEngine
  server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
Labels: ready-to-merge

#12628 allow group by null ordinal, casted to a specific type
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/analyze/relations/OrderByAnalyzerTest.java
Labels: ready-to-merge, v/4.8

#12632 Bp: Update gha workflow to add PRs to project beta board
  .github/workflows/project.yml
Labels: ready-to-merge

#12634 Fix flaky `testFailsToStartIfDowngraded` test
  server/src/test/java/org/elasticsearch/env/NodeMetadataTests.java
Labels: ready-to-merge, v/4.8

#12639 bp: Remove not-null contrsaints from the pg_constraint table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge

#12641 Remove enterprise licence header from checkstyle
  devs/docs/basics.rst
  gradle/checkstyle/checkstyle.xml
  gradle/checkstyle/enterprise_header.txt
  gradle/javaModule.gradle
Labels: ready-to-merge

#12636 Add a note that changing `codec` only applies to newly written segments
  docs/general/ddl/alter-table.rst
Labels: ready-to-merge, v/4.8

#12638 Updated Admin UI to 1.22.1
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12642 tests: Fix printed gradle reproduction line
  devs/docs/tests.rst
  server/src/testFixtures/java/org/elasticsearch/test/junit/listeners/ReproduceInfoPrinter.java
Labels: ready-to-merge, v/4.8

#12651 `pg_get_expr` should also accept `pretty` arg
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/systeminformation/PgGetExpr.java
  server/src/test/java/io/crate/expression/scalar/postgres/PgGetExprFunctionTest.java
Labels: ready-to-merge

#12649 Add `pg_catalog.pg_get_partkeydef` function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/PgGetPartkeydefFunction.java
  server/src/test/java/io/crate/expression/scalar/postgres/PgGetPartkeydefFunctionTest.java
Labels: ready-to-merge

#12650 Switch CrateDBs `pg_node_tree` representation from `OBJECT(ARRAY)` to `TEXT` in `pg_index` and `pg_class `
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgClassTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgIndexTable.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge, breaking change

#12656 Fix refresh after idle for queries with fetch operation
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/JobLauncher.java
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/AbstractTask.java
  server/src/main/java/io/crate/execution/jobs/CountTask.java
  server/src/main/java/io/crate/execution/jobs/DistResultRXTask.java
  server/src/main/java/io/crate/execution/jobs/PKLookupTask.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
  server/src/main/java/io/crate/execution/jobs/Task.java
  server/src/main/java/io/crate/metadata/Routing.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/analyze/AlterTableRerouteAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchTaskTest.java
  server/src/test/java/io/crate/execution/jobs/AbstractTaskTest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, v/4.8

#12662 Support ORDER BY + LIMIT 0 in SortingTopNProjector
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/sort/SortingTopNProjector.java
  server/src/test/java/io/crate/execution/engine/sort/SortingTopNProjectorTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/4.8

#12666 Fix NPE in maybeRefreshReaders
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
Labels: ready-to-merge, v/4.8

#12669 tests: Handle `null` methodName in ReproduceInfoPrinter
  server/src/testFixtures/java/org/elasticsearch/test/junit/listeners/ReproduceInfoPrinter.java
Labels: ready-to-merge, v/4.8

#12661 Deprecate the azure discovery plugin
  docs/appendices/release-notes/unreleased.rst
  plugins/azure-discovery/src/main/java/io/crate/azure/plugin/AzureDiscoveryPlugin.java
Labels: ready-to-merge

#12673 Fix PostgreSQL wire protocol simple query on error
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge, v/4.8

#12677 Add empty `pg_catalog.pg_shdescription` table
  .github/styles/Vocab/CrateDB/accept.txt
  docs/appendices/release-notes/unreleased.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgShdescriptionTable.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#12679 Prevent `IS NULL` from matching rows without NULL values
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
Labels: ready-to-merge, v/4.8

#12671 Allow cast from bigint to regclass
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/RegclassType.java
  server/src/main/java/io/crate/types/RegprocType.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  server/src/test/java/io/crate/types/RegclassTypeTest.java
  server/src/test/java/io/crate/types/RegprocTypeTest.java
Labels: ready-to-merge

#12680 Replace deprecated DocValuesFieldExistsQuery/NormsFieldExistsQuery
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#12684 Support array element access via subscript on top of key lookups
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/SubscriptValidator.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/SubscriptFunctionTest.java
Labels: ready-to-merge
