Repository crate/crate, pull requests merged in 2022-05, with the labels that each got.

#12424 Allow users with AL privileges to run ANALYZE
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge

#12425 Move `quote_ident()` function to `pg_catalog`
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/string/QuoteIdentFunction.java
  server/src/test/java/io/crate/expression/scalar/string/QuoteIdentFunctionTest.java
Labels: ready-to-merge

#12428 Don't evaluate primary key defaults multiple times
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/RawInsertSource.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/ValidatedRawInsertSource.java
  server/src/main/java/io/crate/execution/engine/collect/RowShardResolver.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ItemFactory.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/node/dml/UpdateById.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/ValidatedRawInsertSourceTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/4.7, v/4.8

#12434 Add use case specific static factories to ShardUpsertRequest.Item
  server/src/main/java/io/crate/execution/dml/ShardRequestExecutor.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/node/dml/DeleteById.java
  server/src/main/java/io/crate/planner/node/dml/UpdateById.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
Labels: ready-to-merge

#12435 Account for 4.7.3 release in ShardUpsertRequest.Item streaming
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
Labels: ready-to-merge

#12355 12259 concat ws
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ConcatWsFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/test/java/io/crate/expression/scalar/ConcatWsFunctionTest.java
Labels: ready-to-merge

#12430 Update bundled JDK to 18.0.1+10
  build.gradle
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12437 Fix retrieval of relation names in logical plan operators
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
Labels: ready-to-merge

#12445 Enable use of append only optimization
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/collect/RowShardResolver.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ItemFactory.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
Labels: ready-to-merge

#12464 Remove reference to removed HDFS repository from old release notes
  docs/appendices/release-notes/4.0.0.rst
Labels: ready-to-merge, v/4.8

#12467 add typsend column to pg_catalog.pgtype table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
  server/src/main/java/io/crate/protocols/postgres/types/AnyType.java
  server/src/main/java/io/crate/protocols/postgres/types/PGType.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/types/AnyTypeTest.java
Labels: ready-to-merge

#12474 Add alias target symbol evaluation in the EvaluationNormalizer
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/4.8

#12472 Use VarHandle for long decoding in MurmurHash3
  server/src/main/java/org/elasticsearch/common/hash/MurmurHash3.java
Labels: ready-to-merge

#12481 Make instance cancellable variable volatile at RetryRunnable
  server/src/main/java/io/crate/execution/support/RetryRunnable.java
Labels: ready-to-merge, v/4.8

#12469 add object_keys function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/object/ObjectKeysFunction.java
  server/src/test/java/io/crate/expression/scalar/object/ObjectKeysFunctionTest.java
Labels: ready-to-merge

#12487 Fix restoreInfo=null error while restoring subscribed tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
Labels: ready-to-merge, v/4.8

#12294 Update JDBC to 42.3.5
  gradle/version.properties
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/DiskDisruptionIT.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/testFixtures/java/org/elasticsearch/test/BackgroundIndexer.java
Labels: ready-to-merge

#12403 Change community support link to discourse
  .github/ISSUE_TEMPLATE/config.yml
Labels: ready-to-merge

#12493 Move some more options from FieldMapper to TextFieldMapper
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
Labels: ready-to-merge

#12498 Fix parameter binding for table functions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/ProjectSet.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/4.7, v/4.8

#12488 Fix error handling when subscribing to unknown publication
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/io/crate/replication/logical/action/TransportCreateSubscriptionAction.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
Labels: ready-to-merge, v/4.8

#12501 Remove caching in table parameters
  server/src/main/java/io/crate/analyze/TableParameter.java
Labels: ready-to-merge

#12495 Make soft-deletes mandatory for newly created tables
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
  server/src/test/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzerTest.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/testFixtures/java/org/elasticsearch/test/ESIntegTestCase.java
Labels: ready-to-merge

#12499 Add extra local variable to fix eclipse compile error
  server/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
Labels: ready-to-merge

#12516 Support using `null` without explicit cast in UNION
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/UnionSelect.java
  server/src/main/java/io/crate/expression/symbol/Symbol.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
Labels: ready-to-merge

#12519 Make soft-deletes mandatory for newly created partitioned tables
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
Labels: ready-to-merge

#12524 Fix randomization in forRandomMasterOrDataNode
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/RoutingProvider.java
  server/src/test/java/io/crate/metadata/RoutingProviderTest.java
Labels: ready-to-merge, v/4.7, v/4.8

#12521 Use bulk inserts in test_snapshot_with_corrupted_shard_index_file
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#12527 Remove alter open operation from published/subscribed tables
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/test/java/io/crate/metadata/table/OperationTest.java
Labels: ready-to-merge

#12510 alter table fix varchar length info being dropped
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
Labels: ready-to-merge, v/4.7, v/4.8

#12532 Fix length 0 bulkArgs handling in test layer
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, v/4.7, v/4.8

#12540 Implement support for non-recursive, DQL WITH sql statements
  docs/appendices/release-notes/unreleased.rst
  docs/general/dql/selects.rst
  docs/sql/statements/index.rst
  docs/sql/statements/with.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Query.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/With.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/WithQuery.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/relations/ParentRelations.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#12541 Fix NPE while writing a ShardResponse with an empty failure message
  server/src/main/java/io/crate/exceptions/SQLExceptions.java
Labels: ready-to-merge, v/4.7, v/4.8

#12528 Make timeout handler & cancellable property final
  server/src/main/java/org/elasticsearch/transport/Transport.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
Labels: ready-to-merge

#12523 Enable to alter settings in subscribed tables
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/metadata/settings/NumberOfReplicasSetting.java
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/routing/UnassignedInfo.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/EnableAllocationDecider.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/MaxRetryAllocationDecider.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/MergeSchedulerConfig.java
  server/src/test/java/io/crate/metadata/table/OperationTest.java
  server/src/test/java/io/crate/planner/node/ddl/AlterTablePlanTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, v/4.8

#12551 Remove ExpressionToColumnIdentVisitor
  server/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableRerouteAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/analyze/CopyAnalyzer.java
  server/src/main/java/io/crate/analyze/CreateAnalyzerStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/CreateRepositoryAnalyzer.java
  server/src/main/java/io/crate/analyze/CreateSnapshotAnalyzer.java
  server/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/OptimizeTableAnalyzer.java
  server/src/main/java/io/crate/analyze/RefreshTableAnalyzer.java
  server/src/main/java/io/crate/analyze/ResetStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/RestoreSnapshotAnalyzer.java
  server/src/main/java/io/crate/analyze/SetStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionToColumnIdentVisitor.java
  server/src/main/java/io/crate/analyze/expressions/TableReferenceResolver.java
  server/src/main/java/io/crate/analyze/relations/FieldProvider.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/main/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzer.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionToColumnIdentVisitorTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge

#12556 Bump version to 4.7.4-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12558 Reflect release 4.7.3
  docs/appendices/release-notes/4.7.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12557 Release 4.8.1
  docs/appendices/release-notes/4.8.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12560 Bump version to 4.8.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12564 Remove unused RefAndLiteral
  server/src/main/java/io/crate/lucene/RefAndLiteral.java
Labels: ready-to-merge

#12566 bp: Fix testRerouteOccursOnDiskPassingHighWatermark
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
Labels: ready-to-merge, v/4.8

#12570 Prune unreleased fixes
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#12569 Add a `getParents` iterable to TableInfo
  server/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/table/TableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge

#12571 tests: Remove isColumnPolicy custom matcher
  server/src/test/java/io/crate/analyze/SymbolToColumnDefinitionConverterTest.java
  server/src/testFixtures/java/io/crate/testing/NodeMatchers.java
  server/src/testFixtures/java/io/crate/testing/SymbolMatchers.java
Labels: ready-to-merge

#12565 Change timestamp alias to timestamp without time zone
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/GenerateSeriesTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge, breaking change

#12572 Remove .add from GenericProperties
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GenericProperties.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryPluginAnalyzerTest.java
  server/src/main/java/io/crate/analyze/CreateAnalyzerStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
Labels: ready-to-merge

#12573 Move characterMaximumLength to DataType
  server/src/main/java/io/crate/expression/reference/information/ColumnContext.java
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/execution/engine/collect/sources/ColumnsIterableTest.java
Labels: ready-to-merge

#12576 Upgrade to Lucene 9.2.0
  gradle/version.properties
  plugins/es-analysis-phonetic/src/test/java/org/elasticsearch/index/analysis/SimplePhoneticAnalysisTests.java
  server/src/main/java/io/crate/execution/engine/sort/NullFieldComparatorSource.java
  server/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
  server/src/main/java/io/crate/lucene/match/CrateRegexQuery.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
  server/src/test/java/io/crate/integrationtests/ExplainAnalyzeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TablesNeedUpgradeSysCheckTest.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/DiskDisruptionIT.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/BitStringQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
  server/src/test/java/org/apache/lucene/index/TestShuffleForcedMergePolicyTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinationStateTestCluster.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/test/java/org/elasticsearch/cluster/service/FakeThreadPoolMasterService.java
  server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/elasticsearch/gateway/IncrementalClusterStateWriterTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicyTests.java
  server/src/test/java/org/elasticsearch/index/engine/VersionValueTests.java
  server/src/test/java/org/elasticsearch/index/store/StoreTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/testFixtures/java/org/apache/lucene/index/PatchedAssertingLeafReader.java
  server/src/testFixtures/java/org/elasticsearch/common/io/PathUtilsForTesting.java
  server/src/testFixtures/java/org/elasticsearch/common/util/MockBigArrays.java
  server/src/testFixtures/java/org/elasticsearch/common/util/MockPageCacheRecycler.java
  server/src/testFixtures/java/org/elasticsearch/index/translog/TestTranslog.java
  server/src/testFixtures/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/CorruptionUtils.java
  server/src/testFixtures/java/org/elasticsearch/test/ESIntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/FieldMaskingReader.java
  server/src/testFixtures/java/org/elasticsearch/test/InternalTestCluster.java
  server/src/testFixtures/java/org/elasticsearch/test/MockKeywordPlugin.java
  server/src/testFixtures/java/org/elasticsearch/test/engine/MockEngineSupport.java
  server/src/testFixtures/java/org/elasticsearch/test/store/MockFSDirectoryFactory.java
  server/src/testFixtures/java/org/elasticsearch/test/test/InternalTestClusterTests.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/MockTransport.java
Labels: ready-to-merge
