Repository crate/crate, pull requests merged in 2022-11, with the labels that each got.

#13203 docs: Fix NOTE entry in `SHOW` statement
  docs/sql/statements/show.rst
Labels: ready-to-merge, docs, v/5.1

#13207 Add ramAccounting to percentile agg / fix out-of-memory errors
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/PercentileAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TDigestState.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
Labels: ready-to-merge, v/5.1

#13192 Update bundled JDK to 19.0.1+10
  gradle/version.properties
Labels: ready-to-merge

#13212 Fix name of BitStringFieldMapper to avoid clash in objects
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/index/mapper/BitStringFieldMapper.java
  server/src/test/java/org/elasticsearch/index/mapper/BitStringFieldMapperTest.java
Labels: ready-to-merge, v/5.1

#13209 Avoid dynamic mapping update in `test_types_with_storage_can_be_inserted_and_queried`
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#13216 Add ability to download bundled Mac aarch64 jdk
  buildSrc/src/main/java/io/crate/gradle/OS.java
  buildSrc/src/test/java/io/crate/gradle/plugins/jdk/JdkDownloadPluginFunctionalTest.java
  buildSrc/src/test/resources/fake_artifacts/13.0.2+8/aarch64_mac.tar.gz
  buildSrc/src/testKit/jdk-download/sub/build.gradle
  gradle/javaModule.gradle
Labels: ready-to-merge

#13214 Explain how to use nested arrays
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#13220 Documentation: Fix anchors at new section about "Nested arrays"
  docs/general/ddl/data-types.rst
Labels: ready-to-merge, v/5.1

#13224 Add example to debug the installDist variant to dev docs
  devs/docs/basics.rst
Labels: ready-to-merge

#13223 Change function resolve order to check built-in and udfs per schema in search path
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
Labels: ready-to-merge, v/5.1

#13235 Fix String/BytesRef cast in OptimizeQueryForSearchAfter
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfter.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfterTest.java
Labels: ready-to-merge, v/5.1

#13240 Fix terms query generation for `_id` column
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyEqOperator.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
Labels: ready-to-merge, v/5.1

#13245 Fix `./gradlew :app:run` and `./gradlew :app:runDebug`
  .gitignore
  .vscode/launch.json
  app/build.gradle
  idea/crateApp.xml
  sandbox/crate/config/crate.yml
Labels: ready-to-merge

#13248 Release 5.1.1
  docs/appendices/release-notes/5.1.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13249 Bump version to 5.1.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13251 Reflect release 5.1.1
  docs/appendices/release-notes/5.1.1.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13253 Skip more unrelated backports
  devs/docs/es-backports.rst
Labels: ready-to-merge

#13252 Skip datastream backports
  devs/docs/es-backports.rst
Labels: ready-to-merge

#13258 Update netty to 4.1.85
  gradle/version.properties
Labels: ready-to-merge

#13254 GEO_SHAPE typed columns must compute generated expressions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
Labels: ready-to-merge, v/5.1

#13259 Clarify that shard allocations settings are not mutually exclusive
  docs/general/ddl/shard-allocation.rst
Labels: ready-to-merge, docs, v/5.1

#13266 Fix NPE in IsNullPredicate.refExistsQuery
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/test/java/io/crate/expression/predicate/IsNullPredicateTest.java
Labels: ready-to-merge, v/5.1

#13270 Expose require, include, exclude routing.allocation for partitions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/PartitionInfos.java
  server/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge

#13271 Set `--enable-preview` in jvmArgs
  app/build.gradle
  app/src/bin/crate.bat
  app/src/main/dist/bin/crate
  gradle/javaModule.gradle
Labels: ready-to-merge

#13274 Change documents on ParsedDocument/Index to single doc
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java
  server/src/main/java/org/elasticsearch/index/mapper/ParsedDocument.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#13238 ADD COLUMN based on delta, V2
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
  server/src/main/java/io/crate/metadata/IndexReference.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropCheckConstraintPlan.java
  server/src/main/java/io/crate/types/StorageSupport.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge

#13261 Fix COPY FROM resulting in dulicate data due to consecutive SocketTimeout
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
Labels: bug, ready-to-merge, v/5.1

#13275 Replace ParseContext.Document with Lucene Document
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java
  server/src/main/java/org/elasticsearch/index/mapper/ParsedDocument.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#13288 Add bit-operators.rst to test_docs and add bit string example
  blackbox/test_docs.py
  docs/general/builtins/bit-operators.rst
Labels: ready-to-merge

#13291 Register bitwise operators without storing all operators
  server/src/main/java/io/crate/expression/scalar/bitwise/BitwiseFunctions.java
Labels: ready-to-merge

#13287 Add missing rst files to doc tests
  blackbox/test_docs.py
  docs/general/builtins/comparison-operators.rst
Labels: ready-to-merge

#13293 Replace AbstractRecyclerC with default method on interface
  server/src/main/java/org/elasticsearch/common/recycler/AbstractRecyclerC.java
  server/src/main/java/org/elasticsearch/common/recycler/Recycler.java
  server/src/main/java/org/elasticsearch/common/util/PageCacheRecycler.java
Labels: ready-to-merge

#13294 Avoid boxing in ShardDMLExecutor.ROW_COUNT_COLLECTOR
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
Labels: ready-to-merge

#13297 Skip FieldMapper related patches
  devs/docs/es-backports.rst
Labels: ready-to-merge

#13292 Fix inefficient table swap in joins when expected rows are unavailable
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/testFixtures/java/io/crate/analyze/TableDefinitions.java
Labels: ready-to-merge, v/5.1

#13298 bp: Shortcut mapping update if the incoming mapping version is the sa…
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
Labels: ready-to-merge

#13309 Update to Admin UI 1.24.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#13314 Make Symbol and DataType accountable
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/main/java/io/crate/expression/symbol/Aggregation.java
  server/src/main/java/io/crate/expression/symbol/AliasSymbol.java
  server/src/main/java/io/crate/expression/symbol/FetchMarker.java
  server/src/main/java/io/crate/expression/symbol/FetchReference.java
  server/src/main/java/io/crate/expression/symbol/FetchStub.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/expression/symbol/InputColumn.java
  server/src/main/java/io/crate/expression/symbol/Literal.java
  server/src/main/java/io/crate/expression/symbol/MatchPredicate.java
  server/src/main/java/io/crate/expression/symbol/OuterColumn.java
  server/src/main/java/io/crate/expression/symbol/ParameterSymbol.java
  server/src/main/java/io/crate/expression/symbol/ScopedSymbol.java
  server/src/main/java/io/crate/expression/symbol/SelectSymbol.java
  server/src/main/java/io/crate/expression/symbol/Symbol.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/main/java/io/crate/metadata/FunctionName.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/ReferenceIdent.java
  server/src/main/java/io/crate/metadata/RelationName.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/main/java/io/crate/metadata/functions/Signature.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/main/java/io/crate/types/TypeSignature.java
  server/src/test/java/io/crate/expression/symbol/SymbolsTest.java
Labels: ready-to-merge, v/5.1

#13305 Fix table swap in NestedLoop Join for single node
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.1
