Repository crate/crate, pull requests merged in 2022-07, with the labels that each got.

#12691 add support of the CharacterType to the HyperLogLogDistinctAggregation
  extensions/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
Labels: ready-to-merge

#12692 Fix flaky org.elasticsearch.index.shard.IndexShardTests#testRestoreLocalHistoryFromTranslogOnPromotion
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge, v/4.8

#12610 Fix cast to `regclass` to be aware of the current search_path
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/data-types.rst
  libs/shared/src/main/java/io/crate/common/StringUtils.java
  server/src/main/java/io/crate/exceptions/InvalidRelationName.java
  server/src/main/java/io/crate/expression/scalar/cast/ExplicitCastFunction.java
  server/src/main/java/io/crate/expression/scalar/cast/TryCastFunction.java
  server/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  server/src/main/java/io/crate/metadata/Scalar.java
  server/src/main/java/io/crate/protocols/postgres/types/RegclassType.java
  server/src/main/java/io/crate/protocols/postgres/types/TimestampZType.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/CharacterType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/JsonType.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/main/java/io/crate/types/Regclass.java
  server/src/main/java/io/crate/types/RegclassType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/types/BitStringTypeTest.java
  server/src/test/java/io/crate/types/CharacterTypeTest.java
  server/src/test/java/io/crate/types/JsonTypeTest.java
  server/src/test/java/io/crate/types/RegclassTypeTest.java
  server/src/test/java/io/crate/types/StringTypeTest.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge

#12694 Don't overwrite formattedGeneratedExpression with formattedDefaultExpression
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
Labels: ready-to-merge, v/4.8

#12696 Optimize `arr = []` queries
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#12700 Group release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#12701 Remove deprecated FunctionInfo and FunctionIdent
  extensions/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  server/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/TableFunctionRelation.java
  server/src/main/java/io/crate/analyze/validator/GroupBySymbolValidator.java
  server/src/main/java/io/crate/analyze/validator/HavingSymbolValidator.java
  server/src/main/java/io/crate/analyze/validator/SelectSymbolValidator.java
  server/src/main/java/io/crate/analyze/where/WhereClauseValidator.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  server/src/main/java/io/crate/expression/BaseImplementationSymbolVisitor.java
  server/src/main/java/io/crate/expression/InputFactory.java
  server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  server/src/main/java/io/crate/expression/predicate/MatchPredicate.java
  server/src/main/java/io/crate/expression/scalar/conditional/GreatestFunction.java
  server/src/main/java/io/crate/expression/scalar/conditional/LeastFunction.java
  server/src/main/java/io/crate/expression/symbol/Aggregation.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/expression/symbol/GroupAndAggregateSemantics.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/expression/tablefunctions/TableFunctionFactory.java
  server/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/metadata/FunctionIdent.java
  server/src/main/java/io/crate/metadata/FunctionImplementation.java
  server/src/main/java/io/crate/metadata/FunctionInfo.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/metadata/functions/Signature.java
  server/src/main/java/io/crate/metadata/tablefunctions/TableFunctionImplementation.java
  server/src/main/java/io/crate/planner/consumer/OrderByWithAggregationValidator.java
  server/src/main/java/io/crate/planner/operators/HashAggregate.java
  server/src/main/java/io/crate/planner/operators/ProjectSet.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/expression/InputFactoryTest.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  server/src/test/java/io/crate/expression/symbol/AggregationTest.java
  server/src/test/java/io/crate/expression/tablefunctions/AbstractTableFunctionsTest.java
  server/src/test/java/io/crate/expression/tablefunctions/UnnestFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
  server/src/testFixtures/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
  server/src/testFixtures/java/io/crate/integrationtests/SQLIntegrationTestCase.java
Labels: ready-to-merge

#12702 Document `array_upper` behavior on empty array
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge

#12705 Remove redundant checks from IsNullPredicate
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
Labels: ready-to-merge

#12712 tests: Remove duplicate -Dtests.nightly=true
  server/src/testFixtures/java/org/elasticsearch/test/junit/listeners/ReproduceInfoPrinter.java
Labels: ready-to-merge, v/4.8

#12709 Support implicit casts with UNION
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/select.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
Labels: ready-to-merge

#12721 Update hash in git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: ready-to-merge

#12717 fix 'array_length > x' on array with duplicates or nulls
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
Labels: ready-to-merge, v/4.8

#12725 Update hash in git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: ready-to-merge

#12723 tests: Revert removal of suppress warnings
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  server/src/test/java/io/crate/integrationtests/BulkInsertOnClientNodeTest.java
  server/src/testFixtures/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
Labels: ready-to-merge

#12728 tests: Fix flaky IndexRecoveryIT#testRerouteRecovery
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge, v/4.8

#12731 pass concrete argument types when streaming signature as functionInfo
  server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java
  server/src/main/java/io/crate/expression/symbol/Aggregation.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/metadata/functions/Signature.java
  server/src/test/java/io/crate/execution/dsl/projection/WindowAggProjectionSerialisationTest.java
Labels: ready-to-merge

#12732 Release 4.8.2
  docs/appendices/release-notes/4.8.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12735 Reflect release 4.8.2
  docs/appendices/release-notes/4.8.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12741 Bump version to 5.0.1-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12742 Update Apache HttpComponents libraries `httpclient` and `httpcore`
  gradle/version.properties
Labels: ready-to-merge, v/4.8, v/5.0

#12740 Remove cluster_id setting removal from test layer
  server/src/testFixtures/java/org/elasticsearch/test/ESIntegTestCase.java
Labels: ready-to-merge

#12744 Remove the azure-discovery plugin
  app/build.gradle
  docs/admin/discovery.rst
  docs/appendices/release-notes/unreleased.rst
  docs/config/cluster.rst
  plugins/azure-discovery/build.gradle
  plugins/azure-discovery/src/main/java/io/crate/azure/AzureConfiguration.java
  plugins/azure-discovery/src/main/java/io/crate/azure/discovery/AzureSeedHostsProvider.java
  plugins/azure-discovery/src/main/java/io/crate/azure/management/AzureComputeService.java
  plugins/azure-discovery/src/main/java/io/crate/azure/management/AzureComputeServiceImpl.java
  plugins/azure-discovery/src/main/java/io/crate/azure/plugin/AzureDiscoveryPlugin.java
  plugins/azure-discovery/src/main/resources/plugin-descriptor.properties
  plugins/azure-discovery/src/test/java/io/crate/azure/AbstractAzureComputeServiceTestCase.java
  plugins/azure-discovery/src/test/java/io/crate/azure/AzureSimpleTests.java
  plugins/azure-discovery/src/test/java/io/crate/azure/discovery/AzureSeedHostsProviderTest.java
  settings.gradle
Labels: ready-to-merge

#12757 Documentation: Fix broken links
  docs/config/environment.rst
  docs/config/logging.rst
Labels: ready-to-merge, v/4.8, v/5.0

#12753 Make Gateway stateRecovery non-blocking
  server/src/main/java/org/elasticsearch/client/node/NodeClient.java
  server/src/main/java/org/elasticsearch/gateway/Gateway.java
Labels: ready-to-merge

#12765 fix gradle dependency typo
  plugins/es-repository-s3/build.gradle
Labels: ready-to-merge

#12755 Allow group by on array type
  docs/appendices/release-notes/unreleased.rst
  docs/general/dql/selects.rst
  server/src/main/java/io/crate/exceptions/ArrayViaDocValuesUnsupportedException.java
  server/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BitStringColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BooleanColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/ByteColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/BytesRefColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/DoubleColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/FloatColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/GeoPointColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IntegerColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IpColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LongColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/ShortColumnReference.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/expression/reference/doc/IpColumnReferenceTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
Labels: ready-to-merge

#12770 Reduce overhead of TimestampType.explicit/implicitCast on non-number strings
  benchmarks/src/main/java/io/crate/common/StringUtilsBenchmark.java
  libs/shared/src/main/java/io/crate/common/StringUtils.java
  server/src/main/java/io/crate/types/TimestampType.java
Labels: ready-to-merge

#12773 Fix linkcheck failure
  docs/appendices/release-notes/4.6.0.rst
Labels: ready-to-merge

#12772 Tune GHA workflows
  .github/workflows/docs.yml
  .github/workflows/main.yml
  .github/workflows/skip.yml
Labels: ready-to-merge

#12779 Use configured timeout on dynamic mapping updates
  server/src/main/java/io/crate/execution/ddl/SchemaUpdateClient.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
Labels: ready-to-merge

#12780 Support selecting _doc['child-col'] with primary key lookups
  server/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  server/src/main/java/io/crate/expression/reference/DocRefResolver.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#12781 Fix resolveNodeId error handling in ShardDMLExecutor
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
Labels: ready-to-merge, v/4.8, v/5.0

#12763 fix array_upper and array_lower for multidimensional arrays
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ArrayLowerFunction.java
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/test/java/io/crate/expression/scalar/ArrayLowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUpperFunctionTest.java
Labels: ready-to-merge, v/4.8, v/5.0

#12789 Update jdbc to 42.4.0
  gradle/version.properties
Labels: ready-to-merge

#12793 Don't block on store release in RecoverySourceHandler
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
Labels: ready-to-merge

#12796 Add commit org.junit.Assert.xxx imports to ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12794 Reduce amount of indirections in Releasables.close
  server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/elasticsearch/common/lease/Releasables.java
  server/src/main/java/org/elasticsearch/common/util/BigArrays.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java
  server/src/main/java/org/elasticsearch/transport/InboundMessage.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4MessageChannelHandler.java
  server/src/testFixtures/java/org/elasticsearch/test/hamcrest/ElasticsearchAssertions.java
Labels: ready-to-merge

#12798 Add commit org.junit.Assert.xxx imports to ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12788 Avoid map.containsKey/.get calls if trace logging is disabled
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
Labels: ready-to-merge

#12801 tests: Add assertj migration to blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12802 tests: Add assertj migration to blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12803 Fix `MapComparator` util
  server/src/main/java/io/crate/common/collections/MapComparator.java
  server/src/test/java/io/crate/common/collections/MapComparatorTest.java
  server/src/test/java/io/crate/types/DataTypesTest.java
Labels: ready-to-merge, v/4.8, v/5.0

#12807 Ensure response handlers force execution
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/testFixtures/java/org/elasticsearch/test/InternalTestCluster.java
Labels: ready-to-merge

#12809 Fix flaky testShardNotAvailableExceptionWhenEngineClosedConcurrently
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#12818 tests: Add assertj fixes to blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12819 tests: Add assertj fixes to blame ignore
  .git-blame-ignore-revs
Labels: ready-to-merge

#12814 bp: Fix constructors of NoOpResult
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#12812 Update bundled JDK to 18.0.2+9
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/5.0

#12820 Fix gradle deprecation warnings (prepare for v8.0)
  app/build.gradle
  build.gradle
  libs/pgwire/build.gradle
  libs/sql-parser/build.gradle
  server/build.gradle
Labels: ready-to-merge

#12808 Attempt to fix testTransientErrorsDuringRecoveryAreRetried
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryState.java
Labels: ready-to-merge, v/5.0

#12816 Add support for `catalog` in FQNs of tables/columns
  docs/appendices/release-notes/unreleased.rst
  docs/sql/general/value-expressions.rst
  server/src/main/java/io/crate/analyze/relations/FullQualifiedNameFieldProvider.java
  server/src/main/java/io/crate/metadata/RelationName.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/test/java/io/crate/analyze/relations/FieldProviderTest.java
  server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java
  server/src/test/java/io/crate/metadata/SchemasTest.java
Labels: ready-to-merge

#12823 Improve error message of invalid column refs in insert into
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge

#12826 Documentation: Improve rendering of 5.0.0 release notes
  docs/appendices/release-notes/5.0.0.rst
Labels: v/5.0

#12824 Dump active tasks and threads on timeout in LR tests
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/testFixtures/java/io/crate/integrationtests/SQLIntegrationTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/InternalTestCluster.java
  server/src/testFixtures/java/org/elasticsearch/threadpool/TestThreadPool.java
Labels: ready-to-merge

#12829 bp: Remove Redundant Loading of RepositoryData during Restore
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/cluster/routing/ShardRoutingTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/testFixtures/java/org/elasticsearch/cluster/routing/TestShardRouting.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#12830 bp: Don't Upload Redundant Shard Files
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/index/store/StoreFileMetadata.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge

#12832 bp: Ignore timeouts with single-node discovery (#52159)
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/coordination/ClusterBootstrapService.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java
  server/src/test/java/org/elasticsearch/cluster/coordination/AbstractCoordinatorTestCase.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinatorTests.java
Labels: ready-to-merge

#12831 Remove duplicate store ref decrement call
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
Labels: ready-to-merge

#12834 bp: Deciders should not by default collect yes'es
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDecidersTests.java
Labels: ready-to-merge

#12836 bp: Clarify when shard iterators get sorted
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/routing/GroupShardsIterator.java
  server/src/main/java/org/elasticsearch/cluster/routing/RoutingTable.java
Labels: ready-to-merge

#12838 bp: Allow joining node to trigger term bump
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinRequest.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/MessagesTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NodeJoinTests.java
Labels: ready-to-merge
