Repository crate/crate, pull requests merged in 2022-03, with the labels that each got.

#12177 Fix flaky testTranslogReplayWithFailure
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#12186 bp: Fix Snapshot Repository Corruption in Downgrade Scenarios
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
Labels: ready-to-merge

#12189 bp: Ignore shutdown when retrying recoveries
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
Labels: ready-to-merge

#12187 fix nondeterministic default exprs that were not evaluated per row
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/upsert/GeneratedColsFromRawInsertSource.java
  server/src/test/java/io/crate/execution/dml/upsert/GeneratedColsFromRawInsertSourceTest.java
Labels: ready-to-merge, v/4.6

#12168 Adding target columns and csv header option for copyfrom statement
  benchmarks/src/main/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/3.0.7.rst
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/copy-from.rst
  libs/sql-parser/src/main/antlr/SqlBase.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CopyFrom.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/analyze/AnalyzedCopyFrom.java
  server/src/main/java/io/crate/analyze/AnalyzedCopyFromReturnSummary.java
  server/src/main/java/io/crate/analyze/BoundCopyFrom.java
  server/src/main/java/io/crate/analyze/CopyAnalyzer.java
  server/src/main/java/io/crate/analyze/CopyFromParserProperties.java
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/execution/dsl/phases/FileUriCollectPhase.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/files/LineParser.java
  server/src/main/java/io/crate/execution/engine/collect/files/LineProcessor.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/io/crate/expression/reference/file/LineContext.java
  server/src/main/java/io/crate/operation/collect/files/CSVLineParser.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/execution/dsl/phases/FileUriCollectPhaseTest.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/LineProcessorTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
  server/src/test/resources/essetup/data/copy/test_copy_from_csv_extra_column.ext
  server/src/test/resources/essetup/data/copy/test_copy_from_csv_no_header.ext
  server/src/test/resources/essetup/data/copy/test_copy_from_extra_column.json
Labels: ready-to-merge

#12165 Improve performance of implicit casts by moving parsing of target type into compile
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/cast/ImplicitCastFunction.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge

#12194 Reflect 4.6.8 release
  docs/appendices/release-notes/4.6.8.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12199 Bump version to 4.7.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#12126 validate the source data of COPY-FROM
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/generated-columns.rst
  docs/general/dml.rst
  docs/sql/statements/copy-from.rst
  docs/sql/statements/create-table.rst
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/support/ParameterizedXContentParser.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java
  server/src/main/java/io/crate/execution/dml/upsert/GeneratedColsFromRawInsertSource.java
  server/src/main/java/io/crate/execution/dml/upsert/GeneratedColumns.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/dml/upsert/FromRawInsertSourceTest.java
  server/src/test/java/io/crate/execution/dml/upsert/GeneratedColsFromRawInsertSourceTest.java
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/testFixtures/java/io/crate/testing/SymbolMatchers.java
Labels: bug, ready-to-merge

#12202 Update netty to 4.1.75
  gradle/version.properties
Labels: ready-to-merge

#12205 Update gradle to 7.4.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ready-to-merge, v/4.7

#12216 Remove wacklig upload from GHA workflows
  .github/workflows/main.yml
Labels: ready-to-merge

#12221 Fix conversion of intervals to function expression
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/LiteralValueFormatter.java
  server/src/test/java/io/crate/expression/symbol/LiteralValueFormatterTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
Labels: ready-to-merge

#12220 Fix closing of an empty partitioned table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
Labels: ready-to-merge, v/4.6, v/4.7

#12223 Remove Netty4Utils.setup
  server/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  server/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Utils.java
Labels: ready-to-merge

#12228 Backport idle shard changes
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#12226 bp: Optimize FilterStreamInput for Network Reads
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/common/io/stream/FilterStreamInput.java
  server/src/main/java/org/elasticsearch/index/translog/BufferedChecksumStreamInput.java
Labels: ready-to-merge

#12232 Fix SJK download url used by jmx blackbox tests
  blackbox/test_jmx.py
Labels: ready-to-merge, v/4.6, v/4.7

#12231 Fix re-open a closed empty partitioned table
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportOpenCloseTableOrPartitionAction.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
Labels: ready-to-merge, v/4.6, v/4.7

#12241 Inline readList/readSet in StreamInput
  server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
Labels: ready-to-merge

#12219 add a boolean withOption 'validation' for COPY-FROM
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/execution/dml/upsert/GeneratedColumns.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceFromCells.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/RawInsertSource.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/ValidatedRawInsertSource.java
  server/src/main/java/io/crate/execution/dsl/projection/SourceIndexWriterProjection.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dml/upsert/GeneratedColumnsTest.java
  server/src/test/java/io/crate/execution/dml/upsert/SourceFromCellsTest.java
  server/src/test/java/io/crate/execution/dml/upsert/ValidatedRawInsertSourceTest.java
  server/src/test/java/io/crate/execution/dsl/projection/SourceIndexWriterProjectionSerializationTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorUnitTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#12246 Optimize parsing of pg arrays when array is a string literal
  docs/appendices/release-notes/unreleased.rst
  libs/pgwire/src/main/java/io/crate/protocols/postgres/parser/PgArrayParser.java
  libs/pgwire/src/test/java/io/crate/protocols/postgres/parser/PgArrayParserTest.java
  server/src/main/java/io/crate/types/ArrayType.java
Labels: ready-to-merge

#12248 bp: Fix testSendSnapshotSendsOps
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
Labels: ready-to-merge

#12243 Remove shouldRebuildConnection from connectionStrategy
  server/src/main/java/org/elasticsearch/transport/RemoteClusterConnection.java
  server/src/main/java/org/elasticsearch/transport/RemoteConnectionStrategy.java
  server/src/main/java/org/elasticsearch/transport/SniffConnectionStrategy.java
  server/src/test/java/org/elasticsearch/transport/RemoteConnectionStrategyTests.java
  server/src/test/java/org/elasticsearch/transport/SniffConnectionStrategyTests.java
Labels: ready-to-merge

#12254 Bump JNA library to 5.10.0 to satisfy warnings on macOS M1
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge

#12249 Add ``array_position`` scalar function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ArrayPositionFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/test/java/io/crate/expression/scalar/ArrayPositionFunctionTest.java
Labels: ready-to-merge

#12263 Updated to Admin UI 1.20.2, fixing duplicate entries in query history
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/4.7

#12264 Fix privileges and owner check for DROP/ALTER publication/subscription
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzer.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
  server/src/test/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzerTest.java
Labels: ready-to-merge

#11930 Add pgwire tunneling for CCR
  docs/sql/statements/create-subscription.rst
  server/src/main/java/io/crate/protocols/postgres/ClientMessages.java
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/protocols/postgres/PgClientFactory.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/metadata/PublicationsMetadata.java
  server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/RemoteCluster.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusters.java
  server/src/main/java/org/elasticsearch/transport/RemoteConnectionManager.java
  server/src/main/java/org/elasticsearch/transport/TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4MessageChannelHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/disruption/replication/logical/SubscriptionDisruptionIT.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresNettyPublishPortTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerTest.java
  server/src/testFixtures/java/io/crate/protocols/postgres/MockPgClient.java
  server/src/testFixtures/java/io/crate/protocols/postgres/MockPgClientFactory.java
  server/src/testFixtures/java/io/crate/testing/MoreMatchers.java
  server/src/testFixtures/java/org/elasticsearch/node/MockNode.java
  server/src/testFixtures/java/org/elasticsearch/test/InternalTestCluster.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/StubbableTransport.java
Labels: ready-to-merge

#12275 Fix handling of missing indexMetadata in createMultiShardScoreDocCollector
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
Labels: ready-to-merge

#12276 Increase timeout for replication in test_new_table_and_new_partition_is_replicated
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#12271 Add a `prefer` ssl mode for the pg_tunnel subscription mode
  docs/sql/statements/create-subscription.rst
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
Labels: ready-to-merge

#12262 Use correct regex case-insensitive match operator
  docs/general/builtins/comparison-operators.rst
Labels: ready-to-merge

#12282 increase timeout for replication in tests
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#12265 Update logical replication security section
  docs/admin/logical-replication.rst
Labels: ready-to-merge

#12277 Update crate-logo.png
  docs/_static/crate-logo.png
Labels: ready-to-merge

#12281 Docs: Clarify ALTER TABLE REROUTE note
  docs/sql/statements/alter-table.rst
Labels: ready-to-merge
