Repository crate/crate, pull requests merged in 2023-05, with the labels that each got.

#14039 Added attgenerated col to pg_attributes
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge

#14044 Remove duplicate getters from TimeValue
  libs/shared/src/main/java/io/crate/common/unit/TimeValue.java
  plugins/dns-discovery/src/main/java/io/crate/discovery/SrvUnicastHostsProvider.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageService.java
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/stats/JobsLogService.java
  server/src/main/java/io/crate/execution/engine/collect/stats/TimeBasedQEviction.java
  server/src/main/java/io/crate/execution/engine/distribution/TransportDistributedResultAction.java
  server/src/main/java/io/crate/expression/reference/sys/check/node/RecoveryAfterTimeSysCheck.java
  server/src/main/java/io/crate/udc/service/UDCService.java
  server/src/main/java/org/elasticsearch/action/support/RetryableAction.java
  server/src/main/java/org/elasticsearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/elasticsearch/cluster/service/MasterService.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/FutureUtils.java
  server/src/main/java/org/elasticsearch/gateway/IncrementalClusterStateWriter.java
  server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/elasticsearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableConcurrentIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ThreadPoolsExhaustedIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/AbstractDisruptionTestCase.java
  server/src/test/java/org/elasticsearch/common/settings/SettingTests.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/testFixtures/java/org/elasticsearch/index/translog/TranslogDeletionPolicies.java
  server/src/testFixtures/java/org/elasticsearch/test/disruption/LongGCDisruption.java
Labels: ready-to-merge

#14045 Add `statement_timeout` cluster setting variant
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  docs/config/node.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/main/java/io/crate/metadata/settings/SessionSettings.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#14048 Add link to user survey at the README
  README.rst
Labels: ready-to-merge

#14050 Fix issue with join condition referencing a previous relation
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.3

#14052 RTD: Update to Ubuntu 22 and Python 3.11
  .readthedocs.yml
Labels: ready-to-merge, v/5.3

#13567 Improve documentation and health checks around cluster settings
  app/src/main/dist/config/crate.yml
  docs/admin/system-information.rst
  docs/appendices/release-notes/unreleased.rst
  docs/concepts/clustering.rst
  docs/concepts/storage-consistency.rst
  docs/config/cluster.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/io/crate/expression/reference/sys/check/node/RecoveryAfterNodesSysCheck.java
  server/src/main/java/io/crate/expression/reference/sys/check/node/RecoveryExpectedNodesSysCheck.java
  server/src/test/java/io/crate/expression/reference/sys/check/node/SysNodeChecksTest.java
  server/src/test/java/io/crate/integrationtests/SysNodeCheckerIntegrationTest.java
Labels: ready-to-merge

#13932 Update bundled JDK to 20.0.1+9
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
  server/src/testFixtures/java/org/elasticsearch/test/disruption/IntermittentLongGCDisruption.java
  server/src/testFixtures/java/org/elasticsearch/test/disruption/LongGCDisruption.java
  server/src/testFixtures/java/org/elasticsearch/test/disruption/LongGCDisruptionTests.java
Labels: ready-to-merge

#14060 Improve error msg and docs for `date_bin`.
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/DateBinFunction.java
  server/src/test/java/io/crate/expression/scalar/DateBinFunctionTest.java
Labels: ready-to-merge, v/5.3

#14065 Improve output representation of timestamp subtraction
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/AgeFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/SubtractTimestampScalar.java
  server/src/main/java/io/crate/types/IntervalType.java
  server/src/test/java/io/crate/expression/scalar/TypeInferenceTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/TimestampArithmeticTest.java
Labels: ready-to-merge, v/5.3

#14062 Add assertion in order to verify that there is no holes in positions sequence
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge, v/5.3

#14069 Fix output representation for ts subtraction
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/scalar/AgeFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/SubtractTimestampScalar.java
  server/src/main/java/io/crate/types/IntervalType.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/TimestampArithmeticTest.java
Labels: ready-to-merge, v/5.3

#14072 Fix DROP TABLE IF EXISTS with catalog prefix.
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/test/java/io/crate/analyze/DropTableAnalyzerTest.java
Labels: ready-to-merge, v/5.3

#14078 Always move filter below eval
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReference.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathEval.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/testFixtures/java/io/crate/testing/ProjectionAssert.java
Labels: ready-to-merge, v/5.2, v/5.3

#14074 Handle all columns in position computation check
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge, v/5.3

#14082 Raise nicer error on string -> object casts
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
Labels: ready-to-merge

#14086 revert assertion in 5.3
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge

#14090 Unnest arrays in ANY to number of dimensions required
  docs/appendices/release-notes/unreleased.rst
  docs/general/dql/selects.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/expression/scalar/ArrayUnnestFunction.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
Labels: ready-to-merge

#14095 Replace contains with containsExactly in AnyEqOperatorTest
  server/src/test/java/io/crate/expression/operator/any/AnyEqOperatorTest.java
Labels: ready-to-merge

#14104 Release 5.2.8
  docs/appendices/release-notes/5.2.8.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14106 Reflect release 5.2.8
  docs/appendices/release-notes/5.2.8.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14081 Fix interval comparisons to avoid overflow
  server/src/main/java/io/crate/types/IntervalType.java
  server/src/test/java/io/crate/expression/operator/CmpOperatorTest.java
Labels: ready-to-merge

#14107 Reflect release 5.2.8
  docs/appendices/release-notes/5.2.8.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14112 Add a second node sandbox folder
  .gitignore
  .vscode/launch.json
  sandbox/crate2/config/crate.yml
  sandbox/crate2/config/log4j2.properties
Labels: ready-to-merge

#14109 Apply normalization to INTERVAL literals
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/interval/IntervalParser.java
  server/src/main/java/io/crate/interval/NumericalIntervalParser.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/IntervalAnalysisTest.java
  server/src/test/java/io/crate/expression/scalar/ExtractFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/interval/IntervalParserTest.java
  server/src/test/java/io/crate/types/IntervalTypeTest.java
Labels: ready-to-merge

#14108 Move TableStats into PlannerContext
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/PlannerContext.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/planner/PlannerTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/CollectTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/SelectivityFunctionsCalculationTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#14058 Add support for AVG() on INTERVAL types
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/AggregationImplModule.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/IntervalAverageAggregation.java
  server/src/main/java/io/crate/types/IntervalType.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
Labels: ready-to-merge

#14113 Add some additional trace logging to jobs/tasks/dist-execution
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
Labels: ready-to-merge

#14049 Convert empty arrays inserted dynamically into nulls
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/DocRefResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/executor/transport/task/elasticsearch/DocRefResolverTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge, v/5.3

#14117 Fix broken link to wikipedia CDIR notation
  docs/general/builtins/comparison-operators.rst
  docs/general/ddl/data-types.rst
Labels: ready-to-merge, v/5.3

#14115 docs: Add NOTE that `index off` cannot be used with parted cols
  docs/general/ddl/fulltext-indices.rst
  docs/general/ddl/storage.rst
Labels: ready-to-merge, v/5.3

#14122 Improve performance for Interval comparisons
  server/src/main/java/io/crate/types/IntervalType.java
  server/src/test/java/io/crate/types/IntervalTypeTest.java
Labels: ready-to-merge

#14129 Reorder cols of pg_catalog tables
  server/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgClassTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgConstraintTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgIndexTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgProcTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgRolesTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgTypeTable.java
Labels: ready-to-merge

#14131 Update Lucene to 9.6.0
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge

#14138 Migrate IndexSettingsTests to assertj
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
Labels: ready-to-merge

#14139 Remove dataWithClusterFiles from Environment
  server/src/main/java/org/elasticsearch/env/Environment.java
Labels: ready-to-merge

#14137 Mention unnest behavior in array comparison docs
  docs/general/builtins/array-comparisons.rst
Labels: ready-to-merge

#14084 Remove duplicate positions checker thread in tests
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge

#14141 Fix source columns building in BWC branch
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
Labels: ready-to-merge

#14154 Cleanup code for es-repository-azure
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobContainer.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepository.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageService.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageSettings.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureStorageServiceMock.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureStorageServiceTests.java
Labels: ready-to-merge

#14150 Clean up join test
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge

#14160 Docs: Remove brackets around the `TABLE` clause in `CREATE|RESTORE SNAPSHOT`
  docs/sql/statements/create-snapshot.rst
  docs/sql/statements/restore-snapshot.rst
Labels: ready-to-merge, docs, v/5.3

#14161 Mention support of GEO POINT in column store docs
  docs/general/ddl/storage.rst
Labels: ready-to-merge, docs, v/5.3

#14168 Fix issue with `?` in LIKE/ILIKE pattern
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/operator/LikeOperators.java
  server/src/test/java/io/crate/expression/operator/LikeOperatorTest.java
Labels: ready-to-merge, v/5.3

#14156 Fixed a race condition issue when accessing S3 repositories
  docs/appendices/release-notes/unreleased.rst
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/AwsS3ServiceImplTests.java
Labels: ready-to-merge, v/5.3

#14170 Fix insert into with on conflict column order handling
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.3

#14054 Fix ClassCastException while replicating dynamic long column
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
Labels: ready-to-merge, v/5.3

#14187 Fix cosmetic issue with NOTE box in SHOW statement docs
  docs/sql/statements/show.rst
Labels: ready-to-merge, docs, v/5.3

#14191 Migrate SubQueryPlannerTest to assertj
  server/src/test/java/io/crate/planner/SubQueryPlannerTest.java
Labels: ready-to-merge

#14180 Protect against infinite loops in IterativeOptimizer
  server/src/main/java/io/crate/planner/optimizer/iterative/IterativeOptimizer.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
Labels: ready-to-merge

#14179 Remove swapSide marker from HashJoin
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteNestedLoopJoinToHashJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/SwapHashJoin.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
Labels: ready-to-merge

#14190 Improve error message for default on object cols
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, v/5.3

#14185 Fix Stats calculation for Collect operator
  server/src/main/java/io/crate/planner/optimizer/costs/PlanStats.java
  server/src/test/java/io/crate/planner/operators/CollectTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
Labels: ready-to-merge

#14195 Cleanup code around Mapper
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/MapperTestUtils.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
Labels: ready-to-merge

#14198 Use `estimateSizeForColumns` for estimated left row size in hash joins
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/statistics/Stats.java
Labels: ready-to-merge

#14172 Introduce rule to swap sides of nl-loop
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/SwapNestedLoopJoin.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
Labels: ready-to-merge

#14196 Fix handling of defaults on object child columns
  blackbox/test_docs.py
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/metadata/ColumnIdentTest.java
Labels: ready-to-merge, v/5.3

#14197 Fix: empty partitioned tables not listed in sys.snapshots
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshot.java
  server/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshots.java
  server/src/test/java/io/crate/expression/reference/sys/snapshot/SysSnapshotsTest.java
  server/src/test/java/io/crate/integrationtests/SysSnapshotsTest.java
Labels: ready-to-merge, v/5.3

#14200 Remove numExpectedRows and estimatedRowSize from Collect
  server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MergeFilterAndCollect.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
  server/src/test/java/io/crate/planner/operators/LimitTest.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/matcher/PatternTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MergeFiltersTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoopTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
Labels: ready-to-merge

#14207 Rename Swap-Join Rules to Reorder-Join Rules
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderHashJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderNestedLoopJoin.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#14208 Cleanup code around FunctionToQuery
  server/src/main/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfter.java
  server/src/main/java/io/crate/expression/operator/CIDROperator.java
  server/src/main/java/io/crate/expression/operator/CmpOperator.java
  server/src/main/java/io/crate/expression/operator/LikeOperator.java
  server/src/main/java/io/crate/expression/operator/RegexpMatchCaseInsensitiveOperator.java
  server/src/main/java/io/crate/expression/operator/RegexpMatchOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyRangeOperator.java
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
  server/src/main/java/io/crate/lucene/FunctionToQuery.java
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/main/java/org/elasticsearch/common/network/InetAddresses.java
Labels: ready-to-merge

#14214 Fix ON CONFLICT handling with generated primary key columns
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.3

#14216 Integrate selectivity calculation for Filter operator
  server/src/main/java/io/crate/planner/optimizer/costs/PlanStats.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
Labels: ready-to-merge

#14217 Create visitor only once in PlanStats
  server/src/main/java/io/crate/planner/optimizer/costs/PlanStats.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#14210 tests: Fix flaky test_copy_from_with_fail_fast_with_write_error_[on, off]_handler_node
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
Labels: ready-to-merge, test-failure, v/5.3

#14222 tests: Fix flakly `testQueuedSnapshotsWaitingForShardReady`
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge, test-failure, v/5.3

#14223 tests: Fix flaky `testInsertStringGreaterThanDocValuesLimit`
  server/src/test/java/io/crate/integrationtests/StorageOptionsITest.java
Labels: ready-to-merge, test-failure
