Repository crate/crate, pull requests merged in 2023-04, with the labels that each got.

#13911 Fix resume handling for pgwire protocol level fetch
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/BaseResultReceiver.java
  server/src/main/java/io/crate/action/sql/CollectingResultReceiver.java
  server/src/main/java/io/crate/action/sql/ResultReceiver.java
  server/src/main/java/io/crate/action/sql/RowConsumerToResultReceiver.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  server/src/main/java/io/crate/protocols/postgres/RetryOnFailureResultReceiver.java
  server/src/main/java/io/crate/protocols/postgres/RowCountReceiver.java
  server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java
  server/src/main/java/io/crate/rest/action/RestResultSetReceiver.java
  server/src/main/java/io/crate/rest/action/RestRowCountReceiver.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, v/5.2

#13913 Update jacoco to 0.8.9
  build.gradle
Labels: ready-to-merge

#13916 Allow PostgreSQL clients to describe cursor queries
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
Labels: ready-to-merge, v/5.2

#13914 Make percentage of rules to disable configurable
  server/src/test/java/io/crate/testing/SqlTransportExecutorTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/io/crate/testing/TestExecutionConfig.java
  server/src/testFixtures/java/io/crate/testing/UseRandomizedOptimizerRules.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13915 Migrate PostgresITest to assertj
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge

#13919 Improve message for create repo errors due to location outside path.repo
  server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
  server/src/test/java/io/crate/integrationtests/RepositoryIntegrationTest.java
Labels: ready-to-merge

#13923 Bump version to 5.2.7-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13926 Mark read-only scrollable cursor as supported in sql_features
  server/src/main/resources/sql_features.tsv
Labels: ready-to-merge

#13924 Remove deprecated method from Environment
  server/src/main/java/org/elasticsearch/env/Environment.java
Labels: ready-to-merge

#13929 Bump version to 5.4.0-SNAPSHOT
  .mergify.yml
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/cluster/commands/FixCorruptedMetadataCommandTest.java
Labels: ready-to-merge

#13922 Update netty to 4.1.91
  gradle/version.properties
Labels: ready-to-merge

#13815 Unify shard failure handling in getIterators
  server/src/main/java/io/crate/execution/engine/collect/RemoteCollectorFactory.java
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
Labels: ready-to-merge

#13933 tests: Use Version.CURRENT to assert version created
  server/src/test/java/io/crate/cluster/commands/FixCorruptedMetadataCommandTest.java
Labels: ready-to-merge

#13941 Fix warnings in AstBuilder & Literal
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Literal.java
Labels: ready-to-merge

#13943 followup: Fix resume handling for pgwire protocol level fetch
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/RowConsumerToResultReceiver.java
Labels: bug, ready-to-merge, v/5.2, v/5.3

#13946 Fixed NPE exception when querying with NOT on null object field
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
Labels: bug, ready-to-merge, v/5.2, v/5.3

#13937 Fix parsing error when quoted subscript expressions contain quotes
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
Labels: bug, ready-to-merge, v/5.2, v/5.3

#13420 Upgraded PostgreSQL Wire Protocol to 14
  docs/appendices/release-notes/unreleased.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#13957 Don't wrap queries in object IS NULL in another BooleanQuery
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
Labels: ready-to-merge

#13959 Add new column rngmultitypid to pg_range table
  server/src/main/java/io/crate/metadata/pgcatalog/PgRangeTable.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge

#13958 Randomize optimizer rules in Integration Tests
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/EmptyStringRoutingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SwapTableITest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UnionIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13961 Remove unused `filtered` and shallow methods from Queries
  server/src/main/java/io/crate/expression/operator/CIDROperator.java
  server/src/main/java/io/crate/expression/operator/CmpOperator.java
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyEqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/main/java/io/crate/expression/scalar/geo/DistanceFunction.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/org/elasticsearch/common/lucene/search/MultiPhrasePrefixQuery.java
  server/src/main/java/org/elasticsearch/common/lucene/search/Queries.java
  server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineSearcherTotalHitsMatcher.java
Labels: ready-to-merge

#13962 Make RewriteInsertFromSubQueryToInsertFromValues Rule mandatory
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#13960 Add a `null_or_empty` scalar
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  docs/general/dql/selects.rst
  server/src/main/java/io/crate/expression/scalar/NullOrEmptyFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/test/java/io/crate/expression/scalar/NullOrEmptyFunctionTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge, v/5.2, v/5.3

#13969 Use DataType#compare in array/row comparators
  benchmarks/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/distribution/merge/SortedPagingIteratorBenchmark.java
  server/src/main/java/io/crate/execution/dsl/phases/MergePhase.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/distribution/merge/PagingIterator.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/engine/sort/Comparators.java
  server/src/main/java/io/crate/execution/engine/sort/NullAwareComparator.java
  server/src/main/java/io/crate/execution/engine/sort/OrderingByPosition.java
  server/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/test/java/io/crate/action/sql/CursorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/SortedPagingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/sort/OrderingByPositionTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingLimitAndOffsetProjectorTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingProjectorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
  server/src/test/java/io/crate/integrationtests/JoinGroupByIntegrationTests.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/testFixtures/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
Labels: ready-to-merge

#13972 Fix incorrect assignment of PRIMAY KEY on ADD COLUMN with multiple primary key columns
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge, v/5.2, v/5.3

#13970 Remove raw type from Stats
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/test/java/io/crate/planner/operators/SelectivityFunctionsCalculationTest.java
  server/src/test/java/io/crate/planner/selectivity/SelectivityFunctionsTest.java
Labels: ready-to-merge

#13980 Add statement_timeout session setting
  docs/appendices/release-notes/unreleased.rst
  docs/config/session.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/main/java/io/crate/metadata/settings/SessionSettings.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#13981 Fix linkcheck failures
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#13984 Fix `bin/crate -h`
  app/src/main/dist/bin/crate
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/5.2, v/5.3

#13977 Add test case to verify that it's possible to add a column of array(geo_shape)
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
Labels: ready-to-merge, v/5.3

#13976 Migrate some more tests to assertj
  server/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
Labels: ready-to-merge

#14004 Fix IS NULL on geo shape arrays
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.2, v/5.3

#14007 Ensure that default expression is assigned to ARRAY types
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AnalyzedColumnDefinition.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge, v/5.2, v/5.3

#13985 Migrate OpenCloseTableIntegrationTest to assertj
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
Labels: ready-to-merge

#14012 Handle default expression on Reference serialization
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/test/java/io/crate/metadata/ReferenceTest.java
Labels: ready-to-merge

#14016 Update jacoco to 0.8.10
  build.gradle
Labels: ready-to-merge

#14020 docs: Update example to save crate's pid to a file
  docs/cli-tools.rst
Labels: ready-to-merge, docs, v/5.3

#14021 Relax rule to move filters with object subscript beneath eval
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathFetchOrEval.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/5.2, v/5.3

#13749 Improve `COPY FROM` retry logic
  benchmarks/src/main/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/unreleased.rst
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
Labels: ready-to-merge

#14030 Release 5.2.7
  docs/appendices/release-notes/5.2.7.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14031 Bump version to 5.2.8-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14032 Reflect release 5.2.7
  docs/appendices/release-notes/5.2.7.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14027 Release notes: Switch to AlmaLinux standard OCI image resolving K8s flaw
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge, v/5.3

#14033 Reflect release 5.2.7
  docs/appendices/release-notes/5.2.7.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14035 Release 5.3.1
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.3.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/cluster/commands/FixCorruptedMetadataCommandTest.java
Labels: ready-to-merge

#14037 Reflect release 5.3.1
  docs/appendices/release-notes/5.3.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14038 Bump version to 5.3.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge
