Repository crate/crate, pull requests merged in 2023-02, with the labels that each got.

#13548 Amend doc to reflect logging level for SET SESSION/LOCAL ignored settings
  docs/sql/statements/set.rst
Labels: ready-to-merge, docs

#13549 Change testDynamicNullArrayAndDouble to assert result
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge

#13558 Add factory method to retrieve SubscriptionsMetadata
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/metadata/SubscriptionsMetadata.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
Labels: ready-to-merge

#13568 Replace awaitBusy with assertBusy
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/testFixtures/java/org/elasticsearch/common/util/MockBigArrays.java
  server/src/testFixtures/java/org/elasticsearch/common/util/MockPageCacheRecycler.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#13569 Release 5.1.4
  docs/appendices/release-notes/5.1.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13562 Fix behaviour of `FETCH RELATIVE`
  docs/appendices/release-notes/unreleased.rst
  libs/sql-parser/src/main/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Fetch.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/action/sql/Cursor.java
  server/src/test/java/io/crate/action/sql/CursorTest.java
  server/src/test/java/io/crate/integrationtests/CursorITest.java
Labels: ready-to-merge, v/5.2

#13571 Bump version to 5.1.5-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13575 Reflect release 5.1.4
  docs/appendices/release-notes/5.1.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13574 Reflect release 5.1.4
  docs/appendices/release-notes/5.1.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13528 Allow schema and table names to contain upper case letters
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/create-table.rst
  docs/sql/general/lexical-structure.rst
  libs/sql-parser/src/main/java/io/crate/sql/Identifiers.java
  libs/sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  server/src/main/java/io/crate/expression/symbol/AliasSymbol.java
  server/src/main/java/io/crate/expression/symbol/FetchMarker.java
  server/src/main/java/io/crate/expression/symbol/ScopedSymbol.java
  server/src/main/java/io/crate/expression/symbol/Symbol.java
  server/src/main/java/io/crate/metadata/FunctionName.java
  server/src/main/java/io/crate/metadata/IndexParts.java
  server/src/main/java/io/crate/metadata/RelationName.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/MixedCaseSchemaAndRelationNamesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13579 Release 5.2.1
  docs/appendices/release-notes/5.2.0.rst
  docs/appendices/release-notes/5.2.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13582 Bump version to 5.2.2-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/metadata/bugfix/CorruptedMetadataFixerTest.java
Labels: ready-to-merge

#13583 Reflect release 5.2.1
  docs/appendices/release-notes/5.2.0.rst
  docs/appendices/release-notes/5.2.1.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13588 Improve error when `ORDER BY` or `MIN`/`MAX` on `INTERVAL`
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
Labels: ready-to-merge, v/5.2

#13596 tests: Fix flaky testTimedRamAccountingQueueSink
  server/src/test/java/io/crate/execution/engine/collect/stats/RamAccountingQueueSinkTest.java
Labels: ready-to-merge, v/5.2

#13599 Don't register proxy transport actions for subscriber cluster actions
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/action/ReplayChangesAction.java
  server/src/main/java/io/crate/replication/logical/action/UpdateSubscriptionAction.java
Labels: ready-to-merge

#13600 Inline RestoreClusterStateListener.createAndRegisterListener
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreClusterStateListener.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
Labels: ready-to-merge

#13601 Update subscriptions in MetadataTracker at most once per cluster state change
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#13602 Fix IndexNotFoundException when deleting partitions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropTableAction.java
  server/src/main/java/io/crate/metadata/cluster/DropTableClusterStateTaskExecutor.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/DeleteIndexClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/TransportDeleteIndexAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableConcurrentIntegrationTest.java
Labels: ready-to-merge, v/5.2

#13584 Allow schema and table names to start with '_'
  docs/appendices/release-notes/unreleased.rst
  docs/general/ddl/create-table.rst
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  server/src/main/java/io/crate/metadata/RelationName.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/SchemaAndRelationNamesIntegrationTest.java
Labels: ready-to-merge

#13604 Remove PutMappingClusterStateUpdateRequest
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/TransportPutMappingAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataMappingService.java
Labels: ready-to-merge

#13607 Ensure ActionListener.delegateFailure does not swallow failures
  server/src/main/java/org/elasticsearch/action/ActionListener.java
  server/src/test/java/org/elasticsearch/action/ActionListenerTest.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#13572 Don't remove unknown publications from subscriber state
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#13608 Migrate un-/registerRepository from listener to CompletableFuture
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/delete/TransportDeleteRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/TransportPutRepositoryAction.java
  server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
Labels: ready-to-merge

#13609 Remove UpdateSettingsClusterStateUpdateRequest
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsRequest.java
  server/src/main/java/org/elasticsearch/cluster/ack/IndicesClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
Labels: ready-to-merge

#13610 Remove ShardCoreKeyMap and trim IndicesQueryCache
  server/src/main/java/org/elasticsearch/common/lucene/ShardCoreKeyMap.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/cache/query/DisabledQueryCache.java
  server/src/main/java/org/elasticsearch/index/cache/query/IndexQueryCache.java
  server/src/main/java/org/elasticsearch/index/cache/query/QueryCache.java
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
Labels: ready-to-merge

#13595 Use current subscription data in MetadataTracker cluster state update task
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#13611 Reduce amount of code duplication for table settings updates
  server/src/main/java/io/crate/execution/ddl/tables/TransportAlterTableAction.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
Labels: ready-to-merge

#13614 Always use disabled cache for IndexMetadata verification
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/cache/query/DisabledQueryCache.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#13620 Change pg_type typsend and typreceive values to match PostgreSQL
  docs/appendices/release-notes/unreleased.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/protocols/postgres/types/BitType.java
  server/src/main/java/io/crate/protocols/postgres/types/DateType.java
  server/src/main/java/io/crate/protocols/postgres/types/IntervalType.java
  server/src/main/java/io/crate/protocols/postgres/types/JsonType.java
  server/src/main/java/io/crate/protocols/postgres/types/NumericType.java
  server/src/main/java/io/crate/protocols/postgres/types/PGArray.java
  server/src/main/java/io/crate/protocols/postgres/types/PGType.java
  server/src/main/java/io/crate/protocols/postgres/types/PointType.java
  server/src/main/java/io/crate/protocols/postgres/types/RecordType.java
  server/src/main/java/io/crate/protocols/postgres/types/TimeTZType.java
  server/src/main/java/io/crate/protocols/postgres/types/TimestampType.java
  server/src/main/java/io/crate/protocols/postgres/types/TimestampZType.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge, v/5.2

#13621 Move fix for corrupted metadata to a command
  docs/appendices/release-notes/unreleased.rst
  docs/cli-tools.rst
  server/src/main/java/io/crate/cluster/commands/FixCorruptedMetadataCommand.java
  server/src/main/java/org/elasticsearch/cluster/coordination/NodeToolCli.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/test/java/io/crate/cluster/commands/FixCorruptedMetadataCommandTest.java
  server/src/test/java/io/crate/integrationtests/FixCorruptedMetadataCommandITest.java
Labels: ready-to-merge, v/5.2

#13618 Convert AnalyzeITest to use AssertJ
  server/src/test/java/io/crate/integrationtests/AnalyzeITest.java
Labels: ready-to-merge

#13629 Release 5.2.2
  docs/appendices/release-notes/5.2.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13631 Reflect release 5.2.2
  docs/appendices/release-notes/5.2.2.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13632 docs: Add missing tag for release 5.2.2
  docs/appendices/release-notes/5.2.2.rst
Labels: ready-to-merge, docs

#13633 docs: Add info for working with `git worktree`
  devs/docs/basics.rst
  devs/docs/release.rst
Labels: ready-to-merge, docs, v/5.2

#13627 Add a caution about using `max_num_segments` with low values
  docs/sql/statements/optimize.rst
Labels: ready-to-merge, docs, v/5.2

#13619 Try to reduce test output exception noise
  server/src/main/java/org/elasticsearch/cluster/NodeConnectionsService.java
  server/src/main/java/org/elasticsearch/discovery/HandshakingTransportAddressConnector.java
  server/src/main/java/org/elasticsearch/transport/ClusterConnectionManager.java
Labels: ready-to-merge

#13639 Fix warnings in OrderedLuceneBatchIteratorFactoryTest
  server/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactory.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#13641 Fix testMemorySize on machines with large memory
  server/src/test/java/org/elasticsearch/common/settings/SettingTests.java
Labels: ready-to-merge

#13642 Try fix flaky `test_ensure_lucene_ordered_collector_propagates_kill`
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#13644 Add more ConcurrentSnapshotsIT tests
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13652 Extract AddColumnTask from TransportAddColumnAction
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
Labels: ready-to-merge

#13646 Remove lock from RemoteClusterMultiChunkTransfer
  server/src/main/java/io/crate/replication/logical/repository/RemoteClusterMultiChunkTransfer.java
Labels: ready-to-merge

#13656 tests: Fix flaky testMasterFailOverWithQueuedDeletes
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13655 Add more ConcurrentSnapshotsIT tests
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13657 Fix warnings in ColumnPolicyIntegrationTest / move to assertJ
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
Labels: ready-to-merge

#13663 tests: fix test_validate_sub_columns_while_dropping_udf
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionServiceTest.java
Labels: ready-to-merge, v/5.2

#13665 Add missing retention lease creation
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#13666 Replace assertThrowsMatches with assertSQLError
  plugins/es-analysis-common/src/test/java/io/crate/integrationtests/FulltextAnalyzerResolverTest.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryIntegrationTest.java
  plugins/es-repository-url/src/test/java/org/elasticsearch/repositories/url/URLRepositoryITest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  server/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BlobTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CountStarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateBreakerTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/JobIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/OptimizeTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/QueryThenFetchIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RegexpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RepositoryIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/ShardLimitsIT.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/StaticInformationSchemaQueryTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SwapTableITest.java
  server/src/test/java/io/crate/integrationtests/SysClusterTest.java
  server/src/test/java/io/crate/integrationtests/SysNodesITest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/TableBlocksIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UserManagementIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayIndexStateIT.java
  server/src/test/java/org/elasticsearch/index/IndexServiceTests.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
Labels: ready-to-merge

#13667 Run RemoveRedundantFetchOrEval rule again after column pruning
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
  server/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge

#13670 Update to Admin UI 1.24.2
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/5.2

#13679 Update to Admin UI 1.24.3
  docs/appendices/release-notes/unreleased.rst
  gradle/version.properties
Labels: ready-to-merge, v/5.2

#13672 Ensure left-right relations order in joinPairsByRelations key
  server/src/main/java/io/crate/execution/engine/join/JoinOperations.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge, v/5.2

#13685 Deprecate hamcrest based isPlan assertions
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#13686 tests: Replace isPlan with Asserts.isEqualTo
  server/src/test/java/io/crate/planner/GroupByScalarPlannerTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
  server/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/LimitTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
  server/src/test/java/io/crate/planner/operators/SelectDistinctLogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/WindowAggTest.java
  server/src/test/java/io/crate/planner/optimizer/iterative/IterativeOptimizerTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathWindowAggTest.java
  server/src/testFixtures/java/io/crate/testing/LogicalPlanAssert.java
Labels: ready-to-merge

#13687 tests: Minor assertion improvements
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfterTest.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/org/elasticsearch/cluster/metadata/DiffableStringMapTests.java
  server/src/test/java/org/elasticsearch/transport/TransportServiceDeserializationFailureTests.java
Labels: ready-to-merge

#13690 Fix deprecation warnings in GroupByAggregateTest
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#13645 Close MultiChunkTransfer instance when finished in LogicalReplicationRepository
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/io/crate/replication/logical/repository/RemoteClusterMultiChunkTransfer.java
Labels: ready-to-merge

#13693 Fix warnings in PKLookupOperation
  libs/dex/src/main/java/io/crate/data/CompositeBatchIterator.java
  server/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
Labels: ready-to-merge

#13698 Avoid calls to dependencies in Group References
  server/src/main/java/io/crate/planner/operators/MultiPhase.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReference.java
Labels: ready-to-merge

#13695 Set nullable correctly on columns of index references
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
Labels: ready-to-merge

#13699 Add relation names to Group References
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReference.java
  server/src/main/java/io/crate/planner/optimizer/iterative/Memo.java
  server/src/test/java/io/crate/planner/optimizer/iterative/MemoTest.java
  server/src/test/java/io/crate/planner/optimizer/matcher/PatternTest.java
Labels: ready-to-merge

#13702 Fix warnings in InsertIntoIntegrationTest / migrate to assertj
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge

#13704 Remove pointsOnly and strategyName option for GeoShapeFieldMapper
  docs/general/ddl/data-types.rst
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
Labels: ready-to-merge

#13707 Use seqNo as indicator for skip on replica
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/org/elasticsearch/index/seqno/SequenceNumbers.java
Labels: ready-to-merge

#13703 Migrate PgCatalogITest to assertj
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/testFixtures/java/io/crate/testing/SQLResponseAssert.java
Labels: ready-to-merge

#13705 Adapt javadoc in rules regarding relation names in group references
  server/src/main/java/io/crate/planner/optimizer/Rule.java
Labels: ready-to-merge

#13701 Merge Filter Join Rules together
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathNestedLoop.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerTest.java
Labels: ready-to-merge

#13712 Add fields used in WHERE to toCollect
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  server/src/test/java/io/crate/execution/dsl/projection/builder/SplitPointsTest.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
  server/src/testFixtures/java/io/crate/testing/SymbolAssert.java
Labels: ready-to-merge, v/5.2

#13711 Release 5.2.3
  docs/appendices/release-notes/5.2.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13714 Bump version to 5.2.4-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13715 Reflect release 5.2.3
  docs/appendices/release-notes/5.2.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13717 Migrate PartitionNameTest to assertj / fix warnings
  server/src/test/java/io/crate/metadata/PartitionNameTest.java
Labels: ready-to-merge

#13725 Create GeoReference also for geo shape arrays
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/metadata/GeoReference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/test/java/io/crate/metadata/GeoReferenceTest.java
Labels: ready-to-merge

#13727 Update apache commons codec to 1.15
  gradle/version.properties
  server/src/test/java/io/crate/metadata/PartitionNameTest.java
Labels: ready-to-merge

#13421 Add optimizer rule to push down a Filter beneath a CorrelatedJoin
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathCorrelatedJoin.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge

#13733 Fix null value handling for `x != ANY([...])`
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.2

#13734 Fix concurrent add-column with AddColumnTask; require type match
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
Labels: ready-to-merge

#13723 Migrate ShowIntegrationTest to assertj
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#13739 Migrate FulltextIntegrationTest to assertj / fix warnings
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
Labels: ready-to-merge

#13737 Migrate CastIntegrationTest to assertj / fix warnings
  server/src/test/java/io/crate/integrationtests/CastIntegrationTest.java
Labels: ready-to-merge
