Repository crate/crate, pull requests merged in 2023-10, with the labels that each got.

#14779 Fix undefined label in system-information.rst
  docs/admin/system-information.rst
Labels: ready-to-merge

#14759 Remove unused LocaleUtils
  server/src/main/java/org/elasticsearch/common/util/LocaleUtils.java
Labels: ready-to-merge

#14719 Let UPDATE operations continue on error in case of partial failures
  docs/appendices/release-notes/5.5.0.rst
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge

#14771 Simplify join-graph
  server/src/main/java/io/crate/planner/optimizer/joinorder/JoinGraph.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
Labels: ready-to-merge

#14760 Deduplicate SuppressForbidden annotation
  libs/cli/build.gradle
  libs/cli/src/main/java/org/elasticsearch/cli/Command.java
  libs/cli/src/main/java/org/elasticsearch/cli/SuppressForbidden.java
  libs/cli/src/main/java/org/elasticsearch/cli/Terminal.java
Labels: ready-to-merge

#14782 Update Lucene to 9.8.0
  gradle/version.properties
  server/src/main/java/io/crate/execution/dml/FloatVectorIndexer.java
  server/src/main/java/io/crate/types/FloatVectorType.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/elasticsearch/index/mapper/FloatVectorFieldMapper.java
Labels: ready-to-merge

#14793 Update netty to 4.1.99
  pom.xml
Labels: ready-to-merge

#14783 Update github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-to-merge

#14794 Run *IT classes with surefire
  pom.xml
Labels: ready-to-merge

#14799 Fix sphinx build, avoid use system's sphinx-build
  blackbox/bin/sphinx
Labels: ready-to-merge

#14780 Azure Blob Storage: Support endpoint & secondary endpoint params
  docs/appendices/release-notes/5.5.0.rst
  docs/sql/statements/create-repository.rst
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepository.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageService.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureStorageSettings.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureBlobStoreContainerTests.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureStorageServiceMock.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureStorageServiceTests.java
Labels: ready-to-merge

#14797 Update maven used by wrapper to 3.9.4
  .mvn/wrapper/maven-wrapper.properties
Labels: ready-to-merge

#14802 Add java modules required by jmx_exporter to jlink jdk
  pom.xml
Labels: ready-to-merge

#14804 Fix java path in distribution script
  app/src/main/dist/bin/crate
Labels: ready-to-merge

#14806 Fix issue with privileges bypassed for scalar subselects
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge, v/5.4

#14803 Prefix dropped columns in the mapping
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/metadata/cluster/DDLClusterStateHelpers.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge

#14809 Remove AddColumnResponse, use AcknowledgedResponse instead
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnResponse.java
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnResponseTest.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
Labels: ready-to-merge

#14810 Expose dropped column in pg_attribute table
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/RelationInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgAttributeTable.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge

#14812 Add prefix to unknown columns name in the source
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/execution/dml/ValueIndexer.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#14811 Fix any operators when the args contain nulls
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNotLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyRangeOperator.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.4

#14835 Change (I)LIKE ANY operators signature to allow only string arguments
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/expression/operator/LikeOperators.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/expression/operator/any/AnyLikeOperatorTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
Labels: ready-to-merge, v/5.4

#14831 Generate new identifiers on snapshot of swapped table
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/repositories/IndexMetaDataGenerations.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge, v/5.4

#14830 Don't add ignored column prefix on tables created with CrateDB < 5.5
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#14837 Clarify difference between DataType valueForInsert and sanitizeValue
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/CharacterType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/main/java/io/crate/types/RegprocType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/main/java/io/crate/types/TimeTZType.java
Labels: ready-to-merge

#14840 Support cast from (json) string to object array
  docs/appendices/release-notes/5.5.0.rst
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge

#14844 Update netty to 4.1.100
  pom.xml
Labels: ready-to-merge

#14845 Re-use visitSymbols in AccessControlImpl to ensure all symbols are processed
  server/src/main/java/io/crate/auth/AccessControlImpl.java
Labels: ready-to-merge

#14846 Add a change entry for DROP COLUMN statement support.
  docs/appendices/release-notes/5.5.0.rst
Labels: ready-to-merge

#14842 Simplify Join Type
  libs/sql-parser/src/main/java/io/crate/sql/tree/JoinType.java
Labels: ready-to-merge

#14847 Support `IS NULL` on columns that have column store disabled
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge, v/5.4

#14848 Default maven to use -T1C
  .github/workflows/main.yml
  .mvn/maven.config
  Jenkinsfile
Labels: ready-to-merge

#14851 Update reproduction info to show mvn command
  pom.xml
  server/src/testFixtures/java/org/elasticsearch/test/junit/listeners/ReproduceInfoPrinter.java
Labels: ready-to-merge

#14300 Remove copy_to on upgrade
  server/src/main/java/io/crate/metadata/upgrade/MetadataIndexUpgrader.java
  server/src/test/java/io/crate/metadata/upgrade/MappingConstants.java
Labels: ready-to-merge

#14868 Release 5.2.10
  docs/appendices/release-notes/5.2.10.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14871 Reflect release 5.2.10
  docs/appendices/release-notes/5.2.10.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14872 Reflect release 5.2.10
  docs/appendices/release-notes/5.2.10.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14870 Bump version to 5.2.11-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14874 Release 5.3.7
  docs/appendices/release-notes/5.3.7.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14876 Bump version to 5.3.8-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14877 Reflect release 5.3.7
  docs/appendices/release-notes/5.3.7.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14859 Add constant join conditions to Join-graph
  server/src/main/java/io/crate/planner/optimizer/joinorder/JoinGraph.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
Labels: ready-to-merge

#14880 Release 5.4.4
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14881 Bump version to 5.4.5-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14883 Fix ident of some entries in 5.4.4 fixes list.
  docs/appendices/release-notes/5.4.4.rst
Labels: ready-to-merge

#14882 Reflect release 5.4.5
  docs/appendices/release-notes/5.4.4.rst
  docs/appendices/release-notes/5.4.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14843 Update bundled JDK to 21+35
  .github/workflows/main.yml
  pom.xml
Labels: ready-to-merge

#14884 tests: Fix flaky create_azure_snapshot_and_restore_with_secondary_endpoint
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
Labels: ready-to-merge

#14888 Remove unused code
  server/src/main/java/io/crate/execution/dml/upsert/CheckConstraints.java
  server/src/main/java/io/crate/execution/dml/upsert/FromSourceRefResolver.java
  server/src/main/java/io/crate/execution/dml/upsert/GeneratedColumns.java
  server/src/test/java/io/crate/execution/dml/upsert/CheckConstraintsTest.java
  server/src/test/java/io/crate/execution/dml/upsert/GeneratedColumnsTest.java
Labels: ready-to-merge

#14889 Rename/rework createMappingForDroppedCols/createMappingToRemove
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
Labels: ready-to-merge

#14890 Use Indexer/MappingUtil in AggregationTestCase
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#14892 Remove throttle assertions from testRerouteRecovery
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#14878 Fix UNION to recognize ambiguous columns
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/analyze/relations/UnionSelect.java
  server/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
Labels: bug, ready-to-merge, v/5.4

#14893 Update jacoco, junit5, log4j
  pom.xml
Labels: ready-to-merge

#14885 Cleanup unused classes, methods, method args
  libs/guice/src/main/java/org/elasticsearch/common/inject/internal/MoreTypes.java
  libs/guice/src/main/java/org/elasticsearch/common/inject/util/Modules.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/SqlParser.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/breaker/TypeGuessEstimateRowSize.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/collect/RemoteCollectorFactory.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/main/java/io/crate/metadata/settings/CrateSettings.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteGroupByKeysLimitToLimitDistinct.java
  server/src/main/java/io/crate/protocols/postgres/ClientInterrupted.java
  server/src/main/java/io/crate/protocols/postgres/ClientMessages.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/elasticsearch/common/geo/SpatialStrategy.java
  server/src/main/java/org/elasticsearch/common/util/DoubleArray.java
  server/src/main/java/org/elasticsearch/common/util/FloatArray.java
  server/src/main/java/org/elasticsearch/common/util/LongArray.java
  server/src/main/java/org/elasticsearch/index/analysis/AnalysisRegistry.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/transport/TransportSettings.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjectionTest.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/KeywordFieldMapperTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogHeaderTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/testFixtures/java/io/crate/testing/ProjectionMatchers.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#14894 Hide dropped columns in the information_schema.columns table
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge

#14897 Replace copy(Reader, Writer) with Streams.readFully
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureHttpHandler.java
  server/src/main/java/org/elasticsearch/common/io/Streams.java
Labels: ready-to-merge

#14895 Inline ForEach in GeoJSONUtils
  libs/shared/src/main/java/io/crate/common/collections/ForEach.java
  libs/shared/src/test/java/io/crate/common/collections/ForEachTest.java
  server/src/main/java/io/crate/geo/GeoJSONUtils.java
Labels: ready-to-merge

#14901 Set base port used in tests based on surefire forkNumber
  pom.xml
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/test/ESTestCaseTests.java
Labels: ready-to-merge

#14904 Replace expectThrows with assertThatThrownBy
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ElectionSchedulerFactoryTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityCheckerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NoMasterBlockServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PreVoteCollectorTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ReconfiguratorTests.java
  server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodeRoleTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocateUnassignedDecisionTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
  server/src/test/java/org/elasticsearch/common/bytes/AbstractBytesReferenceTestCase.java
  server/src/test/java/org/elasticsearch/common/io/stream/BytesStreamsTests.java
  server/src/test/java/org/elasticsearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/elasticsearch/common/settings/SecureStringTests.java
  server/src/test/java/org/elasticsearch/common/settings/SettingTests.java
  server/src/test/java/org/elasticsearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/elasticsearch/common/settings/SettingsTests.java
  server/src/test/java/org/elasticsearch/common/util/CancellableThreadsTests.java
  server/src/test/java/org/elasticsearch/common/util/concurrent/AbstractAsyncTaskTests.java
  server/src/test/java/org/elasticsearch/common/util/concurrent/AsyncIOProcessorTests.java
  server/src/test/java/org/elasticsearch/env/NodeMetadataTests.java
  server/src/test/java/org/elasticsearch/env/NodeRepurposeCommandTests.java
  server/src/test/java/org/elasticsearch/env/OverrideNodeVersionCommandTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
  server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/elasticsearch/index/engine/CombinedDeletionPolicyTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/LuceneChangesSnapshotTests.java
  server/src/test/java/org/elasticsearch/index/engine/NoOpEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/elasticsearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseTests.java
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeasesTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardRetentionLeaseTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/store/StoreTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogHeaderTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/IndexingMemoryControllerTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoverySourceServiceTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  server/src/test/java/org/elasticsearch/transport/InboundDecoderTests.java
  server/src/test/java/org/elasticsearch/transport/InboundPipelineTests.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTest.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTests.java
  server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java
  server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
  server/src/testFixtures/java/org/elasticsearch/repositories/ESBlobStoreContainerTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/hamcrest/ElasticsearchAssertionsTests.java
  server/src/testFixtures/java/org/elasticsearch/test/test/ESTestCaseTests.java
  server/src/testFixtures/java/org/elasticsearch/test/test/LoggingListenerTests.java
Labels: ready-to-merge

#14887 Fix Lucene query building for array types
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/BooleanType.java
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/EqQuery.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/main/java/io/crate/types/FloatVectorType.java
  server/src/main/java/io/crate/types/IntEqQuery.java
  server/src/main/java/io/crate/types/IpType.java
  server/src/main/java/io/crate/types/LongEqQuery.java
  server/src/main/java/io/crate/types/StorageSupport.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/lucene/BitStringEqQueryTest.java
  server/src/test/java/io/crate/lucene/DoubleEqQueryTest.java
  server/src/test/java/io/crate/lucene/FloatEqQueryTest.java
  server/src/test/java/io/crate/lucene/IntEqQueryTest.java
  server/src/test/java/io/crate/lucene/IpEqQueryTest.java
  server/src/test/java/io/crate/lucene/StringEqQueryTest.java
Labels: ready-to-merge

#14910 Show schema in pg_namespace if user has permissions on any contained table
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge, v/5.4

#14912 Generate crate-build.properties on build and update Build/version info
  app/pom.xml
  pom.xml
  server/src/main/java/org/elasticsearch/Build.java
Labels: ready-to-merge

#14919 Skip forbiddenApis when no code is changed
  .github/workflows/skip.yml
Labels: ready-to-merge

#14921 Avoid creation of dependency-reduced-pom.xml in benchmarks
  benchmarks/pom.xml
Labels: ready-to-merge

#14923 Clarify query breakdown for empty partitioned tables
  docs/sql/statements/explain.rst
Labels: ready-to-merge, v/5.4

#14917 Let OS choose port in AzureSnapshotIntegrationTest
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
Labels: ready-to-merge

#14928 tests: Try improve duration of `dynamic_mapping_updates` with `copy from`
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge

#14929 Fix SourceParser to ignore nested dropped columns
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge

#14900 Fix docs: regarding max_clause_count
  docs/config/node.rst
  docs/general/dql/selects.rst
Labels: ready-to-merge

#14932 Introduce maven profile to run server tests
  devs/docs/tests.rst
  pom.xml
  server/pom.xml
Labels: ready-to-merge

#14941 Remove suppressions file config from checkstyle.xml
  checkstyle.xml
Labels: ready-to-merge

#14946 Fix handling of joins with filter containing correlated joins
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
Labels: ready-to-merge, v/5.4

#14947 Update to Admin UI 1.24.5
  app/pom.xml
Labels: ready-to-merge

#14950 Fix warnings and minor code cleanup for sql-parser
  .idea/inspectionProfiles/Project_Default.xml
  libs/sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/Identifiers.java
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/CaseInsensitiveStream.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/SqlParser.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/SqlParserOptions.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AlterTableReroute.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/BeginStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/BitString.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CheckColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CheckConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CommitStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateTable.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DeallocateStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/FunctionArgument.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/IntervalLiteral.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/JoinUsing.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PartitionedBy.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrivilegeStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PromoteReplica.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/QualifiedName.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/RerouteOption.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/SubscriptExpression.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/TrimMode.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/TryCast.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Values.java
Labels: ready-to-merge

#14951 Exclude checkerframework from caffeine dependency
  server/pom.xml
Labels: ready-to-merge

#14949 Add empty pg_catalog.pg_event_trigger table
  .vale.ini
  docs/appendices/release-notes/5.5.0.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgEventTrigger.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#14945 Remove waitForMappingUpdateOnAll
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#14954 test: change test name to match what it really does
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
Labels: ready-to-merge

#14908 Add missing fqn -> storageIdent conversion
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#14958 Restrict itest and blackbox tests to x64
  Jenkinsfile
Labels: ready-to-merge, v/5.4

#14956 Don't ignore index properties for columns of geo shape array
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
Labels: ready-to-merge

#14960 Don't ignore index properties for columns of geo shape array
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
Labels: ready-to-merge

#14955 Fix handling of new query while same portal is suspended
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/action/sql/RowConsumerToResultReceiver.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge, v/5.4

#14963 docs: Clarify `blocks.read_only_allow_delete`
  docs/config/cluster.rst
  docs/sql/statements/create-table.rst
Labels: ready-to-merge, docs, v/5.4

#14816 Fix UNION's pruning logic when outputs contain duplicates
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
Labels: ready-to-merge, v/5.4

#14967 Release 5.4.5
  docs/appendices/release-notes/5.4.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14968 Bump version to 5.4.6-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14969 Reflect release 5.4.5
  docs/appendices/release-notes/5.4.5.rst
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14970 tests: Remove excess assertj's assertThat imports
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/analyze/AlterTableDropCheckConstraintAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SetAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/integrationtests/CastIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/JoinGroupByIntegrationTests.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/integrationtests/NodeStatsTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/disruption/routing/PrimaryAllocationIT.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
  server/src/test/java/io/crate/planner/operators/FetchRewriteTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MergeFiltersTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoinTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
  server/src/test/java/org/elasticsearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/test/java/org/elasticsearch/cluster/metadata/DiffableStringMapTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DecisionsImpactOnClusterHealthTests.java
  server/src/test/java/org/elasticsearch/common/compress/DeflateCompressTests.java
  server/src/test/java/org/elasticsearch/common/compress/DeflateCompressedXContentTests.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/test/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java
  server/src/test/java/org/elasticsearch/index/snapshots/blobstore/SlicedInputStreamTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/test/java/org/elasticsearch/transport/CompressibleBytesOutputStreamTests.java
  server/src/test/java/org/elasticsearch/transport/TransportServiceDeserializationFailureTests.java
Labels: ready-to-merge

#14974 Enable DROP COLUMN at sql feature (F033) resource file
  server/src/main/resources/sql_features.tsv
Labels: ready-to-merge

#14975 Release 5.5.0
  docs/appendices/release-notes/5.5.0.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14977 Fix logical-replication subscription version test
  server/src/test/java/io/crate/replication/logical/action/TransportCreateSubscriptionActionTest.java
Labels: ready-to-merge

#14978 Fix logical-replication subscription version test (backport #14977)
  server/src/test/java/io/crate/replication/logical/action/TransportCreateSubscriptionActionTest.java
Labels: ready-to-merge

#14976 Bump version to 5.5.1-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.1.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14981 Fix rendering of 5.5.0 release notes
  docs/appendices/release-notes/5.5.0.rst
Labels: ready-to-merge, docs, v/5.5

#14980 tests: Migrate to assertj
  server/src/main/java/io/crate/analyze/AnalyzedCreateFunction.java
  server/src/test/java/io/crate/BlobHandlerTest.java
  server/src/test/java/io/crate/DigestBlobTests.java
  server/src/test/java/io/crate/SerializationTests.java
  server/src/test/java/io/crate/analyze/CreateFunctionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DataTypeAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DecommissionNodeAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DropFunctionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DropViewAnalyzerTest.java
  server/src/test/java/io/crate/analyze/IdTest.java
  server/src/test/java/io/crate/analyze/IsWriteOperationTest.java
  server/src/test/java/io/crate/analyze/NumberOfReplicasTest.java
  server/src/test/java/io/crate/analyze/NumberOfShardsTest.java
  server/src/test/java/io/crate/analyze/OrderByTest.java
  server/src/test/java/io/crate/analyze/PartitionPropertiesAnalyzerTest.java
  server/src/test/java/io/crate/analyze/QuerySpecTest.java
  server/src/test/java/io/crate/analyze/ResetAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UserDDLAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
  server/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  server/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/auth/user/UserPrivilegesTest.java
  server/src/test/java/io/crate/blob/BlobCoordinatorTest.java
  server/src/test/java/io/crate/blob/DeleteBlobRequestTest.java
  server/src/test/java/io/crate/blob/DeleteBlobResponseTest.java
  server/src/test/java/io/crate/blob/v2/BlobIndexTest.java
  server/src/test/java/io/crate/blob/v2/BlobIndicesServiceTest.java
  server/src/test/java/io/crate/breaker/CrateCircuitBreakerServiceTest.java
  server/src/test/java/io/crate/exceptions/MultiExceptionTest.java
  server/src/test/java/io/crate/exceptions/SQLExceptionsTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/types/BitStringTypeTest.java
  server/src/test/java/io/crate/types/ByteTypeTest.java
  server/src/test/java/io/crate/types/CharacterTypeTest.java
  server/src/test/java/io/crate/types/DoubleTypeTest.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
  server/src/test/java/io/crate/types/IntegerTypeTest.java
  server/src/test/java/io/crate/types/IpTypeTest.java
  server/src/test/java/io/crate/types/JsonTypeTest.java
  server/src/test/java/io/crate/types/LongTypeTest.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/test/java/io/crate/types/RegclassTypeTest.java
  server/src/test/java/io/crate/types/RegprocTypeTest.java
  server/src/test/java/io/crate/types/RowTypeTest.java
  server/src/test/java/io/crate/udc/ping/PingTaskTest.java
  server/src/test/java/io/crate/user/PrivilegesRequestTest.java
  server/src/test/java/io/crate/user/PrivilegesResponseTest.java
  server/src/test/java/io/crate/user/TransportPrivilegesActionTest.java
  server/src/test/java/io/crate/user/TransportUserActionTest.java
  server/src/test/java/io/crate/user/UserActionsTest.java
  server/src/test/java/io/crate/user/metadata/CustomMetadataTest.java
  server/src/test/java/io/crate/user/metadata/PrivilegesMetadataUpgraderTest.java
  server/src/test/java/io/crate/user/metadata/SecureHashTest.java
  server/src/test/java/io/crate/user/metadata/UserDefinitions.java
  server/src/test/java/io/crate/user/metadata/UsersMetadataTest.java
  server/src/test/java/io/crate/user/metadata/UsersPrivilegesMetadataTest.java
Labels: ready-to-merge, v/5.5

#14953 Add empty pg_catalog.pg_depend table
  docs/appendices/release-notes/5.6.0.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgDepend.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#14957 Update bundled JDK to 21.0.1+12
  pom.xml
Labels: ready-to-merge, v/5.5

#14940 Null column constraint
  docs/appendices/release-notes/5.6.0.rst
  docs/general/ddl/constraints.rst
  docs/sql/general/constraints.rst
  docs/sql/statements/alter-table.rst
  docs/sql/statements/create-table.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/NullColumnConstraint.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge

#14988 Make shard creation async/non-blocking on locked shards
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/ShardLockIT.java
Labels: ready-to-merge

#14199 Use runtime information to calculate block size in hash joins
  benchmarks/src/main/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/sort/SortingLimitAndOffsetCollectorBenchmark.java
  libs/dex/src/main/java/io/crate/data/breaker/RowAccounting.java
  libs/dex/src/main/java/io/crate/data/join/CrossJoinBlockNLBatchIterator.java
  libs/dex/src/test/java/io/crate/data/join/CrossJoinBlockNLBatchIteratorTest.java
  server/src/main/java/io/crate/breaker/RowAccountingWithEstimators.java
  server/src/main/java/io/crate/breaker/RowCellsAccountingWithEstimators.java
  server/src/main/java/io/crate/execution/engine/join/HashInnerJoinBatchIterator.java
  server/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  server/src/main/java/io/crate/execution/engine/join/NestedLoopOperation.java
  server/src/main/java/io/crate/execution/engine/join/RamBlockSizeCalculator.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorBehaviouralTest.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorMemoryTest.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/join/RamBlockSizeCalculatorTest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/testFixtures/java/io/crate/execution/engine/sort/IgnoreRowCellsAccounting.java
  server/src/testFixtures/java/io/crate/execution/engine/window/IgnoreRowAccounting.java
Labels: ready-to-merge

#14992 Replace expectedException with assertThatThrownBy in CopyAnalyzerTest
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
Labels: ready-to-merge

#14995 Revert "Make shard creation async/non-blocking on locked shards"
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/ShardLockIT.java
Labels: ready-to-merge

#14994 Fix deprecation warnings in ResizeShardsITest
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
Labels: ready-to-merge

#14996 Port withTempIndexService from ES
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
Labels: ready-to-merge
