Repository crate/crate, pull requests merged in 2023-11, with the labels that each got.

#14991 Fix issue when attempting to DROP col with a CHECK constraint
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropConstraintAction.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, v/5.5

#15009 Add jcmd to bundled JDK
  docs/appendices/release-notes/5.5.1.rst
  pom.xml
Labels: v/5.5

#15011 Remove CodeQL GHA workflow
  .github/workflows/codeql-analysis.yml
Labels: ready-to-merge

#14999 Support named PK constraints
  .github/styles/Vocab/CrateDB/accept.txt
  docs/appendices/release-notes/5.6.0.rst
  docs/sql/general/constraints.rst
  docs/sql/statements/create-table.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrimaryKeyColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrimaryKeyConstraint.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableAddColumn.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateTable.java
  server/src/main/java/io/crate/analyze/BoundCreateTable.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/RelationInfo.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
  server/src/test/java/io/crate/execution/ddl/tables/CreateTableRequestTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#15015 Remove map functionality from FutureActionListener
  server/src/main/java/io/crate/action/FutureActionListener.java
  server/src/main/java/io/crate/execution/engine/fetch/TransportFetchOperation.java
  server/src/main/java/io/crate/execution/engine/profile/TransportCollectProfileOperation.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/ShardReplicationChangesTracker.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/main/java/org/elasticsearch/action/support/TransportAction.java
  server/src/main/java/org/elasticsearch/common/network/CloseableChannel.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryRequestTracker.java
  server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/transport/SniffRemoteClient.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/RemoteCollectorTest.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  server/src/test/java/io/crate/execution/engine/distribution/TransportDistributedResultActionTest.java
  server/src/test/java/io/crate/execution/jobs/transport/NodeDisconnectJobMonitorServiceTest.java
  server/src/test/java/io/crate/planner/node/management/KillPlanTest.java
  server/src/test/java/io/crate/replication/logical/action/TransportCreateSubscriptionActionTest.java
  server/src/test/java/org/elasticsearch/action/ActionListenerTest.java
  server/src/test/java/org/elasticsearch/action/support/RetryableActionTests.java
  server/src/test/java/org/elasticsearch/action/support/replication/PendingReplicationActionsTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoveryRequestTrackerTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  server/src/test/java/org/elasticsearch/transport/TransportHandshakerTests.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/protocols/postgres/MockPgClient.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/org/elasticsearch/common/util/concurrent/TestFutureUtils.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
  server/src/testFixtures/java/org/elasticsearch/repositories/blobstore/BlobStoreTestUtil.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: ready-to-merge

#15017 Update maven and surefire plugin
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
Labels: ready-to-merge

#14984 Add parser support for CREATE ROLE statement
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateRole.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/test/java/io/crate/expression/tablefunctions/PgGetKeywordsFunctionTest.java
Labels: ready-to-merge

#15021 Test: add test_named_primary_key_constraint_names_are_visible()
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge

#15019 Merge UpdateTask and BatchedTask
  server/src/main/java/org/elasticsearch/cluster/service/ClusterService.java
  server/src/main/java/org/elasticsearch/cluster/service/MasterService.java
  server/src/main/java/org/elasticsearch/cluster/service/TaskBatcher.java
Labels: ready-to-merge

#15020 Fix docs and failure reproduction info for test method filtering
  devs/docs/tests.rst
  server/src/testFixtures/java/org/elasticsearch/test/junit/listeners/ReproduceInfoPrinter.java
Labels: ready-to-merge, v/5.5

#15032 Remove unused table size from HashJoinPhase
  server/src/main/java/io/crate/execution/dsl/phases/HashJoinPhase.java
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/test/java/io/crate/planner/node/dql/JoinPhaseTest.java
Labels: ready-to-merge

#15034 Fix a couple of doc issues
  docs/appendices/release-notes/4.8.0.rst
  docs/config/session.rst
Labels: ready-to-merge, v/4.8, v/5.3, v/5.4, v/5.5

#15033 Add support for ALTER & DROP ROLE
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AlterRole.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropRole.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/UserAnalyzer.java
Labels: ready-to-merge

#15027 Categorize columns in DocTableInfo constructor instead of outside
  server/src/main/java/io/crate/metadata/IndexReference.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#15045 Remove references collecting side effect from TableReferenceResolver
  server/src/main/java/io/crate/analyze/expressions/TableReferenceResolver.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
Labels: ready-to-merge

#15041 Unify Parser code for CREATE ROLE and CREATE USER
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateRole.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateUser.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/AnalyzedUser.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/UserAnalyzer.java
  server/src/test/java/io/crate/analyze/UserDDLAnalyzerTest.java
Labels: ready-to-merge

#15048 docs: Update syntax for CREATE USER
  docs/sql/statements/create-user.rst
Labels: ready-to-merge

#15047 Set references of GeneratedReference in generatedExpression setter
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/test/java/io/crate/metadata/GeneratedReferenceTest.java
Labels: ready-to-merge

#15046 Remove DocIndexMetadata dependency from PartitionInfos
  server/src/main/java/io/crate/metadata/PartitionInfos.java
Labels: ready-to-merge

#15028 Remove DocIndexMetadata; build DocTableInfo in Factory
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropConstraintAction.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/DDLClusterStateHelpers.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/metadata/upgrade/IndexTemplateUpgrader.java
  server/src/main/java/io/crate/replication/logical/metadata/PublicationsMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataMappingService.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoFactoryTest.java
Labels: ready-to-merge

#15030 Fix hash symbol generation for hash-joins with more than two relations
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/HashJoinTest.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
Labels: ready-to-merge, v/5.4, v/5.5

#15049 Make generated expression not-nullable in GeneratedReference
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/test/java/io/crate/metadata/GeneratedReferenceTest.java
Labels: ready-to-merge

#15056 Remove columnName from CheckConstraint
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CheckConstraint.java
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/MetadataToASTNodeResolver.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
Labels: ready-to-merge

#15051 Fix filter push-down in nested-joins
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoinTest.java
Labels: ready-to-merge, v/5.5

#15065 Infer not-null columns from references in DocTableInfo
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#15069 Drop support for UsersMetadata v1
  server/src/main/java/io/crate/user/metadata/UsersMetadata.java
  server/src/test/java/io/crate/user/metadata/UsersMetadataTest.java
Labels: ready-to-merge

#15067 Set hasAutoGeneratedPrimaryKey in DocTableInfo ctor
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#15063 Reject empty string as a name for field mapper
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/elasticsearch/index/mapper/BitStringFieldMapperTest.java
Labels: bug, ready-to-merge, v/5.5

#15070 More DocTableInfo tweaks
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#15074 Fix ``NOT AND`` Expression for three-valued logic
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.4, v/5.5

#15086 Add OptimizerTracer to Optimizer Context
  server/src/main/java/io/crate/planner/optimizer/iterative/IterativeOptimizer.java
Labels: ready-to-merge

#15090 Avoid unnecessary extraction of the logical plan from the memo
  server/src/main/java/io/crate/planner/node/management/VerboseOptimizerTracer.java
  server/src/main/java/io/crate/planner/optimizer/iterative/IterativeOptimizer.java
  server/src/main/java/io/crate/planner/optimizer/tracer/LoggingOptimizerTracer.java
  server/src/main/java/io/crate/planner/optimizer/tracer/OptimizerTracer.java
Labels: ready-to-merge

#15094 Raise an error if using table functions in generated or default expressions
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.4, v/5.5

#15095 Don't stop resolving indices after first found index
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/snapshots/RestoreServiceTest.java
Labels: ready-to-merge

#15091 Update to Admin UI 1.24.6
  app/pom.xml
Labels: ready-to-merge

#15098 Fix flaky test_doc_values_write_and_read_roundtrip_inclusive_doc_mapper_parse
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge

#15031 Add support for renaming tables on restoring
  docs/appendices/release-notes/5.6.0.rst
  docs/sql/statements/restore-snapshot.rst
  server/src/main/java/io/crate/analyze/SnapshotSettings.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/analyze/SnapshotRestoreAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#15055 Change drop column to operate on DocTable, then serialize to mapping
  libs/sql-parser/src/main/java/io/crate/sql/tree/CheckConstraint.java
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/BoundCreateTable.java
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/GeoReference.java
  server/src/main/java/io/crate/metadata/IndexReference.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge

#15100 Fix INSERT INTO .. ON CONFLICT handling with generated primary keys
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/analyze/Id.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.4, v/5.5

#15110 Generate IndexReference for columns with analyzer in DocTableInfoFactory
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
Labels: ready-to-merge

#15104 Fix three-valued-logic for NOT-Predicate
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/main/java/io/crate/expression/scalar/ArrayAppendFunction.java
  server/src/main/java/io/crate/expression/scalar/ArrayCatFunction.java
  server/src/main/java/io/crate/expression/scalar/ArrayUniqueFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.4, v/5.5

#15108 Don't expose indices with non-active primary shards in publications
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/metadata/RelationMetadata.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#15123 Fix typo in changelog
  docs/appendices/release-notes/5.4.6.rst
  docs/appendices/release-notes/5.5.1.rst
Labels: ready-to-merge, v/5.4, v/5.5

#15126 Release 5.5.1
  docs/appendices/release-notes/5.5.1.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15127 Release 5.4.6
  docs/appendices/release-notes/5.4.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15085 Allow pushdown of filter beneath a view over multiple join
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoinTest.java
Labels: ready-to-merge

#15129 Bump to 5.5.2 snapshot
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge
