Repository crate/crate, pull requests merged in 2023-09, with the labels that each got.

#14638 Documentation: Fix markup of a few bullet lists
  docs/config/node.rst
  docs/general/builtins/aggregation.rst
  docs/general/builtins/table-functions.rst
  docs/general/ddl/create-table.rst
  docs/general/ddl/fulltext-indices.rst
  docs/general/dql/geo.rst
  docs/general/dql/joins.rst
Labels: ready-to-merge, v/5.4

#14631 Ensure correct order of hash symbols used in HashJoin plans
  docs/appendices/release-notes/5.4.3.rst
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/5.4

#14642 Improve optimizer logging
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/main/java/io/crate/planner/optimizer/Optimizer.java
  server/src/main/java/io/crate/planner/optimizer/Rule.java
  server/src/main/java/io/crate/planner/optimizer/iterative/IterativeOptimizer.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#14639 Remove top-most-left-relation from NestedLoop Join
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/main/java/io/crate/planner/operators/CorrelatedJoin.java
  server/src/main/java/io/crate/planner/operators/Count.java
  server/src/main/java/io/crate/planner/operators/ForwardingLogicalPlan.java
  server/src/main/java/io/crate/planner/operators/Get.java
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/Insert.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlan.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/operators/Rename.java
  server/src/main/java/io/crate/planner/operators/TableFunction.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReference.java
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathCorrelatedJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderNestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteNestedLoopJoinToHashJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/iterative/MemoTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoopTest.java
Labels: ready-to-merge

#14650 Remove unused method
  server/src/main/java/io/crate/expression/reference/Doc.java
Labels: ready-to-merge

#14655 Adjust 5.4 known issues in release notes
  docs/appendices/release-notes/5.4.0.rst
  docs/appendices/release-notes/5.4.1.rst
  docs/appendices/release-notes/5.4.2.rst
Labels: ready-to-merge, v/5.4

#14657 Release 5.4.3
  docs/appendices/release-notes/5.4.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14660 Don't use a symlink path for selecting current release notes
  app/build.gradle
Labels: ready-to-merge, v/5.4

#14663 Remove unused FromRowWithSubscript
  server/src/main/java/io/crate/expression/ValueExtractors.java
Labels: ready-to-merge

#14654 Force validation for COPY FROM
  docs/appendices/release-notes/5.5.0.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/analyze/AnalyzedCopyFrom.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/RawInsertSource.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dsl/projection/SourceIndexWriterProjection.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/node/dml/UpdateById.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/dsl/projection/SourceIndexWriterProjectionSerializationTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/IndexWriterProjectorUnitTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
Labels: ready-to-merge

#14672 Update netty to 4.1.97
  gradle/version.properties
Labels: ready-to-merge

#14649 Move filter beneath nested joins
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoinTest.java
Labels: ready-to-merge

#14674 Rename BatchIterators.partition -> chunks
  libs/dex/src/main/java/io/crate/data/BatchIterators.java
  libs/dex/src/test/java/io/crate/data/BatchIteratorsTest.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
Labels: ready-to-merge

#14673 Add an annotation to start up a new cluster for a test case
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/testFixtures/java/io/crate/testing/UseNewCluster.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#14675 Replace regex based system column validation with manual loop
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/test/java/io/crate/metadata/ColumnIdentTest.java
Labels: ready-to-merge

#14682 Remove duplicate getter from RoutingTable
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/elasticsearch/cluster/routing/RoutingTable.java
Labels: ready-to-merge

#14679 Inline some methods in Strings
  server/src/main/java/org/elasticsearch/common/Strings.java
Labels: ready-to-merge

#14683 Replace legacyInsert with RawIndexer
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/upsert/InsertSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/ReturnValueGen.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/ValidatedRawInsertSource.java
  server/src/test/java/io/crate/execution/dml/upsert/ReturnValueGenTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/ValidatedRawInsertSourceTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge

#14689 Remove deprecated getRepositoryData() variant
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/RestoreOnlyRepository.java
  server/src/testFixtures/java/org/elasticsearch/repositories/ESBlobStoreTestCase.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: ready-to-merge

#14692 Replace ListenableFuture with CompletableFuture
  server/src/main/java/org/elasticsearch/action/StepListener.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/ListenableFuture.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryRequestTracker.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/elasticsearch/transport/ClusterConnectionManager.java
Labels: ready-to-merge

#14695 Fix uri comparsion on macOS at FileReadingCollectorTest
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
Labels: ready-to-merge

#14697 Use SourceParser on primary key lookups
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  server/src/main/java/io/crate/execution/jobs/PKLookupTask.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#14694 Make liberal use of newlines in RepositoryData/SnapshotService
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotId.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#14702 Fix COPY FROM into a table having non-deterministic generated columns to have constant values on primary and replica
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#14704 tests: Fix FileReadingCollectorTest
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
Labels: ready-to-merge

#14705 Use Symbols.containsColumn in SourceParser.register
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
Labels: ready-to-merge

#14709 Convert RepositoryDataTests to assertj
  server/src/test/java/org/elasticsearch/repositories/RepositoryDataTests.java
Labels: ready-to-merge

#14668 Fix SourceLookUp for nested access to ignored objects
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceLookup.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceLookupTest.java
Labels: bug, ready-to-merge, v/5.4

#14710 Remove some unused logic in around GetSnapshotAction
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/GetSnapshotsRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
  server/src/main/java/org/elasticsearch/repositories/IndexId.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/FileRestoreContext.java
Labels: ready-to-merge

#14715 Remove useless maybeInvertPair method
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
Labels: ready-to-merge

#14717 🧹 Remove useless new instances of the CollectorContext
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
Labels: ready-to-merge

#14724 tests: Migrate various itests to assertj
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableRerouteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/AnyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ArrayMapperITest.java
  server/src/test/java/io/crate/integrationtests/ArraySubQueryIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BlobHttpIntegrationTest.java
Labels: ready-to-merge

#14725 Fix NPE when inserting null for a float_vector column
  server/src/main/java/io/crate/execution/dml/FloatVectorIndexer.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/FloatVectorColumnReference.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge

#14728 Make MoveFilterBeneathJoin operate on any Join again
  server/src/main/java/io/crate/planner/optimizer/rule/FilterOnJoinsUtil.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoin.java
Labels: ready-to-merge

#14699 Increase limit for float vectors to 2048
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/execution/dml/FloatVectorIndexer.java
  server/src/main/java/org/elasticsearch/index/mapper/FloatVectorFieldMapper.java
  server/src/test/java/io/crate/execution/dml/FloatVectorIndexerTest.java
Labels: ready-to-merge

#14718 Fix file not found errors on restore after snapshot of swapped tables
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/org/elasticsearch/repositories/IndexMetaDataGenerations.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge, v/5.2, v/5.4

#14732 Minor code improvements & fix warnings
  server/src/main/java/io/crate/execution/dsl/projection/builder/InputColumns.java
  server/src/main/java/io/crate/expression/symbol/AliasResolver.java
  server/src/main/java/io/crate/expression/symbol/Assignments.java
  server/src/main/java/io/crate/expression/symbol/FieldReplacer.java
  server/src/main/java/io/crate/expression/symbol/FieldsVisitor.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/main/java/io/crate/expression/symbol/GroupAndAggregateSemantics.java
  server/src/main/java/io/crate/expression/symbol/Literal.java
  server/src/main/java/io/crate/expression/symbol/LiteralValueFormatter.java
  server/src/main/java/io/crate/expression/symbol/MappingSymbolVisitor.java
  server/src/main/java/io/crate/expression/symbol/RefVisitor.java
  server/src/main/java/io/crate/expression/symbol/SymbolVisitors.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/expression/symbol/format/MatchPrinter.java
Labels: ready-to-merge

#14737 Reflect release 5.2.9
  docs/appendices/release-notes/5.2.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14736 Reflect release 5.2.9
  docs/appendices/release-notes/5.2.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14735 Reflect release 5.2.9
  docs/appendices/release-notes/5.2.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14739 Assign OID's to all references by a dedicated logic
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  server/src/main/java/io/crate/metadata/DocReferences.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/GeoReference.java
  server/src/main/java/io/crate/metadata/IndexReference.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/io/crate/metadata/DocReferencesTest.java
  server/src/test/java/io/crate/metadata/IndexReferenceTest.java
  server/src/test/java/io/crate/metadata/ReferenceTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#14741 Remove empty source files
  server/src/testFixtures/java/org/elasticsearch/index/mapper/FieldTypeTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/tasks/MockTaskManager.java
  server/src/testFixtures/java/org/elasticsearch/transport/FakeTcpChannel.java
Labels: ready-to-merge

#14742 Update netty to 4.1.98
  gradle/version.properties
Labels: ready-to-merge

#14752 Restrict column definition with the same name and same type on CREATE TABLE
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/analyze/CreateTableStatementAnalyzer.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge

#14754 Fix join graph creation with multiple aliases with the same name
  server/src/main/java/io/crate/planner/optimizer/joinorder/JoinGraph.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
Labels: ready-to-merge

#14753 Add duplicate column check to INSERT statement
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
Labels: ready-to-merge, v/5.4

#14745 Add max_identifier_length read-only session setting
  docs/appendices/release-notes/5.5.0.rst
  docs/config/session.rst
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#14757 Add test case for duplicate column definition
  docs/appendices/release-notes/5.4.4.rst
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge

#14751 Replace crate.io with cratedb.com in README
  README.rst
Labels: ready-to-merge

#14750 Invert gradle <-> blackbox relationship
  Jenkinsfile
  blackbox/bin/sphinx
  blackbox/bin/test
  blackbox/bin/test-all
  blackbox/bin/test-decommission
  blackbox/bin/test-docs
  blackbox/bin/test-jmx
  blackbox/bin/test-s3
  blackbox/bin/test-ssl
  blackbox/build.gradle
  blackbox/testutils/paths.py
  devs/docs/tests.rst
  devs/docs/write_docs.rst
  settings.gradle
Labels: ready-to-merge

#14758 Do not throw an error on UPDATE on a table, emptied by DELETE
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/execution/dml/ShardRequestExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
Labels: ready-to-merge, v/5.4

#14723 Fix UNION involving merging objects and implicit cast of sub-cols
  .github/styles/Vocab/CrateDB/accept.txt
  docs/appendices/release-notes/5.4.4.rst
  docs/general/dql/union.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/UnionSelect.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/analyze/UnionAnalyzerTest.java
  server/src/test/java/io/crate/types/DataTypesTest.java
Labels: bug, ready-to-merge, v/5.4

#14765 Fix issue with unmatched return types for CASE
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
Labels: ready-to-merge, v/5.4

#14667 Fix for ineffective IS_NULL on sub-cols of ignored objects
  docs/appendices/release-notes/5.4.4.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/test/java/io/crate/expression/predicate/IsNullPredicateTest.java
Labels: bug, ready-to-merge, v/5.4

#14769 Minor code improvements & fix warnings
  server/src/main/java/io/crate/server/xcontent/XContentMapValues.java
  server/src/main/java/io/crate/statistics/ColumnStats.java
  server/src/main/java/io/crate/statistics/FetchSampleRequest.java
  server/src/main/java/io/crate/statistics/FetchSampleResponse.java
  server/src/main/java/io/crate/statistics/MostCommonValues.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/BooleanType.java
  server/src/main/java/io/crate/types/ByteType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/DateType.java
  server/src/main/java/io/crate/types/GeoPointType.java
  server/src/main/java/io/crate/types/LongType.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/main/java/io/crate/types/OidVectorType.java
  server/src/main/java/io/crate/types/RegclassType.java
  server/src/main/java/io/crate/types/RegprocType.java
  server/src/main/java/io/crate/types/StorageSupport.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/main/java/io/crate/types/TimeTZParser.java
  server/src/main/java/io/crate/types/TimeTZType.java
  server/src/main/java/io/crate/types/TypeSignature.java
  server/src/main/java/io/crate/udc/ping/PingTask.java
  server/src/main/java/io/crate/udc/service/UDCService.java
  server/src/main/java/io/crate/user/PrivilegeIdent.java
  server/src/main/java/io/crate/user/TransportDropUserAction.java
  server/src/main/java/io/crate/user/User.java
  server/src/main/java/io/crate/user/UserActions.java
  server/src/main/java/io/crate/user/UserLookupService.java
  server/src/main/java/io/crate/user/metadata/PrivilegesMetadataUpgrader.java
Labels: ready-to-merge

#14770 Add join-reordering back to JoinPlanBuilder
  server/src/main/java/io/crate/planner/operators/JoinOrdering.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinOrderingTest.java
Labels: ready-to-merge

#14774 Documentation: Make link checker ignore "codeproject.com", it went down
  docs/conf.py
Labels: ready-to-merge

#14775 Make cross-join in join-test explicit
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge
