Repository crate/crate, pull requests merged in 2023-03, with the labels that each got.

#13741 Migrate CommonQueryBuilderTest to assertj / fix warnings
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#13747 Migrate TransportSQLActionSingleNodeTest to assertj
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
Labels: ready-to-merge

#13708 Remove old 'drop constraint' and 'add column'
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropCheckConstraintPlan.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/ddl/TransportSchemaUpdateActionTest.java
  server/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
Labels: ready-to-merge

#13716 Refine `ColumnUnknownException` such that `MaskSensitiveExceptions` can be specialized
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedTableElements.java
  server/src/main/java/io/crate/analyze/expressions/TableReferenceResolver.java
  server/src/main/java/io/crate/analyze/expressions/ValueNormalizer.java
  server/src/main/java/io/crate/analyze/relations/FullQualifiedNameFieldProvider.java
  server/src/main/java/io/crate/analyze/relations/NameFieldProvider.java
  server/src/main/java/io/crate/analyze/relations/TableFunctionRelation.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/exceptions/ColumnUnknownException.java
  server/src/main/java/io/crate/exceptions/CrateExceptionVisitor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
Labels: ready-to-merge, v/5.2

#13755 tests: fix flaky testEquivalentDeletesAreDeduplicated
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13728 Fix TableIdentsExtractor to be able to extract from AliasSymbol
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/TableIdentsExtractor.java
  server/src/test/java/io/crate/analyze/TableIdentsExtractorTest.java
Labels: ready-to-merge, v/5.2

#13759 Skip generated null values in Indexer
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#13762 Handle missing child Reference in ObjectIndexer
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
Labels: ready-to-merge

#13763 Migrate ObjectColumnTest to assertj
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
Labels: ready-to-merge

#13767 Migrate NodeLimitsTest to assertj
  server/src/test/java/io/crate/execution/jobs/NodeLimitsTest.java
Labels: ready-to-merge

#13758 Add conversion from update to insert; Use Indexer for updates
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateSourceGen.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/main/java/io/crate/expression/reference/DocRefResolver.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateSourceGenTest.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
Labels: ready-to-merge

#13765 Use IndexThrottle also for delete operations
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
Labels: ready-to-merge, v/5.2

#13770 Use Lucene 9.5 Long/Int/Float/Double-Field
  server/src/main/java/io/crate/execution/dml/DoubleIndexer.java
  server/src/main/java/io/crate/execution/dml/FloatIndexer.java
  server/src/main/java/io/crate/execution/dml/IntIndexer.java
  server/src/main/java/io/crate/execution/dml/LongIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#13766 Update netty to 4.1.89
  gradle/version.properties
Labels: ready-to-merge

#13773 Extend assertions in DynamicMappingUpdateITest
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
Labels: ready-to-merge

#13744 Fix invalid conversions of UnsupportedFeatureExceptions to MissingPrivilegeExceptions
  docs/appendices/release-notes/unreleased.rst
  extensions/functions/src/test/java/io/crate/window/NthValueFunctionsTest.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/exceptions/CrateExceptionVisitor.java
  server/src/main/java/io/crate/exceptions/UnsupportedFunctionException.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/main/java/io/crate/rest/action/HttpError.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationtest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/operator/CmpOperatorTest.java
  server/src/test/java/io/crate/expression/scalar/AgeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayAvgFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayCatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayDifferenceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayLowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayMaxFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayMinFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArraySliceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArraySumFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayToStringFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUpperFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ConcatWsFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ExtractFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/StringToArrayFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/MapFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/AreaFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/CoordinateFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/GeoHashFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/object/ObjectKeysFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/regex/RegexpReplaceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/QuoteIdentFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
  server/src/test/java/io/crate/lucene/BitStringQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, v/5.2

#13778 Fix insert on conflict when column to update not in insert cols
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge

#13774 Check types of all existing columns, don't break early
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
Labels: ready-to-merge

#13784 Fix issue with aggregations and UNION
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.2

#13756 Use Indexer for replica operation
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge

#13787 Change CrateLuceneTestCase to delegate to LuceneTestCase
  gradle/version.properties
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobStoreContainerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/RemoveCustomsCommandIT.java
  server/src/test/java/org/elasticsearch/cluster/coordination/RemoveSettingsCommandIT.java
  server/src/test/java/org/elasticsearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/test/java/org/elasticsearch/common/settings/SettingTests.java
  server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/testFixtures/java/org/apache/lucene/tests/index/CrateRandomIndexWriter.java
  server/src/testFixtures/java/org/apache/lucene/tests/util/CrateLuceneTestCase.java
  server/src/testFixtures/java/org/apache/lucene/tests/util/CrateTestRuleSetupAndRestoreClassEnv.java
  server/src/testFixtures/java/org/apache/lucene/tests/util/CrateTestRuleTemporaryFilesCleanup.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
  server/src/testFixtures/java/org/elasticsearch/test/store/MockFSDirectoryFactory.java
  server/src/testFixtures/java/org/elasticsearch/test/test/InternalTestClusterTests.java
Labels: ready-to-merge

#13788 Fix field order determinism in Indexer & DocTableinfo
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#13742 Fix nested joins
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/JoinRelation.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalysisContext.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
  server/src/testFixtures/java/io/crate/testing/JoinPairAssert.java
Labels: ready-to-merge, v/5.2

#13791 Fix join using for nested joins
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.2

#13794 Release 5.2.4
  docs/appendices/release-notes/5.2.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13796 Bump version to 5.2.5-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13797 Reflect release 5.2.4
  docs/appendices/release-notes/5.2.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13792 Use source on replica if present in items
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
Labels: ready-to-merge

#13801 Remove unused date time formats
  server/src/main/java/io/crate/expression/scalar/DateTruncFunction.java
  server/src/main/java/org/elasticsearch/common/joda/Joda.java
  server/src/main/java/org/elasticsearch/common/rounding/DateTimeUnit.java
  server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
Labels: ready-to-merge

#13803 Remove unused methods from Metdata; de-duplicate getters
  server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableTarget.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportBroadcastReplicationAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/TemplateUpgradeService.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/main/java/org/elasticsearch/gateway/LocalAllocateDangledIndices.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/metadata/ReferenceTest.java
  server/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
  server/src/test/java/org/elasticsearch/gateway/MetadataWriteDataNodesIT.java
Labels: ready-to-merge

#13804 Remove unused jobId property from CreatePartitionsRequest
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreatePartitionsRequest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/CreatePartitionsRequestTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge

#13802 Add optimizer rule to rewrite nl-join to hash-join
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteNestedLoopJoinToHashJoin.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathNestedLoopTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13809 Don't discard additional implicit join conditions in nested joins
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.2

#13798 Update netty to 4.1.90
  gradle/version.properties
Labels: ready-to-merge

#13813 Replace expectThrows overload with assertThatThrownBy
  server/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationAllPermitsAcquisitionTests.java
  server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/elasticsearch/env/NodeRepurposeCommandTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/testFixtures/java/org/apache/lucene/tests/util/CrateLuceneTestCase.java
Labels: ready-to-merge

#13812 Implement getRelocated for IndexReference and GeoReference
  server/src/main/java/io/crate/metadata/GeoReference.java
  server/src/main/java/io/crate/metadata/IndexReference.java
  server/src/main/java/io/crate/metadata/SimpleReference.java
Labels: ready-to-merge

#13816 Bump version to 5.2.6-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13817 Reflect release 5.2.5
  docs/appendices/release-notes/5.2.4.rst
  docs/appendices/release-notes/5.2.5.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13821 Add back SuppressFileSystems to NodeEnvironmentTests
  server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java
Labels: ready-to-merge

#13824 Avoid unchecked warnings in ShardCollectSource
  libs/dex/src/main/java/io/crate/data/CompositeBatchIterator.java
  libs/dex/src/test/java/io/crate/data/AsyncCompositeBatchIteratorTest.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
Labels: ready-to-merge

#13823 Remove VIntKeySerializer
  server/src/main/java/org/elasticsearch/cluster/DiffableUtils.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
Labels: ready-to-merge

#13825 Fix `ColumnUnknownException` due to missing quotes in a subscript expression
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: bug, ready-to-merge, v/5.2

#13834 Fix some resource leak warnings
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/cluster/coordination/NodeToolCli.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/index/store/Store.java
  server/src/main/java/org/elasticsearch/index/translog/TranslogDeletionPolicy.java
Labels: ready-to-merge

#13842 Update antlr and jdbc
  gradle/version.properties
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#13806 Receive rules for LoadedRules directly from LogicalPlanner
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
Labels: ready-to-merge

#13833 Fix docs
  docs/config/session.rst
Labels: ready-to-merge, docs, v/5.2

#13853 docs: Clarify arg types for conditional functions
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge, docs, v/5.2

#13858 Fixed default scroll behaviour of Cursors
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/declare.rst
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  server/src/test/java/io/crate/analyze/CursorTest.java
  server/src/test/java/io/crate/integrationtests/CursorITest.java
Labels: ready-to-merge, v/5.2

#13843 Do only one "probe" index creation when inserting into partitioned table
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
Labels: ready-to-merge

#13861 Make setters private in LogicalReplicationSettings
  server/src/main/java/io/crate/replication/logical/LogicalReplicationSettings.java
Labels: ready-to-merge

#13850 Fix resource leak which can happen in non happy path scenarios
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
Labels: ready-to-merge, v/5.2

#13849 fix refresh_interval docs, mention correct default value
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/io/crate/analyze/GenericPropertiesConverter.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.2

#13863 Remove unused & deprecated functions from XContentGenerator
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/XContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/XContentGenerator.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContentGenerator.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/smile/SmileXContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/yaml/YamlXContent.java
Labels: ready-to-merge

#13866 Make AliasValidator methods static
  server/src/main/java/org/elasticsearch/cluster/metadata/AliasValidator.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge

#13867 Remove includes/excludes option from XContentGenerator
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/XContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContentGenerator.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/smile/SmileXContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/smile/SmileXContentGenerator.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/yaml/YamlXContent.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/yaml/YamlXContentGenerator.java
Labels: ready-to-merge

#13878 Replace deprecated Constants.JAVA_VERSION with Runtime.version
  server/src/main/java/io/crate/expression/reference/sys/node/NodeStatsContext.java
  server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
  server/src/test/java/io/crate/integrationtests/NodeStatsTest.java
Labels: ready-to-merge

#13881 Fix reader.document deprecation warnings
  server/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
  server/src/main/java/io/crate/execution/engine/fetch/ReaderContext.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java
Labels: ready-to-merge

#13880 Migrate NodeStatsTest & PrimaryAllocationIT to assertj
  server/src/test/java/io/crate/integrationtests/NodeStatsTest.java
  server/src/test/java/io/crate/integrationtests/disruption/routing/PrimaryAllocationIT.java
Labels: ready-to-merge

#13887 Group release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#13891 Don't create ReaderContext per row in ScoreDocRowFunction
  server/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
Labels: ready-to-merge

#13876 Remove undocumented index.store.preload setting
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/store/FsDirectoryFactory.java
  server/src/test/java/org/elasticsearch/index/store/FsDirectoryFactoryTests.java
Labels: ready-to-merge

#13895 Prune columns of scalar sub-queries
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge, v/5.2

#13890 Fix QuerySplitter from losing previous query parts
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/relations/QuerySplitter.java
  server/src/test/java/io/crate/analyze/relations/QuerySplitterTest.java
Labels: ready-to-merge, v/5.2

#13886 Document ability to add a sub-column to an OBJECT(STRICT)
  docs/general/ddl/alter-table.rst
  docs/general/ddl/data-types.rst
  docs/sql/statements/alter-table.rst
Labels: ready-to-merge, v/5.2

#13906 tests: Fix flaky testEquivalentDeletesAreDeduplicated
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13902 Migrate to assertj
  server/src/test/java/io/crate/analyze/AlterTableOpenCloseAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableRenameAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableRerouteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CompoundLiteralTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
  server/src/test/java/io/crate/common/collections/MapComparatorTest.java
  server/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  server/src/test/java/io/crate/execution/dml/upsert/CheckConstraintsTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/engine/FailureOnlyResponseListenerTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchTaskTest.java
  server/src/test/java/io/crate/execution/jobs/transport/NodeDisconnectJobMonitorServiceTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
  server/src/test/java/io/crate/user/PrivilegesTest.java
Labels: ready-to-merge

#13882 Fix rawtype/unchecked warning in Optimizers
  server/src/main/java/io/crate/planner/optimizer/Optimizer.java
  server/src/main/java/io/crate/planner/optimizer/iterative/IterativeOptimizer.java
  server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java
Labels: ready-to-merge
