Repository crate/crate, pull requests merged in 2023-08, with the labels that each got.

#14506 Fix handling of `empty_obj_column = {}`
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14512 Fix handling of dual session/global settings in SetSessionPlan
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/planner/statement/SetSessionPlan.java
  server/src/test/java/io/crate/planner/statement/SetSessionPlanTest.java
Labels: ready-to-merge, v/5.4

#14510 Update netty to 4.1.96
  gradle/version.properties
Labels: ready-to-merge

#14500 Don't bypass alias for subscript lookup
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14509 Allow users with AL permission to see all of sys.jobs/jobs_log
  docs/appendices/release-notes/5.5.0.rst
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: ready-to-merge

#14522 Fix eclipse compile error in SysClusterSettingsTest
  server/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
Labels: ready-to-merge

#14514 Remove SingleStartEnforcer in IndexRecoveryIT
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#14520 Convert DeleteIntegrationTest to assertj / enable more random rules
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/EmptyStringRoutingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UnionIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/org/elasticsearch/index/engine/MaxDocsLimitIT.java
Labels: ready-to-merge

#14524 Update bundled JDK to 20.0.2+9
  docs/appendices/release-notes/5.4.1.rst
  gradle/version.properties
Labels: ready-to-merge, v/5.4

#14530 Add Analyzer support for DROP COLUMN
  docs/appendices/compatibility.rst
  docs/general/ddl/alter-table.rst
  docs/sql/statements/alter-table.rst
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropColumnDefinition.java
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableDropColumn.java
  server/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnRequest.java
  server/src/test/java/io/crate/analyze/AlterTableDropColumnAnalyzerTest.java
Labels: ready-to-merge

#14531 Add CURRENT_DATE/TIME/TIMESTAMP to non-reserved keywords
  docs/appendices/release-notes/5.5.0.rst
  libs/sql-parser/src/main/antlr/SqlBaseParser.g4
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
Labels: ready-to-merge

#14533 Release 5.3.5
  docs/appendices/release-notes/5.3.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14534 Reflect release 5.3.5
  docs/appendices/release-notes/5.3.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14536 Reflect release 5.3.5
  docs/appendices/release-notes/5.3.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14537 Fix chooseReleaseNotes gradle task for end-of-life branch
  app/build.gradle
Labels: ready-to-merge, v/5.3, v/5.4

#14535 Bump version to 5.3.6-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14540 Release 5.4.1
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14542 Reflect release 5.4.1
  docs/appendices/release-notes/5.4.1.rst
  docs/appendices/release-notes/5.4.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14541 Bump version to 5.4.2-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14544 docs: Clarify `plain` type for composite indices
  docs/general/ddl/fulltext-indices.rst
Labels: ready-to-merge, v/5.4

#14547 Refactor Drop column analysis
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTableDropColumn.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/AlterTableDropColumnAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge

#14549 Add operation memory limit as node & session setting
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.0.rst
  docs/config/cluster.rst
  docs/config/session.rst
  libs/dex/src/main/java/io/crate/data/breaker/BlockBasedRamAccounting.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/analyze/relations/StatementAnalysisContext.java
  server/src/main/java/io/crate/breaker/ConcurrentRamAccounting.java
  server/src/main/java/io/crate/execution/engine/collect/stats/RamAccountingQueue.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchOperation.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/main/java/io/crate/metadata/settings/SessionSettings.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/breaker/ConcurrentRamAccountingTest.java
  server/src/test/java/io/crate/breaker/RowAccountingWithEstimatorsTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchTaskTest.java
  server/src/test/java/io/crate/execution/engine/fetch/NodeFetchResponseTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingLimitAndOffsetProjectorTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingProjectorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/metadata/settings/SessionSettingsTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerTest.java
Labels: ready-to-merge

#14559 Adjust version number in ViewMetadata serialization
  server/src/main/java/io/crate/metadata/view/ViewMetadata.java
  server/src/test/java/io/crate/metadata/view/ViewMetadataTest.java
Labels: ready-to-merge

#14567 Fix a CrateDB typo
  docs/general/ddl/replication.rst
Labels: ready-to-merge, docs, v/5.4

#14566 Fix a typo in the CREATE REPOSITORY documentation
  docs/sql/statements/create-repository.rst
Labels: ready-to-merge, docs, v/5.4

#14573 Clarify how regex comparison operators and full text search can be used on the same field
  docs/general/builtins/comparison-operators.rst
  docs/general/dql/selects.rst
Labels: ready-to-merge, docs, v/5.4

#14576 Release 5.3.6
  docs/appendices/release-notes/5.3.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14578 Reflect release 5.3.6
  docs/appendices/release-notes/5.3.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14579 Reflect release 5.3.6
  docs/appendices/release-notes/5.3.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14580 Release 5.4.2
  docs/appendices/release-notes/5.4.2.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14581 Bump version to 5.4.3-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14588 docs: Clarify that knn_match limit is per shard
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge

#14589 docs: Add warning note for JOIN regression in 5.4
  docs/appendices/release-notes/5.4.0.rst
  docs/appendices/release-notes/5.4.1.rst
  docs/appendices/release-notes/5.4.2.rst
Labels: ready-to-merge, v/5.4

#14551 Rename createSession → newSession
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/integrationtests/BaseUsersIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#14596 Fix chooseReleaseNotes gradle task on windows
  app/build.gradle
Labels: ready-to-merge, v/5.3, v/5.4

#14599 Fix chooseReleaseNotes
  app/build.gradle
Labels: ready-to-merge

#14600 Remove executeIO from CancellableThreads
  server/src/main/java/io/crate/blob/recovery/BlobRecoveryHandler.java
  server/src/main/java/org/elasticsearch/common/util/CancellableThreads.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/test/java/org/elasticsearch/common/util/CancellableThreadsTests.java
Labels: ready-to-merge

#14609 Add substring(string FROM pattern)
  docs/appendices/release-notes/5.5.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/SubstrFunction.java
  server/src/test/java/io/crate/expression/scalar/SubstrFunctionTest.java
Labels: ready-to-merge

#14615 Raise an error if knn_match is used outside of WHERE/table scope
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/KnnMatch.java
  server/src/test/java/io/crate/expression/scalar/KnnMatchTest.java
Labels: ready-to-merge

#14620 Minor code cleanup & fix/suppress warnings
  benchmarks/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationContext.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/IntervalSumAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/statistics/FetchSampleResponse.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/io/crate/statistics/Samples.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#14622 Implement drop object sub-column
  benchmarks/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  server/src/main/java/io/crate/execution/ddl/tables/DropColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/CollectorContext.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceLookup.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/metadata/doc/DocIndexMetadata.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  server/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#14607 Minor code improvements & cleanup
  server/src/main/java/io/crate/expression/predicate/MatchPredicate.java
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/main/java/io/crate/expression/reference/MapLookupByPathExpression.java
  server/src/main/java/io/crate/expression/reference/StaticTableDefinition.java
  server/src/main/java/io/crate/expression/reference/StaticTableReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IdCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/OrderByCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/sys/SysRowUpdater.java
  server/src/main/java/io/crate/expression/reference/sys/check/SysCheck.java
  server/src/main/java/io/crate/expression/reference/sys/shard/ShardRowContext.java
  server/src/main/java/io/crate/expression/reference/sys/shard/ShardSegment.java
  server/src/test/java/io/crate/expression/reference/MapLookupByPathExpressionTest.java
Labels: ready-to-merge

#14624 Don't use JDK19 API just yet
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
Labels: ready-to-merge

#14627 Remove unused logic from S3FileReadingCollectorTest
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
Labels: ready-to-merge

#14632 Introduce ReferenceAssert to make Reference assertions composable
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/TableFunctionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/execution/dml/upsert/ValidatedRawInsertSourceTest.java
  server/src/test/java/io/crate/expression/symbol/FetchMarkerTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/metadata/GeneratedReferenceTest.java
  server/src/test/java/io/crate/metadata/SystemTableTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/planner/InsertPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
  server/src/testFixtures/java/io/crate/testing/ReferenceAssert.java
  server/src/testFixtures/java/io/crate/testing/SymbolAssert.java
Labels: ready-to-merge

#14634 added hasOid method to ReferenceAssert
  server/src/testFixtures/java/io/crate/testing/ReferenceAssert.java
Labels: ready-to-merge
