Repository crate/crate, pull requests merged in 2023-12, with the labels that each got.

#15130 Reflect 5.4.6 on 5.5
  docs/appendices/release-notes/5.4.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15132 Reflect 5.5.1
  docs/appendices/release-notes/5.5.1.rst
  docs/appendices/release-notes/5.5.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15131 Reflect 5.4.6
  docs/appendices/release-notes/5.4.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15116 Update PostgreSQL JDBC to 42.7.0
  pom.xml
Labels: ready-to-merge

#15137 Use DataTypeTestCase for GeoShapeTypeTest
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
Labels: ready-to-merge

#15141 Remove TemplateUpgradeService; upgrade on restore
  server/src/main/java/org/elasticsearch/cluster/metadata/TemplateUpgradeService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
Labels: ready-to-merge

#15134 Fix application of optimized iterator for group by queries with a single key
  docs/appendices/release-notes/5.5.2.rst
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge, v/5.5

#15149 Ignore backslash in C-Style escaped string unless it's escaped by another backslash
  docs/appendices/release-notes/5.5.2.rst
  libs/sql-parser/src/main/java/io/crate/sql/Literals.java
  libs/sql-parser/src/test/java/io/crate/sql/LiteralsTest.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/test/java/io/crate/expression/operator/LikeOperatorTest.java
  server/src/test/java/io/crate/expression/operator/any/AnyLikeOperatorTest.java
  server/src/test/java/io/crate/expression/operator/any/AnyNotLikeOperatorTest.java
Labels: ready-to-merge, v/5.5

#15158 docs: Add missing password column to sys.users
  .vale.ini
  docs/admin/system-information.rst
  docs/admin/user-management.rst
Labels: ready-to-merge, docs, v/5.5

#15168 Upgrade dependencies to their latest version
  pom.xml
Labels: ready-to-merge

#15169 tests: Migrate aggregation unit tests to assertj
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArrayAggTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/KahanSummationForDoubleTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/KahanSummationForFloatTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/util/OverflowAwareMutableLongTest.java
Labels: ready-to-merge

#15178 Fix remote collect DistResultRXTask leak
  docs/appendices/release-notes/5.5.2.rst
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/collect/RemoteCollectorFactory.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/RemoteCollector.java
Labels: v/5.5

#15182 Add missing header
  server/src/test/java/io/crate/execution/ddl/tables/RenameColumnTaskTest.java
Labels: ready-to-merge

#15186 Remove unused response handlers
  server/src/main/java/org/elasticsearch/discovery/AckClusterStatePublishResponseHandler.java
  server/src/main/java/org/elasticsearch/discovery/BlockingClusterStatePublishResponseHandler.java
Labels: ready-to-merge

#15189 Fix evaluation of `NULLIF` and `OR` in where clause
  docs/appendices/release-notes/5.5.2.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.5

#15187 Fix DROP COLUMN on a parent and child in a single stmt
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
Labels: ready-to-merge

#15195 Add Licence header to new files in Intellij
  .idea/copyright/profiles_settings.xml
Labels: ready-to-merge

#15196 Enable checkstyle for tests
  pom.xml
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
  server/src/test/java/io/crate/breaker/CrateCircuitBreakerServiceTest.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/expression/scalar/ScalarNullabilityTest.java
  server/src/test/java/io/crate/integrationtests/BkdTreeGeoMatchIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PrefixTreeGeoMatchIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/planner/operators/HashJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoinTest.java
  server/src/test/java/io/crate/role/UserActionsTest.java
Labels: ready-to-merge

#15197 Add versions to the rest of the used maven plugins
  pom.xml
Labels: ready-to-merge

#15206 Add maven-enforcer-plugin
  pom.xml
Labels: ready-to-merge

#15185 Replace ConcurrentCollections.newConcurrentSet with Set.newConcurrentHashSet
  server/src/main/java/io/crate/replication/logical/repository/PublisherRestoreService.java
  server/src/main/java/org/elasticsearch/action/support/replication/PendingReplicationActions.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/ConcurrentCollections.java
  server/src/main/java/org/elasticsearch/index/engine/ElasticsearchConcurrentMergeScheduler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TransportKeepAlive.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/ClusterDisruptionIT.java
  server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoveryRequestTrackerTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/testFixtures/java/org/elasticsearch/test/BackgroundIndexer.java
Labels: ready-to-merge

#15209 Upgrade to lucene 9.9.1
  pom.xml
  server/src/main/java/io/crate/execution/engine/sort/NullFieldComparatorSource.java
  server/src/main/java/io/crate/execution/engine/sort/SortSymbolVisitor.java
  server/src/main/java/io/crate/lucene/BlendedTermQuery.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
Labels: ready-to-merge

#15214 Add error message for >= 5.6 when changing privileges
  server/src/main/java/io/crate/role/TransportAlterRoleAction.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/main/java/io/crate/role/TransportPrivilegesAction.java
Labels: ready-to-merge

#15217 Remove unneeded release entry
  docs/appendices/release-notes/5.5.2.rst
Labels: ready-to-merge

#15215 Add notice about distro package changes to 5.5.2 release notes
  docs/appendices/release-notes/5.5.2.rst
Labels: ready-to-merge, v/5.5

#15223 Move static Role factory methods to a test helper
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/RolesService.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/main/java/io/crate/role/metadata/UsersPrivilegesMetadata.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/analyze/CreateViewAnalyzerTest.java
  server/src/test/java/io/crate/analyze/PrivilegesDCLAnalyzerTest.java
  server/src/test/java/io/crate/auth/ClientCertAuthTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
  server/src/test/java/io/crate/execution/engine/collect/stats/JobsLogsTest.java
  server/src/test/java/io/crate/expression/reference/StaticTableDefinitionTest.java
  server/src/test/java/io/crate/expression/scalar/HasDatabasePrivilegeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/HasSchemaPrivilegeFunctionTest.java
  server/src/test/java/io/crate/integrationtests/BaseRolesIntegrationTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerTest.java
  server/src/test/java/io/crate/planner/statement/SetSessionAuthorizationPlanTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzerTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/role/PrivilegesTest.java
  server/src/test/java/io/crate/role/RolesServiceTest.java
  server/src/test/java/io/crate/role/TransportPrivilegesActionTest.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
  server/src/test/java/io/crate/role/metadata/CustomMetadataTest.java
  server/src/test/java/io/crate/role/metadata/RolesHelper.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
  server/src/test/java/io/crate/role/metadata/UsersMetadataTest.java
  server/src/test/java/io/crate/role/scalar/UserFunctionTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
Labels: ready-to-merge

#15220 Move metadata (de-)serialization of a role to the `Role` class
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/SecureHash.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/main/java/io/crate/role/metadata/UsersMetadata.java
Labels: ready-to-merge

#15212 Add optimizer rule to move a limit beneath a union
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnion.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/PlanPrinterTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnionTest.java
Labels: ready-to-merge

#15177 Propagate ALTER TABLE on child columns to its parent columns inner types
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge

#15230 Fix ambigious quote escaping at the end of C-Style string
  docs/appendices/release-notes/5.5.2.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.5

#15234 Disable trust of HTTP ``X-Real-IP`` header by default.
  .github/styles/CrateDB/Terminology.yml
  docs/admin/auth/hba.rst
  docs/appendices/release-notes/5.5.2.rst
  docs/config/node.rst
  server/src/main/java/io/crate/auth/AuthSettings.java
  server/src/main/java/io/crate/auth/HttpAuthUpstreamHandler.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
Labels: ready-to-merge, v/5.2, v/5.3, v/5.4, v/5.5

#15229 Use `FieldExistsQuery` if at least one arg of `!=` is nullable
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#15238 Add missing word to our styles config to fix vale
  .github/styles/CrateDB/Terminology.yml
  .github/styles/Vocab/CrateDB/accept.txt
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5

#15245 Release CrateDB 5.3.8
  docs/admin/auth/hba.rst
  docs/appendices/release-notes/5.3.8.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15244 Release CrateDB 5.4.7
  docs/admin/auth/hba.rst
  docs/appendices/release-notes/5.4.7.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15248 Reflect 5.5.2 release in pom files
  app/pom.xml
  benchmarks/pom.xml
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
Labels: ready-to-merge

#15250 Bump version to 5.4.8-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.8.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15251 Bump version to 5.2.12-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15252 Bump version to 5.5.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15253 Bump version to 5.3.9-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.3.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15256 Reflect release 5.2.11 at 5.3
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15258 Reflect releases 5.2.11 and 5.3.8 at 5.4
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/5.3.8.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15257 Reflect releases 5.2.11, 5.3.8 and 5.4.7 in 5.5
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/5.3.8.rst
  docs/appendices/release-notes/5.4.7.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15259 Reflect releases 5.2.11, 5.3.8, 5.4.7, 5.5.2 at master
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/5.3.8.rst
  docs/appendices/release-notes/5.4.7.rst
  docs/appendices/release-notes/5.5.2.rst
  docs/appendices/release-notes/5.5.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15261 Always try to migrate users to roles on CREATE/ALTER/DROP ROLE
  server/src/main/java/io/crate/role/TransportAlterRoleAction.java
  server/src/main/java/io/crate/role/TransportCreateRoleAction.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
Labels: ready-to-merge

#15247 Remove FieldExistsQuery added to arguments to Coalesce
  server/src/main/java/io/crate/expression/scalar/conditional/CoalesceFunction.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge

#15264 Add a unit test for altering user's passwd
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge

#15269 tests: Migrate to assertj
  server/src/test/java/io/crate/cluster/gracefulstop/DecommissioningServiceTest.java
  server/src/test/java/io/crate/execution/engine/JobLauncherWaitForCompletionTest.java
  server/src/test/java/io/crate/execution/engine/collect/CollectTaskTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/RemoteCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/count/InternalCountOperationTest.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  server/src/test/java/io/crate/execution/jobs/RootTaskTest.java
  server/src/test/java/io/crate/expression/reference/sys/check/node/SysNodeChecksTest.java
  server/src/test/java/io/crate/replication/logical/action/ReplayChangesActionTest.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
Labels: ready-to-merge

#15263 Add `parents` column to `sys.users` and `sys.roles`
  docs/admin/system-information.rst
  docs/admin/user-management.rst
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/role/GrantedRole.java
  server/src/main/java/io/crate/role/metadata/SysRolesTableInfo.java
  server/src/main/java/io/crate/role/metadata/SysUsersTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#15273 Code improvements for RolesMetadata and its Test
  server/src/main/java/io/crate/role/TransportPrivilegesAction.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
Labels: ready-to-merge

#15271 docs: Add and modify documentation regarding ROLES
  docs/admin/auth/hba.rst
  docs/admin/privileges.rst
  docs/admin/user-management.rst
  docs/appendices/release-notes/5.6.0.rst
  docs/sql/statements/alter-role.rst
  docs/sql/statements/alter-user.rst
  docs/sql/statements/create-role.rst
  docs/sql/statements/create-user.rst
  docs/sql/statements/drop-role.rst
  docs/sql/statements/drop-user.rst
  docs/sql/statements/grant.rst
  docs/sql/statements/index.rst
  docs/sql/statements/revoke.rst
Labels: ready-to-merge

#15275 tests: Use data node session when running a query
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.5
