Repository crate/crate, pull requests merged in 2023-07, with the labels that each got.

#14335 Fix issue with re-ordered pruned outputs
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/LimitDistinct.java
  server/src/main/java/io/crate/planner/operators/LogicalPlan.java
  server/src/main/java/io/crate/planner/operators/ProjectSet.java
  server/src/main/java/io/crate/planner/operators/WindowAgg.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.3

#14354 Disallow CHECK constraints for object sub-cols at column level
  docs/appendices/release-notes/unreleased.rst
  docs/sql/general/constraints.rst
  libs/sql-parser/src/main/java/io/crate/sql/tree/ObjectColumnType.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.3

#14358 tests: Fix flaky test_nested_join_with_primary_key_lookup
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#14346 Add storage class setting to S3 repository
  docs/appendices/release-notes/unreleased.rst
  docs/sql/statements/create-repository.rst
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryPluginAnalyzerTest.java
Labels: ready-to-merge

#14362 Change column policy for the test, verifying dynamic array creation
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#14363 Add join-reordering rules to release note
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#14366 Cast partitioned by columns in the Indexer from string to required ty…
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, v/5.3

#14364 Ensure that CLUSTERED BY column is not NULL on insert-from-subquery
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/engine/collect/RowShardResolver.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.3

#14367 Fix fields used in IP value indexer when indexing is turned off
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/IpIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, v/5.3

#14368 Fix `index` and `hasDocValues` propagation in BitStringFieldmapper
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/execution/dml/BitStringIndexer.java
  server/src/main/java/org/elasticsearch/index/mapper/BitStringFieldMapper.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/org/elasticsearch/index/mapper/BitStringFieldMapperTest.java
Labels: ready-to-merge, v/5.3

#14255 Fix issue with empty arrays, selecting by id
  docs/appendices/release-notes/5.3.2.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/DocRefResolver.java
  server/src/test/java/io/crate/executor/transport/task/elasticsearch/DocRefResolverTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge, v/5.3

#14376 Admin UI: Updated to Admin UI version 1.24.4
  gradle/version.properties
Labels: ready-to-merge

#14384 Convert some more tests to assertj
  server/src/test/java/io/crate/analyze/CreateAlterPartitionedTableAnalyzerTest.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
Labels: ready-to-merge

#14391 Release 5.3.4
  docs/appendices/release-notes/5.3.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14393 Bump version to 5.3.5-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14394 Reflect release 5.3.4
  docs/appendices/release-notes/5.3.4.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14396 Release 5.4.0
  docs/appendices/release-notes/5.4.0.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14399 Update mergify backport rules (+5.4, -5.2)
  .mergify.yml
Labels: ready-to-merge

#14400 Reflect release 5.4.0
  CHANGES.txt
  app/build.gradle
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.0.rst
  docs/appendices/release-notes/5.4.1.rst
  docs/appendices/release-notes/5.5.0.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#14402 Update Lucene to 9.7.0
  gradle/version.properties
  server/src/main/java/org/elasticsearch/Version.java
  server/src/testFixtures/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: ready-to-merge

#14403 Change `unreleased` to `5.3.5`-unreleased scheme
  CHANGES.txt
  app/build.gradle
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#14404 Add `5.3.5.rst`-unreleased
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/index.rst
Labels: ready-to-merge

#14405 Add `5.3.5.rst`-unreleased
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/index.rst
Labels: ready-to-merge

#14390 Remove map/mapExpression from TableElements
  libs/sql-parser/src/main/java/io/crate/sql/tree/AddColumnDefinition.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CheckConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CollectionColumnType.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ColumnDefinition.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ColumnType.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateFunction.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GenericProperty.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/IndexDefinition.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ObjectColumnType.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrimaryKeyConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/TableElement.java
  server/src/main/java/io/crate/analyze/CreateFunctionAnalyzer.java
  server/src/main/java/io/crate/analyze/FunctionArgumentDefinition.java
  server/src/main/java/io/crate/analyze/ResetStatementAnalyzer.java
Labels: ready-to-merge

#14401 Fix IndexOutOfBoundsException due to `IS_NULL` over a subscript function
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14411 Update NOTE for `CHECK` constraint on subcolumn
  docs/sql/general/constraints.rst
Labels: docs

#14410 Adapt estimated row count for Limit to be aware of source estimate
  server/src/main/java/io/crate/planner/optimizer/costs/PlanStats.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/testFixtures/java/io/crate/testing/LogicalPlanAssert.java
Labels: ready-to-merge

#14406 Add more context to create table error messages
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge

#14413 docs: Fix `5.4.0` release notes ref link
  docs/appendices/release-notes/5.4.0.rst
Labels: ready-to-merge, v/5.4

#14412 Improve error message for `CHECK` on subcol without full fqn path
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge

#14373 Validate generated expressions of partitioned by columns
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjection.java
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/sources/CollectSourceResolver.java
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjectionTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/planner/InsertPlannerTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14418 combine pg_catalog related changes to a list
  docs/appendices/release-notes/5.4.0.rst
Labels: ready-to-merge, docs, v/5.4

#14419 Fix: NPE when using `null` value for `compression` in `COPY TO`
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/analyze/GenericPropertiesConverter.java
  server/src/test/java/io/crate/planner/statement/CopyToPlannerTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14423 Add fix entries to 5.3.5
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
Labels: ready-to-merge

#14425 Remove onCompletion from ColumnIndexWriterProjector/ShardingUpsertExecutor
  server/src/main/java/io/crate/execution/engine/indexing/ColumnIndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
Labels: ready-to-merge

#14424 Remove single-use LogicalPlanAssert overload
  server/src/testFixtures/java/io/crate/testing/Asserts.java
  server/src/testFixtures/java/io/crate/testing/LogicalPlanAssert.java
Labels: ready-to-merge

#14429 Remove benchmarks stage from Jenkinsfile
  Jenkinsfile
Labels: v/5.3, v/5.4

#14426 Move CreateTableAsPlan to top level
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlan.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlanner.java
Labels: ready-to-merge

#14432 Remove dead code from SnapshotsService
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: ready-to-merge

#14439 Fix NPE with cross joins and fetch phases (Reset state on moveToStart in AsyncFlatMapBatchIterator)
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  libs/dex/src/main/java/io/crate/data/AsyncFlatMapBatchIterator.java
  libs/dex/src/test/java/io/crate/data/AsyncFlatMapBatchIteratorTest.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchRows.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14442 Remove benchmarks stage from Jenkinsfile (backport #14429)
  Jenkinsfile
Labels: ready-to-merge

#14444 Fix information schema queries when cluster state has outdated views
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/metadata/view/ViewInfoFactory.java
  server/src/test/java/io/crate/metadata/view/ViewInfoFactoryTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14448 Allow trailing `/` in connection URL for CREATE SUBSCRIPTION
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/test/java/io/crate/replication/logical/metadata/ConnectionInfoTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14460 docs: Clarify docs around cluster.routing.allocation.* settings
  docs/config/cluster.rst
Labels: ready-to-merge, v/5.3, v/5.4

#14456 Fix an issue that caused arrays in ignored objects to become nulls
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14468 Fix flaky testArrayLengthWithAllSupportedTypes
  server/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/FloatVectorType.java
  server/src/main/java/org/elasticsearch/index/mapper/FloatVectorFieldMapper.java
  server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/types/DataTypesTest.java
Labels: ready-to-merge

#14458 Fix arbitrary on IP columns
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregationTest.java
Labels: ready-to-merge, v/5.3, v/5.4

#14466 Limit amount of errors in COPY RETURN SUMMARY
  docs/appendices/release-notes/5.5.0.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResults.java
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
Labels: ready-to-merge

#14472 Fix flaky test_cross_join_on_top_of_fetch
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#14467 Avoid newline splitting in hasRows() assertion
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/testFixtures/java/io/crate/testing/SQLResponseAssert.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge

#14478 tests: migrate SysClusterSettingsTest to assertj
  server/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
Labels: ready-to-merge

#14481 Add missing spaces to `RecoveryExpectedNodesSysCheck` message
  server/src/main/java/io/crate/expression/reference/sys/check/node/RecoveryExpectedNodesSysCheck.java
Labels: ready-to-merge, v/5.3, v/5.4

#14477 Don't print implicit casts via Symbol.toString
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/MetadataToASTNodeResolverTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/where/NullEliminatorTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/planner/ExplainPlannerTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
Labels: ready-to-merge

#14489 Correct float_vector maximum length in docs
  docs/general/ddl/data-types.rst
Labels: ready-to-merge

#14491 Store search path in view metadata
  docs/appendices/release-notes/5.3.5.rst
  docs/appendices/release-notes/5.4.1.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/StatementAnalysisContext.java
  server/src/main/java/io/crate/execution/ddl/views/CreateViewRequest.java
  server/src/main/java/io/crate/execution/ddl/views/TransportCreateViewAction.java
  server/src/main/java/io/crate/metadata/SearchPath.java
  server/src/main/java/io/crate/metadata/view/ViewMetadata.java
  server/src/main/java/io/crate/metadata/view/ViewsMetadata.java
  server/src/main/java/io/crate/planner/CreateViewPlan.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/analyze/SelectFromViewAnalyzerTest.java
  server/src/test/java/io/crate/execution/ddl/views/CreateViewRequestTest.java
  server/src/test/java/io/crate/metadata/view/ViewInfoFactoryTest.java
  server/src/test/java/io/crate/metadata/view/ViewsMetadataTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, v/5.3, v/5.4

#14494 Use stored searchPath when analysing views for information_schema.views
  server/src/main/java/io/crate/metadata/view/ViewInfoFactory.java
  server/src/test/java/io/crate/metadata/view/ViewInfoFactoryTest.java
Labels: v/5.3, v/5.4

#14492 Documentation: Improve reading flow on "Clustering" page
  docs/concepts/clustering.rst
Labels: ready-to-merge, v/5.4
