Repository crate/crate, pull requests merged in 2023-01, with the labels that each got.

#12624 Add `parse_uri()` / `parse_url()` function
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/string/ParseURIFunction.java
  server/src/main/java/io/crate/expression/scalar/string/ParseURLFunction.java
  server/src/test/java/io/crate/expression/scalar/ParseURIFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ParseURLFunctionTest.java
Labels: ready-to-merge

#13422 Skip irrelevant patches
  devs/docs/es-backports.rst
Labels: ready-to-merge

#13427 Remove unused startTime from IndexNameExpressionResolver Context
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
Labels: ready-to-merge

#13425 Fix function resolution for bit types with different lengths
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/types/TypeCompatibility.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
Labels: ready-to-merge, v/5.1

#13429 Remove redundant unmodifiable set wrappers
  server/src/main/java/org/elasticsearch/cluster/ClusterModule.java
  server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/AliasMetadata.java
  server/src/testFixtures/java/org/elasticsearch/cluster/ESAllocationTestCase.java
Labels: ready-to-merge

#13430 Try to fix flaky testSelectFromClosedPartition
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13428 Use parent RamAccounting instance in ShardDMLExecutor
  server/src/main/java/io/crate/execution/engine/indexing/BatchIteratorBackpressureExecutor.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
Labels: ready-to-merge

#13435 Merge NetworkMessage into OutboundMessage
  server/src/main/java/org/elasticsearch/transport/NetworkMessage.java
  server/src/main/java/org/elasticsearch/transport/OutboundMessage.java
Labels: ready-to-merge

#13438 bp: Ensure ReplicationOperation notify listener once (#68256)
  server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java
Labels: ready-to-merge

#13433 Remove transport profiles
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/common/transport/PortsRange.java
  server/src/main/java/org/elasticsearch/transport/TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpServerChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
  server/src/main/java/org/elasticsearch/transport/Transport.java
  server/src/main/java/org/elasticsearch/transport/TransportChannel.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/main/java/org/elasticsearch/transport/TransportSettings.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpServerChannel.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/org/elasticsearch/action/support/replication/TransportReplicationAllPermitsAcquisitionTests.java
  server/src/test/java/org/elasticsearch/cluster/NodeConnectionsServiceTests.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTest.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTests.java
  server/src/testFixtures/java/org/elasticsearch/test/disruption/DisruptableMockTransport.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/FakeTransport.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/StubbableTransport.java
  server/src/testFixtures/java/org/elasticsearch/transport/FakeTcpChannel.java
  server/src/testFixtures/java/org/elasticsearch/transport/TestTransportChannel.java
Labels: ready-to-merge

#13436 Try to fix flaky testInsertIntoClosedPartition
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13440 Remove HttpServerChannel and TcpServerChannel
  server/src/main/java/org/elasticsearch/common/network/CloseableChannel.java
  server/src/main/java/org/elasticsearch/http/HttpServerChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpServerChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpServerChannel.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTest.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTests.java
Labels: ready-to-merge

#13445 Fix: has_database_privilege `CREATE` on superuser
  server/src/main/java/io/crate/expression/scalar/HasDatabasePrivilegeFunction.java
  server/src/test/java/io/crate/expression/scalar/HasDatabasePrivilegeFunctionTest.java
Labels: ready-to-merge

#13446 Reduce number of shards in testHealthWithClosedIndices
  server/src/test/java/org/elasticsearch/cluster/ClusterHealthIT.java
Labels: ready-to-merge

#13447 Add assertBusy to testSelectFromClosedTableNotAllowed
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
Labels: ready-to-merge

#13439 Do not unwrap aliases in Eval.rewriteToFetch
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/planner/operators/Eval.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.1

#13449 Release 5.1.3
  docs/appendices/release-notes/5.1.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13450 Bump version to 5.1.4-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13451 Reflect release 5.1.3
  docs/appendices/release-notes/5.1.3.rst
  docs/appendices/release-notes/index.rst
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13453 Group release notes by topic
  docs/appendices/release-notes/unreleased.rst
Labels: ready-to-merge

#13456 Bump version to 5.2.1-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13457 Bump version to 5.3.0-SNAPSHOT
  docs/admin/system-information.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#13458 Update mergify backport rules (-5.0, +5.2)
  .mergify.yml
Labels: ready-to-merge

#13409 bp: Add WARN Logging on Slow Transport Message Handling
  devs/docs/es-backports.rst
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/transport/Header.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/InboundMessage.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/Transport.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/main/java/org/elasticsearch/transport/TransportSettings.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
Labels: ready-to-merge

#13462 Fix incorrect reference to 5.3.0 in 5.2.0 release notes
  docs/appendices/release-notes/5.2.0.rst
Labels: ready-to-merge, v/5.2

#13442 Unify CloseableChannel implementations
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/org/elasticsearch/common/AsyncBiFunction.java
  server/src/main/java/org/elasticsearch/common/network/CloseableChannel.java
  server/src/main/java/org/elasticsearch/transport/ChannelStats.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
  server/src/main/java/org/elasticsearch/transport/TransportHandshaker.java
  server/src/main/java/org/elasticsearch/transport/TransportKeepAlive.java
  server/src/main/java/org/elasticsearch/transport/TransportLogger.java
  server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4MessageChannelHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpChannel.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4TcpServerChannel.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/InboundPipelineTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTest.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTests.java
  server/src/test/java/org/elasticsearch/transport/TransportHandshakerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportKeepAliveTests.java
  server/src/testFixtures/java/org/elasticsearch/transport/FakeTcpChannel.java
Labels: ready-to-merge

#13465 Update netty to 4.1.87
  gradle/version.properties
Labels: ready-to-merge

#13468 Try to fix flaky testInsertIntoClosedPartition
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13401 Introduce case function to efficiently handle case expressions
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctionModule.java
  server/src/main/java/io/crate/expression/scalar/conditional/CaseFunction.java
  server/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
Labels: ready-to-merge

#13244 Exclude implicit `pg_catalog` from show search path
  docs/appendices/release-notes/unreleased.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/metadata/SearchPath.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/test/java/io/crate/expression/scalar/postgres/CurrentSettingFunctionTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/metadata/SearchPathTest.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
Labels: ready-to-merge

#13466 Change outputHandler.sendBytes to take byte[]
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TransportKeepAlive.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportKeepAliveTests.java
Labels: ready-to-merge

#13470 Add a "Run CrateDB" config to launch.json
  .vscode/launch.json
Labels: ready-to-merge

#13477 Try to fix flaky testSelectFromClosedPartition
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#13473 Improve error message when fetching `ABSOLUTE` past last row
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/Cursor.java
  server/src/test/java/io/crate/action/sql/CursorTest.java
Labels: ready-to-merge, v/5.2

#13478 Add initial ConcurrentSnapshotsIT test case
  devs/docs/es-backports.rst
  server/src/test/java/io/crate/integrationtests/disruption/discovery/AbstractDisruptionTestCase.java
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
Labels: ready-to-merge

#13480 Inline ChannelStats into CloseableChannel
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/org/elasticsearch/common/network/CloseableChannel.java
  server/src/main/java/org/elasticsearch/transport/ChannelStats.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TransportKeepAlive.java
  server/src/test/java/org/elasticsearch/transport/TransportKeepAliveTests.java
Labels: ready-to-merge

#13484 mergify: Remove deprecated `rebase_fallback` option
  .mergify.yml
Labels: ready-to-merge, v/5.2

#13404 Recover from corrupted Metadata caused by #13380
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/metadata/bugfix/CorruptedMetadataFixer.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/test/java/io/crate/integrationtests/CorruptedMetadataFixerIntegrationTest.java
  server/src/test/java/io/crate/metadata/bugfix/CorruptedMetadataFixerTest.java
  server/src/test/resources/indices/data_home/cratedata-5.1.2-swap-table-bug-#13380-2.zip
  server/src/test/resources/indices/data_home/cratedata-5.1.2-swap-table-bug-#13380-3.zip
  server/src/test/resources/indices/data_home/cratedata-5.1.2-swap-table-bug-#13380.zip
Labels: ready-to-merge, v/5.1, v/5.2

#13483 Port more ConcurrentSnapshotsIT cases
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/testFixtures/java/io/crate/testing/SQLResponseAssert.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: ready-to-merge

#13493 Fix release date for 5.1.3
  docs/appendices/release-notes/5.1.3.rst
Labels: ready-to-merge, v/5.1, v/5.2

#13497 Fix issues with updating cursorPosition
  server/src/main/java/io/crate/action/sql/Cursor.java
Labels: ready-to-merge, v/5.2

#13496 Port ConcurrentSnapshotsIT test cases - part 3
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13505 bp: Use Threadpool Time in ClusterApplierService
  server/src/main/java/org/elasticsearch/cluster/ClusterStateObserver.java
Labels: ready-to-merge

#13500 Don't cache parsed analyze statement in TableStatsService
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/statistics/TableStatsService.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
Labels: ready-to-merge

#13507 Add validation to reject inner columns containing whitespace chars
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.1, v/5.2

#13512 Handle ForbiddenApis failure
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
Labels: ready-to-merge

#13514 Mute CursorITest
  server/src/test/java/io/crate/integrationtests/CursorITest.java
Labels: ready-to-merge

#13519 Fix output column names that were missing a subscript
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: ready-to-merge, v/5.1, v/5.2

#13506 Backport more ConcurrentSnapshotsIT test cases
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
Labels: ready-to-merge

#13511 Fix ClassCastException while querying implicit nested arrays
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge, v/5.1, v/5.2

#13523 Drop support for pre CrateDB 4.0 translog format
  server/src/main/java/org/elasticsearch/index/translog/TranslogHeader.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogHeaderTests.java
Labels: ready-to-merge

#13517 Update bundled JDK to 19.0.2+7
  gradle/version.properties
Labels: ready-to-merge, v/5.2

#13535 Fix deprecation warnings in MetadataTrackerITest
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#13533 Fix: Release accounted memory when cursor closed
  docs/appendices/release-notes/unreleased.rst
  server/src/main/java/io/crate/action/sql/Cursor.java
  server/src/main/java/io/crate/planner/DeclarePlan.java
  server/src/test/java/io/crate/action/sql/CursorTest.java
  server/src/test/java/io/crate/integrationtests/CursorITest.java
Labels: ready-to-merge, v/5.2

#13537 Add toString implementation to ShardChangesAction.Request
  server/src/main/java/io/crate/replication/logical/action/ShardChangesAction.java
Labels: ready-to-merge

#13536 Increase assertBusy duration in test_schema_changes_of_multiple_tables_are_replicated
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
Labels: ready-to-merge

#13542 Remove unused format from TransportLogger
  server/src/main/java/org/elasticsearch/transport/TransportLogger.java
Labels: ready-to-merge

#13540 Remove undocumented tracer settings
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/transport/TransportMessageListener.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/main/java/org/elasticsearch/transport/TransportSettings.java
  server/src/test/java/org/elasticsearch/common/settings/ScopedSettingsTests.java
Labels: ready-to-merge

#13545 Track all failures in CountdownFutureCallback
  server/src/main/java/io/crate/concurrent/CountdownFutureCallback.java
  server/src/test/java/io/crate/concurrent/CountdownFutureCallbackTest.java
Labels: ready-to-merge

#13546 Fix add project GHA workflow
  .github/workflows/project.yml
Labels: ready-to-merge

#13543 Fix warnings in ESTestCase
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#13527 Fix pg array parsing of unquoted string witn many whitespaces
  docs/appendices/release-notes/unreleased.rst
  libs/pgwire/src/main/antlr/PgArray.g4
  server/src/test/java/io/crate/protocols/postgres/types/PGArrayTest.java
Labels: ready-to-merge, v/5.1, v/5.2

#13550 bp: Simplify reroute counting in InternalSnapshotsInfoServiceTests
  server/src/test/java/org/elasticsearch/snapshots/InternalSnapshotsInfoServiceTests.java
Labels: ready-to-merge

#13556 Replace LazilyInitializedRerouteService with Supplier/SetOnce
  server/src/main/java/org/elasticsearch/cluster/routing/LazilyInitializedRerouteService.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge

#13551 Fix warnings in IndexRecoveryIT
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#13554 Fix flaky testTransientErrorsDuringRecoveryAreRetried
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#13538 Remove synchronized from MetadataTracker#start
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge

#13547 Remove transport type setting
  server/src/main/java/org/elasticsearch/common/network/NetworkModule.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/org/elasticsearch/indices/IndicesServiceCloseTests.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/test/InternalTestClusterIT.java
  server/src/testFixtures/java/org/elasticsearch/test/test/InternalTestClusterTests.java
Labels: ready-to-merge

#13555 Update Lucene to 9.5
  gradle/version.properties
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicy.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
  server/src/testFixtures/java/org/apache/lucene/tests/util/CrateTestRuleSetupAndRestoreClassEnv.java
Labels: ready-to-merge

#13563 Remove --enable-preview flag
  app/build.gradle
  app/src/bin/crate.bat
  app/src/main/dist/bin/crate
  gradle/javaModule.gradle
Labels: ready-to-merge

#13559 Fix or suppress unchecked/rawtypes warnings in TransportService
  server/src/main/java/org/elasticsearch/transport/TransportService.java
Labels: ready-to-merge
