Repository crate/crate, pull requests merged in 2024-10, with the labels that each got.

#16694 Fixed issue with parted tables and NOT on WHERE clause
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/analyze/ScalarsAndRefsToTrue.java
  server/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  server/src/test/java/io/crate/analyze/ScalarsAndRefsToTrueTest.java
  server/src/testFixtures/java/io/crate/testing/SqlExpressions.java
Labels: ready-to-merge, v/5.8, cla-signed

#16698 Update sql_features
  server/src/main/resources/sql_features.tsv
Labels: ready-to-merge, cla-signed

#16700 Update netty to 4.1.114
  pom.xml
Labels: ready-to-merge, cla-signed

#16651 Introduce capacity parameter for topk
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge, cla-signed

#16707 Fix column pruning for table function
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/planner/operators/TableFunction.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/planner/CorrelatedJoinPlannerTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/StatementClassifierTest.java
  server/src/test/java/io/crate/planner/operators/TableFunctionTest.java
Labels: ready-to-merge, v/5.8, cla-signed

#16703 Fix filtering by `=[[]]`
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/test/java/io/crate/lucene/NestedArrayLuceneQueryBuilderTest.java
Labels: ready-to-merge, cla-signed

#16712 Remove reference to try.crate.io from README
  README.rst
Labels: ready-to-merge, cla-signed

#16713 Fix role granting to not loose existing privileges.
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/role/PrivilegesModifier.java
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
Labels: ready-to-merge, v/5.8, cla-signed

#16716 Release 5.8.4
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16718 Bump version to 5.8.5-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16711 Make UncheckedObjectType a singleton
  server/src/main/java/io/crate/types/UncheckedObjectType.java
  server/src/test/java/io/crate/types/UncheckedObjectTypeTest.java
Labels: ready-to-merge, cla-signed

#16721 Remove duplicate release entry
  docs/appendices/release-notes/5.8.4.rst
Labels: ready-to-merge, cla-signed

#16720 Update forbidden apis to 3.8
  pom.xml
Labels: ready-to-merge, cla-signed

#16725 Update guide links from install-quick to install-tarball
  docs/config/environment.rst
  docs/config/logging.rst
Labels: cla-signed

#16728 Docs: Remove CTEs from unsupported SQL features
  docs/appendices/compatibility.rst
Labels: docs, cla-signed

#16729 Remove unnecessary/dead logic from WithinFunction
  server/src/main/java/io/crate/expression/scalar/geo/WithinFunction.java
Labels: cla-signed

#16732 Documentation: Update to crate-docs-theme 0.35.0
  blackbox/requirements.txt
  docs/requirements.txt
Labels: ready-to-merge, v/5.7, v/5.8, cla-signed

#16740 Release 5.9.0
  docs/appendices/release-notes/5.9.0.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16742 Bump to 5.10.0-SNAPSHOT
  .mergify.yml
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.0.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16743 Bump to 5.9.1-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.1.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16739 Reduce overloads for ClusterStateObserver
  server/src/main/java/io/crate/execution/engine/collect/collectors/ShardStateObserver.java
  server/src/main/java/io/crate/replication/logical/action/ReplayChangesAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/elasticsearch/action/support/ActiveShardsObserver.java
  server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java
  server/src/main/java/org/elasticsearch/cluster/ClusterStateObserver.java
  server/src/main/java/org/elasticsearch/cluster/action/shard/ShardStateAction.java
  server/src/main/java/org/elasticsearch/common/logging/NodeAndClusterIdStateListener.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: ready-to-merge, cla-signed

#16738 Don't use type guessing for estimation of object size.
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16733 Documentation: Improve page about the HTTP endpoint/interface
  docs/interfaces/http.rst
Labels: v/5.8, cla-signed, v/5.9

#16746 Use ColumnIdent instead of String for routing in CreateTableRequest
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/ddl/tables/CreateTableRequestTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge, cla-signed

#16701 Create active shards list only once in IndexingMemoryController
  server/src/main/java/org/elasticsearch/indices/IndexingMemoryController.java
Labels: ready-to-merge, cla-signed

#16724 Fix under accounting of geo shape values
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/types/GeoShapeType.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16755 Fix issue with DROP view/table, dropping irrelevant user privileges
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/role/PrivilegesModifier.java
  server/src/test/java/io/crate/role/PrivilegesModifierTest.java
  server/src/test/java/io/crate/role/metadata/UsersPrivilegesMetadataTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16655 Update bundled JDK to 23
  .github/workflows/main.yml
  pom.xml
Labels: ready-to-merge, cla-signed, v/5.10

#16759 Change JDK to 23 for IntelliJ config
  .idea/misc.xml
Labels: ready-to-merge, cla-signed

#16760 Add `Issue Assignment` to contrib guide
  CONTRIBUTING.rst
Labels: ready-to-merge, cla-signed

#16765 Route `sys.allocations` to the master node to get correct decisions
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/metadata/sys/SysAllocationsTableInfo.java
  server/src/test/java/io/crate/metadata/sys/SysAllocationsTableInfoTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16769 Fix Role.Properties BWC streaming support
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/role/Role.java
  server/src/test/java/io/crate/role/RolePropertiesTest.java
Labels: ready-to-merge, v/5.9

#16773 Fix array related cast optimization, do not apply on explicit casts
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveArrayLengthOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveSubscriptOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/test/java/io/crate/planner/optimizer/symbol/OptimizerTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16777 Fix flaky testCancelRecoveryDuringPhase1
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
Labels: cla-signed

#16778 gha: Run vale checks on ubuntu-22
  .github/workflows/docs.yml
Labels: ready-to-merge, cla-signed

#16660 Remove provided name index setting
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/testFixtures/java/org/elasticsearch/test/InternalSettingsPlugin.java
Labels: ready-to-merge, cla-signed

#16779 Use `uv` for blackbox venv if available
  blackbox/bootstrap.sh
Labels: ready-to-merge, cla-signed

#16781 Add debug logging statements to ReservoirSampler
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16792 Fix Rename prune handling for duplicate parent expressions
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/planner/operators/Rename.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16790 Remove unused/duplicate BytesReferenceStreamInput
  server/src/main/java/org/elasticsearch/common/bytes/BytesReferenceStreamInput.java
Labels: ready-to-merge, cla-signed

#16798 Skip BytesRef creation for BytesArray -> String conversion
  server/src/main/java/org/elasticsearch/common/bytes/BytesArray.java
Labels: ready-to-merge, cla-signed

#16731 Fix `<numeric> = <numeric>` with different precision/scale
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
  server/src/test/java/io/crate/types/TypeCompatibilityTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16800 Fix issues with CHAR comparisons
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/types/CharacterType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfterTest.java
  server/src/test/java/io/crate/lucene/CharacterEqQueryTest.java
  server/src/test/java/io/crate/types/CharacterTypeTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16791 Upgrade to Lucene 9.12.0
  pom.xml
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/CrateCodec.java
  server/src/main/java/org/elasticsearch/index/store/Store.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/io/crate/lucene/IpEqQueryTest.java
  server/src/test/java/org/elasticsearch/index/store/StoreTests.java
  server/src/testFixtures/java/org/elasticsearch/test/CorruptionUtils.java
Labels: ready-to-merge, cla-signed

#16808 tests: Fix warnings and remove unused code
  server/src/test/java/io/crate/monitor/SysInfoUtilTest.java
  server/src/test/java/org/elasticsearch/cluster/block/ClusterBlockTests.java
Labels: ready-to-merge, cla-signed

#16807 tests: Improve PostgreITest tests
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge, cla-signed

#16806 Fix issue with PG de-/serialization of BigDecimal.ZERO
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/protocols/postgres/types/NumericType.java
  server/src/test/java/io/crate/protocols/postgres/types/NumericTypeTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16811 Fix issue with correlated join on primary key
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/analyze/SymbolEvaluator.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16812 tests: Fix deprecation warnings
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  server/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitorTest.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
  server/src/test/java/io/crate/protocols/ssl/SslContextProviderTest.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicyTests.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge, cla-signed

#16761 GeoShapeType.compare must return 0 for equal polygons
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  docs/general/builtins/comparison-operators.rst
  server/src/main/java/io/crate/geo/GeoJSONUtils.java
  server/src/main/java/io/crate/types/GeoShapeType.java
  server/src/test/java/io/crate/integrationtests/GeoShapeIntegrationTest.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16820 tests: Replace `expects` with `assertThatThrownBy` in LogFunctionTest
  server/src/test/java/io/crate/expression/scalar/arithmetic/LogFunctionTest.java
Labels: ready-to-merge, cla-signed

#16821 tests: Replace `expected` with assertThatThrownBy
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/ValueNormalizerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, cla-signed

#16822 tests: group tests for trigonometric functions
  server/src/main/java/io/crate/expression/symbol/Literal.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctionsTest.java
Labels: ready-to-merge, cla-signed

#16818 Implement `NUMERIC` overload for arithmetic functions
  docs/appendices/release-notes/5.10.0.rst
  docs/general/builtins/scalar-functions.rst
  pom.xml
  server/pom.xml
  server/src/main/java/io/crate/expression/scalar/arithmetic/AbsFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/CeilFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/FloorFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/RoundFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/SquareRootFunction.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/AbsFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/CeilFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/ExpFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/FloorFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/RoundFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/SquareRootFunctionTest.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
Labels: ready-to-merge, cla-signed

#16824 Add support for `NUMERIC` arg to `log()` and `ln()`
  docs/appendices/release-notes/5.10.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/LogFunction.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/LogFunctionTest.java
Labels: ready-to-merge, cla-signed

#16825 Add support for NUMERIC arg to trigonometric funcs
  docs/appendices/release-notes/5.10.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  server/src/main/java/io/crate/expression/symbol/Literal.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctionsTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
Labels: ready-to-merge, cla-signed

#16832 Change ChecksumBlobStoreFormat to use Writeable instead of xContent
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepository.java
  plugins/es-repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureRepositoryPlugin.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureRepositorySettingsTests.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RepositoryPlugin.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryTests.java
  plugins/es-repository-url/src/main/java/org/elasticsearch/plugin/repository/url/URLRepositoryPlugin.java
  plugins/es-repository-url/src/main/java/org/elasticsearch/repositories/url/URLRepository.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepository.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepositoryPlugin.java
  server/src/main/java/org/elasticsearch/common/compress/Compressor.java
  server/src/main/java/org/elasticsearch/common/compress/DeflateCompressor.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshot.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/SnapshotFiles.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/RepositoryPlugin.java
  server/src/main/java/org/elasticsearch/repositories/RepositoriesModule.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java
  server/src/main/java/org/elasticsearch/transport/CompressibleBytesOutputStream.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/test/java/org/elasticsearch/snapshots/BlobStoreFormatIT.java
  server/src/test/java/org/elasticsearch/snapshots/BlobStoreIncrementalityIT.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepository.java
  server/src/test/java/org/elasticsearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
Labels: cla-signed

#16835 Tests: Flush response header immediately.
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSBlobContainerRetriesTests.java
Labels: ready-to-merge, cla-signed

#16723 Fix `<numeric> cmp <numeric>`
  docs/appendices/release-notes/5.8.5.rst
  docs/appendices/release-notes/5.9.1.rst
  server/src/main/java/io/crate/expression/operator/GtOperator.java
  server/src/main/java/io/crate/expression/operator/GteOperator.java
  server/src/main/java/io/crate/expression/operator/LtOperator.java
  server/src/main/java/io/crate/expression/operator/LteOperator.java
  server/src/main/java/io/crate/types/NumericEqQuery.java
  server/src/main/java/io/crate/types/NumericStorage.java
  server/src/test/java/io/crate/lucene/NumericEqQueryTest.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16843 docs: Add NOTE for HTTP/Json limitation for NUMERIC values
  docs/general/ddl/data-types.rst
Labels: ready-to-merge, docs, v/5.8, cla-signed, v/5.9

#16840 Remove release notes; not backported to 5.8
  docs/appendices/release-notes/5.8.5.rst
Labels: ready-to-merge, cla-signed, v/5.9

#16842 Update JDK to 23.0.1
  pom.xml
Labels: ready-to-merge, cla-signed

#16848 Fix tiny typo in the partitioned tables docs
  docs/general/ddl/partitioned-tables.rst
Labels: cla-signed

#16847 Correctly handle Lists in TestingHelpers.printedTable()
  server/src/test/java/io/crate/expression/tablefunctions/MatchesFunctionTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/ScalarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge, cla-signed

#16852 Don't lowercase exception names for ElasticsearchException
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
Labels: ready-to-merge, cla-signed

#16855 Fix return type of math functions with `NUMERIC` args
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/LogFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/SquareRootFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/AbsFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/CeilFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/ExpFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/FloorFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/LogFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/RoundFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/SquareRootFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctionsTest.java
Labels: ready-to-merge, cla-signed

#16859 Enable annotation processing for benchmarks
  pom.xml
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16763 Add node settings to provide default JWT configuration
  app/src/main/dist/config/crate.yml
  docs/admin/auth/hba.rst
  docs/admin/auth/methods.rst
  docs/appendices/release-notes/5.10.0.rst
  docs/config/node.rst
  docs/sql/statements/alter-role.rst
  docs/sql/statements/create-user.rst
  server/src/main/java/io/crate/auth/AuthSettings.java
  server/src/main/java/io/crate/auth/Credentials.java
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/main/java/io/crate/auth/HttpAuthUpstreamHandler.java
  server/src/main/java/io/crate/auth/JWTAuthenticationMethod.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/main/java/io/crate/role/Roles.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/auth/CredentialsTest.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
Labels: ready-to-merge, cla-signed

#16862 Fix filtering by unbounded numeric literal, `= <numeric>::numeric`
  server/src/main/java/io/crate/types/NumericEqQuery.java
  server/src/test/java/io/crate/lucene/NumericEqQueryTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16871 docs: Remove reference to article about visual join representation
  docs/concepts/joins.rst
Labels: ready-to-merge, cla-signed

#16866 Fix filtering by unbounded numeric array literal, `= <numeric_array>::numeric[]`
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/main/java/io/crate/types/NumericEqQuery.java
  server/src/test/java/io/crate/lucene/NumericEqQueryTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16880 Update to Admin UI 1.24.8
  app/pom.xml
Labels: ready-to-merge, cla-signed

#16882 Bump version to 5.9.2-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.2.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#15976 Remove undocumented and unexposed index priority
  server/src/main/java/io/crate/replication/logical/LogicalReplicationSettings.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/gateway/PriorityComparator.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationServiceTests.java
Labels: ready-to-merge, cla-signed

#16879 Move AST/show-create table specific logic from TableParameters
  server/src/main/java/io/crate/analyze/TableInfoToAST.java
  server/src/main/java/io/crate/analyze/TableParameters.java
Labels: ready-to-merge, cla-signed

#16874 Remove undocumented shard.check_on_startup index setting
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#16877 Rewrite right-outer-join to left-outer-hash-join
  docs/appendices/release-notes/5.10.0.rst
  docs/general/dql/joins.rst
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteRightOuterJoinToHashJoin.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/OuterJoinRewriteTest.java
Labels: ready-to-merge, cla-signed

#16884 Fix BWC issue when reading Role.Properties from the cluster state
  docs/appendices/release-notes/5.9.2.rst
  server/src/main/java/io/crate/role/Role.java
  server/src/test/java/io/crate/role/RolePropertiesTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16886 Remove preserveExisting flag from UpdateSettingsRequest
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsRequest.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
Labels: ready-to-merge, cla-signed

#16889 Bump version to 5.9.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16894 Improve join-reordering explaination in docs
  docs/general/dql/joins.rst
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9

#16893 Fix reference tree recursion when children have the same name as parent
  server/src/main/java/io/crate/metadata/ReferenceTree.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, cla-signed

#16897 Don't used nested objects in ObjectTypeTest
  server/src/test/java/io/crate/types/ObjectTypeTest.java
Labels: ready-to-merge, cla-signed

#16899 Remove duplicate number of shards presence check
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
Labels: ready-to-merge, cla-signed

#16898 Rename TableCreator & AlterTableOperation
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableClient.java
  server/src/main/java/io/crate/metadata/IndexParts.java
  server/src/main/java/io/crate/planner/DependencyCarrier.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableAddColumnPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropCheckConstraintPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropColumnPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableOpenClosePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableRenameTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateTablePlan.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/execution/ddl/tables/AlterTableOperationTest.java
  server/src/test/java/io/crate/integrationtests/DanglingIndicesIntegrationTest.java
Labels: ready-to-merge, cla-signed

#16901 Enable cast from array of text to array of object
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/expression/symbol/Symbol.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16870 Fix filtering by comparisions of different data types
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/RemoveRedundantImplicitCastOverReferences.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/NumericEqQueryTest.java
Labels: ready-to-merge, cla-signed, v/5.9
