Repository crate/crate, pull requests merged in 2024-02, with the labels that each got.

#15487 Do not use PkLookUp if any pk cols are under NOT predicate
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/ColumnsUnderNotPredicateFinderTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.6

#15502 Update packaging related release notes, note RPM change
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/5.3.8.rst
  docs/appendices/release-notes/5.4.7.rst
  docs/appendices/release-notes/5.5.2.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5, v/5.6

#15501 Ignore unsupported float_array type in NestedArrayTypeTest
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
Labels: ready-to-merge

#15509 Update related release notes to mention the public CVE and reporter
  docs/appendices/release-notes/5.3.9.rst
  docs/appendices/release-notes/5.4.8.rst
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.6.1.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5, v/5.6

#15508 Adjust "machine data" mention
  docs/index.rst
Labels: docs

#15514 Apply additional `null` filter if the query is equivalent to `null`
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, v/5.6

#15523 Add a minor note about usage of MATCH with multiple columns
  docs/general/dql/fulltext.rst
Labels: ready-to-merge, docs

#15528 Add numericPrecision method to DataType
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/main/java/io/crate/types/ByteType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/main/java/io/crate/types/IntegerType.java
  server/src/main/java/io/crate/types/LongType.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/main/java/io/crate/types/ShortType.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
Labels: ready-to-merge

#15532 Move fix entries accidentally went into 5.6.1 to 5.6.2
  docs/appendices/release-notes/5.6.1.rst
  docs/appendices/release-notes/5.6.2.rst
Labels: ready-to-merge, v/5.6

#15525 Include numeric parameters when binding function return types
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/metadata/functions/BoundSignature.java
  server/src/main/java/io/crate/metadata/functions/SignatureBinder.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/main/java/io/crate/types/TypeCompatibility.java
  server/src/main/java/io/crate/types/TypeSignature.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
  server/src/test/java/io/crate/types/TypeCompatibilityTest.java
Labels: ready-to-merge, v/5.6

#15535 Fixed TRIM/LTRIM/RTRIM/BTRIM on null 2nd arg
  docs/appendices/release-notes/5.6.2.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java
  server/src/test/java/io/crate/expression/scalar/string/TrimFunctionTest.java
Labels: ready-to-merge, v/5.6

#15531 Close SecureString password when created in HTTP
  server/src/main/java/io/crate/auth/Credentials.java
  server/src/main/java/io/crate/auth/HttpAuthUpstreamHandler.java
  server/src/main/java/io/crate/protocols/http/Headers.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/protocols/http/HeadersTest.java
Labels: ready-to-merge

#15540 Fix `NullPointerException` on rename table due to privileges
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/role/RoleManagerDDLModifier.java
  server/src/test/java/io/crate/role/RoleManagerDDLModifierTest.java
  server/src/test/java/io/crate/role/metadata/RolesHelper.java
Labels: ready-to-merge, v/5.6

#15538 Prevent actions that affect roles and privileges during rolling upgrade
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/role/RoleManagerDDLModifier.java
  server/src/test/java/io/crate/role/RoleManagerDDLModifierTest.java
Labels: ready-to-merge, v/5.6

#15520 Prevent duplicate SharedShardContext.readerId
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
  server/src/test/java/io/crate/execution/jobs/SharedShardContextsTest.java
Labels: ready-to-merge, v/5.6

#15550 Update netty to 4.1.107
  pom.xml
Labels: ready-to-merge

#15552 Fix PK Lookup with cast on the PK column
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.6

#15543 Enforce searchPath order when resolving tables and views
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/main/java/io/crate/metadata/table/SchemaInfo.java
  server/src/main/java/io/crate/metadata/view/ViewInfo.java
  server/src/main/java/io/crate/metadata/view/ViewInfoFactory.java
  server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java
  server/src/test/java/io/crate/metadata/pgcatalog/OidHashTest.java
Labels: ready-to-merge, v/5.6

#15555 Fixed issue with symbol Optimizer not optimizing params
  server/src/main/java/io/crate/expression/symbol/SymbolType.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveArrayLengthOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveReferenceCastToLiteralCastOnAnyOperatorsWhenLeftIsReference.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveReferenceCastToLiteralCastOnAnyOperatorsWhenRightIsReference.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/MoveSubscriptOnReferenceCastToLiteralCastInsideOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInLikeOperators.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/OptimizerTest.java
Labels: ready-to-merge, v/5.6

#15556 tests: Introduce an abstract base class for EqualityExtractorTest
  server/src/test/java/io/crate/analyze/where/ColumnsUnderNotPredicateFinderTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorBaseTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.6

#15561 Release 5.6.2
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15564 Reflect release 5.6.3
  docs/appendices/release-notes/5.6.2.rst
  docs/appendices/release-notes/5.6.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15563 Bump version to 5.6.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.6.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15560 Add the CURRENT_ROLE scalar as an alias to CURRENT_USER
  docs/appendices/release-notes/5.7.0.rst
  docs/general/builtins/scalar-functions.rst
  docs/sql/general/lexical-structure.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/test/java/io/crate/expression/tablefunctions/PgGetKeywordsFunctionTest.java
  server/src/test/java/io/crate/role/scalar/UserFunctionTest.java
Labels: ready-to-merge

#15567 Make HttpTestServer request handling configurable
  server/src/test/java/io/crate/http/HttpTestServer.java
  server/src/test/java/io/crate/udc/ping/PingTaskTest.java
Labels: ready-to-merge

#15495 Assert collect task is not completed before fall-back to resume
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
Labels: ready-to-merge

#15569 Fix NPE thrown when USING clause contained unknown columns
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.6

#15570 Add a Metadata.custom(type, defaultValue) overload
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/fdw/AddForeignTableTask.java
  server/src/main/java/io/crate/fdw/AddServerTask.java
  server/src/main/java/io/crate/fdw/DropForeignTableTask.java
  server/src/main/java/io/crate/fdw/DropServerTask.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge

#15574 Update assertj and junit5
  pom.xml
Labels: ready-to-merge

#15575 Update mockito to 5.10.0
  pom.xml
  server/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/RemoteCollectorTest.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
Labels: ready-to-merge

#15576 Add information_schema.user_mappings
  docs/general/information-schema.rst
  docs/sql/statements/create-user-mapping.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/fdw/ServersMetadata.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/information/UserMappingsTableInfo.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#15578 Update to Lucene 9.10.0
  pom.xml
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
Labels: ready-to-merge

#15517 Add support for Google Cloud Storage repositories
  app/pom.xml
  app/src/assembly/src.xml
  docs/appendices/release-notes/5.7.0.rst
  docs/sql/statements/create-repository.rst
  plugins/es-repository-azure/pom.xml
  plugins/repository-gcs/pom.xml
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSBlobContainer.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSBlobStore.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepository.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepositoryPlugin.java
  plugins/repository-gcs/src/main/resources/plugin-descriptor.properties
  plugins/repository-gcs/src/test/java/io/crate/gcs/FakeOAuth2HttpHandler.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSHttpHandler.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSSnapshotIntegrationTest.java
  pom.xml
Labels: ready-to-merge

#15579 Change some deprecated newSlowSetQuery calls
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/BooleanType.java
  server/src/main/java/io/crate/types/IpType.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#15573 Validate CREATE SERVER options
  docs/admin/fdw.rst
  server/src/main/java/io/crate/fdw/CreateServerRequest.java
  server/src/main/java/io/crate/fdw/ForeignDataWrapper.java
  server/src/main/java/io/crate/fdw/ForeignDataWrappers.java
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/main/java/io/crate/fdw/ServersMetadata.java
  server/src/main/java/io/crate/planner/CreateServerPlan.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/org/elasticsearch/common/settings/Settings.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
  server/src/test/java/io/crate/fdw/JdbcForeignDataWrapperTest.java
  server/src/test/java/io/crate/fdw/ServersMetadataTest.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#15581 Validate options in CREATE FOREIGN TABLE
  server/src/main/java/io/crate/fdw/CreateForeignTableRequest.java
  server/src/main/java/io/crate/fdw/ForeignDataWrapper.java
  server/src/main/java/io/crate/fdw/ForeignDataWrappers.java
  server/src/main/java/io/crate/fdw/ForeignTable.java
  server/src/main/java/io/crate/fdw/ForeignTablesMetadata.java
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/main/java/io/crate/planner/CreateForeignTablePlan.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/test/java/io/crate/fdw/AddForeignTableTaskTest.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
  server/src/test/java/io/crate/fdw/ForeignTablesMetadataTest.java
  server/src/test/java/io/crate/fdw/JdbcForeignDataWrapperTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#15583 Document foreign_servers and foreign_tables in information schema docs
  docs/general/information-schema.rst
Labels: ready-to-merge

#15572 Notify pgwire clients that `standard_conforming_strings` is `on`
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge, v/5.6

#15584 Add information_schema.foreign_table_options
  docs/general/information-schema.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/fdw/ForeignTable.java
  server/src/main/java/io/crate/fdw/ForeignTablesMetadata.java
  server/src/main/java/io/crate/metadata/information/ForeignTableOptionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#15589 Fix support for joins on foreign tables
  server/src/main/java/io/crate/execution/dsl/phases/ForeignCollectPhase.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
Labels: ready-to-merge

#15586 Add information_schema.foreign_server_options
  docs/general/information-schema.rst
  docs/sql/statements/create-server.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/fdw/ServersMetadata.java
  server/src/main/java/io/crate/metadata/information/ForeignServerOptionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#15593 Fix issues with PostgreSQL style interval strings
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/interval/PGIntervalParser.java
  server/src/test/java/io/crate/interval/IntervalParserTest.java
Labels: ready-to-merge, v/5.6

#15596 Fix issue with duplicate units for psql style INTERVALs
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/interval/PGIntervalParser.java
  server/src/test/java/io/crate/interval/IntervalParserTest.java
Labels: ready-to-merge, v/5.6

#15599 Amend titles of new FDW doc entries to render verbatim
  docs/sql/statements/create-user-mapping.rst
  docs/sql/statements/drop-foreign-table.rst
  docs/sql/statements/drop-server.rst
  docs/sql/statements/drop-user-mapping.rst
Labels: ready-to-merge, docs

#15600 Documentation: Fix single-spot indentation flaw
  docs/config/cluster.rst
Labels: ready-to-merge, docs

#15601 Fix PK lookup with OR and non-PK column
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/ColumnsUnderOrOperatorFinderTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.6

#15605 Re-use signatures() for findFunctionSignatureByOid
  server/src/main/java/io/crate/metadata/Functions.java
Labels: ready-to-merge

#15610 Update GraalVM version to 23.0.3
  pom.xml
Labels: ready-to-merge

#15609 Update PostgreSQL JDBC to 42.7.2
  pom.xml
Labels: ready-to-merge

#15614 Convert FunctionProvider to record
  server/src/main/java/io/crate/expression/AbstractFunctionModule.java
  server/src/main/java/io/crate/metadata/FunctionProvider.java
  server/src/main/java/io/crate/metadata/Functions.java
Labels: ready-to-merge

#15615 Fix typing around sum/avg array functions
  server/src/main/java/io/crate/expression/scalar/ArrayAvgFunction.java
  server/src/main/java/io/crate/expression/scalar/ArraySumFunction.java
  server/src/main/java/io/crate/expression/scalar/array/ArraySummationFunctions.java
  server/src/main/java/io/crate/types/DataTypes.java
Labels: ready-to-merge

#15617 Remove modulesFile from Environment
  server/src/main/java/org/elasticsearch/env/Environment.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/PluginsService.java
Labels: ready-to-merge

#15618 Factor out DropRoleTask from TransportDropRoleAction
  server/src/main/java/io/crate/role/DropRoleTask.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge

#15598 Integrate open-search google cloud plugin retry logic
  docs/sql/statements/create-repository.rst
  plugins/repository-gcs/pom.xml
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSBlobContainer.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSBlobStore.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSClientSettings.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepository.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRepositoryPlugin.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSRetryingInputStream.java
  plugins/repository-gcs/src/main/java/io/crate/gcs/GCSService.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSBlobContainerRetriesTests.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSBlobStoreContainerTests.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSHttpHandler.java
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSSnapshotIntegrationTest.java
  pom.xml
Labels: ready-to-merge

#15612 Refactor detection for PK under NOT predicate
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/ColumnsUnderNotPredicateFinderTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.6

#15621 Add jdwp.agent to jlink bundle; fix attach debug configuration
  .vscode/launch.json
  pom.xml
Labels: ready-to-merge

#15628 Use Roles default implementations in StubRoleManager
  server/src/test/java/io/crate/analyze/CreateUserMappingAnalyzerTest.java
  server/src/test/java/io/crate/planner/statement/SetSessionAuthorizationPlanTest.java
  server/src/testFixtures/java/io/crate/role/StubRoleManager.java
Labels: ready-to-merge

#15591 Add information_schema.user_mapping_options
  docs/admin/fdw.rst
  docs/general/information-schema.rst
  docs/sql/statements/create-foreign-table.rst
  docs/sql/statements/create-server.rst
  docs/sql/statements/create-user-mapping.rst
  docs/sql/statements/drop-server.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/fdw/CreateUserMappingRequest.java
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/main/java/io/crate/fdw/ServersMetadata.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaInfo.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/information/UserMappingOptionsTableInfo.java
  server/src/main/java/io/crate/planner/CreateUserMappingPlan.java
  server/src/test/java/io/crate/fdw/ServersMetadataTest.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#15635 Fix a bug introduced by #15591
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
Labels: ready-to-merge
