Repository crate/crate, pull requests merged in 2024-09, with the labels that each got.

#16547 Remove unused properties from IndexStats and IndexShardStats
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndexShardStats.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndexStats.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsResponse.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/TransportIndicesStatsAction.java
  server/src/test/java/io/crate/integrationtests/DiskThresholdDeciderIT.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge

#16558 Fix ambiguous symbol lookup
  docs/appendices/release-notes/5.8.3.rst
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  server/src/main/java/io/crate/expression/symbol/ScopedSymbol.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge, v/5.8

#16565 Fix nullability issue for CAST on object columns
  docs/appendices/release-notes/5.8.3.rst
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.8

#16570 Don't check column policy of object ref per inner value
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
Labels: ready-to-merge

#16578 tests: Fix flakiness due to random NUMERIC data generation
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge

#16579 Add support to EXPLAIN ANALYZE a MultiPhase (SubQueries) plan
  docs/appendices/release-notes/5.9.0.rst
  server/src/main/java/io/crate/execution/MultiPhaseExecutor.java
  server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  server/src/test/java/io/crate/integrationtests/ExplainAnalyzeIntegrationTest.java
  server/src/test/java/io/crate/planner/ExplainPlannerTest.java
Labels: ready-to-merge

#16580 tests: Replace `refresh()` with `execute("refresh table XXX")`
  plugins/es-analysis-common/src/test/java/io/crate/integrationtests/FulltextAnalyzerResolverTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/AnyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ArithmeticIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CastIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CircuitBreakerIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/integrationtests/CountStarIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableAsIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DefaultSchemaIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DiskThresholdDeciderIT.java
  server/src/test/java/io/crate/integrationtests/EmptyStringRoutingIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/FixCorruptedMetadataCommandITest.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/OuterJoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RelationAliasITest.java
  server/src/test/java/io/crate/integrationtests/SchemaAndRelationNamesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ShardingUpsertIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SqlAlchemyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/StorageOptionsITest.java
  server/src/test/java/io/crate/integrationtests/SysHealthITest.java
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
  server/src/test/java/io/crate/integrationtests/TasksServiceIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/WherePKIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/disruption/seqno/SequenceConsistencyIT.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/test/java/org/elasticsearch/snapshots/BlobStoreIncrementalityIT.java
Labels: ready-to-merge

#16576 Re-use addColumns in IndexerTest
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#16584 Release 5.7.5
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.7.5.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16586 Reflect release 5.7.5
  docs/appendices/release-notes/5.7.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16587 Reflect release 5.7.5
  docs/appendices/release-notes/5.7.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16590 Update netty to 4.1.113
  pom.xml
Labels: ready-to-merge

#16598 Reduce amount of `validateAlias` variants
  server/src/main/java/org/elasticsearch/cluster/metadata/AliasValidator.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
Labels: ready-to-merge

#16600 Move AzureHttpHandler to a new module
  libs/azure-testing/pom.xml
  libs/azure-testing/src/testFixtures/java/io/crate/azure/testing/AzureHttpHandler.java
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  pom.xml
Labels: ready-to-merge, cla-signed

#16603 Update PULL_REQUEST_TEMPLATE.md - removed CLA check
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#16604 Add `cla-signed` label as pre-requisite to mergify
  .mergify.yml
Labels: ready-to-merge, cla-signed

#16610 Revert "Add `cla-signed` label as pre-requisite to mergify"
  .mergify.yml
Labels: ready-to-merge, cla-signed

#16613 Fix flaky test_explain_analyze_query_execution_contains_shard_and_partition_information
  server/src/test/java/io/crate/integrationtests/ExplainAnalyzeIntegrationTest.java
Labels: ready-to-merge, cla-signed

#16612 Add cla-signed as prerequisite to mergify
  .mergify.yml
Labels: ready-to-merge, cla-signed

#16618 Remove unused local variable from Session
  server/src/main/java/io/crate/action/sql/Session.java
Labels: ready-to-merge, cla-signed

#13965 add precision parameter to round function
  docs/appendices/release-notes/5.9.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/RoundFunction.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/RoundFunctionTest.java
Labels: tool: Tableau, cla-signed

#16621 Add lucene query generation for `IS DISTINCT` queries when possible
  docs/appendices/release-notes/5.9.0.rst
  docs/general/dql/selects.rst
  server/src/main/java/io/crate/expression/operator/DistinctFrom.java
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/test/java/io/crate/expression/predicate/DistinctFromTest.java
Labels: ready-to-merge, cla-signed

#16602 Specialize createIndex for create-table
  server/src/main/java/io/crate/execution/ddl/Templates.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
Labels: ready-to-merge, cla-signed

#16626 Extract names of sessions settings to constants
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
Labels: ready-to-merge, cla-signed

#16625 Remove type specific logic from TypeCompatibility; support array_sum/avg([])
  docs/appendices/release-notes/5.9.0.rst
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/TypeCompatibility.java
  server/src/test/java/io/crate/expression/scalar/ArrayAvgFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArraySumFunctionTest.java
Labels: ready-to-merge, cla-signed

#16632 Release 5.8.3
  docs/appendices/release-notes/5.8.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16620 Implement `sys.sessions` table
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.0.rst
  docs/config/session.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  server/src/main/java/io/crate/metadata/sys/SysSessionsTableInfo.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/protocols/postgres/AuthenticationContext.java
  server/src/main/java/io/crate/protocols/postgres/ConnectionProperties.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/integrationtests/BaseRolesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/integrationtests/UserSessionIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
  server/src/test/java/org/elasticsearch/indices/IndicesServiceCloseTests.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#16633 Bump version to 5.8.4-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.4.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16631 Support Azure Blob Storage in COPY TO/COPY FROM
  app/pom.xml
  app/src/assembly/src.xml
  docs/appendices/release-notes/5.9.0.rst
  docs/sql/statements/copy-from.rst
  docs/sql/statements/copy-to.rst
  libs/azure-testing/src/testFixtures/java/io/crate/azure/testing/AzureHttpHandler.java
  plugins/crate-copy-azure/pom.xml
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureBlobStorageSettings.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureCopyPlugin.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureFileInput.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureFileInputFactory.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureFileOutput.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureFileOutputFactory.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/AzureURI.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/OperatorHelper.java
  plugins/crate-copy-azure/src/main/java/io/crate/copy/azure/SharedAsyncExecutor.java
  plugins/crate-copy-azure/src/main/resources/plugin-descriptor.properties
  plugins/crate-copy-azure/src/test/java/io/crate/copy/azure/AzureBlobStorageSettingsTest.java
  plugins/crate-copy-azure/src/test/java/io/crate/copy/azure/AzureCopyIntegrationTest.java
  plugins/crate-copy-azure/src/test/java/io/crate/copy/azure/AzureURITest.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotIntegrationTest.java
  pom.xml
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
Labels: ready-to-merge, cla-signed

#16634 Reflect release 5.8.3
  docs/appendices/release-notes/5.8.3.rst
  docs/appendices/release-notes/5.8.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16629 Narrow range of bigint to account for null-sentinel
  docs/appendices/release-notes/5.9.0.rst
  docs/general/builtins/aggregation.rst
  docs/general/ddl/data-types.rst
  extensions/functions/src/test/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationTest.java
  server/src/main/java/io/crate/execution/dml/LongIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CmpByAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge, cla-signed

#16628 Try fix flaky testIteratorDoesNotHandleRejectedExecutionException
  libs/dex/src/test/java/io/crate/data/AsyncCompositeBatchIteratorTest.java
Labels: ready-to-merge, cla-signed

#16637 Avoid array copy in md5 scalar
  server/src/main/java/io/crate/expression/scalar/string/HashFunctions.java
Labels: cla-signed

#16642 Add duplicate object child column name detection, throw an error
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge, v/5.8, cla-signed

#16639 Remove deprecated IntegTestCase.refresh()
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CustomSchemaIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RegexpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RenameTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/SeqNoBasedOCCIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#16654 Move INDICES_MAX_CLAUSE_COUNT_SETTING to LuceneQueryBuilder
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/search/SearchModule.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
Labels: ready-to-merge, cla-signed

#16656 Merge CountOperation/InternalCountOperation
  server/src/main/java/io/crate/execution/engine/collect/count/CountOperation.java
  server/src/main/java/io/crate/execution/engine/collect/count/InternalCountOperation.java
  server/src/test/java/io/crate/execution/engine/collect/count/CountOperationTest.java
  server/src/test/java/io/crate/execution/jobs/CountTaskTest.java
Labels: cla-signed

#16658 Try fix flaky testIteratorDoesNotHandleRejectedExecutionException
  libs/dex/src/test/java/io/crate/data/AsyncCompositeBatchIteratorTest.java
Labels: ready-to-merge, cla-signed

#16661 Polish ObjectType
  server/src/main/java/io/crate/expression/scalar/SubscriptFunctions.java
  server/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/metadata/doc/DocIndexMetadataTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
Labels: ready-to-merge, cla-signed

#16657 Replace NullArrayType with ArrayType<UndefinedType>
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/expression/symbol/Symbol.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/NullArrayType.java
  server/src/main/java/io/crate/types/UndefinedType.java
  server/src/test/java/io/crate/DataTypeTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge, cla-signed

#16663 Add undocumented retry count setting; use in test_decommission
  blackbox/test_decommission.py
  server/src/main/java/io/crate/Constants.java
  server/src/main/java/io/crate/session/RetryOnFailureResultReceiver.java
  server/src/main/java/io/crate/session/Session.java
  server/src/main/java/io/crate/session/Sessions.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/session/RetryOnFailureResultReceiverTest.java
Labels: ready-to-merge, cla-signed

#16670 Fix integer overflow at the ShardsLimitValidator
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/org/elasticsearch/indices/ShardLimitValidator.java
  server/src/test/java/org/elasticsearch/indices/ShardLimitValidatorTests.java
Labels: ready-to-merge, v/5.8, cla-signed

#16672 Don't convert numbers or booleans to text for undefined type in SourceParser
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge, v/5.8, cla-signed

#16677 Use 127.0.0.1 as account.endpoint_suffix in tests.
  plugins/crate-copy-azure/src/test/java/io/crate/copy/azure/AzureCopyIntegrationTest.java
Labels: ready-to-merge, cla-signed

#16680 Allow INSERT FROM VALUES to consume null arrays
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/analyze/ValuesAnalyzerTest.java
Labels: ready-to-merge, cla-signed

#16682 Handle concurrent calls at the QueryProfiler
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/org/elasticsearch/search/profile/query/QueryProfiler.java
  server/src/test/java/org/elasticsearch/search/profile/query/QueryProfilerTest.java
Labels: ready-to-merge, v/5.8, cla-signed

#16693 Suppress native access warning; enable use of incubator.vector
  app/src/main/dist/bin/crate
  app/src/main/dist/bin/crate.bat
  pom.xml
Labels: ready-to-merge, cla-signed

#16695 Fix comparison and ORDER BY of IPs
  docs/appendices/release-notes/5.8.4.rst
  server/src/main/java/io/crate/types/IpType.java
  server/src/main/java/org/elasticsearch/common/network/InetAddresses.java
  server/src/test/java/io/crate/expression/operator/CmpOperatorTest.java
  server/src/test/java/io/crate/integrationtests/OrderByITest.java
Labels: ready-to-merge, v/5.8, cla-signed
