Repository crate/crate, pull requests merged in 2024-08, with the labels that each got.

#16441 Add testcase for returning numeric type from UDFs
  extensions/lang-js/src/test/java/io/crate/operation/language/PolyglotValuesTest.java
Labels: ready-to-merge

#16443 Make sure MetaDataTracker is inactive first, when stopped
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
Labels: ready-to-merge, v/5.7, v/5.8

#16447 Optimize short and byte for topk aggregation
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16452 Ensure topk test data generation does not contain duplicate values
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16453 Add topk optimization for timestamp
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16454 Enable doc-values for ip-adresses in top-k
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16457 Clean up topk testcase
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16455 Add assertion for doc-value-aggregator in top-k tests
  server/src/test/java/io/crate/execution/engine/aggregation/impl/TopKAggregationTest.java
Labels: ready-to-merge

#16456 Add schema property to NodeInfo/ShardInfo JMX bean
  blackbox/test_jmx.py
  docs/appendices/release-notes/5.8.2.rst
  extensions/jmx-monitoring/src/main/java/io/crate/beans/NodeInfo.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/ShardInfo.java
Labels: ready-to-merge, v/5.8

#16459 Fix handling of un-merged ordered result in INSERT INTO
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/io/crate/planner/operators/Insert.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.8

#16458 Add support for explaining insert statements
  docs/appendices/release-notes/5.9.0.rst
  server/src/main/java/io/crate/analyze/ExplainStatementAnalyzer.java
  server/src/test/java/io/crate/planner/ExplainPlannerTest.java
Labels: ready-to-merge

#16464 Add a reference to hyperloglog in count distinct docs
  docs/general/builtins/aggregation.rst
Labels: ready-to-merge

#16451 Fix ARRAY_LENGTH on array sub-cols of object arrays to fall back to generic function query
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/io/crate/expression/scalar/ArrayUpperFunction.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryBuilderBeforeV590Test.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryBuilderTest.java
Labels: ready-to-merge, v/5.8

#16466 Simplify topk aggregation code and test setup
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#16467 Allow users with AL permission to execute alter role
  docs/sql/statements/alter-role.rst
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge

#16469 Remove datatype field from topk states
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
Labels: ready-to-merge

#16475 Move wait_for_completion setting to CopyStatementSettings
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
Labels: ready-to-merge

#16480 Move CSV settings to copyCopyFromSettings.
  server/src/main/java/io/crate/analyze/CopyStatementSettings.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
Labels: ready-to-merge

#16483 Fix link to google service account docs
  docs/sql/statements/create-repository.rst
Labels: ready-to-merge

#16482 Ensure that partition column values are always added to _doc
  docs/appendices/release-notes/5.9.0.rst
  docs/sql/statements/copy-to.rst
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/export/FileWriterCountCollector.java
  server/src/main/java/io/crate/execution/engine/export/FileWriterProjector.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchOperation.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/jobs/PKLookupTask.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/DocCollectorExpression.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/PartitionValueInjector.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocLevelCollectTest.java
  server/src/test/java/io/crate/execution/engine/export/FileWriterCountCollectorTest.java
  server/src/test/java/io/crate/execution/engine/export/FileWriterProjectorTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#16360 Fix `refMatchesAnyArrayLiteral` for empty arrays or array of nulls
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/io/crate/expression/operator/any/AnyEqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNotLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyRangeOperator.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: bug, ready-to-merge, v/5.8

#16486 Enable missing version-chooser in documentation
  docs/conf.py
Labels: ready-to-merge, v/3.3, v/4.8, v/5.7, v/5.8

#16498 docs: Rephrase changelog entry & warning for COPY TO on parted tables
  docs/appendices/release-notes/5.9.0.rst
Labels: ready-to-merge

#16495 Fix ClassCastException from EqOperator on nested arrays
  libs/shared/src/main/java/io/crate/common/collections/Lists.java
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/test/java/io/crate/lucene/NestedArrayLuceneQueryBuilderTest.java
Labels: ready-to-merge, v/5.8

#16481 Fix unchecked/rawtype warnings in ArrayMinFunction
  server/src/main/java/io/crate/expression/scalar/ArrayMinFunction.java
Labels: ready-to-merge

#16471 Add support for numeric storage
  docs/appendices/release-notes/5.9.0.rst
  docs/general/ddl/data-types.rst
  extensions/lang-js/src/test/java/io/crate/operation/language/PolyglotValuesTest.java
  server/src/main/java/io/crate/analyze/validator/SemanticSortValidator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageStateType.java
  server/src/main/java/io/crate/execution/engine/sort/LuceneSort.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/IntegerColumnReference.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/NumericEqQuery.java
  server/src/main/java/io/crate/types/NumericStorage.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/test/java/io/crate/analyze/parser/TypeSignatureParserTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/expression/operator/EqOperatorTest.java
  server/src/test/java/io/crate/expression/predicate/FieldExistsQueryTest.java
  server/src/test/java/io/crate/expression/predicate/NotPredicateTest.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/lucene/ArrayLengthQueryTest.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
  server/src/test/java/io/crate/testing/DataTypeTestingTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
  server/src/test/java/io/crate/types/TypeCompatibilityTest.java
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#16485 Optimize numeric lucene queries
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/types/NumericEqQuery.java
  server/src/main/java/io/crate/types/NumericStorage.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/lucene/NumericEqQueryTest.java
Labels: ready-to-merge

#16496 Fix ClassCastException from EqOperator over nested array subscript expression
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/test/java/io/crate/lucene/NestedArrayLuceneQueryBuilderTest.java
Labels: ready-to-merge, v/5.8

#16497 Fix ClassCastException from AnyEqOperator on nested array literals
  server/src/main/java/io/crate/expression/operator/any/AnyEqOperator.java
  server/src/test/java/io/crate/lucene/NestedArrayLuceneQueryBuilderTest.java
Labels: ready-to-merge, v/5.8

#16508 Make flattenUnique more general
  libs/shared/src/main/java/io/crate/common/collections/Lists.java
Labels: ready-to-merge, v/5.8

#16513 Update maven used by mvn wrapper to 3.9.9
  .mvn/wrapper/maven-wrapper.properties
Labels: ready-to-merge

#16511 Fix flaky `testNullOperators`
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
Labels: ready-to-merge

#16505 Simplify LuceneSort; Replace `nullSentinelForReducedType` with `nullSentinel`
  server/src/main/java/io/crate/execution/engine/sort/LuceneSort.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/NullSentinelValues.java
Labels: ready-to-merge

#16512 Fix TopK agg exception due to partial type != final result
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/test/java/io/crate/integrationtests/AggregateExpressionIntegrationTest.java
Labels: ready-to-merge

#16510 Add release note entries for #16495, #16496, #16497
  docs/appendices/release-notes/5.8.2.rst
Labels: ready-to-merge, v/5.8

#16515 Improve assertEvaluate test failure message for ScalarTestCase
  server/src/test/java/io/crate/expression/scalar/bitwise/BitwiseFunctionsTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
Labels: ready-to-merge

#16517 Remove unused searchPath from ProjectionBuilder#aggregationProjection()
  server/src/main/java/io/crate/execution/dsl/projection/builder/ProjectionBuilder.java
  server/src/main/java/io/crate/planner/operators/GroupHashAggregate.java
  server/src/main/java/io/crate/planner/operators/HashAggregate.java
Labels: ready-to-merge

#16520 tests: Improve AggregationTestCase to use partial states
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#16522 tests: Fix flaky test_types_with_storage_can_be_inserted_and_queried (numeric type issue)
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge

#16523 Fix issue with empty array and dynamic col policy
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, v/5.8

#16525 Update broken link to RFC2396 in COPY docs
  docs/sql/statements/copy-from.rst
  docs/sql/statements/copy-to.rst
Labels: ready-to-merge, v/5.8

#16528 Pre-size refreshActions in FetchTask
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
Labels: ready-to-merge

#16527 Add braces in sql-parser
  libs/dex/src/main/java/io/crate/data/Row1.java
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/ConstructingObjectParser.java
  libs/shared/src/main/java/io/crate/common/unit/TimeValue.java
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AlterTableRenameColumn.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ArrayComparisonExpression.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ArrayLikePredicate.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ArrayLiteral.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ArraySubQueryExpression.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateFunction.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateView.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DeallocateStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DefaultConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropAnalyzer.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropFunction.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropRepository.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DropView.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/FrameBound.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/FunctionArgument.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GeneratedExpressionConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/NotNullColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/NullColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ObjectLiteral.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ParameterExpression.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PartitionedBy.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrimaryKeyColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrivilegeStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ShowSessionParameter.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/SubscriptExpression.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Window.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/WindowFrame.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/With.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/WithQuery.java
Labels: ready-to-merge

#16530 Skip future chaining in RootTask.start if completed/failed
  server/src/main/java/io/crate/execution/jobs/RootTask.java
Labels: ready-to-merge

#16531 tests: Add comment explanation on test for dyn cols & empty arrays
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge

#16532 tests: Improve aggregation unit tests
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge

#16533 Ensure precision > scale for random numeric type values
  server/src/testFixtures/java/io/crate/testing/DataTypeTesting.java
Labels: ready-to-merge

#16535 Preserve the number of shards of existing partitions when altering the table
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, v/5.8

#16538 Deduplicate empty settings
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/PutRepositoryRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/settings/ClusterUpdateSettingsRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsRequest.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/common/settings/Settings.java
  server/src/main/java/org/elasticsearch/index/analysis/AnalysisRegistry.java
  server/src/main/java/org/elasticsearch/plugins/Plugin.java
  server/src/testFixtures/java/org/elasticsearch/cluster/ESAllocationTestCase.java
Labels: ready-to-merge

#16540 Release 5.8.2
  docs/appendices/release-notes/5.8.2.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16541 Update maven plugins to their latest versions
  pom.xml
Labels: ready-to-merge

#16543 Bump to 5.8.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16545 Reflect release 5.8.2
  docs/appendices/release-notes/5.8.2.rst
  docs/appendices/release-notes/5.8.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16542 Copy types for row accounting for HTTP results
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
Labels: ready-to-merge

#16546 Reduce API surface of CreateIndexRequest
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeActionTest.java
Labels: ready-to-merge

#16548 Update lib dependencies to their latest versions
  pom.xml
Labels: ready-to-merge

#16550 Fix an issue preventing to update password for users with jwt properties
  docs/appendices/release-notes/5.8.3.rst
  server/src/main/java/io/crate/role/TransportAlterRoleAction.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge, v/5.8
