Repository crate/crate, pull requests merged in 2024-01, with the labels that each got.

#15287 Fix flaky test: test_copy_from_can_import_json_with_same_columns_in_d…
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge, v/5.5

#15288 Fix performance regression for (group/hash) aggregates without doc-values
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
Labels: ready-to-merge, v/5.5

#15291 Add unknown type for pgwire
  docs/appendices/release-notes/5.6.0.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/protocols/postgres/types/PGTypes.java
  server/src/main/java/io/crate/protocols/postgres/types/UnknownType.java
  server/src/test/java/io/crate/protocols/postgres/types/PGTypesTest.java
Labels: ready-to-merge

#15289 Update dependencies
  docs/appendices/release-notes/5.6.0.rst
  pom.xml
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
Labels: ready-to-merge

#15188 Create generic AlterTableTask that can replace ADD/DROP/RENAME COLUMN tasks
  server/src/main/java/io/crate/execution/ddl/tables/AddColumnTask.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableTask.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropColumnAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameColumnAction.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/RenameColumnTaskTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge

#15293 Fix handling of query conditions in delete/update with WHERE doc-keys
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/main/java/io/crate/planner/WhereClauseOptimizer.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
Labels: ready-to-merge, v/5.5

#15286 Fix perf regression caused by nested Fetch operators
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge

#15296 Fix subscript lookup on object array children
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
Labels: ready-to-merge, v/5.5

#15260 Documentation: Add notices about reporting security flaws
  README.rst
  SECURITY.md
Labels: ready-to-merge

#15301 Return NULL from subscript lookup instead of error if type contains key
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  server/src/test/java/io/crate/expression/scalar/SubscriptFunctionTest.java
Labels: ready-to-merge, v/5.5

#15052 Docs: references to overload protection for copy and insert from query
  docs/sql/statements/copy-from.rst
  docs/sql/statements/copy-to.rst
  docs/sql/statements/insert.rst
Labels: ready-to-merge

#15304 Rename `parents` to `granted_roles` for `sys.roles/users`
  docs/admin/system-information.rst
  docs/admin/user-management.rst
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/role/metadata/SysRolesTableInfo.java
  server/src/main/java/io/crate/role/metadata/SysUsersTableInfo.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
Labels: ready-to-merge

#15305 Revert "Add optimizer rule to move a limit beneath a join operator"
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnion.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveLimitBeneathJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnionTest.java
Labels: ready-to-merge

#15307 Add release note for RBAC functionality
  docs/appendices/release-notes/5.6.0.rst
Labels: ready-to-merge

#15308 Fix type signature of unnest with single argument
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/expression/tablefunctions/UnnestFunction.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
Labels: ready-to-merge, v/5.5

#15313 Update maven used by maven-wrapper to 3.9.6
  .mvn/wrapper/maven-wrapper.properties
Labels: ready-to-merge

#15315 Move hierarchical hasPrivilege implementation to interface
  server/src/main/java/io/crate/role/Roles.java
  server/src/main/java/io/crate/role/RolesService.java
Labels: ready-to-merge

#15310 Revert "Add optimizer rule to move a limit beneath a union operator"
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnion.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/PlanPrinterTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveLimitBeneathUnionTest.java
Labels: ready-to-merge

#15317 Rename RolePrivilegesToApply -> GrantedRolesChange
  server/src/main/java/io/crate/analyze/AnalyzedPrivileges.java
  server/src/main/java/io/crate/analyze/PrivilegesAnalyzer.java
  server/src/main/java/io/crate/role/GrantedRolesChange.java
  server/src/main/java/io/crate/role/PrivilegesRequest.java
  server/src/main/java/io/crate/role/RoleManager.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/TransportPrivilegesAction.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/test/java/io/crate/role/GrantedRolesChangeTest.java
  server/src/test/java/io/crate/role/PrivilegesRequestTest.java
  server/src/test/java/io/crate/role/TransportPrivilegesActionTest.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
  server/src/testFixtures/java/io/crate/role/StubRoleManager.java
Labels: ready-to-merge

#15318 Inline constants on Roles
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/Roles.java
Labels: ready-to-merge

#15320 Provide nice error message when `crate` superuser is granted roles
  docs/admin/privileges.rst
  server/src/main/java/io/crate/analyze/PrivilegesAnalyzer.java
  server/src/test/java/io/crate/analyze/PrivilegesAnalyzerTest.java
Labels: ready-to-merge

#15319 Forbid renaming a table/view if the target exists
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  server/src/test/java/io/crate/integrationtests/RenameTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
Labels: ready-to-merge, v/5.5

#15321 Temporarily disable codeproject.com from linkcheck
  docs/conf.py
Labels: ready-to-merge, v/5.5

#15280 Do not use FieldExistsQuery over REF that is arg of NON_NULLABLE function
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#15330 docs: Add sys.privileges table in reference section
  docs/admin/privileges.rst
  docs/admin/system-information.rst
Labels: ready-to-merge, docs, v/5.5

#15332 Rename Privilege.Clazz to Securable
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DenyPrivilege.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GrantPrivilege.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/PrivilegeStatement.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/RevokePrivilege.java
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/analyze/PrivilegesAnalyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/expression/scalar/HasDatabasePrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasPrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgRolesTable.java
  server/src/main/java/io/crate/metadata/sys/SysShardsTableInfo.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/role/Privilege.java
  server/src/main/java/io/crate/role/PrivilegeIdent.java
  server/src/main/java/io/crate/role/Privileges.java
  server/src/main/java/io/crate/role/PrivilegesModifier.java
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/RolePrivileges.java
  server/src/main/java/io/crate/role/Roles.java
  server/src/main/java/io/crate/role/Securable.java
  server/src/main/java/io/crate/role/metadata/SysPrivilegesTableInfo.java
  server/src/test/java/io/crate/action/sql/SessionsTest.java
  server/src/test/java/io/crate/analyze/PrivilegesAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
  server/src/test/java/io/crate/auth/user/RolePrivilegesTest.java
  server/src/test/java/io/crate/expression/scalar/HasDatabasePrivilegeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/HasSchemaPrivilegeFunctionTest.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysPrivilegesIntegrationTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
  server/src/test/java/io/crate/role/PrivilegesModifierTest.java
  server/src/test/java/io/crate/role/PrivilegesRequestTest.java
  server/src/test/java/io/crate/role/PrivilegesTest.java
  server/src/test/java/io/crate/role/RolesServiceTest.java
  server/src/test/java/io/crate/role/TransportPrivilegesActionTest.java
  server/src/test/java/io/crate/role/metadata/RolesHelper.java
Labels: ready-to-merge

#15337 Update to Admin UI 1.24.7
  app/pom.xml
  docs/appendices/release-notes/5.6.0.rst
Labels: ready-to-merge

#15341 Add reference to primary key constraints to release notes
  docs/appendices/release-notes/5.6.0.rst
Labels: ready-to-merge

#15342 Remove custom findUser in RolesService
  server/src/main/java/io/crate/role/RolesService.java
Labels: ready-to-merge

#15343 Add notice about distro package changes to 5.4.7, 5.3.8, 5.2.11 release notes
  docs/appendices/release-notes/5.2.11.rst
  docs/appendices/release-notes/5.3.8.rst
  docs/appendices/release-notes/5.4.7.rst
Labels: ready-to-merge, v/5.2, v/5.3, v/5.4

#15333 Don't override non-deterministic sub-column on replica if it's already computed
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, v/5.5

#15356 Replace some guava Ordering constructs with java 8 Comparator
  libs/shared/src/main/java/io/crate/common/collections/LexicographicalOrdering.java
  libs/shared/src/main/java/io/crate/common/collections/Ordering.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/testFixtures/java/io/crate/testing/SQLPrinter.java
Labels: ready-to-merge

#15354 Migrate TableFunctionITest to assertj
  server/src/test/java/io/crate/integrationtests/TableFunctionITest.java
Labels: ready-to-merge

#15357 Fix unchecked and rawtypes warnings
  libs/dex/src/main/java/io/crate/data/join/JoinBatchIterator.java
  libs/dex/src/testFixtures/java/io/crate/data/testing/TestingBatchIterators.java
  server/src/main/java/io/crate/analyze/FunctionArgumentDefinition.java
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/ShardResponse.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dsl/projection/AbstractIndexWriterProjection.java
  server/src/main/java/io/crate/execution/dsl/projection/ColumnIndexWriterProjection.java
  server/src/main/java/io/crate/execution/dsl/projection/FetchProjection.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/IntervalSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageState.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/io/crate/execution/engine/collect/sources/SystemCollectSource.java
  server/src/main/java/io/crate/execution/engine/distribution/StreamBucket.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchRequest.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchResponse.java
  server/src/main/java/io/crate/execution/engine/fetch/TransportFetchOperation.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  server/src/main/java/io/crate/expression/eval/NullEliminator.java
  server/src/main/java/io/crate/expression/operator/AllOperator.java
  server/src/main/java/io/crate/expression/operator/AndOperator.java
  server/src/test/java/io/crate/execution/engine/fetch/NodeFetchResponseTest.java
  server/src/testFixtures/java/io/crate/testing/MemoryLimits.java
Labels: ready-to-merge

#15358 Replace arrayAsArrayList with Arrays.asList/List.of
  server/src/main/java/org/elasticsearch/common/util/CollectionUtils.java
  server/src/main/java/org/elasticsearch/index/query/Operator.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
  server/src/test/java/io/crate/auth/AccessControlMaySeeTest.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#15362 bp: Logger: Merge ESLoggerFactory into Loggers
  server/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/metadata/functions/SignatureBinder.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/ShardReplicationChangesTracker.java
  server/src/main/java/io/crate/replication/logical/ShardReplicationService.java
  server/src/main/java/io/crate/replication/logical/action/GetStoreMetadataAction.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/io/crate/replication/logical/action/ReleasePublisherResourcesAction.java
  server/src/main/java/io/crate/replication/logical/action/ReplayChangesAction.java
  server/src/main/java/io/crate/replication/logical/action/ShardChangesAction.java
  server/src/main/java/io/crate/replication/logical/action/TransportAlterPublicationAction.java
  server/src/main/java/io/crate/replication/logical/repository/RemoteClusterMultiChunkTransfer.java
  server/src/main/java/io/crate/replication/logical/seqno/RetentionLeaseHelper.java
  server/src/main/java/org/elasticsearch/action/support/single/shard/TransportSingleShardAction.java
  server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/elasticsearch/common/logging/ESLoggerFactory.java
  server/src/main/java/org/elasticsearch/common/logging/Loggers.java
  server/src/main/java/org/elasticsearch/common/logging/PrefixLogger.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateActionTests.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
  server/src/test/java/org/elasticsearch/transport/TcpTransportTests.java
Labels: ready-to-merge

#15340 Ensure equi-join condition refers to two columns from two different relations
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/test/java/io/crate/planner/operators/EquiJoinDetectorTest.java
Labels: ready-to-merge, v/5.5

#15363 Remove unused Operator enum
  server/src/main/java/org/elasticsearch/index/query/Operator.java
Labels: ready-to-merge

#15370 Backport test cases only from #15280
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge

#15349 Support running `blackbox/test_s3` on linux/darwin arm64 machines
  blackbox/test_s3.py
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5

#15372 Minor code improvements for benchmarks module
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  benchmarks/src/main/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/TimePrecisionIncreaseTest.java
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/AggregateCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/GroupingLongCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/GroupingStringCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/sort/SortingLimitAndOffsetCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationBenchmark.java
  benchmarks/src/main/java/io/crate/operation/aggregation/IntervalAggregationBenchmark.java
Labels: ready-to-merge

#15365 Remove unused declarations
  server/src/main/java/io/crate/lucene/FunctionLiteralPair.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java
  server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java
  server/src/main/java/org/elasticsearch/cluster/RestoreInProgress.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexGraveyard.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/common/util/ArrayUtils.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/PrioritizedCallable.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/PrioritizedEsThreadPoolExecutor.java
Labels: ready-to-merge

#15378 Lookup name by OID first when parsing source
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
Labels: ready-to-merge, v/5.5

#15383 Fix issue with building & releasing from git worktrees
  app/pom.xml
Labels: v/5.5

#15382 Release 5.5.3
  docs/appendices/release-notes/5.5.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15388 Bump version to 5.5.4-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15355 Explicitly mention BM25 in score docs
  docs/general/ddl/system-columns.rst
Labels: ready-to-merge

#15390 Reflect 5.5.3 release in master
  docs/appendices/release-notes/5.5.3.rst
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15396 Links in score documentation were not properly formed
  docs/general/ddl/system-columns.rst
Labels: ready-to-merge

#15400 Release 5.6.0
  docs/appendices/release-notes/5.6.0.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15406 update release date
  docs/appendices/release-notes/5.6.0.rst
Labels: ready-to-merge

#15407 Exclude exp() function test from doc tests
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5

#15414 Release 5.6.0
  docs/appendices/release-notes/5.6.0.rst
Labels: ready-to-merge

#15420 Bump version to 5.6.1-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.6.1.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15409 Update netty to 4.1.106
  pom.xml
Labels: ready-to-merge

#15424 Bump to 5.6.1-SNAPSHOT inside pom files
  app/pom.xml
  benchmarks/pom.xml
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
Labels: ready-to-merge

#15425 Revert read/writeEnum() to read/write enum ordinals
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/io/crate/role/Privilege.java
  server/src/main/java/io/crate/role/Subject.java
Labels: ready-to-merge, v/5.6

#15222 Add use_path_style_access setting for S3 snapshot repository.
  docs/appendices/release-notes/5.7.0.rst
  docs/sql/statements/create-repository.rst
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3ClientSettings.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Repository.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RepositorySettings.java
  plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientSettingsTests.java
Labels: ready-to-merge

#15427 Remove cr> prefix from exp() function doc
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5, v/5.6

#15408 Update jdk to 21.0.2
  docs/appendices/release-notes/5.6.1.rst
  pom.xml
  server/src/main/java/org/elasticsearch/common/util/concurrent/EsExecutors.java
Labels: ready-to-merge, v/5.6

#15434 Revert "Pin java to 21.0.1 in GHA"
  .github/workflows/main.yml
Labels: ready-to-merge, v/5.6

#15399 Add `--env CRATE_HEAP_SIZE=1g` to docker run examples
  README.rst
  docs/admin/monitoring.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5, v/5.6

#15449 Add translog test to DataTypeTestCase and extend to more datatypes
  server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  server/src/test/java/io/crate/types/BitStringTypeTest.java
  server/src/test/java/io/crate/types/BooleanTypeTest.java
  server/src/test/java/io/crate/types/ByteTypeTest.java
  server/src/test/java/io/crate/types/CharacterTypeTest.java
  server/src/test/java/io/crate/types/DoubleTypeTest.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
  server/src/test/java/io/crate/types/IntegerTypeTest.java
  server/src/test/java/io/crate/types/IntervalTypeTest.java
  server/src/test/java/io/crate/types/IpTypeTest.java
  server/src/test/java/io/crate/types/JsonTypeTest.java
  server/src/test/java/io/crate/types/LongTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/test/java/io/crate/types/RegclassTypeTest.java
  server/src/test/java/io/crate/types/RegprocTypeTest.java
  server/src/test/java/io/crate/types/ShortTypeTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#15453 Skip translog_streaming_roundtrip for ArrayTypeTest
  server/src/test/java/io/crate/types/ArrayTypeTest.java
Labels: ready-to-merge

#15448 Keep correlated subquery data on multi phase execution
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/SubQueryResults.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
Labels: ready-to-merge, v/5.5, v/5.6

#15452 Declare scalar functions not yet marked nullable as nullable
  server/src/main/java/io/crate/expression/scalar/ArrayAvgFunction.java
  server/src/main/java/io/crate/expression/scalar/ExtractFunctions.java
  server/src/main/java/io/crate/expression/scalar/TripleScalar.java
  server/src/main/java/io/crate/expression/scalar/UnaryScalar.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/AbsFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/ArithmeticFunctions.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/BinaryScalar.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/CeilFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/FloorFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/NegateFunctions.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctions.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/RoundFunction.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/TrigonometricFunctions.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/TruncFunction.java
  server/src/main/java/io/crate/expression/scalar/bitwise/BitwiseFunctions.java
  server/src/main/java/io/crate/expression/scalar/geo/AreaFunction.java
  server/src/main/java/io/crate/expression/scalar/geo/CoordinateFunction.java
  server/src/main/java/io/crate/expression/scalar/geo/GeoHashFunction.java
  server/src/main/java/io/crate/expression/scalar/object/ObjectKeysFunction.java
  server/src/main/java/io/crate/expression/scalar/postgres/PgGetUserByIdFunction.java
  server/src/main/java/io/crate/expression/scalar/string/AsciiFunction.java
  server/src/main/java/io/crate/expression/scalar/string/EncodeDecodeFunction.java
  server/src/main/java/io/crate/expression/scalar/string/HashFunctions.java
  server/src/main/java/io/crate/expression/scalar/string/InitCapFunction.java
  server/src/main/java/io/crate/expression/scalar/string/LengthFunction.java
  server/src/main/java/io/crate/expression/scalar/string/QuoteIdentFunction.java
  server/src/main/java/io/crate/expression/scalar/string/ReplaceFunction.java
  server/src/main/java/io/crate/expression/scalar/string/StringCaseFunction.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/PgGetPartkeydefFunction.java
  server/src/main/java/io/crate/expression/scalar/systeminformation/PgGetSerialSequenceFunction.java
  server/src/test/java/io/crate/execution/engine/pipeline/MapRowUsingInputsTest.java
  server/src/test/java/io/crate/expression/InputFactoryTest.java
Labels: ready-to-merge, v/5.6

#15462 #14640 Support lowercase yyyy in to_char
  docs/appendices/release-notes/5.7.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/formatting/DateTimeFormatter.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge

#15465 Restrict `COPY FROM` using local files to superuser
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.6.1.rst
  docs/sql/statements/copy-from.rst
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/exceptions/UnauthorizedException.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/sources/FileCollectSourceTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#15467 Restrict `COPY FROM` using local files to superuser
  docs/appendices/release-notes/5.5.4.rst
  docs/sql/statements/copy-from.rst
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/exceptions/UnauthorizedException.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/sources/FileCollectSourceTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#15468 Revert "Normalize `<non_null_ref> is null` to `false`"
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/io/crate/expression/predicate/IsNullPredicate.java
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
  server/src/test/java/io/crate/expression/predicate/IsNullPredicateTest.java
  server/src/test/java/io/crate/expression/predicate/NotPredicateTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
Labels: ready-to-merge, v/5.5, v/5.6

#15469 Restrict `COPY FROM` using local files to superuser
  benchmarks/src/main/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/5.4.8.rst
  docs/sql/statements/copy-from.rst
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/exceptions/UnauthorizedException.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#15464 Update sitemap URL
  docs/_extra/robots.txt
Labels: ready-to-merge

#15473 Restrict `COPY FROM` using local files to superuser
  benchmarks/src/main/java/io/crate/execution/engine/reader/CsvReaderBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/reader/JsonReaderBenchmark.java
  docs/appendices/release-notes/5.3.9.rst
  docs/sql/statements/copy-from.rst
  plugins/cr8-copy-s3/src/test/java/io/crate/copy/s3/S3FileReadingCollectorTest.java
  server/src/main/java/io/crate/exceptions/UnauthorizedException.java
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/main/java/io/crate/execution/engine/collect/sources/FileCollectSource.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/execution/engine/collect/MapSideDataCollectOperationTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge

#15474 Release 5.3.9
  docs/appendices/release-notes/5.3.9.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15475 Release 5.4.8
  docs/appendices/release-notes/5.4.8.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15477 Bump version to 5.4.9-SNAPSHOT
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.4.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15481 Release 5.6.1
  docs/appendices/release-notes/5.6.1.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15480 Bump version to 5.5.5-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.5.5.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15482 Reflect release 5.3.9
  docs/appendices/release-notes/5.3.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15484 Bump version to 5.6.2-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.6.2.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15485 Reflect recent hotfix releases 5.3.9, 5.4.8, 5.5.4 and 5.6.1
  docs/appendices/release-notes/5.3.9.rst
  docs/appendices/release-notes/5.4.8.rst
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.5.5.rst
  docs/appendices/release-notes/5.6.1.rst
  docs/appendices/release-notes/5.6.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15486 Reflect recent hotfix releases 5.3.9, 5.4.8, 5.5.4 at 5.6
  docs/appendices/release-notes/5.3.9.rst
  docs/appendices/release-notes/5.4.8.rst
  docs/appendices/release-notes/5.5.4.rst
  docs/appendices/release-notes/5.5.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15489 Reuse channel closing code in HostBasedAuthHandler
  server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java
Labels: ready-to-merge

#15479 Don't mark concat_ws as Nullable
  docs/appendices/release-notes/5.6.2.rst
  server/src/main/java/io/crate/expression/scalar/ConcatWsFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.6

#15491 Add a Metadata.contains(RelationName)
  server/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/io/crate/execution/ddl/views/TransportCreateViewAction.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlan.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge

#15211 Support nested arrays in table schemas
  docs/appendices/release-notes/5.7.0.rst
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/analyze/SubscriptContext.java
  server/src/main/java/io/crate/analyze/SubscriptVisitor.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/org/elasticsearch/index/mapper/ArrayMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ArrayTypeParser.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SubscriptValidatorTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/test/java/io/crate/types/ArrayTypeTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/testFixtures/java/io/crate/testing/ParsedDocumentAssert.java
Labels: ready-to-merge
