Repository crate/crate, pull requests merged in 2024-03, with the labels that each got.

#15648 Reword outdated 127.0.0.1:5432 fdw default notice in docs
  docs/admin/fdw.rst
Labels: ready-to-merge

#15626 Remove ExtensiblePlugin
  server/src/main/java/org/elasticsearch/plugins/ExtensiblePlugin.java
  server/src/main/java/org/elasticsearch/plugins/PluginInfo.java
  server/src/main/java/org/elasticsearch/plugins/PluginsService.java
Labels: ready-to-merge

#15658 Documentation: Fix broken links after transitioning to the CrateDB Guide
  docs/config/environment.rst
  docs/config/logging.rst
Labels: ready-to-merge, v/5.3, v/5.4, v/5.5, v/5.6

#15657 Prevent SHOW CREATE TABLE from leaking table names
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/analyze/ShowStatementAnalyzer.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge, v/5.6

#15673 Fix ALTER USER to actually update jwt properties
  server/src/main/java/io/crate/role/TransportAlterRoleAction.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge

#15666 Add aud (audience) to JWT properties
  docs/admin/auth/methods.rst
  docs/admin/system-information.rst
  docs/sql/statements/alter-role.rst
  docs/sql/statements/create-user.rst
  server/src/main/java/io/crate/auth/Credentials.java
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/main/java/io/crate/auth/JWTAuthenticationMethod.java
  server/src/main/java/io/crate/role/JwtProperties.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/TransportAlterRoleAction.java
  server/src/main/java/io/crate/role/TransportCreateRoleAction.java
  server/src/main/java/io/crate/role/metadata/RolesMetadata.java
  server/src/main/java/io/crate/role/metadata/SysUsersTableInfo.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/auth/JwtAuthenticationIntegrationTest.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/RoleManagementIntegrationTest.java
  server/src/test/java/io/crate/planner/node/ddl/CreateRolePlanTest.java
  server/src/test/java/io/crate/role/CreateRoleRequestTest.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
  server/src/test/java/io/crate/role/metadata/RolesHelper.java
  server/src/test/java/io/crate/role/metadata/RolesMetadataTest.java
Labels: ready-to-merge

#15653 Add predicate pushdown for foreign data wrappers
  server/src/main/java/io/crate/execution/dsl/phases/ForeignCollectPhase.java
  server/src/main/java/io/crate/fdw/ForeignDataWrapper.java
  server/src/main/java/io/crate/fdw/ForeignDataWrappers.java
  server/src/main/java/io/crate/fdw/JdbcBatchIterator.java
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/operators/ForeignCollect.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MergeFilterAndForeignCollect.java
  server/src/test/java/io/crate/fdw/JdbcBatchIteratorTest.java
  server/src/test/java/io/crate/fdw/JdbcForeignDataWrapperTest.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/CollectTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge

#15656 Support foreign tables in SHOW CREATE TABLE
  docs/sql/statements/create-foreign-table.rst
  docs/sql/statements/show-create-table.rst
  server/src/main/java/io/crate/analyze/AnalyzedShowCreateTable.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/analyze/ShowStatementAnalyzer.java
  server/src/main/java/io/crate/analyze/TableInfoToAST.java
  server/src/main/java/io/crate/fdw/AddForeignTableTask.java
  server/src/main/java/io/crate/fdw/FdwAnalyzer.java
  server/src/main/java/io/crate/fdw/ForeignTable.java
  server/src/main/java/io/crate/planner/CreateForeignTablePlan.java
  server/src/main/java/io/crate/planner/node/management/ShowCreateTablePlan.java
  server/src/test/java/io/crate/analyze/TableInfoToASTTest.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#15678 Replace broken jobs_log_filter example in docs
  docs/config/cluster.rst
Labels: ready-to-merge, v/5.6

#15651 Add `reverse` scalar function.
  docs/appendices/release-notes/5.7.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/string/ReverseFunction.java
  server/src/test/java/io/crate/expression/scalar/string/ReverseFunctionTest.java
Labels: ready-to-merge

#15685 Fix linkcheck failure (broken POSIX regex link anchor)
  docs/general/dql/selects.rst
Labels: ready-to-merge, v/5.6

#15684 Use existing LoadedRules singleton in tests instead of new instance
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/test/java/io/crate/metadata/settings/session/SessionSettingRegistryTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
Labels: ready-to-merge

#15689 Ensure operations unsupported on views/foreign tables raise helpful error
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
Labels: ready-to-merge

#15691 Raise helpful error on CREATE PUBLICATION with system-/foreign table
  docs/sql/statements/create-foreign-table.rst
  docs/sql/statements/create-publication.rst
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/main/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzer.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableDropColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableOpenCloseAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableRerouteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DropTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/OptimizeTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/RefreshAnalyzerTest.java
  server/src/test/java/io/crate/analyze/RestoreSnapshotAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SwapTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableBlocksIntegrationTest.java
  server/src/test/java/io/crate/metadata/SchemasTest.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
  server/src/test/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzerTest.java
Labels: ready-to-merge

#15692 Document interval type id in http interface docs
  docs/interfaces/http.rst
Labels: ready-to-merge, v/5.6

#15664 Add Lookup-Join optimization for Equi-Inner-Joins
  docs/appendices/release-notes/5.7.0.rst
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/JoinConditionSymbolsExtractor.java
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/HashJoinConditionSymbolsExtractorTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoinTest.java
Labels: ready-to-merge

#15694 Merge resolveTableInfo/resolveRelationInfo in Schemas
  server/src/main/java/io/crate/analyze/AlterTableAddColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableRenameColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/CopyAnalyzer.java
  server/src/main/java/io/crate/analyze/DropCheckConstraintAnalyzer.java
  server/src/main/java/io/crate/analyze/DropTableAnalyzer.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/analyze/OptimizeTableAnalyzer.java
  server/src/main/java/io/crate/analyze/RefreshTableAnalyzer.java
  server/src/main/java/io/crate/analyze/SwapTableAnalyzer.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/io/crate/replication/logical/analyze/LogicalReplicationAnalyzer.java
  server/src/test/java/io/crate/metadata/SchemasTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#15697 Fix flaky lookup-join integration test
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
Labels: ready-to-merge

#15695 Allow pushdowns of constant-join-conditions on all join types
  server/src/main/java/io/crate/planner/operators/AbstractJoinPlan.java
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderNestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteJoinPlan.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoinTest.java
Labels: ready-to-merge

#15643 Changed EXP function to return double types
  docs/appendices/release-notes/5.7.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/ExpFunction.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/ExpFunctionTest.java
Labels: ready-to-merge

#15698 Document FDW push down limitations
  docs/admin/fdw.rst
Labels: ready-to-merge

#15706 Ensure that sample docids are iterated in order
  server/src/main/java/io/crate/statistics/Reservoir.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/test/java/io/crate/statistics/ReservoirTest.java
Labels: ready-to-merge

#15705 Add GH handle to external contributions
  docs/appendices/release-notes/5.7.0.rst
Labels: ready-to-merge

#15703 Migrate GeoJSONUtilsTest to assertj
  server/src/test/java/io/crate/geo/GeoJSONUtilsTest.java
Labels: ready-to-merge

#15711 Migrate AuthSettingsTest to assertj
  server/src/test/java/io/crate/auth/AuthSettingsTest.java
Labels: ready-to-merge

#15708 Fix flaky testReadRangeBlobWithRetries
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSBlobContainerRetriesTests.java
Labels: ready-to-merge

#15714 Fix handling of filters on top of a ordered collect
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/execution/engine/collect/sources/ShardCollectSource.java
  server/src/main/java/io/crate/planner/node/dql/Collect.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/5.6

#15704 Group interval fixes in 5.6.3 release notes
  docs/appendices/release-notes/5.6.3.rst
Labels: ready-to-merge, v/5.6

#15707 Remove `Schemas.getTableInfo(RelationName, Operation)` overload
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/collect/count/InternalCountOperation.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/metadata/SchemasTest.java
Labels: ready-to-merge

#15710 Update PostgreSQL jdbc to 42.7.3
  pom.xml
Labels: ready-to-merge

#15729 Migrate tests to assertj
  server/src/test/java/io/crate/blob/BlobContainerTest.java
  server/src/test/java/io/crate/lucene/BitStringQueryTest.java
  server/src/test/java/io/crate/lucene/CIDRRangeQueryTest.java
  server/src/test/java/io/crate/netty/channel/PipelineRegistryTest.java
  server/src/test/java/io/crate/rest/AdminUIHttpIntegrationTest.java
  server/src/test/java/io/crate/types/ShortTypeTest.java
Labels: ready-to-merge

#15715 Add a release note entry for #15695
  docs/appendices/release-notes/5.7.0.rst
Labels: ready-to-merge

#15725 Run MergeFilterAndCollect rule after column pruning
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
Labels: ready-to-merge, v/5.6

#15733 Match test name for JoinConditionSymbolsExtractor
  server/src/test/java/io/crate/planner/operators/JoinConditionSymbolsExtractorTest.java
Labels: ready-to-merge, v/5.6

#15734 Migrate ValueNormalizerTest to assertj
  server/src/test/java/io/crate/analyze/ValueNormalizerTest.java
Labels: ready-to-merge

#15737 Move change entry for hash-join filter push down to 5.6.3
  docs/appendices/release-notes/5.6.3.rst
  docs/appendices/release-notes/5.7.0.rst
Labels: ready-to-merge, v/5.6

#15744 Release 5.6.3
  docs/appendices/release-notes/5.6.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15745 Bump version to 5.6.4-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.6.4.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15746 Reflect release 5.6.3 on master
  docs/appendices/release-notes/5.6.3.rst
  docs/appendices/release-notes/5.6.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15756 Adjust ExpFunctionTest so that it passes on apple silicon
  server/src/test/java/io/crate/expression/scalar/arithmetic/ExpFunctionTest.java
Labels: ready-to-merge

#15755 Check for mixed-cluster analyze calls in FetchSampleRequest constructor
  server/src/main/java/io/crate/statistics/FetchSampleRequest.java
  server/src/main/java/io/crate/statistics/Reservoir.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/io/crate/statistics/Samples.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
Labels: ready-to-merge

#15758 Update GraalVM to 24.0.0; switch to polyglot package
  extensions/lang-js/pom.xml
  pom.xml
Labels: ready-to-merge

#15759 Implement JavaScriptLanguage as a generic PolyglotLanguage
  extensions/lang-js/src/main/java/io/crate/module/JavaScriptLanguageModule.java
  extensions/lang-js/src/main/java/io/crate/operation/language/JavaScriptLanguage.java
  extensions/lang-js/src/main/java/io/crate/operation/language/PolyglotLanguage.java
  extensions/lang-js/src/main/java/io/crate/operation/language/PolyglotScalar.java
  extensions/lang-js/src/main/java/io/crate/plugin/JavaScriptLanguagePlugin.java
  extensions/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
Labels: ready-to-merge

#15761 Improve assertions on JoinIntegrationTest
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#15769 Revert "Update GraalVM to 24.0.0; switch to polyglot package"
  extensions/lang-js/pom.xml
  pom.xml
Labels: ready-to-merge

#15742 Refactor `DropRoleTask`
  server/src/main/java/io/crate/exceptions/RoleUnknownException.java
  server/src/main/java/io/crate/role/DropRoleTask.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge

#15770 Register has_database/schema_privilege functions under pg_catalog
  docs/appendices/release-notes/5.6.4.rst
  server/src/main/java/io/crate/expression/scalar/HasDatabasePrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java
  server/src/test/java/io/crate/expression/scalar/HasDatabasePrivilegeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/HasSchemaPrivilegeFunctionTest.java
Labels: ready-to-merge, v/5.6

#15773 Replace deprecated TopFieldCollector.create/searcher.search Lucene calls
  server/src/main/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollector.java
  server/src/main/java/io/crate/lucene/WrappingCollectorManager.java
  server/src/main/java/org/elasticsearch/common/lucene/MinimumScoreCollector.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#15777 Revert "Refactor DropRoleTask"
  server/src/main/java/io/crate/exceptions/RoleUnknownException.java
  server/src/main/java/io/crate/role/DropRoleTask.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge
