Repository crate/crate, pull requests merged in 2024-04, with the labels that each got.

#15779 Update netty to 4.1.108, mockito to 5.11.0 and datasketches to 5.0.2
  pom.xml
Labels: ready-to-merge

#15783 Implement httpErrorStatus in exceptions derived from ESException
  server/src/main/java/io/crate/exceptions/InvalidArgumentException.java
  server/src/main/java/io/crate/exceptions/InvalidColumnNameException.java
  server/src/main/java/io/crate/exceptions/JobKilledException.java
  server/src/main/java/io/crate/exceptions/MissingPrivilegeException.java
  server/src/main/java/io/crate/exceptions/OperationOnInaccessibleRelationException.java
  server/src/main/java/io/crate/exceptions/RelationAlreadyExists.java
  server/src/main/java/io/crate/exceptions/RelationUnknown.java
  server/src/main/java/io/crate/exceptions/RoleAlreadyExistsException.java
  server/src/main/java/io/crate/exceptions/SchemaUnknownException.java
  server/src/main/java/io/crate/exceptions/UnauthorizedException.java
  server/src/main/java/io/crate/exceptions/UnsupportedFeatureException.java
  server/src/main/java/io/crate/exceptions/UserDefinedFunctionAlreadyExistsException.java
  server/src/main/java/io/crate/exceptions/UserDefinedFunctionUnknownException.java
  server/src/main/java/io/crate/exceptions/VersioningValidationException.java
  server/src/main/java/io/crate/rest/action/HttpError.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperParsingException.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryMissingException.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotMissingException.java
Labels: ready-to-merge

#15781 Make role not found errors more consistent
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/exceptions/RoleUnknownException.java
  server/src/main/java/io/crate/expression/scalar/HasPrivilegeFunction.java
  server/src/main/java/io/crate/planner/statement/SetSessionAuthorizationPlan.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/Roles.java
  server/src/test/java/io/crate/analyze/CreateUserMappingAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/HasDatabasePrivilegeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/HasSchemaPrivilegeFunctionTest.java
  server/src/test/java/io/crate/integrationtests/BaseRolesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/planner/statement/SetSessionAuthorizationPlanTest.java
  server/src/test/java/io/crate/replication/logical/action/TransportCreateSubscriptionActionTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15784 Return empty statistics as default value for logical plans
  server/src/main/java/io/crate/planner/optimizer/costs/PlanStats.java
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/planner/optimizer/iterative/MemoTest.java
Labels: ready-to-merge

#15789 Fix flaky test_ensure_lucene_ordered_collector_propagates_kill
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
Labels: ready-to-merge

#15787 Make fail_fast handling in COPY FROM independent of return summary
  server/src/main/java/io/crate/execution/dsl/projection/SourceIndexWriterReturnSummaryProjection.java
  server/src/main/java/io/crate/execution/engine/indexing/IndexWriterProjector.java
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResultCollectors.java
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResultContext.java
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResults.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
  server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java
Labels: ready-to-merge

#15788 Make RoleUnknownException streamable and map to pg code 42704
  server/src/main/java/io/crate/exceptions/RoleUnknownException.java
  server/src/main/java/io/crate/rest/action/HttpError.java
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
Labels: ready-to-merge

#15792 Verify JWT token only when connection gets established
  docs/admin/auth/methods.rst
  server/src/main/java/io/crate/auth/HttpAuthUpstreamHandler.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
Labels: ready-to-merge

#15794 Update jacoco to 0.8.12
  pom.xml
Labels: ready-to-merge

#15776 Allow non super users to access remote servers
  docs/sql/statements/create-server.rst
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/test/java/io/crate/fdw/JdbcForeignDataWrapperTest.java
Labels: ready-to-merge

#15753 Fix LIKE matching an empty string pattern in WHERE clause
  docs/appendices/release-notes/5.6.4.rst
  server/src/main/java/io/crate/expression/operator/LikeOperator.java
  server/src/test/java/io/crate/lucene/LikeQueryBuilderTest.java
Labels: ready-to-merge, v/5.6

#15795 Convert TypeConversionTest to assertj
  server/src/test/java/io/crate/types/TypeConversionTest.java
Labels: ready-to-merge

#15798 Amend year of 5.6.3 release from 2023 to 2024
  docs/appendices/release-notes/5.6.3.rst
Labels: ready-to-merge, docs, v/5.6

#15791 Fixes Issue #15790 - Update SVG background
  devs/docs/architecture.svg
Labels: ready-to-merge

#15804 Revert "Refactor DropRoleTask"
  server/src/main/java/io/crate/role/DropRoleTask.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/TransportDropRoleAction.java
  server/src/test/java/io/crate/role/TransportRoleActionTest.java
Labels: ready-to-merge

#15806 Remove dedicated fix for PKLookup of empty arrays
  server/src/main/java/io/crate/expression/reference/DocRefResolver.java
  server/src/test/java/io/crate/executor/transport/task/elasticsearch/DocRefResolverTest.java
Labels: ready-to-merge

#15808 Bump version to 5.6.5-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15815 Add support for strpos scalar function
  docs/appendices/release-notes/5.8.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/string/StringPositionFucntion.java
  server/src/test/java/io/crate/expression/scalar/string/StringPositionFunctionTest.java
Labels: ready-to-merge

#15817 Fix formatting of 5.7.0 release note
  docs/appendices/release-notes/5.7.0.rst
Labels: ready-to-merge, v/5.7

#15799 Add a warning that blobs backup is not supported
  docs/admin/snapshots.rst
  docs/general/blobs.rst
Labels: ready-to-merge

#15819 Add warning about silent ANALYZER alteration
  docs/sql/statements/create-analyzer.rst
Labels: ready-to-merge, docs, v/5.7

#15823 Fix flaky test_write_to_subscribed_empty_partitioned_table_is_forbidden
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
Labels: ready-to-merge

#15824 Remove duplicate getters from IndexTemplateMetadata
  server/src/main/java/io/crate/execution/engine/pipeline/TableSettingsResolver.java
  server/src/main/java/io/crate/expression/reference/sys/snapshot/SysSnapshots.java
  server/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge

#15825 Remove customData from IndexMetadata
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
Labels: ready-to-merge

#15827 Rename getRelationNames to relationNames in Logical Plan
  server/src/main/java/io/crate/planner/operators/AbstractJoinPlan.java
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/main/java/io/crate/planner/operators/CorrelatedJoin.java
  server/src/main/java/io/crate/planner/operators/Count.java
  server/src/main/java/io/crate/planner/operators/ForeignCollect.java
  server/src/main/java/io/crate/planner/operators/ForwardingLogicalPlan.java
  server/src/main/java/io/crate/planner/operators/Get.java
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/Insert.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/io/crate/planner/operators/LogicalPlan.java
  server/src/main/java/io/crate/planner/operators/Rename.java
  server/src/main/java/io/crate/planner/operators/TableFunction.java
  server/src/main/java/io/crate/planner/operators/Union.java
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReference.java
  server/src/main/java/io/crate/planner/optimizer/iterative/Memo.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathCorrelatedJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/RelationNamesInLogicalPlanTest.java
  server/src/test/java/io/crate/planner/optimizer/iterative/MemoTest.java
Labels: ready-to-merge

#15828 Remove unnecessary resolveSearchRouting
  server/src/main/java/io/crate/analyze/WhereClause.java
  server/src/main/java/io/crate/metadata/RoutingProvider.java
  server/src/main/java/io/crate/metadata/blob/BlobTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
Labels: ready-to-merge

#15830 Update intellij to jdk 22
  .idea/misc.xml
Labels: ready-to-merge

#15833 Remove unused MapperService param from snapshot method
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/RestoreOnlyRepository.java
Labels: ready-to-merge

#15839 Fix typo in class name
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/string/StringPositionFunction.java
Labels: ready-to-merge

#15841 VoidReference always has RowGranularity.DOC
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/main/java/io/crate/expression/symbol/VoidReference.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
Labels: ready-to-merge

#15842 Remove unused fieldFilters from MapperPlugin
  server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/indices/mapper/MapperRegistry.java
  server/src/main/java/org/elasticsearch/plugins/MapperPlugin.java
  server/src/testFixtures/java/org/elasticsearch/index/mapper/MockFieldFilterPlugin.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15831 Simplify IndexNameExpressionResolver
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
Labels: ready-to-merge

#15844 Update netty to 4.1.109
  pom.xml
Labels: ready-to-merge

#15846 Remove indexSettings from Mappers
  server/src/main/java/org/elasticsearch/index/mapper/BuilderFactory.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectArrayMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
  server/src/test/java/org/elasticsearch/index/mapper/BitStringFieldMapperTest.java
Labels: ready-to-merge

#15832 Add vector_similarity scalar function (euclidean based)
  docs/appendices/release-notes/5.8.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/VectorSimilarityFunction.java
  server/src/main/java/io/crate/metadata/functions/SignatureBinder.java
  server/src/test/java/io/crate/expression/scalar/VectorSimilarityFunctionTest.java
Labels: ready-to-merge

#15848 Update checkstyle to 10.15.0
  checkstyle.xml
  pom.xml
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/org/elasticsearch/index/analysis/AnalysisRegistry.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/rest/RestStatus.java
Labels: ready-to-merge

#15843 Take to account all new partitions when checking shard limits
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/test/java/io/crate/integrationtests/ShardLimitsIT.java
Labels: ready-to-merge, v/5.6, v/5.7

#15849 docs: fix actual max number of replicas for "all"
  docs/sql/statements/create-table.rst
Labels: ready-to-merge, docs, v/5.6, v/5.7

#15856 Use different name for the worker.id property.
  pom.xml
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#15850 Add retries for logical replication itests
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/testFixtures/java/io/crate/testing/RetryRule.java
Labels: ready-to-merge

#15840 Make lookup-joins work with sub-queries
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  docs/appendices/release-notes/5.8.0.rst
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/analyze/relations/AnalyzedRelationVisitor.java
  server/src/main/java/io/crate/analyze/relations/PlannedRelation.java
  server/src/main/java/io/crate/execution/MultiPhaseExecutor.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/PlannerContext.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/iterative/GroupReferenceResolver.java
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
  server/src/test/java/io/crate/planner/PlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoinTest.java
  server/src/test/java/io/crate/planner/statement/SetSessionPlanTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15860 Clarify behavior of max_shards_per_node and total_shards_per_node
  docs/config/cluster.rst
  docs/sql/statements/create-table.rst
Labels: ready-to-merge, docs, v/5.6, v/5.7

#15866 Track and expose via JMX detailed network stats
  docs/admin/monitoring.rst
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.0.rst
  extensions/jmx-monitoring/src/main/java/io/crate/beans/Connections.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/ConnectionsMBean.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/NodeStatusMBean.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/QueryStats.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/QueryStatsMBean.java
  extensions/jmx-monitoring/src/main/java/io/crate/beans/ShardInfo.java
  extensions/jmx-monitoring/src/main/java/io/crate/plugin/CrateMonitor.java
  server/src/main/java/io/crate/expression/reference/sys/node/NodeStatsContext.java
  server/src/main/java/io/crate/expression/reference/sys/node/NodeStatsContextFieldResolver.java
  server/src/main/java/io/crate/metadata/sys/SysNodesTableInfo.java
  server/src/main/java/io/crate/protocols/ConnectionStats.java
  server/src/main/java/io/crate/protocols/postgres/PostgresNetty.java
  server/src/main/java/org/elasticsearch/http/HttpServerTransport.java
  server/src/main/java/org/elasticsearch/http/HttpStats.java
  server/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/StatsTracker.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/Transport.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/main/java/org/elasticsearch/transport/TransportStats.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4InboundStatsHandler.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4OutboundStatsHandler.java
  server/src/test/java/io/crate/expression/reference/sys/node/NodeStatsContextFieldResolverTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/org/elasticsearch/cluster/NodeConnectionsServiceTests.java
  server/src/test/java/org/elasticsearch/transport/InboundPipelineTests.java
  server/src/testFixtures/java/org/elasticsearch/test/MockHttpTransport.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/FakeTransport.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/StubbableTransport.java
Labels: ready-to-merge

#15869 Fix handling of custom GC logging options in Windows build
  app/src/main/dist/bin/crate.bat
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
Labels: platform: windows, ready-to-merge, v/5.6, v/5.7

#15874 bp: Auto-expand replicated closed indices
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
  server/src/main/java/org/elasticsearch/cluster/metadata/AutoExpandReplicas.java
  server/src/test/java/io/crate/integrationtests/OpenCloseTableIntegrationTest.java
Labels: ready-to-merge, v/5.6, v/5.7

#15862 Introduce planner.createContext to keep optimize functionality internal
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  plugins/es-analysis-common/src/test/java/io/crate/analyze/CreateAnalyzerAnalyzerTest.java
  plugins/es-repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureRepositoryAnalyzerTest.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryPluginAnalyzerTest.java
  server/src/main/java/io/crate/action/sql/Session.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/PlannerContext.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
  server/src/test/java/io/crate/analyze/AlterTableRerouteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterPartitionedTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/CreateDropRepositoryAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DecommissionNodeAnalyzerTest.java
  server/src/test/java/io/crate/analyze/KillAnalyzerTest.java
  server/src/test/java/io/crate/analyze/OptimizeTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/RestoreSnapshotAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/JobLauncherWaitForCompletionTest.java
  server/src/test/java/io/crate/planner/ExplainPlannerTest.java
  server/src/test/java/io/crate/planner/PlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
  server/src/test/java/io/crate/planner/operators/CollectTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/operators/LimitTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/OptimizerTest.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
  server/src/test/java/io/crate/planner/statement/CopyToPlannerTest.java
  server/src/test/java/io/crate/planner/statement/SetSessionPlanTest.java
  server/src/test/java/io/crate/replication/logical/plan/CreateSubscriptionPlanTest.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15859 Use monotonic clock in SingleObjectCache
  server/src/main/java/org/elasticsearch/common/util/SingleObjectCache.java
  server/src/test/java/org/elasticsearch/common/util/SingleObjectCacheTests.java
Labels: ready-to-merge

#15881 Correct DocTableInfo.versionCreated() annotation
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
Labels: ready-to-merge

#15882 Local variable cleanup in Indexer
  server/src/main/java/io/crate/execution/dml/Indexer.java
Labels: ready-to-merge

#15884 Fix streaming of netstats for psql protocol
  server/src/main/java/io/crate/expression/reference/sys/node/NodeStatsContext.java
Labels: ready-to-merge

#15877 Fix lookup-join when the smaller side contains multiple outputs
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
Labels: ready-to-merge

#15885 Remove dead code from GatewayService
  server/src/main/java/io/crate/expression/reference/sys/check/node/SysNodeChecks.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/cluster/ClusterState.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/service/MasterService.java
  server/src/main/java/org/elasticsearch/discovery/Discovery.java
  server/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java
  server/src/main/java/org/elasticsearch/gateway/Gateway.java
  server/src/main/java/org/elasticsearch/gateway/GatewayService.java
  server/src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayServiceTests.java
  server/src/test/java/org/elasticsearch/gateway/MetadataWriteDataNodesIT.java
Labels: ready-to-merge

#15851 Remove deprecated index.warmer.enabled setting
  docs/appendices/release-notes/5.8.0.rst
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationSettings.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#15889 Fix order of columns of smaller side of the lookup-join
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
Labels: ready-to-merge

#15887 Add clarification to shard limit docs
  docs/config/cluster.rst
  docs/sql/statements/create-table.rst
Labels: ready-to-merge, v/5.6, v/5.7

#15895 Use `languageLevel` 21 for intellij
  .idea/misc.xml
Labels: ready-to-merge

#15896 Fix partition name creation in RESTORE SNAPSHOT/COPY FROM
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
  docs/sql/statements/restore-snapshot.rst
  server/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java
  server/src/test/java/io/crate/analyze/PartitionPropertiesAnalyzerTest.java
Labels: ready-to-merge, v/5.6, v/5.7

#15899 Add note to FDW doc that only DQL stmts are supported
  docs/admin/fdw.rst
Labels: ready-to-merge, v/5.7

#15888 Unify blob/non-blob alter table settings handling
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AlterBlobTable.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/Table.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/AlterTableAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterBlobTable.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTable.java
  server/src/main/java/io/crate/analyze/AnalyzedStatementVisitor.java
  server/src/main/java/io/crate/analyze/Analyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/node/ddl/AlterBlobTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
Labels: ready-to-merge

#15903 Revert "Use `languageLevel` 21 for intellij"
  .idea/misc.xml
Labels: ready-to-merge

#15890 Clarify createPartitionName/toPartitionName diff in PartitionPropertiesAnalyzer
  server/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java
  server/src/main/java/io/crate/exceptions/PartitionUnknownException.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableOpenClosePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/ddl/OptimizeTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/RefreshTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/management/AlterTableReroutePlan.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/test/java/io/crate/analyze/CreateAlterPartitionedTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/PartitionPropertiesAnalyzerTest.java
Labels: ready-to-merge

#15892 Add IF NOT EXISTS to CREATE TABLE AS
  docs/appendices/release-notes/5.8.0.rst
  docs/sql/statements/create-table-as.rst
  docs/sql/statements/create-table.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/CreateTableAs.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/analyze/CreateTableAsAnalyzer.java
  server/src/main/java/io/crate/execution/ddl/tables/TableCreator.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateTablePlan.java
  server/src/test/java/io/crate/analyze/CreateTableAsAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableAsIntegrationTest.java
Labels: ready-to-merge

#15904 Use free port in test_body_jwk_endpoint_not_responding_contains_error
  server/src/test/java/io/crate/auth/JwtAuthenticationIntegrationTest.java
Labels: ready-to-merge, v/5.7

#15905 Integrate PartitionPropertiesAnalyzer methods into PartitionName
  server/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java
  server/src/main/java/io/crate/metadata/PartitionName.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableOpenClosePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/ddl/OptimizeTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/RefreshTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/management/AlterTableReroutePlan.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/test/java/io/crate/analyze/PartitionPropertiesAnalyzerTest.java
  server/src/test/java/io/crate/metadata/PartitionNameTest.java
Labels: ready-to-merge

#15911 Avoid intermediate map in PartitionName.ofAssignmentsUnsafe
  server/src/main/java/io/crate/metadata/PartitionName.java
Labels: ready-to-merge

#15912 Remove `toIndexName(PartitionName)` from `IndexParts`
  server/src/main/java/io/crate/metadata/IndexParts.java
  server/src/main/java/io/crate/metadata/PartitionName.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
Labels: ready-to-merge

#15917 Fix TODO in GeoShapeIntegrationTest; re-add response column type asserts
  server/src/test/java/io/crate/integrationtests/GeoShapeIntegrationTest.java
  server/src/testFixtures/java/io/crate/testing/SQLResponse.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge

#15918 Apply OpenRewrite assertj recipes
  server/src/test/java/io/crate/execution/dsl/projection/UpdateProjectionTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/BatchPagingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchCollectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorBehaviouralTest.java
  server/src/test/java/io/crate/execution/engine/join/RamBlockSizeCalculatorTest.java
  server/src/test/java/io/crate/execution/engine/profile/CollectProfileRequestTest.java
  server/src/test/java/io/crate/execution/engine/profile/NodeCollectProfileResponseTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  server/src/test/java/io/crate/expression/reference/MapLookupByPathExpressionTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/NodeStatsITest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
  server/src/test/java/io/crate/memory/OnHeapMemoryManagerTest.java
  server/src/test/java/io/crate/metadata/ColumnIdentTest.java
  server/src/test/java/io/crate/metadata/sys/SysOperationsLogTableInfoTest.java
  server/src/test/java/io/crate/metadata/sys/SysSnapshotRestoreTableInfoTest.java
  server/src/test/java/io/crate/metadata/upgrade/IndexTemplateUpgraderTest.java
  server/src/test/java/io/crate/operation/collect/files/CSVLineParserTest.java
  server/src/test/java/io/crate/planner/IndexBaseBuilderTest.java
  server/src/test/java/io/crate/planner/PositionalOrderByTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
  server/src/test/java/io/crate/protocols/ErrorMappingTest.java
  server/src/test/java/io/crate/protocols/postgres/DelayableWriteChannelTest.java
  server/src/test/java/io/crate/protocols/postgres/types/BitTypeTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/types/UndefinedTypeTest.java
  server/src/test/java/org/elasticsearch/action/StepListenerTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/elasticsearch/common/unit/ByteSizeValueTest.java
  server/src/test/java/org/elasticsearch/common/util/concurrent/ThreadContextTest.java
  server/src/test/java/org/elasticsearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/repositories/RepositoryDataTests.java
  server/src/test/java/org/elasticsearch/snapshots/InternalSnapshotsInfoServiceTests.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportHandshakerTests.java
Labels: ready-to-merge

#15920 Ensure that irrelevant partitions are filtered out when generated column and its expression have different types
  docs/appendices/release-notes/5.8.0.rst
  server/src/main/java/io/crate/analyze/GeneratedColumnExpander.java
  server/src/test/java/io/crate/planner/WhereClauseOptimizerTest.java
Labels: ready-to-merge

#15921 MapperService/DocumentMapperParser doesn't need a NamedXContentRegistry
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/RenameColumnTaskTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/KeywordFieldMapperTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
  server/src/test/java/org/elasticsearch/index/engine/LuceneChangesSnapshotTests.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/MapperTestUtils.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#15922 Move CREATE/ALTER ROLE properties parsing to Role.Properties.of()
  libs/sql-parser/src/main/java/io/crate/sql/tree/GenericProperties.java
  server/src/main/java/io/crate/planner/node/ddl/AlterRolePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateRolePlan.java
  server/src/main/java/io/crate/role/Role.java
  server/src/main/java/io/crate/role/UserActions.java
  server/src/test/java/io/crate/planner/node/ddl/CreateRolePlanTest.java
  server/src/test/java/io/crate/role/UserActionsTest.java
Labels: ready-to-merge

#15923 Encapsulate Map within GenericProperties
  libs/sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/ColumnStorageDefinition.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GenericProperties.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/IndexColumnConstraint.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/IndexDefinition.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3RepositoryPluginAnalyzerTest.java
  server/src/main/java/io/crate/analyze/AlterTableRerouteAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedAlterTable.java
  server/src/main/java/io/crate/analyze/AnalyzedCopyFrom.java
  server/src/main/java/io/crate/analyze/AnalyzedCopyTo.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateAnalyzer.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateBlobTable.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateRepository.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateSnapshot.java
  server/src/main/java/io/crate/analyze/AnalyzedCreateTable.java
  server/src/main/java/io/crate/analyze/AnalyzedOptimizeTable.java
  server/src/main/java/io/crate/analyze/AnalyzedRestoreSnapshot.java
  server/src/main/java/io/crate/analyze/AnalyzedRole.java
  server/src/main/java/io/crate/analyze/SwapTableAnalyzer.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/analyze/TableProperties.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/analyze/repositories/RepositoryParamValidator.java
  server/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateRolePlan.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/replication/logical/analyze/AnalyzedCreateSubscription.java
  server/src/main/java/org/elasticsearch/common/settings/Settings.java
Labels: ready-to-merge

#15927 Remove support for updating index settings via wildcards
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
Labels: ready-to-merge

#15928 Replace TransportUpdateSettingsAction usages with alter table
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/UpdateSettingsRequest.java
  server/src/test/java/org/elasticsearch/cluster/ClusterHealthIT.java
  server/src/test/java/org/elasticsearch/index/IndexServiceTests.java
  server/src/test/java/org/elasticsearch/index/seqno/GlobalCheckpointSyncIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15929 Remove DestructiveOperations
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/TransportDeleteIndexAction.java
  server/src/main/java/org/elasticsearch/action/support/DestructiveOperations.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
Labels: ready-to-merge

#15930 Use locally defined FieldTypes in Indexers
  benchmarks/src/main/java/io/crate/execution/dml/IndexerBenchmark.java
  server/src/main/java/io/crate/execution/dml/BitStringIndexer.java
  server/src/main/java/io/crate/execution/dml/BooleanIndexer.java
  server/src/main/java/io/crate/execution/dml/DoubleIndexer.java
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/FloatIndexer.java
  server/src/main/java/io/crate/execution/dml/FloatVectorIndexer.java
  server/src/main/java/io/crate/execution/dml/FulltextIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoPointIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoShapeIndexer.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/IntIndexer.java
  server/src/main/java/io/crate/execution/dml/IpIndexer.java
  server/src/main/java/io/crate/execution/dml/LongIndexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/StringIndexer.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/BitStringType.java
  server/src/main/java/io/crate/types/BooleanType.java
  server/src/main/java/io/crate/types/ByteType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/main/java/io/crate/types/FloatVectorType.java
  server/src/main/java/io/crate/types/GeoPointType.java
  server/src/main/java/io/crate/types/GeoShapeType.java
  server/src/main/java/io/crate/types/IntegerType.java
  server/src/main/java/io/crate/types/IpType.java
  server/src/main/java/io/crate/types/LongType.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/main/java/io/crate/types/ShortType.java
  server/src/main/java/io/crate/types/StorageSupport.java
  server/src/main/java/io/crate/types/StringType.java
  server/src/main/java/io/crate/types/TimestampType.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/test/java/io/crate/execution/dml/FloatVectorIndexerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#15931 Prohibit creating tables named _all
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
  server/src/main/java/io/crate/metadata/RelationName.java
  server/src/test/java/io/crate/metadata/RelationNameTest.java
Labels: ready-to-merge, v/5.6, v/5.7

#15935 Make Table/index resolving strict to prevent resolving _all
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/planner/DeletePlannerTest.java
Labels: ready-to-merge, v/5.6, v/5.7

#15939 Raise error on getPartitions if table is not partitioned
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
Labels: ready-to-merge

#15940 Engine translog operations don't need MapperService
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java
  server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/LuceneChangesSnapshotTests.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge
