Repository crate/crate, pull requests merged in 2024-06, with the labels that each got.

#16072 Update maven plugins
  pom.xml
  server/pom.xml
Labels: ready-to-merge

#16053 Make Schemas final in IndicesService
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge

#16077 Fix current_setting(<setting>, <boolean>) nullability
  server/src/main/java/io/crate/expression/scalar/postgres/CurrentSettingFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.7

#16041 Allow access to foreign table referenced by view with view owner's user mapping
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/execution/dsl/phases/ForeignCollectPhase.java
  server/src/main/java/io/crate/fdw/ForeignDataWrappers.java
  server/src/main/java/io/crate/fdw/JdbcForeignDataWrapper.java
  server/src/main/java/io/crate/planner/operators/ForeignCollect.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/optimizer/rule/MergeFilterAndForeignCollect.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
Labels: ready-to-merge, v/5.7

#16054 Add memory accounting for caching rows in lag/lead
  benchmarks/src/main/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  docs/appendices/release-notes/5.7.2.rst
  extensions/functions/src/main/java/io/crate/window/NthValueFunctions.java
  extensions/functions/src/main/java/io/crate/window/OffsetValueFunctions.java
  extensions/functions/src/main/java/io/crate/window/RankFunctions.java
  extensions/functions/src/test/java/io/crate/window/OffsetValueFunctionsTest.java
  server/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  server/src/main/java/io/crate/execution/engine/window/RowNumberWindowFunction.java
  server/src/main/java/io/crate/execution/engine/window/WindowFunction.java
  server/src/main/java/io/crate/execution/engine/window/WindowFunctionBatchIterator.java
  server/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
  server/src/test/java/io/crate/statistics/SketchRamAccountingTest.java
  server/src/testFixtures/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  server/src/testFixtures/java/io/crate/testing/PlainRamAccounting.java
Labels: ready-to-merge, v/5.7

#16073 Replace deprecated TermInSetQuery ctor call
  server/src/main/java/io/crate/expression/operator/EqOperator.java
  server/src/test/java/io/crate/integrationtests/LuceneQueryBuilderIntegrationTest.java
Labels: ready-to-merge

#16081 Remove quote/search analyzers
  server/src/main/java/org/elasticsearch/index/analysis/IndexAnalyzers.java
  server/src/main/java/org/elasticsearch/index/mapper/ArrayFieldType.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
  server/src/main/java/org/elasticsearch/index/query/QueryShardContext.java
  server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
  server/src/main/java/org/elasticsearch/index/search/MultiMatchQuery.java
Labels: ready-to-merge

#16083 Correctly parse geopoints within nested arrays
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge, v/5.7

#16091 Give IndexShard access to DocTableInfo supplier
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#16089 Convert FieldNamesFieldMapper into singleton
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
Labels: ready-to-merge

#16094 Add changes entry for #16083
  docs/appendices/release-notes/5.7.2.rst
Labels: ready-to-merge, v/5.7

#16079 Fix column pruning in collect operator
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/test/java/io/crate/planner/operators/CollectTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.7

#16098 Fix issue with slow query because of PK extraction
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorBaseTest.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, v/5.7

#16068 Fix has_table_privilege for unknown tables
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/HasTablePrivilegeFunction.java
  server/src/main/java/io/crate/role/RolePrivileges.java
  server/src/test/java/io/crate/expression/scalar/HasTablePrivilegeFunctionTest.java
Labels: ready-to-merge

#16092 Remove fieldType() from MapperService; move IndexAnalyzer to IndexShard
  server/src/main/java/io/crate/lucene/FieldTypeLookup.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/index/analysis/AnalysisRegistry.java
  server/src/main/java/org/elasticsearch/index/analysis/IndexAnalyzers.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: ready-to-merge

#16093 Remove MapperService.merge
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/expression/reference/sys/shard/ShardRowContext.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/expression/predicate/IsNullPredicateTest.java
  server/src/test/java/io/crate/expression/reference/doc/DocLevelExpressionsTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/KeywordFieldMapperTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
  server/src/testFixtures/java/org/elasticsearch/index/MapperTestUtils.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#16102 Remove MapperService and related components
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MappingMetadata.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/mapper/ArrayTypeParser.java
  server/src/main/java/org/elasticsearch/index/mapper/BitStringFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentFieldMappers.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FloatVectorFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperMergeValidator.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperUtils.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapping.java
  server/src/main/java/org/elasticsearch/index/mapper/MetadataFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectArrayMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ParsedDocument.java
  server/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TypeParsers.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/elasticsearch/indices/mapper/MapperRegistry.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/metadata/upgrade/IndexTemplateUpgraderTest.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
Labels: ready-to-merge

#16087 Docs: Add few COPY TO examples
  docs/sql/statements/copy-to.rst
Labels: docs

#16101 Identify has-privilege scalar functions as NULLABLE
  server/src/main/java/io/crate/expression/scalar/HasDatabasePrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasPrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasSchemaPrivilegeFunction.java
  server/src/main/java/io/crate/expression/scalar/HasTablePrivilegeFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge

#15760 Enable push-down of constant join conditions in cross and outer-joins
  docs/appendices/release-notes/5.8.0.rst
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoinTest.java
Labels: ready-to-merge

#16105 Reuse IndexParts.isDangling in DanglingArtifactsService
  server/src/main/java/io/crate/metadata/DanglingArtifactsService.java
Labels: ready-to-merge

#16115 Update to Lucene 9.11.0
  pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16113 Update drop-repository.rst
  docs/sql/statements/drop-repository.rst
Labels: ready-to-merge, v/5.7

#16108 Take into account connection payload on HBA method matching
  docs/admin/auth/hba.rst
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/auth/ClientCertAuth.java
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/main/java/io/crate/auth/HttpAuthUpstreamHandler.java
  server/src/main/java/io/crate/protocols/postgres/ConnectionProperties.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java
  server/src/test/java/io/crate/auth/AuthenticationWithSSLIntegrationTest.java
  server/src/test/java/io/crate/auth/ClientCertAuthTest.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/protocols/postgres/AuthenticationContextTest.java
Labels: ready-to-merge, v/5.7

#16118 Add user mapping example on empty code block
  docs/sql/statements/create-user-mapping.rst
Labels: ready-to-merge, docs, v/5.7

#16129 Only re-create DocTableInfo if template/index metadata changed
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
Labels: ready-to-merge

#16125 Collect must use it's own output instances on prunning
  server/src/main/java/io/crate/planner/operators/Collect.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.7

#16130 Make BatchIteratorTester result check stricter
  libs/dex/src/test/java/io/crate/data/AsyncCompositeBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/AsyncFlatMapBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/CollectingBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/CompositeBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/FilteringBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/FlatMapBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/InMemoryBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/LimitingBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/SkippingBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/TopNDistinctBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/join/CrossJoinBlockNLBatchIteratorTest.java
  libs/dex/src/test/java/io/crate/data/join/NestedLoopBatchIteratorsTest.java
  libs/dex/src/testFixtures/java/io/crate/data/testing/BatchIteratorTester.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/NodeStatsTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OrderedLuceneBatchIteratorFactoryTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/BatchPagingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
Labels: ready-to-merge

#16136 Fix blob file transfer to clients via HTTPS
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/protocols/http/HttpBlobHandler.java
  server/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
Labels: ready-to-merge, v/5.7

#16135 Migrate tests to use jdk HttpClient instead of apache HttpClient
  server/pom.xml
  server/src/main/java/io/crate/netty/channel/PipelineRegistry.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/test/java/io/crate/auth/AuthenticationIntegrationTest.java
  server/src/test/java/io/crate/auth/JwtAuthenticationIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BlobHttpClient.java
  server/src/test/java/io/crate/integrationtests/BlobHttpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BlobIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RestSQLActionIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLHttpIntegrationTest.java
  server/src/test/java/io/crate/protocols/http/CrateHttpsTransportIntegrationTest.java
  server/src/test/java/io/crate/protocols/http/HttpsTransportKeyStoreReloadIntegrationTest.java
  server/src/test/java/io/crate/rest/AdminUIHttpIntegrationTest.java
  server/src/test/java/io/crate/rest/AdminUIIntegrationTest.java
  server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
  server/src/testFixtures/java/io/crate/test/utils/Blobs.java
Labels: ready-to-merge

#16140 Remove aws s3 sdk dependency from server module
  plugins/cr8-copy-s3/pom.xml
  plugins/es-repository-url/src/main/java/org/elasticsearch/common/blobstore/url/URLBlobStore.java
  pom.xml
  server/pom.xml
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/main/java/org/elasticsearch/common/network/DnsResolver.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
Labels: ready-to-merge

#16139 Fix: allow users with DDL on table to run ALTER TABLE REROUTE
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/metadata/table/ShardedTable.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge, v/5.7

#16141 Remove unused methods from CrateLuceneTestCase
  server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
Labels: ready-to-merge

#16088 Add `pg_table_is_visible` scalar
  docs/appendices/release-notes/5.8.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/postgres/PgTableIsVisibleFunction.java
  server/src/test/java/io/crate/expression/scalar/postgres/PgTableIsVisibleFunctionTest.java
  server/src/testFixtures/java/io/crate/testing/SqlExpressions.java
Labels: ready-to-merge

#16150 Size some Map instances upfront
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  server/src/main/java/io/crate/analyze/AnalyzedInsertStatement.java
  server/src/main/java/io/crate/execution/engine/collect/sources/SysTableRegistry.java
  server/src/main/java/io/crate/expression/reference/sys/check/node/SysNodeChecks.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/role/RoleManagerService.java
  server/src/main/java/io/crate/role/metadata/SysPrivilegesTableInfo.java
  server/src/main/java/io/crate/role/metadata/SysRolesTableInfo.java
  server/src/main/java/io/crate/role/metadata/SysUsersTableInfo.java
  server/src/main/java/io/crate/statistics/Samples.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge

#16146 Implemented pg_catalog.pg_matviews
  docs/appendices/release-notes/5.8.0.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgMatviews.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge

#16142 Expand lucene reference resolver tests to object and geo_point types
  server/src/test/java/io/crate/types/ArrayTypeTest.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#16144 Untangle UserDefinedFunctionService from NodeContext/Schemas
  extensions/lang-js/src/test/java/io/crate/operation/language/JavascriptUserDefinedFunctionTest.java
  server/src/main/java/io/crate/expression/udf/UserDefinedFunctionService.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/main/java/io/crate/metadata/NodeContext.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfoFactory.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  server/src/test/java/io/crate/expression/udf/UdfUnitTest.java
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionServiceTest.java
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionsTest.java
  server/src/test/java/io/crate/integrationtests/SchemaAndRelationNamesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/UserDefinedFunctionsIntegrationTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge

#16137 Fix column pruning for correlated sub-queries
  server/src/main/java/io/crate/planner/operators/CorrelatedJoin.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/planner/CorrelatedJoinPlannerTest.java
Labels: ready-to-merge, v/5.7

#16157 Ignore object reference resolver test temporarily
  server/src/test/java/io/crate/types/ObjectTypeTest.java
Labels: ready-to-merge

#16153 Increase recursion level in TestSqlParser
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
Labels: ready-to-merge

#16160 Bump version to 5.7.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.7.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16161 Reflect release 5.7.2
  docs/appendices/release-notes/5.7.2.rst
  docs/appendices/release-notes/5.7.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#16159 tests: Remove superfluous method for StackOverflowException test in the parser
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
Labels: ready-to-merge

#16163 Don't randomly test nested objects in reference resolver tests
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
Labels: ready-to-merge

#16162 Remove redundant join-reordering from JoinPlanBuilder
  server/src/main/java/io/crate/planner/operators/JoinOrdering.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinOrderingTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
Labels: ready-to-merge

#16134 Resolve view owners during analysis
  server/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
Labels: ready-to-merge

#16165 Show view sub-columns in information_schema.columns
  docs/appendices/release-notes/5.7.3.rst
  docs/sql/statements/create-view.rst
  server/src/main/java/io/crate/metadata/view/ViewInfo.java
  server/src/main/java/io/crate/metadata/view/ViewInfoFactory.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
Labels: ready-to-merge, v/5.7

#16167 Fix issue with JDBC FWD and JSONB PostgreSQL type
  docs/admin/fdw.rst
  docs/appendices/release-notes/5.7.3.rst
  server/src/main/java/io/crate/types/ResultSetParser.java
Labels: ready-to-merge, v/5.7

#16151 Remove NetworkPlugin extension point
  app/src/main/java/org/elasticsearch/bootstrap/BootstrapProxy.java
  app/src/test/java/io/crate/node/NodeSettingsTest.java
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  benchmarks/src/main/java/io/crate/execution/dml/IndexerBenchmark.java
  server/src/main/java/io/crate/netty/channel/PipelineRegistry.java
  server/src/main/java/org/elasticsearch/cluster/ClusterModule.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/AllocationCommand.java
  server/src/main/java/org/elasticsearch/common/network/NetworkModule.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/http/HttpTransportSettings.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
  server/src/main/java/org/elasticsearch/transport/Netty4Plugin.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
  server/src/test/java/io/crate/rest/AdminUIHttpIntegrationTest.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
  server/src/test/java/org/elasticsearch/indices/IndicesServiceCloseTests.java
  server/src/testFixtures/java/org/elasticsearch/node/MockNode.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/test/InternalTestClusterTests.java
Labels: ready-to-merge

#16169 Print info about remaining ForkJoinPool threads
  server/src/testFixtures/java/io/crate/lucene/CrateLuceneTestCase.java
Labels: ready-to-merge

#16175 Move getAccessControl from RoleManager to Roles
  server/src/main/java/io/crate/rest/action/RestSQLAction.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/main/java/io/crate/role/RoleManager.java
  server/src/main/java/io/crate/role/Roles.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
Labels: ready-to-merge

#16183 Convert settings to HBAConf record instead of `Map<String, String>`
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
Labels: ready-to-merge

#16180 Depend directly on RelationAnalzyer in ViewInfoFactory
  server/src/main/java/io/crate/metadata/NodeContext.java
  server/src/main/java/io/crate/metadata/view/ViewInfoFactory.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/view/ViewInfoFactoryTest.java
Labels: ready-to-merge

#16185 Remove blobIndicesService dependency from HttpBlobHandler
  server/src/main/java/io/crate/blob/BlobService.java
  server/src/main/java/io/crate/protocols/http/HttpBlobHandler.java
Labels: ready-to-merge

#16190 Fix joins with foreign tables on multi-node clusters
  docs/appendices/release-notes/5.7.3.rst
  server/src/main/java/io/crate/planner/node/StreamerVisitor.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
Labels: ready-to-merge, v/5.7

#16191 Add `getStreamers` to ExecutionPhase/remove StreamerVisitor
  server/src/main/java/io/crate/execution/dsl/phases/AbstractProjectionsPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/CountPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/ExecutionPhase.java
  server/src/main/java/io/crate/execution/dsl/phases/FetchPhase.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumerFactory.java
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
  server/src/main/java/io/crate/planner/node/StreamerVisitor.java
  server/src/testFixtures/java/io/crate/testing/StubPhases.java
Labels: ready-to-merge

#16197 Bump JDK to 22.0.1+8
  pom.xml
Labels: ready-to-merge

#16198 Fix some rawtype warnings
  server/src/main/java/io/crate/execution/engine/collect/collectors/LuceneBatchIterator.java
  server/src/main/java/io/crate/execution/engine/collect/collectors/ScoreDocRowFunction.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/expression/InputFactory.java
  server/src/main/java/io/crate/expression/RowFilter.java
  server/src/main/java/io/crate/expression/scalar/timestamp/TimezoneFunction.java
  server/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  server/src/main/java/io/crate/metadata/MapBackedRefResolver.java
  server/src/main/java/io/crate/metadata/Scalar.java
  server/src/main/java/io/crate/metadata/shard/ShardReferenceResolver.java
  server/src/main/java/io/crate/protocols/postgres/types/DateType.java
  server/src/main/java/org/elasticsearch/common/collect/ImmutableOpenMap.java
  server/src/test/java/io/crate/analyze/EvaluatingNormalizerTest.java
  server/src/test/java/io/crate/execution/engine/export/FileWriterCountCollectorTest.java
  server/src/test/java/io/crate/metadata/MapBackedRefResolverTest.java
Labels: ready-to-merge

#16205 Update some library dependencies
  pom.xml
Labels: ready-to-merge

#16210 tests: migrate various tests to assertj
  server/src/test/java/io/crate/analyze/TableInfoToASTTest.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/breaker/MapSizeEstimatorTest.java
  server/src/test/java/io/crate/execution/dsl/projection/MergeCountProjectionTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  server/src/test/java/io/crate/execution/engine/collect/HandlerSideLevelCollectTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  server/src/test/java/io/crate/execution/engine/collect/sources/ColumnsIterableTest.java
  server/src/test/java/io/crate/execution/engine/collect/stats/JobsLogsTest.java
  server/src/test/java/io/crate/execution/engine/distribution/BroadcastingBucketBuilderTest.java
  server/src/test/java/io/crate/execution/engine/distribution/TransportDistributedResultActionTest.java
  server/src/test/java/io/crate/execution/engine/fetch/ReaderBucketsTest.java
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/LimitAndOffsetProjectorTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/MapRowUsingInputsTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/window/WindowFunctionBatchIteratorTest.java
  server/src/test/java/io/crate/execution/jobs/DistResultRXTaskTest.java
  server/src/test/java/io/crate/execution/jobs/kill/KillResponseTest.java
  server/src/test/java/io/crate/execution/support/ChainableActionsTest.java
  server/src/test/java/io/crate/executor/transport/ExecutionPhasesRootTaskTest.java
  server/src/test/java/io/crate/expression/reference/MapLookupByPathExpressionTest.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/tablefunctions/AbstractTableFunctionsTest.java
  server/src/test/java/io/crate/expression/tablefunctions/MatchesFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/PgExpandArrayTest.java
  server/src/test/java/io/crate/expression/udf/UserDefinedFunctionServiceTest.java
  server/src/test/java/io/crate/integrationtests/BlobTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BulkInsertOnClientNodeTest.java
  server/src/test/java/io/crate/integrationtests/ExplainAnalyzeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ShardStatsTest.java
  server/src/test/java/io/crate/metadata/RoutingTest.java
  server/src/test/java/io/crate/metadata/SchemasITest.java
  server/src/test/java/io/crate/metadata/table/OperationTest.java
  server/src/test/java/io/crate/metadata/upgrade/MetadataIndexUpgraderTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
  server/src/test/java/io/crate/protocols/ssl/SslContextProviderTest.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/io/crate/rest/action/SqlHttpHandlerTest.java
  server/src/test/java/io/crate/statistics/ColumnStatsTest.java
  server/src/test/java/io/crate/statistics/StatsTest.java
  server/src/test/java/org/elasticsearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/elasticsearch/index/engine/ReadOnlyEngineTests.java
Labels: ready-to-merge

#16212 tests: Fix assertion for testSelectGroupByIncludingUnassignedShards
  server/src/test/java/io/crate/integrationtests/ShardStatsTest.java
Labels: ready-to-merge

#16208 Replace lunasec.io link regarding log4j vulnerability with wikipedia link
  docs/appendices/release-notes/4.6.6.rst
Labels: ready-to-merge, v/4.8, v/5.5, v/5.6, v/5.7

#16211 tests: Remove ExpectedException class Rule
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge

#16200 Fix false positive hash join detection
  docs/appendices/release-notes/5.7.3.rst
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/test/java/io/crate/planner/operators/EquiJoinDetectorTest.java
Labels: ready-to-merge, v/5.7

#16218 Remove some unused setting methods
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
Labels: ready-to-merge

#16220 Test reference resolvers for types with index/column store off
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/types/ArrayTypeTest.java
  server/src/test/java/io/crate/types/BitStringTypeTest.java
  server/src/test/java/io/crate/types/BooleanTypeTest.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
  server/src/test/java/io/crate/types/IpTypeTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#16221 Better encapsulate synthetic columns in indexer
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/BitStringIndexer.java
  server/src/main/java/io/crate/execution/dml/BooleanIndexer.java
  server/src/main/java/io/crate/execution/dml/DoubleIndexer.java
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/execution/dml/FloatIndexer.java
  server/src/main/java/io/crate/execution/dml/FloatVectorIndexer.java
  server/src/main/java/io/crate/execution/dml/FulltextIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoPointIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoShapeIndexer.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/IntIndexer.java
  server/src/main/java/io/crate/execution/dml/IpIndexer.java
  server/src/main/java/io/crate/execution/dml/LongIndexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/execution/dml/StringIndexer.java
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/main/java/io/crate/execution/dml/ValueIndexer.java
Labels: ready-to-merge

#16229 Apply Lucene 9.11.0 changes to CustomLucene90DocValuesConsumer
  server/src/main/java/io/crate/lucene/codec/CustomLucene90DocValuesConsumer.java
Labels: ready-to-merge

#16233 Fixed nullability for `format_type` scalar
  docs/appendices/release-notes/5.7.3.rst
  server/src/main/java/io/crate/expression/scalar/systeminformation/FormatTypeFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, v/5.7

#16223 Remove a few duplicate test table definitions
  server/src/test/java/io/crate/analyze/SelectFromViewAnalyzerTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoinTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoinTest.java
Labels: ready-to-merge

#16231 Undeprecate bytesAsInt and SUPPORTS_V6
  server/src/main/java/org/elasticsearch/common/network/NetworkService.java
  server/src/main/java/org/elasticsearch/common/network/NetworkUtils.java
  server/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
  server/src/main/java/org/elasticsearch/index/shard/PrimaryReplicaSyncer.java
Labels: ready-to-merge

#16242 Fix false positive HashJoin detection for NOT operator
  docs/appendices/release-notes/5.7.3.rst
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/test/java/io/crate/planner/operators/EquiJoinDetectorTest.java
Labels: ready-to-merge, v/5.7

#16245 Remove comment (debugging artefact)
  server/src/test/java/io/crate/planner/operators/EquiJoinDetectorTest.java
Labels: ready-to-merge, v/5.7

#16246 Upgrade to lucene 9.11.1
  pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge
