Repository crate/crate, pull requests merged in 2024-05, with the labels that each got.

#15924 Do not normalize nondeterministic functions during analysis
  docs/appendices/release-notes/5.6.5.rst
  docs/appendices/release-notes/5.7.1.rst
  server/src/main/java/io/crate/analyze/CopyAnalyzer.java
  server/src/main/java/io/crate/analyze/DeleteAnalyzer.java
  server/src/main/java/io/crate/analyze/InsertAnalyzer.java
  server/src/main/java/io/crate/analyze/UpdateAnalyzer.java
  server/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
Labels: ready-to-merge, v/5.6, v/5.7

#15943 Don't pass MapperService to LuceneReferenceResolver
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/fetch/NodeFetchOperation.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolver.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/execution/engine/collect/GroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/LuceneReferenceResolverTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
Labels: ready-to-merge

#15947 Release 5.6.5
  docs/appendices/release-notes/5.6.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15950 Reflect release 5.6.5
  docs/appendices/release-notes/5.6.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15949 Reflect 5.6.5 on 5.7
  docs/appendices/release-notes/5.6.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15953 Release 5.7.1
  docs/appendices/release-notes/5.7.1.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15957 Reflect release 5.7.2 on master
  docs/appendices/release-notes/5.7.1.rst
  docs/appendices/release-notes/5.7.2.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#15952 Simplify CodecService construction
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/CrateCodec.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/indices/IndexingMemoryControllerIT.java
  server/src/test/java/org/elasticsearch/indices/IndexingMemoryControllerTests.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/EngineTestCase.java
Labels: ready-to-merge

#15954 Add tests to verify analyzers do not normalize nondeterministic func
  server/src/test/java/io/crate/analyze/CopyAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/InsertAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
Labels: ready-to-merge

#15960 Call ramAccounting.addBytes once with total, instead of per item
  server/src/main/java/io/crate/execution/engine/indexing/ShardDMLExecutor.java
Labels: ready-to-merge

#15934 Remove join on top of lookup-join when only one side is retrieved
  server/src/main/java/io/crate/planner/operators/AbstractJoinPlan.java
  server/src/main/java/io/crate/planner/operators/HashJoin.java
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveOrderBeneathNestedLoop.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderHashJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/ReorderNestedLoopJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnOuterJoinToInnerJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteJoinPlan.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
Labels: ready-to-merge

#15963 Inline some duplicate setting constants
  server/src/main/java/io/crate/analyze/NumberOfReplicas.java
  server/src/main/java/io/crate/metadata/settings/NumberOfReplicasSetting.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationSettings.java
  server/src/main/java/org/elasticsearch/cluster/metadata/AutoExpandReplicas.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  server/src/test/java/io/crate/analyze/NumberOfReplicasTest.java
  server/src/test/java/io/crate/integrationtests/BlobHttpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RecoveryTests.java
  server/src/test/java/org/elasticsearch/action/support/replication/ClusterStateCreationUtils.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/TrackFailedAllocationNodesTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15964 Update tqdm to latest version
  blackbox/requirements.txt
Labels: ready-to-merge

#15974 Deduplicate test cases in ColumnPolicyIntegrationTest
  server/src/test/java/io/crate/integrationtests/ColumnPolicyIntegrationTest.java
Labels: ready-to-merge

#15975 Remove uses of GetIndexTemplatesRequest from itests
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#15972 Make PriorityComparator final instead of abstract
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/elasticsearch/gateway/PriorityComparator.java
Labels: ready-to-merge

#15985 Remove redundant `executeAlterTable` prefixes from AlterTableOperation
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableOperation.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropCheckConstraintPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableDropColumnPlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableOpenClosePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTableRenameTablePlan.java
Labels: ready-to-merge

#15986 Mark IntegTestCase.refresh as deprecated
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge

#15987 Remove shared setup in js udf itest; use sql table refresh
  extensions/lang-js/src/test/java/io/crate/operation/language/JavaScriptUDFIntegrationTest.java
Labels: ready-to-merge

#15983 Remove putMapping from local shard recovery
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/TransportPutMappingAction.java
  server/src/main/java/org/elasticsearch/client/IndicesAdminClient.java
  server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge

#15968 Add memory accounting for multi-phase execution
  docs/appendices/release-notes/5.7.2.rst
  server/src/main/java/io/crate/execution/MultiPhaseExecutor.java
  server/src/main/java/io/crate/execution/engine/CorrelatedJoinProjector.java
  server/src/main/java/io/crate/execution/engine/FirstColumnConsumers.java
  server/src/main/java/io/crate/expression/symbol/SelectSymbol.java
  server/src/test/java/io/crate/execution/engine/FirstColumnConsumersTest.java
Labels: ready-to-merge, v/5.7

#15991 Remove BlobAdminClient
  server/src/main/java/io/crate/blob/v2/BlobAdminClient.java
  server/src/test/java/io/crate/integrationtests/BlobHttpIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/BlobPathITest.java
  server/src/test/java/io/crate/integrationtests/RecoveryTests.java
Labels: ready-to-merge

#15998 Update GraalVM to 24.0.1
  pom.xml
Labels: ready-to-merge

#15999 Fix rawtype warning in TransportBroadcastReplicationAction
  server/src/main/java/org/elasticsearch/action/support/replication/TransportBroadcastReplicationAction.java
Labels: ready-to-merge

#16006 Remove unused properties from QueryShardContext
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/query/QueryShardContext.java
  server/src/main/java/org/elasticsearch/index/query/QueryShardException.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
Labels: ready-to-merge

#16007 Use DocTableInfo to parse transaction log entries
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/metadata/Schemas.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/index/mapper/Mapping.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/io/crate/testing/ParsedDocumentAssert.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge

#16009 Remove MapperPlugin
  server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/MapperPlugin.java
  server/src/test/java/io/crate/metadata/doc/mappers/KeywordFieldMapperTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/org/elasticsearch/index/MapperTestUtils.java
Labels: ready-to-merge

#16014 Amend SWAP TABLE WITH drop_source explanation
  docs/sql/statements/alter-cluster.rst
Labels: ready-to-merge, docs, v/5.7

#16016 Use .hasSize() instead of .size()).isEqualTo()
  plugins/es-analysis-common/src/test/java/io/crate/integrationtests/FulltextAnalyzerResolverTest.java
  server/src/test/java/io/crate/action/sql/SessionTest.java
  server/src/test/java/io/crate/analyze/CursorTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/parser/TypeSignatureParserTest.java
  server/src/test/java/io/crate/analyze/relations/RelationAnalyzerTest.java
  server/src/test/java/io/crate/execution/ddl/tables/RenameColumnTaskTest.java
  server/src/test/java/io/crate/execution/jobs/SharedShardContextsTest.java
  server/src/test/java/io/crate/integrationtests/BlobPathITest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/disruption/routing/PrimaryAllocationIT.java
  server/src/test/java/io/crate/planner/IndexBaseBuilderTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
  server/src/test/java/io/crate/planner/statement/CopyToPlannerTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
  server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/elasticsearch/cluster/ClusterHealthIT.java
  server/src/test/java/org/elasticsearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ClusterBootstrapServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTests.java
  server/src/test/java/org/elasticsearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/RoutingNodeTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DeadNodesAllocationTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/IndexBalanceTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/elasticsearch/common/bytes/PagedBytesReferenceTests.java
  server/src/test/java/org/elasticsearch/common/bytes/ReleasableBytesReferenceTests.java
  server/src/test/java/org/elasticsearch/common/io/stream/BytesStreamsTests.java
  server/src/test/java/org/elasticsearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/elasticsearch/common/settings/SettingsTests.java
  server/src/test/java/org/elasticsearch/gateway/AsyncShardFetchTests.java
  server/src/test/java/org/elasticsearch/gateway/DanglingIndicesStateTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayIndexStateIT.java
  server/src/test/java/org/elasticsearch/gateway/IncrementalClusterStateWriterTests.java
  server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorTests.java
  server/src/test/java/org/elasticsearch/index/seqno/LocalCheckpointTrackerTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/store/StoreTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTest.java
  server/src/testFixtures/java/io/crate/testing/SettingsAssert.java
  server/src/testFixtures/java/org/elasticsearch/test/AbstractXContentTestCaseTests.java
Labels: ready-to-merge

#16017 Use isTrue()/isFalse() instead of isEqualTo(true/false)
  extensions/jmx-monitoring/src/test/java/io/crate/beans/NodeInfoTest.java
  libs/shared/src/test/java/io/crate/common/StringUtilsTest.java
  plugins/es-repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientSettingsTests.java
  server/src/test/java/io/crate/analyze/CreateFunctionAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/analyze/RoleDDLAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SetAnalyzerTest.java
  server/src/test/java/io/crate/analyze/ValueNormalizerTest.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/FetchCollectorTest.java
  server/src/test/java/io/crate/execution/engine/indexing/UpsertResultsTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/RecoveryTests.java
  server/src/test/java/io/crate/integrationtests/SysNodeCheckerIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  server/src/test/java/io/crate/integrationtests/UpdateIntegrationTest.java
  server/src/test/java/io/crate/metadata/RelationNameTest.java
  server/src/test/java/io/crate/metadata/sys/SysSnapshotRestoreTableInfoTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/types/DataTypesTest.java
  server/src/test/java/io/crate/types/StringTypeTest.java
  server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/elasticsearch/cluster/ClusterHealthIT.java
  server/src/test/java/org/elasticsearch/cluster/coordination/CoordinationMetadataTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/LinearizabilityCheckerTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/AllocationCommandsTests.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DeadNodesAllocationTests.java
  server/src/test/java/org/elasticsearch/common/io/stream/BytesStreamsTests.java
  server/src/test/java/org/elasticsearch/gateway/AsyncShardFetchTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayIndexStateIT.java
  server/src/test/java/org/elasticsearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorTests.java
  server/src/test/java/org/elasticsearch/index/engine/CombinedDeletionPolicyTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/engine/NoOpEngineTests.java
  server/src/test/java/org/elasticsearch/index/seqno/LocalCheckpointTrackerTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/index/store/StoreTests.java
  server/src/test/java/org/elasticsearch/node/InternalSettingsPreparerTest.java
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/hamcrest/ElasticsearchAssertions.java
Labels: ready-to-merge

#16019 Update netty to 4.1.110
  pom.xml
Labels: ready-to-merge

#16021 Set JVM variable rejectClientInitiatedRenegotiation to true by default
  app/src/main/dist/bin/crate
  app/src/main/dist/bin/crate.bat
  docs/appendices/release-notes/5.7.2.rst
Labels: ready-to-merge

#16023 Move rejectClientInitiatedRenegotiation out of GC section; tweak release notes
  app/src/main/dist/bin/crate
  app/src/main/dist/bin/crate.bat
  docs/appendices/release-notes/5.7.2.rst
Labels: ready-to-merge, v/5.7

#16031 Optimize PartitionName.templateName
  server/src/main/java/io/crate/metadata/PartitionName.java
Labels: ready-to-merge

#16032 Fix a NPE in blob recovery
  server/src/main/java/io/crate/blob/BlobContainer.java
Labels: ready-to-merge

#16027 Remove unused removeTemplates from MetadataIndexTemplateService
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
Labels: ready-to-merge

#16037 Exclude system tables when wiping test data
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge

#16038 Remove filters from tablesStream
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
Labels: ready-to-merge

#16034 Remove MapperService dependency from DocTableInfo.writeTo
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableTask.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropColumnAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropConstraintAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameColumnAction.java
  server/src/main/java/io/crate/metadata/ColumnIdent.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/test/java/io/crate/execution/ddl/tables/AddColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/execution/ddl/tables/RenameColumnTaskTest.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/metadata/ColumnIdentTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge

#16051 Update maven used by maven-wrapper to 3.9.7
  .mvn/wrapper/maven-wrapper.properties
Labels: ready-to-merge

#16042 Calculate and set default for `number_of_routing_shards`
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.0.rst
  docs/general/builtins/aggregation.rst
  docs/general/ddl/alter-table.rst
  docs/general/ddl/sharding.rst
  docs/general/dql/fulltext.rst
  docs/general/dql/selects.rst
  docs/sql/statements/create-table.rst
  plugins/es-analysis-common/src/test/java/io/crate/analysis/common/FulltextITest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeActionTest.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexServiceTest.java
Labels: ready-to-merge

#16056 Remove mapperService.merge from AlterTableClusterStateExecutor
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/org/elasticsearch/index/mapper/MapperService.java
Labels: ready-to-merge

#16057 Add timeout for wipeAllTables in test teardown
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge

#16061 Fix flaky join integration test
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
Labels: ready-to-merge

#16058 Remove DocumentParser.parse & FieldMapper.parse
  server/src/main/java/org/elasticsearch/index/mapper/ArrayMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ArrayMapperFactory.java
  server/src/main/java/org/elasticsearch/index/mapper/BitStringFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FloatVectorFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MetadataFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ParseContext.java
  server/src/main/java/org/elasticsearch/index/mapper/ParsedDocument.java
  server/src/main/java/org/elasticsearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/LuceneOrderedDocCollectorTest.java
  server/src/test/java/io/crate/metadata/doc/mappers/array/ArrayMapperTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#16049 Disable lookup-join optimization by default
  docs/appendices/release-notes/5.8.0.rst
  server/src/main/java/io/crate/action/sql/Sessions.java
  server/src/main/java/io/crate/metadata/settings/CoordinatorSessionSettings.java
  server/src/main/java/io/crate/planner/optimizer/LoadedRules.java
  server/src/main/java/io/crate/planner/optimizer/Rule.java
  server/src/main/java/io/crate/planner/optimizer/rule/EquiJoinToLookupJoin.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/ShowIntegrationTest.java
  server/src/test/java/io/crate/planner/optimizer/OptimizerRuleSessionSettingProviderTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
  server/src/testFixtures/java/io/crate/testing/SqlExpressions.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge
