Repository crate/crate, pull requests merged in 2024-11, with the labels that each got.

#16907 Fix issue with subscript on nested object arrays
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/test/java/io/crate/expression/scalar/SubscriptObjectFunctionTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16908 Forbid adding a sub-column to an object(ignored) if table isn't empty
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16911 Minor code fixes in `planner` package
  server/src/main/java/io/crate/planner/AnalyzePlan.java
  server/src/main/java/io/crate/planner/NodeSelection.java
  server/src/main/java/io/crate/planner/NoopPlan.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/planner/RoutingBuilder.java
  server/src/main/java/io/crate/planner/consumer/CreateTableAsPlan.java
  server/src/main/java/io/crate/planner/consumer/InsertFromSubQueryPlanner.java
  server/src/main/java/io/crate/planner/consumer/OrderByPositionVisitor.java
  server/src/main/java/io/crate/planner/consumer/OrderByWithAggregationValidator.java
  server/src/main/java/io/crate/planner/consumer/UpdatePlanner.java
  server/src/main/java/io/crate/planner/distribution/DistributionInfo.java
  server/src/main/java/io/crate/planner/node/ddl/CreateAnalyzerPlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateBlobTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateFunctionPlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/ddl/DeleteAllPartitions.java
  server/src/main/java/io/crate/planner/node/ddl/DeletePartitions.java
  server/src/main/java/io/crate/planner/node/ddl/DropAnalyzerPlan.java
  server/src/main/java/io/crate/planner/node/ddl/DropTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/OptimizeTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/RefreshTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/ResetSettingsPlan.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/dql/GroupByConsumer.java
  server/src/main/java/io/crate/planner/node/fetch/FetchSource.java
  server/src/main/java/io/crate/planner/node/management/ExplainPlan.java
  server/src/main/java/io/crate/planner/operators/AbstractJoinPlan.java
  server/src/main/java/io/crate/planner/operators/Distinct.java
  server/src/main/java/io/crate/planner/operators/EnsureNoMatchPredicate.java
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/main/java/io/crate/planner/operators/FetchRewrite.java
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/main/java/io/crate/planner/operators/Limit.java
  server/src/main/java/io/crate/planner/operators/LogicalPlan.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/main/java/io/crate/planner/operators/NestedLoopJoin.java
  server/src/main/java/io/crate/planner/operators/PlanHint.java
  server/src/main/java/io/crate/planner/operators/Rename.java
  server/src/main/java/io/crate/planner/optimizer/Rule.java
  server/src/main/java/io/crate/planner/optimizer/iterative/Memo.java
  server/src/main/java/io/crate/planner/optimizer/joinorder/JoinGraph.java
  server/src/main/java/io/crate/planner/optimizer/matcher/Pattern.java
  server/src/main/java/io/crate/planner/optimizer/matcher/Patterns.java
  server/src/main/java/io/crate/planner/optimizer/matcher/TypeOfPattern.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathWindowAgg.java
  server/src/main/java/io/crate/planner/optimizer/rule/OptimizeCollectWhereClauseAccess.java
  server/src/main/java/io/crate/planner/optimizer/rule/Util.java
  server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java
  server/src/main/java/io/crate/planner/optimizer/tracer/LoggingOptimizerTracer.java
  server/src/main/java/io/crate/planner/selectivity/SelectivityFunctions.java
  server/src/main/java/io/crate/planner/statement/CopyFromPlan.java
  server/src/main/java/io/crate/planner/statement/CopyToPlan.java
  server/src/main/java/io/crate/planner/statement/SetSessionPlan.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/test/java/io/crate/planner/statement/CopyFromPlannerTest.java
Labels: ready-to-merge, cla-signed

#16913 Update maven plugins to their latest versions
  pom.xml
Labels: ready-to-merge, cla-signed

#16914 Update library dependencies to latest versions
  pom.xml
Labels: ready-to-merge, cla-signed

#16915 Update junit5 from 5.10.3 to 5.11.3
  libs/dex/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  pom.xml
  server/pom.xml
Labels: ready-to-merge, cla-signed

#16917 tests: Cleanup `IntegTestCase`
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#16919 Use fastdoubleparser for string -> float/double parsing
  libs/es-x-content/pom.xml
  libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java
  pom.xml
  server/pom.xml
  server/src/main/java/io/crate/monitor/SysInfo.java
  server/src/main/java/io/crate/protocols/postgres/types/DoubleType.java
  server/src/main/java/io/crate/protocols/postgres/types/PointType.java
  server/src/main/java/io/crate/protocols/postgres/types/RealType.java
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/main/java/org/elasticsearch/common/settings/Settings.java
  server/src/main/java/org/elasticsearch/common/unit/ByteSizeValue.java
  server/src/main/java/org/elasticsearch/common/unit/DistanceUnit.java
  server/src/main/java/org/elasticsearch/common/unit/Fuzziness.java
  server/src/main/java/org/elasticsearch/common/unit/MemorySizeValue.java
  server/src/main/java/org/elasticsearch/common/unit/RatioValue.java
  server/src/main/java/org/elasticsearch/common/unit/SizeValue.java
  server/src/main/java/org/elasticsearch/index/MergePolicyConfig.java
  server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java
Labels: ready-to-merge, cla-signed

#16921 Fix REST bulk row count receiver when run with a single bulk arg
  server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java
  server/src/test/java/io/crate/rest/action/RestActionReceiversTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, cla-signed

#16900 Only store explicitly set table properties as index settings
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.0.rst
  docs/general/ddl/column-policy.rst
  docs/general/ddl/show-create-table.rst
  server/src/main/java/io/crate/analyze/AnalyzedCreateTable.java
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/analyze/TableProperties.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/main/java/io/crate/planner/node/ddl/CreateBlobTablePlan.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/io/crate/analyze/TableInfoToASTTest.java
Labels: ready-to-merge, cla-signed

#16918 Remove type specific logic from DataTypes.merge
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/main/java/io/crate/types/DataType.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/NumericType.java
  server/src/main/java/io/crate/types/ObjectType.java
Labels: ready-to-merge, cla-signed, v/5.9

#16922 Move alter blob table tests to AlterTablePlanTest
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/test/java/io/crate/analyze/BlobTableAnalyzerTest.java
  server/src/test/java/io/crate/planner/node/ddl/AlterTablePlanTest.java
Labels: ready-to-merge, cla-signed

#16923 Allow async responses from TransportBroadcastByNodeAction subclasses
  server/src/main/java/org/elasticsearch/action/admin/indices/forcemerge/TransportForceMergeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/recovery/TransportRecoveryAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/TransportIndicesStatsAction.java
  server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java
Labels: ready-to-merge, cla-signed

#16931 Readd crate-node script to tarball distribution
  app/src/assembly/src.xml
  app/src/main/dist/bin/crate-node
  docs/appendices/release-notes/5.9.3.rst
Labels: ready-to-merge, cla-signed, v/5.9

#16927 Consolidate DataTypeTestCase.getDataDef() and getType()
  server/src/test/java/io/crate/types/ArrayTypeTest.java
  server/src/test/java/io/crate/types/BitStringTypeTest.java
  server/src/test/java/io/crate/types/BooleanTypeTest.java
  server/src/test/java/io/crate/types/ByteTypeTest.java
  server/src/test/java/io/crate/types/CharacterTypeTest.java
  server/src/test/java/io/crate/types/DoubleTypeTest.java
  server/src/test/java/io/crate/types/FloatTypeTest.java
  server/src/test/java/io/crate/types/FloatVectorTypeTest.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
  server/src/test/java/io/crate/types/IntegerTypeTest.java
  server/src/test/java/io/crate/types/IntervalTypeTest.java
  server/src/test/java/io/crate/types/IpTypeTest.java
  server/src/test/java/io/crate/types/LongTypeTest.java
  server/src/test/java/io/crate/types/NestedArrayTypeTest.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/test/java/io/crate/types/RegclassTypeTest.java
  server/src/test/java/io/crate/types/ShortTypeTest.java
  server/src/test/java/io/crate/types/StringTypeTest.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge, cla-signed

#16935 Fix an issue with ORDER BY with query params
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/planner/operators/Order.java
  server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16934 Refactor ArrayOfObjectIndexer.indexValue to call ArrayIndexer.indexValue
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/ArrayOfObjectIndexer.java
Labels: ready-to-merge, cla-signed

#16920 Ensure that all columns inside scalar are added to outputs
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16941 Docs: Add `null_or_empty(array)`
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge, docs, cla-signed, v/5.9

#16957 Fix broken null_or_empty references in docs
  docs/appendices/release-notes/5.2.7.rst
  docs/appendices/release-notes/5.3.1.rst
  docs/general/dql/selects.rst
Labels: ready-to-merge, cla-signed, v/5.9

#16956 Force guava to runtime path in server
  server/pom.xml
Labels: cla-signed

#16961 Stream partition columns as ColumnIdent in CreateTableRequest
  server/src/main/java/io/crate/analyze/AnalyzedCreateTable.java
  server/src/main/java/io/crate/analyze/BoundCreateTable.java
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableClient.java
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/analyze/CreateAlterPartitionedTableAnalyzerTest.java
  server/src/test/java/io/crate/execution/ddl/tables/CreateTableRequestTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: cla-signed

#16962 Add reference tree to find reference's parent/child (partial backport #16569 + #16893)
  server/src/main/java/io/crate/metadata/ReferenceTree.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, cla-signed

#16959 Use iss from token only for payload verification.
  server/src/main/java/io/crate/auth/JWTAuthenticationMethod.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
Labels: ready-to-merge, cla-signed

#16966 Use alt way to set classifier for opendal dep
  plugins/crate-copy-azure/pom.xml
  pom.xml
Labels: ready-to-merge, cla-signed

#16965 Reuse LeafReader where possible in StoredRowLookup
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
Labels: ready-to-merge, cla-signed

#16929 Make warnings in 5.9.0 release notes less scary; clarify it's a testing release
  docs/appendices/release-notes/5.9.0.rst
Labels: ready-to-merge, cla-signed, v/5.9

#16971 Remove TranslogIndexer from DocTableInfo
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/dml/TranslogIndexerTest.java
Labels: ready-to-merge, cla-signed

#16967 Fix ClassCastException when handling failures of the async response
  server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java
Labels: ready-to-merge, cla-signed

#16976 Fix printing of a `CASE` expression.
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16968 Fix query used at JDBC FDW, alias symbols must be replaced by their source
  docs/admin/fdw.rst
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/fdw/JdbcBatchIterator.java
  server/src/main/java/io/crate/planner/operators/ForeignCollect.java
  server/src/test/java/io/crate/fdw/ForeignDataWrapperPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16978 The SubQueryAndParamBinder must not ignore conversion exceptions
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/planner/operators/SubQueryAndParamBinder.java
  server/src/test/java/io/crate/planner/operators/SubQueryAndParamBinderTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16983 Fix: generated columns not dropped with no error
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/main/java/io/crate/metadata/GeneratedReference.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16981 Fix SQL printing of CastFunction target type
  docs/appendices/release-notes/5.9.3.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/analyze/GroupByAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SymbolToColumnDefinitionConverterTest.java
  server/src/test/java/io/crate/analyze/relations/QuerySplitterTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/expression/symbol/format/SymbolPrinterTest.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/optimizer/symbol/CollectQueryCastRulesTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16975 Make names of diff components & methods less verbose
  server/src/main/java/org/elasticsearch/cluster/ClusterState.java
  server/src/main/java/org/elasticsearch/cluster/Diffs.java
  server/src/main/java/org/elasticsearch/cluster/NamedDiffableValueSerializer.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/routing/RoutingTable.java
Labels: ready-to-merge, cla-signed

#16988 Update netty to 4.1.115
  pom.xml
Labels: ready-to-merge, cla-signed

#16979 Fix issue with PK lookup with lots of values
  docs/appendices/release-notes/5.9.3.rst
  docs/concepts/storage-consistency.rst
  docs/general/occ.rst
  docs/sql/statements/refresh.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16969 Fix exceptions thrown when querying nested object arrays' sub-columns
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRow.java
  server/src/main/java/io/crate/metadata/table/TableInfo.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/StoredRowLookupTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16992 Use floatValue and doubleValue to validate values
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/io/crate/types/DoubleType.java
  server/src/main/java/io/crate/types/FloatType.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#16994 Release 5.9.3
  docs/appendices/release-notes/5.9.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16995 Bump version to 5.9.4-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.4.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16996 Reflect release 5.9.3
  docs/appendices/release-notes/5.9.3.rst
  docs/appendices/release-notes/5.9.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#16998 Optimize table must sync retention lease in primary mode
  server/src/main/java/org/elasticsearch/action/admin/indices/retention/TransportSyncRetentionLeasesAction.java
Labels: ready-to-merge, cla-signed

#16939 Do not index array lengths of inner arrays of nested object arrays
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/ArrayOfObjectIndexer.java
  server/src/main/java/io/crate/types/ArrayType.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/lucene/NestedArrayLuceneQueryBuilderTest.java
Labels: ready-to-merge, cla-signed

#17004 Fix rendering of ref in docs
  docs/admin/user-management.rst
Labels: ready-to-merge, cla-signed, v/5.9

#17008 Log shard info on retention lease sync failure
  server/src/main/java/org/elasticsearch/action/admin/indices/retention/TransportSyncRetentionLeasesAction.java
Labels: ready-to-merge, cla-signed

#16937 Support public key caching for jwk endpoints
  docs/admin/auth/methods.rst
  docs/appendices/release-notes/5.10.0.rst
  server/src/main/java/io/crate/auth/CachingJwkProvider.java
  server/src/main/java/io/crate/auth/HostBasedAuthentication.java
  server/src/main/java/io/crate/auth/JWTAuthenticationMethod.java
  server/src/test/java/io/crate/auth/CachingJwkProviderTest.java
  server/src/test/java/io/crate/auth/JwtAuthenticationIntegrationTest.java
  server/src/test/java/io/crate/auth/UserAuthenticationMethodTest.java
  server/src/test/java/io/crate/http/HttpTestServer.java
Labels: ready-to-merge, cla-signed

#17000 Fix ClassCastException when querying object array within object array
  server/src/main/java/io/crate/execution/dml/IndexDocumentBuilder.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed

#17009 Remove duplicate partitionedBy properties from BoundCreateTable
  server/src/main/java/io/crate/analyze/BoundCreateTable.java
Labels: ready-to-merge, cla-signed

#17014 Infer analyzer from IndexReference in DocTableInfo
  server/src/main/java/io/crate/fdw/ForeignTable.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
Labels: ready-to-merge, cla-signed

#17002 Added Support for Group By All
  docs/appendices/release-notes/5.10.0.rst
  docs/sql/statements/select.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/SqlFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/AstVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/DefaultTraversalVisitor.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/GroupBy.java
  libs/sql-parser/src/main/java/io/crate/sql/tree/QuerySpecification.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestSqlParser.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/test/java/io/crate/analyze/relations/GroupByScalarAnalyzerTest.java
Labels: cla-signed

#17017 Mark primary key reference as not null in TableElementsAnalyzer
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/execution/ddl/tables/MappingUtil.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
Labels: ready-to-merge, cla-signed

#17012 Normalize geometry collection geo shapes provided as object literals
  docs/appendices/release-notes/5.9.4.rst
  docs/general/builtins/comparison-operators.rst
  server/src/main/java/io/crate/geo/GeoJSONUtils.java
  server/src/main/java/io/crate/types/GeoShapeType.java
  server/src/test/java/io/crate/geo/GeoJSONUtilsTest.java
  server/src/test/java/io/crate/types/GeoShapeTypeTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17018 Improve error messages for aliased match predicates in select stmts
  server/src/main/java/io/crate/analyze/validator/SelectSymbolValidator.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17048 Remove unrelated release notes entry
  docs/appendices/release-notes/5.10.0.rst
Labels: ready-to-merge

#17047 sanitizeMap must not compose a geometry collection of a single but non-composable type
  server/src/main/java/io/crate/geo/GeoJSONUtils.java
  server/src/test/java/io/crate/geo/GeoJSONUtilsTest.java
Labels: ready-to-merge, v/5.9

#17030 Reenable codeql action
  .github/workflows/codeql.yml
Labels: cla-signed

#17031 Remove ChildArrayIndexer
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
Labels: ready-to-merge, cla-signed

#17056 Fix handling of SET .. TO DEFAULT for memory_limit and statement_timeout
  docs/appendices/release-notes/5.9.4.rst
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/test/java/io/crate/planner/statement/SetSessionPlanTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17041 Use partition created version to determine storage formats
  benchmarks/src/main/java/io/crate/execution/dml/IndexerBenchmark.java
  extensions/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesAggregates.java
  server/src/main/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/LuceneShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/collect/PKLookupOperation.java
  server/src/main/java/io/crate/execution/engine/collect/count/CountOperation.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContext.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
  server/src/main/java/io/crate/lucene/LuceneQueryBuilder.java
  server/src/main/java/io/crate/statistics/ReservoirSampler.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CountAggregationTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesAggregatesTest.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesGroupByOptimizedIteratorTest.java
  server/src/test/java/io/crate/expression/predicate/IsNullPredicateTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
  server/src/testFixtures/java/io/crate/types/DataTypeTestCase.java
Labels: ready-to-merge

#17054 CorreatedJoin prunning must not add SelectSymbol to the input plan outputs
  docs/appendices/release-notes/5.9.4.rst
  server/src/main/java/io/crate/planner/operators/CorrelatedJoin.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, v/5.9

#17059 Add PG Wire protection against invalid or huge startup messages
  docs/appendices/release-notes/5.9.4.rst
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PGError.java
  server/src/main/java/io/crate/protocols/postgres/PgDecoder.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge, v/5.9

#17020 Change CreatePartitionsRequest to use PartitionName instead of index names
  server/src/main/java/io/crate/execution/engine/indexing/BulkShardCreationLimiter.java
  server/src/main/java/io/crate/execution/engine/indexing/GroupRowsByShard.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardedRequests.java
  server/src/main/java/io/crate/execution/engine/indexing/ShardingUpsertExecutor.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreatePartitionsRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/test/java/io/crate/execution/engine/indexing/BulkShardCreationLimiterTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/CreatePartitionsRequestTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge, cla-signed

#17067 Remove cla-signed condition from mergify
  .mergify.yml
Labels: ready-to-merge, v/5.9

#17064 Fix array out of bounds for remaining session settings
  docs/appendices/release-notes/5.9.4.rst
  server/src/main/java/io/crate/metadata/settings/session/SessionSettingRegistry.java
  server/src/main/java/io/crate/planner/statement/SetSessionPlan.java
  server/src/test/java/io/crate/planner/statement/SetSessionPlanTest.java
Labels: ready-to-merge, v/5.9

#17070 Small cleanups in TransportShardAction
  server/src/main/java/io/crate/execution/dml/TransportShardAction.java
  server/src/main/java/io/crate/execution/dml/delete/TransportShardDeleteAction.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/replication/logical/action/ReplayChangesAction.java
  server/src/main/java/org/elasticsearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/test/java/io/crate/execution/dml/delete/TransportShardDeleteActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseSyncActionTests.java
Labels: ready-to-merge

#17058 Exclude test code from codeql
  .github/workflows/codeql.yml
Labels: ready-to-merge

#17072 Release 5.9.4
  docs/appendices/release-notes/5.9.4.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17077 Replace metadata/template asserts with information_schema in PartitionedTableIntegrationTest
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge

#17073 Bump version to 5.9.5-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.5.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17080 Reflect release 5.9.4
  docs/appendices/release-notes/5.9.4.rst
  docs/appendices/release-notes/5.9.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17079 Send partition values instead of index name in OpenTableRequest
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/main/java/io/crate/execution/ddl/tables/OpenCloseTableOrPartitionRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/OpenTableRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportOpenTableAction.java
  server/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/CloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/test/java/io/crate/execution/ddl/tables/OpenTableRequestTest.java
Labels: ready-to-merge

#17081 Remove unused close-table-executor
  server/src/main/java/io/crate/metadata/cluster/AbstractOpenCloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/CloseTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
Labels: ready-to-merge

#17083 Eval prunning must also check that there are no outputs to prune
  docs/appendices/release-notes/5.9.5.rst
  server/src/main/java/io/crate/planner/operators/Eval.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/LookupJoinIntegrationTest.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.9

#17087 Bind explicit-joins before implicit joins
  docs/appendices/release-notes/5.9.5.rst
  server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, v/5.9
