Repository crate/crate, pull requests merged in 2025-07, with the labels that each got.

#18087 Fix request mutation interferring with primary operation retry logic
  docs/appendices/release-notes/5.10.11.rst
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/ShardRequest.java
  server/src/main/java/io/crate/execution/dml/TransportShardAction.java
  server/src/main/java/io/crate/execution/dml/UpsertReplicaRequest.java
  server/src/main/java/io/crate/execution/dml/delete/ShardDeleteRequest.java
  server/src/main/java/io/crate/execution/dml/delete/TransportShardDeleteAction.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/main/java/io/crate/planner/node/dml/DeleteById.java
  server/src/main/java/org/elasticsearch/index/seqno/SequenceNumbers.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/dml/UpsertReplicaRequestTest.java
  server/src/test/java/io/crate/execution/dml/delete/TransportShardDeleteActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
  server/src/test/java/io/crate/integrationtests/InsertIntoIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#18059 Do not allow ALTER on tables created by LR subscription
  docs/appendices/release-notes/5.10.11.rst
  server/src/main/java/io/crate/metadata/table/Operation.java
  server/src/main/java/io/crate/planner/node/ddl/AlterTablePlan.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/TableBlocksIntegrationTest.java
  server/src/test/java/io/crate/metadata/table/OperationTest.java
Labels: bug, ready-to-merge, cla-signed, v/5.10

#18094 Fix incorrect response formatting when single-arg bulk operation fails
  docs/appendices/release-notes/5.10.11.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/integrationtests/DeleteIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/RestSQLActionIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/BatchPortalTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/session/SessionTest.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, cla-signed, v/5.10

#18111 Remove generics from Node in SysClusterTableInfo
  server/src/main/java/io/crate/metadata/sys/SysClusterTableInfo.java
Labels: ready-to-merge, cla-signed

#18106 Add missing refresh to testPrimaryTermIsIncreasedOnReplicaPromotion
  server/src/test/java/io/crate/integrationtests/disruption/seqno/SequenceConsistencyIT.java
Labels: ready-to-merge, cla-signed, v/5.10

#18117 Revert custom awareness settings in sandbox's crate.yml
  sandbox/crate/config/crate.yml
Labels: ready-to-merge, cla-signed, v/5.10

#18112 Fix timeouts in testSeqNoCASLinearizability
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#18120 Remove wrong assertion when adding an IndexMetadata.Builder to the Metadata
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge, cla-signed, v/5.10

#18121 Upgrade indexMetadata with partition values
  server/src/main/java/io/crate/metadata/upgrade/MetadataIndexUpgrader.java
  server/src/test/java/io/crate/metadata/upgrade/MetadataIndexUpgraderTest.java
Labels: ready-to-merge, cla-signed

#18127 tests: Add a CREATE integ test to test `mapping.total_fields.limit`
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge, cla-signed

#18125 Only build index metadata aliases for old (<6.0.0) indices
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpgradeService.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataUpgradeServiceTest.java
Labels: ready-to-merge, cla-signed

#18132 Fix broken link to joda docs
  docs/general/builtins/comparison-operators.rst
Labels: ready-to-merge, cla-signed, v/5.10

#18136 docs: Sync 5.10.11 release notes
  docs/appendices/release-notes/5.10.11.rst
Labels: ready-to-merge, cla-signed

#18025 Revert "revert: Add retry handling to DistributingConsumer"
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumerFactory.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
Labels: cla-signed

#18147 Release 5.10.11
  docs/appendices/release-notes/5.10.11.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#18152 Ensure assertions triggered in ActionListener.wrap's onResponse trigger onFailure
  server/src/main/java/org/elasticsearch/action/ActionListener.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: cla-signed

#18155 Bump to 5.10.12-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.12.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: cla-signed

#18164 Fix rejected execution handling in DistributingConsumer retries
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/org/elasticsearch/common/util/concurrent/PriorityRunnable.java
Labels: cla-signed

#18167 Tweak some log entries & toString implementations
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java
  server/src/testFixtures/java/org/elasticsearch/test/engine/MockEngineSupport.java
Labels: cla-signed

#18170 Fix flaky AbstractAsyncTaskTests.testAutoRepeat
  server/src/test/java/org/elasticsearch/common/util/concurrent/AbstractAsyncTaskTests.java
Labels: cla-signed

#18173 Remove any nullable mark/handling of the `ReplicationRequest.shardId`
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/planner/operators/InsertFromValues.java
  server/src/main/java/org/elasticsearch/action/resync/ResyncReplicationRequest.java
  server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java
  server/src/main/java/org/elasticsearch/index/seqno/GlobalCheckpointSyncAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseBackgroundSyncAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/test/java/io/crate/SerializationTests.java
  server/src/test/java/io/crate/blob/DeleteBlobRequestTest.java
Labels: ready-to-merge, cla-signed

#18182 Queue PRs for merge only on label/review
  .mergify.yml
Labels: cla-signed

#18179 Increase cache for recently killed jobs
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/test/java/io/crate/integrationtests/ThreadPoolsExhaustedIntegrationTest.java
Labels: ready-to-merge, cla-signed

#18185 Minor fixes for 6.0.0 release notes
  docs/appendices/release-notes/6.0.0.rst
Labels: ready-to-merge, cla-signed

#18187 Release 6.0.0
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#18193 Update library dependencies to latest versions
  pom.xml
  server/src/main/java/io/crate/metadata/SystemTable.java
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/org/elasticsearch/transport/RemoteCluster.java
Labels: ready-to-merge, cla-signed

#18175 Fix intermittent subscription loss in logical replication during rolling upgrades
  docs/appendices/release-notes/6.0.1.rst
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
Labels: ready-to-merge, cla-signed, v/6.0

#18197 Make RowConsumer optionally killable; short-circuit DistributingConsumer
  libs/dex/src/main/java/io/crate/data/RowConsumer.java
  server/src/main/java/io/crate/execution/engine/InterceptingRowConsumer.java
  server/src/main/java/io/crate/execution/engine/collect/CollectTask.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectingRowConsumer.java
  server/src/main/java/io/crate/planner/DeclarePlan.java
Labels: ready-to-merge, cla-signed

#18041 Document limitations of PG JDBC versions
  docs/interfaces/postgres.rst
Labels: ready-to-merge, cla-signed

#18209 Change datatype and return value of `columns.is_nullable`
  docs/appendices/release-notes/6.1.0.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
Labels: ready-to-merge, cla-signed

#18213 Extract AL privileges check to methods
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/information/InformationSchemaTableDefinitions.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgRolesTable.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/role/Roles.java
  server/src/main/java/io/crate/session/Sessions.java
  server/src/test/java/io/crate/analyze/PrivilegesAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge, cla-signed

#18214 Implement `pg_auth_members` table
  docs/appendices/release-notes/6.1.0.rst
  docs/general/information-schema.rst
  docs/interfaces/postgres.rst
  server/src/main/java/io/crate/metadata/pgcatalog/OidHash.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgAuthMembersTable.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogSchemaInfo.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge, cla-signed

#18222 Remove unused waitForNextChange overload from ClusterStateObserver
  server/src/main/java/org/elasticsearch/cluster/ClusterStateObserver.java
Labels: ready-to-merge, cla-signed

#18071 Add persistence for table stats
  docs/appendices/release-notes/6.1.0.rst
  libs/shared/src/main/java/io/crate/common/collections/Iterables.java
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/pgcatalog/PgCatalogTableDefinitions.java
  server/src/main/java/io/crate/module/CrateCommonModule.java
  server/src/main/java/io/crate/planner/Planner.java
  server/src/main/java/io/crate/statistics/PublishTableStatsRequest.java
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/main/java/io/crate/statistics/TableStats.java
  server/src/main/java/io/crate/statistics/TableStatsService.java
  server/src/main/java/io/crate/statistics/TransportAnalyzeAction.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/JoinIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
  server/src/test/java/io/crate/planner/operators/GroupHashAggregateTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
  server/src/test/java/io/crate/planner/optimizer/costs/PlanStatsTest.java
  server/src/test/java/io/crate/statistics/TableStatsServiceTest.java
  server/src/test/java/io/crate/statistics/TableStatsTest.java
  server/src/test/java/io/crate/statistics/TransportAnalyzeActionTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#18235 Fix stuck SELECT via pg if maxRows=numRows using batch execution
  docs/appendices/release-notes/5.10.12.rst
  docs/appendices/release-notes/6.0.1.rst
  server/src/main/java/io/crate/protocols/postgres/Portal.java
  server/src/main/java/io/crate/session/RowConsumerToResultReceiver.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
  server/src/test/java/io/crate/session/RowConsumerToResultReceiverTest.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: cla-signed, v/6.0, v/5.10

#18228 Remove table stats when table is dropped
  server/src/main/java/io/crate/statistics/TableStatsService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/TableStatsServiceIntegrationTest.java
Labels: ready-to-merge, cla-signed

#18237 Use NIOFSDirectory explicitly in TableStatsService
  server/src/main/java/io/crate/statistics/TableStatsService.java
Labels: ready-to-merge, cla-signed
