Repository crate/crate, pull requests merged in 2025-05, with the labels that each got.

#17838 Keep consuming in original consumer.accept thread in InterceptingRowConsumer
  server/src/main/java/io/crate/execution/engine/InterceptingRowConsumer.java
Labels: ready-to-merge, cla-signed

#17831 Format _map function using object literal syntax
  server/src/main/java/io/crate/expression/symbol/Function.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/MapFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/cast/CastFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/systeminformation/PgTypeofFunctionTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: cla-signed

#17835 Fix bug.yml to actually add bug reports to Support repo
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ready-to-merge, cla-signed

#17841 Update netty to 4.1.121
  pom.xml
Labels: cla-signed

#17844 Fix value lookup for array objects
  docs/appendices/release-notes/5.10.6.rst
  libs/shared/src/main/java/io/crate/common/collections/Maps.java
  libs/shared/src/test/java/io/crate/common/collections/MapsTest.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRow.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/StoredRowLookupTest.java
  server/src/test/java/io/crate/integrationtests/FulltextIntegrationTest.java
Labels: cla-signed

#17846 Avoid NPEs in PgClientTest
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
Labels: ready-to-merge, cla-signed

#17832 Tweak error message if function is missing or is missing overload
  extensions/functions/src/test/java/io/crate/window/NthValueFunctionsTest.java
  server/src/main/java/io/crate/metadata/Functions.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/DeleteAnalyzerTest.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/AverageAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/SumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/VarianceAggregationTest.java
  server/src/test/java/io/crate/expression/operator/CIDROperatorTest.java
  server/src/test/java/io/crate/expression/scalar/AgeFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayCatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayDifferenceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayLowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayMaxFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayMinFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArraySliceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayToStringFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUniqueFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ArrayUpperFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ConcatFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ConcatWsFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/ExtractFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/StringToArrayFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/IntervalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/MapFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NegateFunctionsTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/PowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/conditional/ConditionalFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/AreaFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/CoordinateFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/DistanceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/GeoHashFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/object/ObjectKeysFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/postgres/PgBackendPidFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/regex/RegexpReplaceFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/ChrFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/string/QuoteIdentFunctionTest.java
  server/src/test/java/io/crate/expression/tablefunctions/ValuesFunctionTest.java
  server/src/test/java/io/crate/lucene/BitStringEqQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/metadata/FunctionsTest.java
Labels: ready-to-merge, cla-signed

#17847 Close transports before tearing down netty event loop in PgClientTest
  server/src/test/java/io/crate/protocols/postgres/PgClientTest.java
Labels: cla-signed

#17850 Release 5.10.6
  docs/appendices/release-notes/5.10.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17851 Bump to 5.10.7-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.7.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17852 Reflect release 5.10.6
  docs/appendices/release-notes/5.10.6.rst
  docs/appendices/release-notes/5.10.7.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17855 UpdateToInsert doesn't need to return a whole IndexItem
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/io/crate/execution/dml/upsert/UpdateToInsert.java
  server/src/test/java/io/crate/execution/dml/upsert/UpdateToInsertTest.java
Labels: ready-to-merge, cla-signed

#17857 Use pooled netty allocator to workaround ByteBuf leaks
  app/src/main/dist/bin/crate
  pom.xml
Labels: ready-to-merge, cla-signed

#17856 Replace deprecated SelfSignedCertificate with netty-pkitesting CertificateBuilder
  server/pom.xml
  server/src/test/java/io/crate/auth/ClientCertAuthTest.java
  server/src/test/java/io/crate/auth/HostBasedAuthenticationTest.java
  server/src/test/java/io/crate/auth/HttpAuthUpstreamHandlerTest.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
  server/src/test/java/io/crate/protocols/http/HttpsTransportKeyStoreReloadIntegrationTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/protocols/postgres/SslReqHandlerIntegrationTest.java
Labels: cla-signed

#17859 DELETE must be retried on temporal errors and not be retried on non-retryable errors.
  docs/appendices/release-notes/5.10.7.rst
  server/src/main/java/io/crate/execution/dml/delete/TransportShardDeleteAction.java
  server/src/test/java/io/crate/execution/dml/delete/TransportShardDeleteActionTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17860 Fix warnings in Session & typo in cast error msg
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/analyze/expressions/ExpressionAnalyzerTest.java
Labels: cla-signed

#17863 Make HierarchyCircuitBreakerService.registerBreaker private
  server/src/main/java/org/elasticsearch/indices/breaker/CircuitBreakerService.java
  server/src/main/java/org/elasticsearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/testFixtures/java/org/elasticsearch/indices/breaker/NoneCircuitBreakerService.java
Labels: cla-signed

#17867 Improve EXPLAIN printing for WindowAgg operator
  server/src/main/java/io/crate/planner/operators/WindowAgg.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
  server/src/test/java/io/crate/planner/operators/WindowAggTest.java
  server/src/test/java/io/crate/planner/optimizer/rule/MoveFilterBeneathWindowAggTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17869 Update Surefire plugin to latest version
  pom.xml
Labels: ready-to-merge, cla-signed

#17878 Remove unused preflight no-op check
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
Labels: ready-to-merge, cla-signed

#17879 bp: Do not fail replica shard due to primary closure
  server/src/main/java/org/elasticsearch/ElasticsearchException.java
  server/src/main/java/org/elasticsearch/action/support/replication/PendingReplicationActions.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/elasticsearch/index/shard/PrimaryShardClosedException.java
  server/src/test/java/org/elasticsearch/action/support/replication/PendingReplicationActionsTests.java
Labels: ready-to-merge, cla-signed

#17880 Remove unused Repository.getSnapshotIndexMetadata(... indexId)
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/repositories/Repository.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/elasticsearch/snapshots/BlobStoreIncrementalityIT.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/RestoreOnlyRepository.java
  server/src/testFixtures/java/org/elasticsearch/repositories/blobstore/BlobStoreTestUtil.java
Labels: ready-to-merge, cla-signed

#17864 Replace JNA with JDK FFI
  app/src/main/java/org/elasticsearch/bootstrap/BootstrapProxy.java
  pom.xml
  server/pom.xml
  server/src/main/java/io/crate/ffi/NativeError.java
  server/src/main/java/io/crate/ffi/Natives.java
  server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/elasticsearch/bootstrap/BootstrapInfo.java
  server/src/main/java/org/elasticsearch/bootstrap/JNACLibrary.java
  server/src/main/java/org/elasticsearch/bootstrap/JNAKernel32Library.java
  server/src/main/java/org/elasticsearch/bootstrap/JNANatives.java
  server/src/main/java/org/elasticsearch/bootstrap/Natives.java
  server/src/test/java/io/crate/ffi/NativesTest.java
Labels: ready-to-merge, cla-signed

#17858 Return name of function as output name via PG
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/aggregation.rst
  docs/general/builtins/comparison-operators.rst
  docs/general/builtins/scalar-functions.rst
  docs/general/builtins/table-functions.rst
  docs/general/ddl/data-types.rst
  docs/general/ddl/partitioned-tables.rst
  docs/general/dql/selects.rst
  docs/general/dql/union.rst
  docs/general/information-schema.rst
  docs/sql/general/lexical-structure.rst
  server/src/main/java/io/crate/analyze/AnalyzedStatement.java
  server/src/main/java/io/crate/analyze/QueriedSelectRelation.java
  server/src/main/java/io/crate/analyze/relations/RelationAnalyzer.java
  server/src/main/java/io/crate/analyze/relations/select/SelectAnalysis.java
  server/src/main/java/io/crate/analyze/relations/select/SelectAnalyzer.java
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/rest/action/RestResultSetReceiver.java
  server/src/main/java/io/crate/rest/action/ResultToXContentBuilder.java
  server/src/main/java/io/crate/rest/action/SqlHttpHandler.java
  server/src/main/java/io/crate/session/DescribeResult.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionSingleNodeTest.java
  server/src/test/java/io/crate/planner/CorrelatedJoinPlannerTest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
  server/src/test/java/io/crate/rest/action/RestActionReceiversTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, cla-signed

#17882 Raise error while analyzing table elements on IGNORED column types
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/types/StorageSupport.java
  server/src/main/java/io/crate/types/UndefinedType.java
  server/src/test/java/io/crate/integrationtests/CreateTableAsIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17887 Add tableVersion to RelationMetadata.Table
  server/src/main/java/io/crate/execution/ddl/SwapRelationsOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTable.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/SwapAndDropIndexExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocSchemaInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterState.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitions.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpgradeService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/RelationMetadata.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, cla-signed

#17886 Include relations in ClusterState string representation
  server/src/main/java/org/elasticsearch/cluster/ClusterState.java
Labels: ready-to-merge, cla-signed

#17885 Resolve existing partitions by the new relations metadata api
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitions.java
Labels: ready-to-merge, cla-signed

#17884 Add retry handling to DistributingConsumer
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumerFactory.java
  server/src/test/java/io/crate/execution/engine/distribution/DistributingConsumerTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: ready-to-merge, cla-signed

#17889 Update bundled PostgreSQL JDBC to 42.7.5
  pom.xml
  server/src/test/java/io/crate/integrationtests/PostgresITest.java
Labels: ready-to-merge, cla-signed

#17890 Fix adding parent & child object sub-cols in one ALTER stmt
  docs/appendices/release-notes/5.10.7.rst
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/test/java/io/crate/analyze/AlterTableAddColumnAnalyzerTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17893 docs: Fix link to elasticsearch discovery settings
  docs/appendices/resiliency.rst
  docs/concepts/resiliency.rst
Labels: ready-to-merge, docs, cla-signed, v/5.9, v/5.10

#17888 Remove unused methods from ConnectionManager
  server/src/main/java/org/elasticsearch/transport/ClusterConnectionManager.java
  server/src/main/java/org/elasticsearch/transport/ConnectionManager.java
  server/src/testFixtures/java/org/elasticsearch/test/transport/StubbableConnectionManager.java
Labels: ready-to-merge, cla-signed

#17898 Handle schedule errors in DistributingConsumer
  server/src/main/java/io/crate/execution/engine/distribution/DistributingConsumer.java
Labels: cla-signed

#17896 Remove unused version from InboundDecoder
  server/src/main/java/org/elasticsearch/transport/InboundDecoder.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/netty4/Netty4MessageChannelHandler.java
  server/src/test/java/org/elasticsearch/transport/InboundDecoderTests.java
  server/src/test/java/org/elasticsearch/transport/InboundPipelineTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
Labels: ready-to-merge, cla-signed

#17877 Add starts_with scalar function
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/main/java/io/crate/expression/scalar/string/StartsWithFunction.java
  server/src/test/java/io/crate/expression/scalar/string/StartsWithFunctionQueryTest.java
  server/src/test/java/io/crate/expression/scalar/string/StartsWithFunctionTest.java
Labels: ready-to-merge, cla-signed

#17559 Add `last_write_before` column to sys.shards
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/metadata/sys/SysShardsTableInfo.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/io/crate/integrationtests/UnassignedShardsTest.java
Labels: ready-to-merge, cla-signed

#17900 Re-use MultiActionListener in NodeStats
  server/src/main/java/io/crate/execution/engine/collect/collectors/NodeStats.java
Labels: cla-signed

#17902 bind transports in ActionModule directly without intermediate Map
  server/src/main/java/org/elasticsearch/action/ActionModule.java
Labels: cla-signed

#17899 Resolve existing partitions on creation without being strict
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitions.java
Labels: ready-to-merge, cla-signed

#17905 Turn TransportRequestOptions into record without builder
  server/src/main/java/io/crate/execution/engine/collect/stats/TransportNodeStatsAction.java
  server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/elasticsearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/elasticsearch/discovery/PeerFinder.java
  server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/elasticsearch/transport/TransportRequestOptions.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
Labels: cla-signed

#17909 Remove TransportMessage
  server/src/main/java/org/elasticsearch/transport/TransportMessage.java
  server/src/main/java/org/elasticsearch/transport/TransportRequest.java
  server/src/main/java/org/elasticsearch/transport/TransportResponse.java
  server/src/test/java/org/elasticsearch/transport/InboundDecoderTests.java
Labels: ready-to-merge, cla-signed

#17913 Fix 5.10.0 release notes
  docs/appendices/release-notes/5.10.0.rst
  docs/general/builtins/scalar-functions.rst
Labels: ready-to-merge, docs, cla-signed, v/5.10

#17914 Remove unused TransportChannelResponseHandler class
  server/src/main/java/org/elasticsearch/transport/TransportChannelResponseHandler.java
Labels: ready-to-merge, cla-signed

#17912 Add NUMERIC support to `power()/radians()/degrees()` funcs.
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/scalar-functions.rst
  server/src/main/java/io/crate/expression/scalar/arithmetic/ArithmeticFunctions.java
  server/src/main/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctions.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/NumericArithmeticTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/PowerFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/arithmetic/RadiansDegreesFunctionsTest.java
Labels: ready-to-merge, cla-signed

#17919 Improve mem accounting for stddev_pop aggregation state.
  docs/appendices/release-notes/5.10.7.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/statistics/Variance.java
Labels: ready-to-merge, cla-signed, v/5.10

#17917 Update library dependencies to latest versions
  pom.xml
  server/src/main/java/io/crate/replication/logical/metadata/ConnectionInfo.java
  server/src/main/java/org/elasticsearch/transport/RemoteCluster.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorTest.java
Labels: ready-to-merge, cla-signed

#17922 Update joda time library to `2.14.0`
  pom.xml
  server/src/test/java/io/crate/expression/scalar/DateFormatFunctionTest.java
Labels: ready-to-merge, cla-signed

#17923 Update rules for versions mvn plugin to exlude `RC` versions + update junit
  pom.xml
Labels: ready-to-merge, cla-signed

#17927 Replace NamedRegistry with MapBuilder
  libs/shared/src/main/java/io/crate/common/collections/MapBuilder.java
  server/src/main/java/org/elasticsearch/common/NamedRegistry.java
  server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java
Labels: cla-signed

#17928 Release 5.10.7
  docs/appendices/release-notes/5.10.7.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17929 Bump to 5.10.8-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.8.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17931 Remove indexVersionCreated from `newState()` method
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/AggregateCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/GroupingLongCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/execution/engine/aggregation/GroupingStringCollectorBenchmark.java
  benchmarks/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregationBenchmark.java
  benchmarks/src/main/java/io/crate/operation/aggregation/IntervalAggregationBenchmark.java
  extensions/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregateCollector.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationPipe.java
  server/src/main/java/io/crate/execution/engine/aggregation/GroupingCollector.java
  server/src/main/java/io/crate/execution/engine/aggregation/GroupingProjector.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArrayAgg.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/IntervalSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/PercentileAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StringAgg.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/IntervalAverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageAggregation.java
  server/src/main/java/io/crate/execution/engine/collect/GroupByOptimizedIterator.java
  server/src/main/java/io/crate/execution/engine/collect/ShardCollectorProvider.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/execution/engine/window/AggregateToWindowFunctionAdapter.java
  server/src/main/java/io/crate/execution/engine/window/WindowProjector.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StringAggTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectorsTest.java
  server/src/testFixtures/java/io/crate/execution/engine/window/AbstractWindowFunctionTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
Labels: ready-to-merge, cla-signed

#17845 Set object depth limit to 100
  docs/appendices/release-notes/6.0.0.rst
  docs/sql/statements/create-table.rst
  server/src/main/java/io/crate/analyze/TableParameters.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTable.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationPartitionsTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  server/src/test/java/io/crate/analyze/CreateAlterTableStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/DDLIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
Labels: ready-to-merge, cla-signed

#17944 Expose indices with non-active primary shards in publications
  docs/appendices/release-notes/5.10.8.rst
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationSettings.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/PublicationsStateAction.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/metadata/RelationMetadata.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITest.java
  server/src/test/java/io/crate/integrationtests/MetadataTrackerITest.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17948 Remove unused MultiException
  server/src/main/java/io/crate/exceptions/MultiException.java
  server/src/test/java/io/crate/exceptions/MultiExceptionTest.java
Labels: cla-signed

#17939 Remove reference to ping discovery configuration
  docs/appendices/resiliency.rst
  docs/concepts/resiliency.rst
Labels: ready-to-merge, docs, cla-signed, v/5.10
