Repository crate/crate, pull requests merged in 2025-04, with the labels that each got.

#17699 tests: ensureState must not trip assertBusy on Exceptions
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, cla-signed

#17704 Fix ALTER TABLE RESET to reset the setting on all partitions
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17703 Verify analyzer specified in MATCH query is same as the analyzer used to index
  docs/appendices/release-notes/5.10.4.rst
  docs/general/dql/fulltext.rst
  plugins/es-analysis-common/src/test/java/io/crate/analysis/common/FulltextITest.java
  server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
  server/src/main/java/org/elasticsearch/index/search/MultiMatchQuery.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17720 Add 5.9 release note entry for 17703
  docs/appendices/release-notes/5.9.13.rst
Labels: ready-to-merge, cla-signed

#17722 Add missing 5.9.13 change entries
  docs/appendices/release-notes/5.9.13.rst
Labels: ready-to-merge, cla-signed

#17664 Use table statistics to improve ram estimation for updates
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/io/crate/execution/dml/ShardRequest.java
  server/src/main/java/io/crate/execution/dml/delete/ShardDeleteRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/engine/pipeline/ProjectionToProjectorVisitor.java
  server/src/main/java/io/crate/metadata/NodeContext.java
  server/src/main/java/io/crate/metadata/RelationInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/planner/node/dml/UpdateById.java
  server/src/main/java/io/crate/statistics/Stats.java
  server/src/test/java/io/crate/execution/dml/upsert/ShardUpsertRequestTest.java
  server/src/testFixtures/java/io/crate/testing/TestingHelpers.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17729 Remove GCDanglingArtifactsAction from DependencyCarrier
  server/src/main/java/io/crate/planner/DependencyCarrier.java
  server/src/main/java/io/crate/planner/GCDanglingArtifactsPlan.java
  server/src/test/java/io/crate/integrationtests/GCDanglingArtifactsIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17731 Fix flaky testAbortedRestoreAlsoAbortFileRestores
  server/src/test/java/org/elasticsearch/snapshots/AbortedRestoreIT.java
Labels: ready-to-merge, cla-signed

#17732 Use List<PartitionNames> instead of List<List<Values>>
  server/src/main/java/io/crate/execution/ddl/tables/DropPartitionsRequest.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropPartitionsAction.java
  server/src/main/java/io/crate/planner/node/ddl/DeletePartitions.java
  server/src/main/java/io/crate/planner/statement/DeletePlanner.java
  server/src/test/java/io/crate/planner/node/ddl/DeletePartitionsTest.java
Labels: ready-to-merge, cla-signed

#17730 Fix replication bug caused by interrupted INSERT
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17737 Update bundled JDK to 24
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  plugins/repository-gcs/src/test/java/io/crate/gcs/GCSBlobContainerRetriesTests.java
  pom.xml
Labels: ready-to-merge, cla-signed

#17740 Release 5.9.13
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17733 Use GCDanglingArtifacts to delete temp indices during resize
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/DeleteIndexRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
Labels: ready-to-merge, cla-signed

#17741 Reflect release 5.9.13
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17743 Release 5.10.4
  docs/appendices/release-notes/5.10.4.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17742 Reflect release 5.9.13
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17744 Bump version to 5.10.5-snapshot
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.5.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17746 Reflect release 5.10.4
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.10.5.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17745 Ensure native epoll transport for netty can be loaded
  server/pom.xml
Labels: ready-to-merge, cla-signed

#17749 Disable Unsafe warnings
  app/src/main/dist/bin/crate
  app/src/main/dist/bin/crate.bat
  pom.xml
Labels: ready-to-merge, cla-signed

#17751 Remove ActionPlugin as it's not used
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/plugins/ActionPlugin.java
Labels: ready-to-merge, cla-signed

#17761 Cleanup of Transport actions
  server/src/main/java/io/crate/blob/TransportDeleteBlob.java
  server/src/main/java/io/crate/blob/TransportPutChunk.java
  server/src/main/java/io/crate/blob/TransportStartBlob.java
  server/src/main/java/io/crate/execution/ddl/tables/CreateTableClient.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumn.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAlterTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropColumn.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportDropConstraint.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportOpenTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameColumn.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportRenameTable.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitions.java
  server/src/main/java/org/elasticsearch/action/admin/indices/delete/TransportDeleteIndex.java
  server/src/main/java/org/elasticsearch/action/admin/indices/refresh/TransportRefresh.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettings.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResize.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/TransportIndicesStats.java
Labels: ready-to-merge, cla-signed

#17758 Update GraalVM to 24.2.0
  pom.xml
Labels: ready-to-merge, cla-signed

#17760 Remove Actions from DependencyCarrier
  server/src/main/java/io/crate/execution/TransportExecutorModule.java
  server/src/main/java/io/crate/execution/ddl/index/TransportSwapAndDropIndexName.java
  server/src/main/java/io/crate/planner/DependencyCarrier.java
  server/src/main/java/io/crate/replication/logical/action/TransportAlterPublication.java
  server/src/main/java/io/crate/replication/logical/action/TransportCreatePublication.java
  server/src/main/java/io/crate/replication/logical/action/TransportCreateSubscription.java
  server/src/main/java/io/crate/replication/logical/action/TransportDropPublication.java
  server/src/main/java/io/crate/replication/logical/plan/AlterPublicationPlan.java
  server/src/main/java/io/crate/replication/logical/plan/CreatePublicationPlan.java
  server/src/main/java/io/crate/replication/logical/plan/CreateSubscriptionPlan.java
  server/src/main/java/io/crate/replication/logical/plan/DropPublicationPlan.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResize.java
  server/src/test/java/io/crate/replication/logical/action/TransportAlterPublicationTest.java
  server/src/test/java/io/crate/replication/logical/action/TransportCreateSubscriptionTest.java
Labels: ready-to-merge, cla-signed

#17767 Add bug issues to "Support" project
  .github/ISSUE_TEMPLATE/bug.yml
Labels: cla-signed

#17771 If the translog fails to sync, log the error at WARN rather than DEBUG
  server/src/main/java/org/elasticsearch/common/util/concurrent/AsyncIOProcessor.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17775 Handle empty columns in jdbc fdw to support `select count(*) ...`
  docs/appendices/release-notes/5.10.5.rst
  server/src/main/java/io/crate/fdw/JdbcBatchIterator.java
  server/src/test/java/io/crate/fdw/JdbcBatchIteratorTest.java
  server/src/test/java/io/crate/integrationtests/ForeignDataWrapperITest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17779 Fix handling of generated columns in MATCH for geo shapes
  docs/appendices/release-notes/5.10.5.rst
  server/src/main/java/io/crate/expression/predicate/MatchPredicate.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/LuceneQueryBuilderTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17780 Imply `compression = 'gzip'` if URLs in COPY FROM end in `.gz`
  docs/appendices/release-notes/6.0.0.rst
  docs/sql/statements/copy-from.rst
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17783 Cancel statement_timeout interrupts on result completion to release memory eagerly
  docs/appendices/release-notes/5.10.5.rst
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17784 Remove unused execute(request, mapper) TransportAction overload
  server/src/main/java/org/elasticsearch/action/support/TransportAction.java
Labels: ready-to-merge, cla-signed

#17788 Replace TransportService.sendChildRequest with sendRequest
  server/src/main/java/org/elasticsearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseBackgroundSyncAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/test/java/org/elasticsearch/transport/TransportServiceDeserializationFailureTests.java
Labels: ready-to-merge, cla-signed

#17789 Fix issue with IP values normalization
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/types/IpType.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/types/IpTypeTest.java
Labels: ready-to-merge, cla-signed

#17795 Fix issue with query on parted table boolean partition col
  docs/appendices/release-notes/6.0.0.rst
  libs/shared/src/main/java/io/crate/common/StringUtils.java
  server/src/main/java/io/crate/analyze/where/DocKeys.java
  server/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  server/src/main/java/io/crate/execution/engine/collect/RowShardResolver.java
  server/src/main/java/io/crate/metadata/IndexName.java
  server/src/test/java/io/crate/analyze/where/DocKeysTest.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17792 Extend task logging a bit
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/main/java/io/crate/execution/jobs/TasksService.java
Labels: ready-to-merge, cla-signed

#17786 Add statement_max_length setting; restrict sql statement length
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
  docs/config/node.rst
  server/src/main/java/io/crate/session/Session.java
  server/src/main/java/io/crate/session/Sessions.java
  server/src/main/java/io/crate/session/parser/SQLRequestParser.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/session/SessionsTest.java
Labels: ready-to-merge, cla-signed

#17799 Reset watermark settings in DiskUsagesITest
  server/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
Labels: ready-to-merge, cla-signed

#17802 Fix flaky testAutomaticReleaseOfIndexBlock
  server/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
Labels: ready-to-merge, cla-signed

#17800 Fix NPE in testDoesNotExceedLowWatermarkWhenRebalancing
  server/src/test/java/io/crate/integrationtests/DiskUsagesITest.java
Labels: ready-to-merge, cla-signed

#17801 Add surefire-report github action step
  .github/workflows/main.yml
Labels: cla-signed

#17804 Apply fail_fast on non-retryable IO errors
  docs/appendices/release-notes/5.10.5.rst
  server/src/main/java/io/crate/execution/engine/collect/files/FileReadingIterator.java
  server/src/test/java/io/crate/execution/engine/collect/files/FileReadingIteratorTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17810 Minor code cleanups in `execution` package
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/BulkShardResponseListener.java
  server/src/main/java/io/crate/execution/dml/GeoShapeIndexer.java
  server/src/main/java/io/crate/execution/dml/IndexItem.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/RawIndexer.java
  server/src/main/java/io/crate/execution/dml/ShardRequest.java
  server/src/main/java/io/crate/execution/dml/StringIndexer.java
  server/src/main/java/io/crate/execution/dml/SysUpdateProjector.java
  server/src/main/java/io/crate/execution/dml/SysUpdateResultSetProjector.java
  server/src/main/java/io/crate/execution/dml/TransportShardAction.java
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/org/elasticsearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseBackgroundSyncAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/main/java/org/elasticsearch/transport/TransportSettings.java
Labels: ready-to-merge, cla-signed

#17811 Remove Action suffix and move INSTANCE as an ACTION subclass
  server/src/main/java/io/crate/cluster/gracefulstop/DecommissioningService.java
  server/src/main/java/io/crate/execution/ddl/RepositoryService.java
  server/src/main/java/io/crate/fdw/TransportDropUserMapping.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/ddl/DropSnapshotPlan.java
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/protocols/http/MainAndStaticFileHandler.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/AddVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/ClearVotingConfigExclusionsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusions.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusions.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealth.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/node/stats/NodesStatsAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/node/stats/TransportNodesStats.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/delete/DeleteRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/delete/TransportDeleteRepository.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/PutRepositoryAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/repositories/put/TransportPutRepository.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/TransportCreateSnapshot.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/DeleteSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/delete/TransportDeleteSnapshot.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshot.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterState.java
  server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/transport/SniffRemoteClient.java
  server/src/test/java/io/crate/cluster/gracefulstop/DecommissioningServiceTest.java
  server/src/test/java/io/crate/execution/ddl/RepositoryServiceTest.java
  server/src/test/java/io/crate/integrationtests/LogicalReplicationITestCase.java
  server/src/test/java/io/crate/integrationtests/PgTunnelLogicalReplicationITest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsTests.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsTests.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/VotingConfigurationIT.java
  server/src/test/java/org/elasticsearch/gateway/GatewayIndexStateIT.java
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/test/java/org/elasticsearch/snapshots/SnapshotShardsServiceIT.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge, cla-signed

#17812 Release 5.10.5
  docs/appendices/release-notes/5.10.5.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17805 Use List for builders for executors construction
  server/src/main/java/org/elasticsearch/threadpool/Scheduler.java
  server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java
Labels: ready-to-merge, cla-signed

#17815 Bump to 5.10.6-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.6.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17816 Reflect release 5.10.5
  docs/appendices/release-notes/5.10.5.rst
  docs/appendices/release-notes/5.10.6.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17817 Remove unused asserts in AbstractSnapshotIntegTestCase & `waitUntil`
  server/src/testFixtures/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
Labels: cla-signed

#17819 Fix storageIdent for pre-oid doclookup references
  docs/appendices/release-notes/5.10.6.rst
  server/src/main/java/io/crate/metadata/Reference.java
  server/src/test/java/io/crate/metadata/ReferenceTest.java
Labels: ready-to-merge, cla-signed

#17822 Replace DummyRowConsumer with TestingRowConsumer
  libs/dex/src/testFixtures/java/io/crate/data/testing/TestingRowConsumer.java
  server/src/test/java/io/crate/execution/engine/pipeline/ProjectingRowConsumerTest.java
  server/src/test/java/io/crate/replication/logical/plan/CreateSubscriptionPlanTest.java
Labels: cla-signed

#17823 Lookup circuit breaker only once per job setup
  server/src/main/java/io/crate/execution/jobs/JobSetup.java
Labels: cla-signed

#17826 Try fix flaky testRecentPrimaryInformation
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge, cla-signed

#17825 Use bulk inserts in some test data setups and rescue Marvin
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionClassLifecycleTest.java
  server/src/testFixtures/java/io/crate/integrationtests/Setup.java
Labels: ready-to-merge, cla-signed

#17824 Unify directResponse/push result handling more
  server/src/main/java/io/crate/execution/engine/BucketForwarder.java
  server/src/main/java/io/crate/execution/engine/FailureOnlyResponseListener.java
  server/src/main/java/io/crate/execution/engine/JobLauncher.java
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/RootTask.java
  server/src/test/java/io/crate/execution/engine/FailureOnlyResponseListenerTest.java
Labels: cla-signed

#17829 Downsize blocks in HashJoinBatchIterator if circuit breaker is almost at limit
  benchmarks/src/main/java/io/crate/data/join/RowsBatchIteratorBenchmark.java
  server/src/main/java/io/crate/execution/engine/join/HashJoinBatchIterator.java
  server/src/main/java/io/crate/execution/engine/join/HashJoinOperation.java
  server/src/main/java/io/crate/execution/engine/join/NestedLoopOperation.java
  server/src/test/java/io/crate/execution/engine/join/HashInnerJoinBatchIteratorTest.java
  server/src/test/java/io/crate/execution/engine/join/HashJoinBatchIteratorBehaviouralTest.java
  server/src/test/java/io/crate/execution/engine/join/HashJoinBatchIteratorMemoryTest.java
  server/src/test/java/io/crate/execution/engine/join/LeftOuterHashJoinBatchIteratorTest.java
Labels: cla-signed
