Repository crate/crate, pull requests merged in 2025-06, with the labels that each got.

#17952 Add NUMERIC support to AVG(DISTINCT <col>)
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregation.java
  server/src/main/java/io/crate/expression/scalar/NumericCollectionAverageFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/CollectSetAggregationTest.java
  server/src/test/java/io/crate/expression/scalar/CollectionAvgFunctionTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
Labels: ready-to-merge, cla-signed

#17876 bp: Make Primary Relocation Not Blocking on Transport Request
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTargetHandler.java
  server/src/main/java/org/elasticsearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/testFixtures/java/org/elasticsearch/indices/recovery/AsyncRecoveryTarget.java
Labels: ready-to-merge, cla-signed

#17963 Re-add default limit to exponentialBackoff
  server/src/main/java/org/elasticsearch/action/bulk/BackoffPolicy.java
  server/src/test/java/io/crate/action/LimitedBackoffPolicyTest.java
Labels: ready-to-merge, cla-signed

#17955 Add unit tests for CumulativePageBucketReceiver
  server/src/test/java/io/crate/execution/jobs/CumulativePageBucketReceiverTest.java
Labels: ready-to-merge, cla-signed

#17965 Fix task leak on `createTask` failures
  docs/appendices/release-notes/5.10.8.rst
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/test/java/io/crate/execution/jobs/TasksServiceTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17966 Improve RamAccounting for stddev_pop/samp on NUMERIC for doc values
  extensions/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  libs/shared/src/main/java/io/crate/common/CheckedTriConsumer.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericStandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/AverageAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/templates/BinaryDocValueAggregator.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/templates/SortedNumericDocValueAggregator.java
Labels: ready-to-merge, cla-signed

#17968 Add tasks missing on kill to `recentlyFailed` cache
  server/src/main/java/io/crate/execution/jobs/TasksService.java
  server/src/test/java/io/crate/execution/jobs/TasksServiceTest.java
Labels: cla-signed

#17964 Add toString implementations for InitializationTracker & CountdownFuture
  server/src/main/java/io/crate/concurrent/CountdownFuture.java
  server/src/main/java/io/crate/execution/engine/InitializationTracker.java
Labels: ready-to-merge, cla-signed

#17946 bp: Parallelize stale index deletion
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
Labels: ready-to-merge, cla-signed

#17977 Ensure that job log is cleared when bulk execution completes with an error
  docs/appendices/release-notes/5.10.8.rst
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: ready-to-merge, cla-signed

#17976 Add a test and a change entry for the fix we already have in 6.0
  docs/appendices/release-notes/5.10.8.rst
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: ready-to-merge, cla-signed

#17987 Include valid discovery types in unknown discovery type error message
  server/src/main/java/org/elasticsearch/discovery/DiscoveryModule.java
Labels: ready-to-merge, cla-signed

#17991 Reflect release 5.10.8
  docs/appendices/release-notes/5.10.8.rst
  docs/appendices/release-notes/5.10.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#18010 Fix restoring snapshots created by < v6.0 nodes
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/resources/repos/5.0.3_repo.zip
Labels: ready-to-merge, cla-signed

#18011 Update maven plugins and lib dependencies
  pom.xml
Labels: ready-to-merge, cla-signed

#18006 Fix NullPointerException when casting values containing null to GEOPOINT
  docs/appendices/release-notes/5.10.9.rst
  server/src/main/java/io/crate/types/GeoPointType.java
  server/src/test/java/io/crate/types/GeoPointTypeTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#18009 Fix aggregation on PARTITION BY cols
  docs/appendices/release-notes/5.10.9.rst
  extensions/functions/src/main/java/io/crate/operation/aggregation/HyperLogLogDistinctAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/AggregationFunction.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/ArbitraryAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CmpByAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/CountAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/GeometricMeanAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericSumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/SumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TopKAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/VarianceAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/average/AverageAggregation.java
  server/src/test/java/io/crate/execution/engine/collect/DocValuesAggregatesTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#18016 Fix upgrading/parsing of old `copy_to` index mapping definition
  server/src/main/java/io/crate/metadata/TableInfoFactory.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpgradeService.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/main/java/org/elasticsearch/gateway/LocalAllocateDangledIndices.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/metadata/SchemasTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoFactoryTest.java
  server/src/test/java/io/crate/replication/logical/action/PublicationsStateActionTest.java
  server/src/test/java/io/crate/replication/logical/action/TransportAlterPublicationTest.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeServiceTest.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataUpgradeServiceTest.java
Labels: ready-to-merge, cla-signed

#18000 Format & fix warnings around Translog/TranslogWriter
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/main/java/org/elasticsearch/index/translog/Translog.java
  server/src/main/java/org/elasticsearch/index/translog/TranslogWriter.java
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
Labels: ready-to-merge, cla-signed

#18023 Remove logging only params from ChannelActionListener
  server/src/main/java/org/elasticsearch/action/support/ChannelActionListener.java
  server/src/main/java/org/elasticsearch/action/support/HandledTransportAction.java
  server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/elasticsearch/action/support/single/shard/TransportSingleShardAction.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
Labels: cla-signed

#18001 Add sanity checks for replica index operation
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/test/java/io/crate/execution/dml/upsert/TransportShardUpsertActionTest.java
Labels: cla-signed

#18029 Reflect release 5.10.9
  docs/appendices/release-notes/5.10.10.rst
  docs/appendices/release-notes/5.10.8.rst
  docs/appendices/release-notes/5.10.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#18032 Merge KillableWrapper/KillableCallable
  server/src/main/java/io/crate/execution/dml/TransportShardAction.java
  server/src/main/java/io/crate/execution/jobs/kill/KillableCallable.java
Labels: cla-signed

#18039 Fix flaky testPreferCopyCanPerformNoopRecovery
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge, cla-signed

#18044 Docs: num_docs does not count values inserted when idle
  docs/admin/system-information.rst
Labels: ready-to-merge, docs, cla-signed, v/5.10

#17973 Set ifSeq/primaryTerm based on read doc for updates
  server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java
  server/src/main/java/io/crate/execution/dml/upsert/TransportShardUpsertAction.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
Labels: cla-signed

#18054 Format/cleanup TransportReplicationAction
  server/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java
Labels: cla-signed

#18046 Fix default UDC URL in docs
  docs/config/cluster.rst
Labels: ready-to-merge, docs, cla-signed, v/5.10

#18076 tests: Fix ts columnstore=false test (randomized timezone)
  server/src/test/java/io/crate/integrationtests/StorageOptionsITest.java
Labels: ready-to-merge, cla-signed
