Repository crate/crate, pull requests merged in 2025-03, with the labels that each got.

#17547 Fix resolving indices from RelationMetadata.Table
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge, cla-signed

#17515 Add more info to sys.segments
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/metadata/sys/SysSegmentsTableInfo.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/engine/Segment.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/SysSegmentsTableInfoTest.java
Labels: ready-to-merge, cla-signed

#17548 Remove ShuffleForcedMergePolicy
  server/src/main/java/io/crate/lucene/index/ShuffleForcedMergePolicy.java
  server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java
  server/src/test/java/io/crate/lucene/index/TestShuffleForcedMergePolicyTests.java
  server/src/test/java/org/elasticsearch/index/engine/PrunePostingsMergePolicyTests.java
  server/src/test/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicyTests.java
Labels: ready-to-merge, cla-signed

#17553 Don't report test timeouts as linearization failures
  server/src/test/java/io/crate/integrationtests/disruption/seqno/ConcurrentSeqNoVersioningIT.java
Labels: ready-to-merge, cla-signed

#17552 Update netty to 4.1.119
  pom.xml
Labels: ready-to-merge, cla-signed

#17550 Improve ConcurrentRamAccounting.addBytes to use releaseBytes when adding negative bytes
  server/src/main/java/io/crate/breaker/ConcurrentRamAccounting.java
  server/src/test/java/io/crate/breaker/ConcurrentRamAccountingTest.java
Labels: ready-to-merge, cla-signed

#17560 Fix privileges check for DROP ANALYZER
  docs/appendices/release-notes/5.10.3.rst
  server/src/main/java/io/crate/analyze/DropAnalyzerStatementAnalyzer.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/planner/node/ddl/DropAnalyzerPlan.java
  server/src/test/java/io/crate/analyze/DropAnalyzerTest.java
  server/src/test/java/io/crate/auth/AccessControlMayExecuteTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17568 Update mvn plugins to latest versions
  pom.xml
Labels: ready-to-merge, cla-signed

#17569 Update library dependencies to latest versions
  pom.xml
Labels: ready-to-merge, cla-signed

#17573 Validate length limits of float vector types when creating tables
  docs/appendices/release-notes/5.10.3.rst
  server/src/main/java/io/crate/types/FloatVectorType.java
  server/src/test/java/io/crate/types/FloatVectorTypeTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17578 Move DisableGraphAttribute instantiation checks into a standalong unit test
  plugins/es-analysis-common/src/test/java/io/crate/analysis/common/CommonAnalyzerITest.java
  server/src/test/java/io/crate/lucene/DisableGraphAttributeTest.java
Labels: ready-to-merge, cla-signed

#17543 Add stddev_pop()
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/StandardDeviationAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/StdDevAggregationTest.java
Labels: ready-to-merge, cla-signed

#17579 Revert "Don't treat warnings as errors during sphinx build"
  blackbox/bin/sphinx
Labels: ready-to-merge, cla-signed

#17584 Remove synced flush
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/SyncedFlushAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/SyncedFlushRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/SyncedFlushResponse.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/TransportSyncedFlushAction.java
  server/src/main/java/org/elasticsearch/indices/IndicesModule.java
  server/src/main/java/org/elasticsearch/indices/flush/ShardsSyncedFlushResult.java
  server/src/main/java/org/elasticsearch/indices/flush/SyncedFlushService.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
  server/src/test/java/org/elasticsearch/indices/flush/SyncedFlushUtil.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge, cla-signed

#17586 Replace ClusterHealthRequest in tests with sys tables queries
  server/src/test/java/io/crate/integrationtests/RecoveryTests.java
  server/src/test/java/io/crate/integrationtests/RemoteCollectorIntegrationTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayIndexStateIT.java
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
  server/src/test/java/org/elasticsearch/index/seqno/RetentionLeaseIT.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
Labels: ready-to-merge, cla-signed

#17589 Add 5.10 breaking changes related to unknown key error handling
  docs/appendices/release-notes/5.10.0.rst
Labels: ready-to-merge, cla-signed, v/5.10

#17593 Fix wording of 5.10 unknown key error handling breaking change
  docs/appendices/release-notes/5.10.0.rst
Labels: ready-to-merge, cla-signed, v/5.10

#17591 Deduplicate UnavailableShardsException
  server/src/main/java/io/crate/metadata/RoutingProvider.java
  server/src/main/java/io/crate/rest/action/HttpError.java
  server/src/main/java/org/elasticsearch/action/UnavailableShardsException.java
  server/src/test/java/io/crate/planner/PlannerTest.java
  server/src/test/java/org/elasticsearch/action/UnavailableShardsExceptionTest.java
Labels: cla-signed

#17596 Fix flaky testDynamicTransientSettings
  server/src/test/java/io/crate/integrationtests/SysClusterSettingsTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17592 Treat UnavailableShardsException as shard failure for read retries
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/exceptions/SQLExceptions.java
  server/src/test/java/io/crate/exceptions/SQLExceptionsTest.java
Labels: cla-signed

#17598 Fix flaky TranslogTests.testWithRandomException
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
Labels: ready-to-merge, cla-signed

#17587 Drop retention lease sync interval to 30 seconds
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/org/elasticsearch/index/IndexService.java
Labels: ready-to-merge, cla-signed

#17580 Fix misbehaving columns with oids in partitioned tables < COLUMN_OID_VERSION
  docs/appendices/release-notes/5.10.3.rst
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17608 Add 5.9 release entry for #17580
  docs/appendices/release-notes/5.9.12.rst
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17612 Add release notes for replica allocation issue
  docs/appendices/release-notes/5.10.3.rst
  docs/appendices/release-notes/5.9.12.rst
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17615 bp: Don't Allocate Redundant Pages in BigArrays
  server/src/main/java/org/elasticsearch/common/util/BigArrays.java
  server/src/test/java/org/elasticsearch/common/util/BigArraysTests.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17616 Populate indnkeyatts in pg_index
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/metadata/pgcatalog/PgIndexTable.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
Labels: ready-to-merge, cla-signed

#17595 Shard snapshot deserialization must re-use FileInfo instances
  docs/appendices/release-notes/5.10.3.rst
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshotsTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17617 Add `sys.cluster_health` table to get the overall cluster health
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/metadata/sys/SysClusterHealth.java
  server/src/main/java/io/crate/metadata/sys/SysSchemaInfo.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/main/java/io/crate/metadata/sys/TableHealth.java
  server/src/main/java/org/elasticsearch/cluster/block/ClusterBlocks.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/TableSettingsTest.java
  server/src/test/java/io/crate/metadata/sys/SysClusterHealthTest.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, cla-signed

#17626 Fix flaky test_renamed_tables_can_be_queried_after_cluster_restart
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17627 Remove TransportFlushAction and associated package
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/close/TransportVerifyShardBeforeCloseAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/FlushRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/FlushResponse.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/ShardFlushRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/TransportFlushAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/TransportShardFlushAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/flush/package-info.java
  server/src/main/java/org/elasticsearch/action/admin/indices/forcemerge/TransportForceMergeAction.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoveryTarget.java
  server/src/test/java/io/crate/integrationtests/SysShardsTest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
  server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge, cla-signed

#17622 Optimize count(not_null_col) to use count operator
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/planner/optimizer/rule/MergeAggregateAndCollectToCount.java
  server/src/test/java/io/crate/planner/SelectPlannerTest.java
  server/src/test/java/io/crate/planner/UpdatePlannerTest.java
Labels: ready-to-merge, cla-signed

#17631 Don't resolve refresh index names twice
  server/src/main/java/org/elasticsearch/action/support/replication/TransportBroadcastReplicationAction.java
  server/src/test/java/io/crate/analyze/RefreshAnalyzerTest.java
Labels: ready-to-merge, cla-signed

#17632 Eagerly release allocated memory for jobs_logs entries
  server/src/main/java/io/crate/execution/engine/collect/stats/JobsLogService.java
  server/src/main/java/io/crate/execution/engine/collect/stats/RamAccountingQueue.java
  server/src/test/java/io/crate/execution/engine/collect/stats/RamAccountingQueueSinkTest.java
Labels: ready-to-merge, cla-signed

#17636 Release 5.9.12
  docs/appendices/release-notes/5.9.12.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17640 Release 5.10.3
  docs/appendices/release-notes/5.10.3.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17634 Remove undocumented circuit breaker type settings
  server/src/main/java/org/elasticsearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/indices/breaker/BreakerSettings.java
  server/src/main/java/org/elasticsearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/io/crate/breaker/RowAccountingWithEstimatorsTest.java
  server/src/test/java/io/crate/execution/engine/collect/stats/RamAccountingQueueSinkTest.java
  server/src/test/java/io/crate/execution/engine/distribution/merge/RamAccountingPageIteratorTest.java
  server/src/test/java/io/crate/execution/engine/fetch/NodeFetchResponseTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingLimitAndOffsetProjectorTest.java
  server/src/test/java/io/crate/execution/engine/sort/SortingProjectorTest.java
  server/src/test/java/org/elasticsearch/common/breaker/ChildMemoryCircuitBreakerTest.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge, cla-signed

#17642 Reflect release 5.10.3
  docs/appendices/release-notes/5.10.3.rst
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17647 Fix NPE queries on `sys.allocations` if no master is discovered
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/io/crate/metadata/Routing.java
  server/src/main/java/io/crate/metadata/sys/SysAllocationsTableInfo.java
  server/src/main/java/io/crate/planner/operators/LogicalPlanner.java
  server/src/test/java/io/crate/metadata/sys/SysAllocationsTableInfoTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17644 Extend filter on project set push down to work on subscripts
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/expression/symbol/Symbols.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  server/src/test/java/io/crate/expression/symbol/SymbolsTest.java
  server/src/test/java/io/crate/planner/operators/PushDownTest.java
Labels: ready-to-merge, cla-signed

#17645 Remove IndicesRequest.Replaceable interface
  server/src/main/java/org/elasticsearch/action/IndicesRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsRequest.java
  server/src/main/java/org/elasticsearch/action/support/broadcast/BroadcastRequest.java
  server/src/test/java/io/crate/integrationtests/DiskThresholdDeciderIT.java
  server/src/test/java/io/crate/integrationtests/disruption/discovery/MasterDisruptionIT.java
  server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java
  server/src/test/java/org/elasticsearch/snapshots/AbortedRestoreIT.java
Labels: ready-to-merge, cla-signed

#17605 Remove version check for creation of RelationMetadata.Table
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
Labels: ready-to-merge, cla-signed

#17650 Add new `pending_tasks` column to the `sys.cluster_health` table
  docs/admin/system-information.rst
  server/src/main/java/io/crate/metadata/sys/SysClusterHealth.java
  server/src/main/java/io/crate/metadata/sys/SysTableDefinitions.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/metadata/sys/SysClusterHealthTest.java
Labels: ready-to-merge, cla-signed

#17653 ReplicationRequest does not need to implement IndicesRequest
  server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java
Labels: ready-to-merge, cla-signed

#17600 Re-implement ensureGreen/Yellow using sys tables
  server/src/test/java/io/crate/integrationtests/GroupByAggregateTest.java
  server/src/test/java/io/crate/integrationtests/SubSelectIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/VersionHandlingIntegrationTest.java
  server/src/testFixtures/java/io/crate/integrationtests/Setup.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: cla-signed

#17655 Simplify SingleShardRequest
  server/src/main/java/io/crate/replication/logical/action/GetFileChunkAction.java
  server/src/main/java/io/crate/replication/logical/action/GetStoreMetadataAction.java
  server/src/main/java/io/crate/replication/logical/action/ReleasePublisherResourcesAction.java
  server/src/main/java/io/crate/replication/logical/action/RestoreShardRequest.java
  server/src/main/java/io/crate/replication/logical/action/ShardChangesAction.java
  server/src/main/java/org/elasticsearch/action/support/single/shard/SingleShardRequest.java
  server/src/main/java/org/elasticsearch/action/support/single/shard/TransportSingleShardAction.java
  server/src/main/java/org/elasticsearch/index/seqno/RetentionLeaseActions.java
Labels: ready-to-merge, cla-signed

#17625 Enforce RHS param of like operators to be the patterns
  docs/appendices/release-notes/6.0.0.rst
  docs/general/dql/selects.rst
  server/src/main/java/io/crate/expression/operator/all/AllLikeOperator.java
  server/src/main/java/io/crate/expression/operator/all/AllNotLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyLikeOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNotLikeOperator.java
  server/src/test/java/io/crate/expression/operator/all/AllLikeOperatorTest.java
  server/src/test/java/io/crate/expression/operator/all/AllNotLikeOperatorTest.java
  server/src/test/java/io/crate/expression/operator/any/AnyLikeOperatorTest.java
  server/src/test/java/io/crate/expression/operator/any/AnyNotLikeOperatorTest.java
  server/src/test/java/io/crate/integrationtests/AnyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/lucene/LikeQueryBuilderTest.java
Labels: ready-to-merge, cla-signed

#17654 Update bug.yml issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: ready-to-merge, cla-signed

#17656 Fix flaky ReplicaShardAllocatorIT.testRecentPrimaryInformation
  server/src/test/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java
Labels: ready-to-merge, cla-signed

#17652 Fix for missing jobs_log entries when jobs submitted via pgwire's simpleQuery failed
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/integrationtests/PostgresJobsLogsITest.java
  server/src/test/java/io/crate/protocols/postgres/PostgresWireProtocolTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17657 Eagerly check for column limit on add column
  docs/appendices/release-notes/5.10.4.rst
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17661 Turn test_simple_query_failures_are_logged_in_sys_jobs_log into unit test
  server/src/test/java/io/crate/integrationtests/PostgresJobsLogsITest.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: ready-to-merge, cla-signed

#17671 Minor code improvements
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
Labels: ready-to-merge, cla-signed

#17672 Disable AWS SDK v1 warnings
  app/src/main/java/io/crate/bootstrap/CrateDB.java
Labels: ready-to-merge, cla-signed

#17673 Fix create shard lock retry logic
  docs/appendices/release-notes/5.10.4.rst
  docs/appendices/release-notes/5.9.13.rst
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/test/java/io/crate/integrationtests/ShardLockIT.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17674 Remove unused CTORs from ExecutorBuilders
  server/src/main/java/org/elasticsearch/threadpool/ExecutorBuilder.java
  server/src/main/java/org/elasticsearch/threadpool/FixedExecutorBuilder.java
  server/src/main/java/org/elasticsearch/threadpool/ScalingExecutorBuilder.java
Labels: ready-to-merge, cla-signed

#17680 Remove IndicesRequest implementation of the ClusterStateRequest.
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
  server/src/main/java/io/crate/replication/logical/metadata/Publication.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/ClusterStateRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/io/crate/integrationtests/PartitionedTableConcurrentIntegrationTest.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/ClusterStateRequestTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/state/TransportClusterStateActionTests.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
Labels: ready-to-merge, cla-signed

#17683 Cleanup code & minor fixes
  server/src/main/java/io/crate/execution/ddl/tables/TransportAlterTableAction.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/repository/LogicalReplicationRepository.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
Labels: ready-to-merge, cla-signed

#17686 Fix DropSubscriptionAction
  server/src/main/java/io/crate/replication/logical/action/DropSubscriptionAction.java
Labels: ready-to-merge, cla-signed

#17685 Remove IOException from CompressedXContent constructor
  server/src/main/java/io/crate/execution/ddl/Templates.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
  server/src/main/java/io/crate/metadata/cluster/DDLClusterStateHelpers.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/upgrade/IndexTemplateUpgrader.java
  server/src/main/java/io/crate/metadata/upgrade/MetadataIndexUpgrader.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MappingMetadata.java
  server/src/main/java/org/elasticsearch/common/compress/CompressedXContent.java
  server/src/main/java/org/elasticsearch/common/compress/Compressor.java
  server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java
  server/src/main/java/org/elasticsearch/common/compress/DeflateCompressor.java
Labels: ready-to-merge, cla-signed

#17684 Remove IndicesRequest impl from the CreateSnapshotRequest
  server/src/main/java/io/crate/metadata/PartitionName.java
  server/src/main/java/io/crate/planner/node/ddl/CreateSnapshotPlan.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
  server/src/test/java/io/crate/analyze/RestoreSnapshotAnalyzerTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequestTest.java
  server/src/test/java/org/elasticsearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/test/java/org/elasticsearch/snapshots/CorruptedBlobStoreRepositoryIT.java
Labels: ready-to-merge, cla-signed

#17679 Percentile function: Switch to MergingDigest with 200 compression as default
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/aggregation.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/TDigestState.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
Labels: ready-to-merge, cla-signed

#17698 Fix new column collection to not contain duplicates
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17702 Fix: create RelationMetadata from IndexMetadata
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/resources/repos/5.12.2_repo.zip
Labels: ready-to-merge, cla-signed
