Repository crate/crate, pull requests merged in 2025-10, with the labels that each got.

#18439 Update links in docs to follow permanent redirects
  docs/admin/ssl.rst
  docs/admin/system-information.rst
  docs/appendices/release-notes/2.0.0.rst
  docs/appendices/release-notes/2.1.0.rst
  docs/appendices/release-notes/3.0.0.rst
  docs/appendices/release-notes/4.0.0.rst
  docs/appendices/resiliency.rst
  docs/cli-tools.rst
  docs/concepts/clustering.rst
  docs/concepts/joins.rst
  docs/concepts/storage-consistency.rst
  docs/config/logging.rst
  docs/config/node.rst
  docs/config/session.rst
  docs/general/ddl/data-types.rst
  docs/general/ddl/replication.rst
  docs/interfaces/postgres.rst
  docs/sql/statements/copy-from.rst
  docs/sql/statements/create-repository.rst
  docs/sql/statements/deallocate.rst
Labels: ready-to-merge, cla-signed

#18441 mergify: Write the merge rules differently
  .mergify.yml
Labels: cla-signed

#18449 Fix mergify by modifying the queue rules
  .mergify.yml
Labels: ready-to-merge, cla-signed

#18369 Fix false omission of NULL-assigned sub-columns during replica recovery
  docs/appendices/release-notes/5.10.13.rst
  docs/appendices/release-notes/6.0.3.rst
  server/src/main/java/io/crate/execution/dml/IndexDocumentBuilder.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed, v/6.0, v/5.10, queued

#18446 Apply writePendingMessage write in callback change to portalSuspended case
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
Labels: ready-to-merge, cla-signed, v/6.0, v/5.10, queued

#18456 Upgrade Lucene to 9.12.3 to avoid mmap leaks
  docs/appendices/release-notes/5.10.13.rst
  pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#18466 Bump version to 6.0.3 in pom.xml files
  app/pom.xml
  benchmarks/pom.xml
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
Labels: cla-signed

#18469 Port a change entry for 5.10 only fix (https://github.com/crate/crate/pull/18456)
  docs/appendices/release-notes/5.10.13.rst
Labels: ready-to-merge, cla-signed, v/6.0, queued

#18470 Fix loss of orderBy/pageSizeHint in mixed cluster RoutedCollectPhase streaming
  server/src/main/java/io/crate/metadata/upgrade/NodeOperationsUpgrader.java
  server/src/test/java/io/crate/metadata/upgrade/NodeOperationsUpgraderTest.java
Labels: ready-to-merge, cla-signed, queued

#18465 Ensure UDFs don't cause metadata upgrade errors
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpgradeService.java
  server/src/main/java/org/elasticsearch/gateway/LocalAllocateDangledIndices.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataUpgradeServiceTest.java
Labels: cla-signed

#18467 Remove nullable annotation from StoredTable.versionCreated
  server/src/main/java/io/crate/metadata/blob/BlobTableInfo.java
  server/src/main/java/io/crate/metadata/information/InformationTablesTableInfo.java
  server/src/main/java/io/crate/metadata/table/StoredTable.java
  server/src/main/java/org/elasticsearch/cluster/metadata/RelationMetadata.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataUpgradeServiceTest.java
Labels: ready-to-merge, cla-signed, queued

#18475 Avoid capturing lambda's in TranslogWriter
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/ArrayOfObjectIndexer.java
  server/src/main/java/io/crate/execution/dml/IndexDocumentBuilder.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/execution/dml/SidecarTranslogWriter.java
  server/src/main/java/io/crate/execution/dml/TranslogWriter.java
  server/src/main/java/io/crate/execution/dml/XContentTranslogWriter.java
Labels: cla-signed

#18472 Bump forbiddenapis to 3.10
  pom.xml
Labels: ready-to-merge, cla-signed, queued

#18480 Add attach with prompt config to launch.json
  .vscode/launch.json
Labels: ready-to-merge, cla-signed

#18482 Add lightweight method `numDocs` to the index shard
  server/src/main/java/io/crate/expression/reference/sys/shard/ShardRowContext.java
  server/src/main/java/org/elasticsearch/index/engine/Engine.java
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
  server/src/test/java/io/crate/expression/reference/sys/SysShardsExpressionsTest.java
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: ready-to-merge, cla-signed, queued

#18486 Update github actions checkout and java to v5
  .github/workflows/codeql.yml
  .github/workflows/main.yml
  .github/workflows/nightly.yml
  .github/workflows/shellcheck.yml
Labels: ready-to-merge, cla-signed, queued
