Repository crate/crate, pull requests merged in 2025-02, with the labels that each got.

#17327 Upgrade to Lucene 10.1.0
  docs/appendices/release-notes/6.0.0.rst
  plugins/es-analysis-common/src/main/java/org/elasticsearch/analysis/common/StemmerTokenFilterFactory.java
  pom.xml
  server/src/main/java/io/crate/execution/engine/collect/collectors/DummyScorer.java
  server/src/main/java/io/crate/expression/operator/RegexpMatchOperator.java
  server/src/main/java/io/crate/expression/scalar/NumTermsPerDocQuery.java
  server/src/main/java/io/crate/lucene/BlendedTermQuery.java
  server/src/main/java/io/crate/lucene/GenericFunctionQuery.java
  server/src/main/java/io/crate/lucene/codec/CustomLucene90DocValuesProducer.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/common/lucene/Lucene.java
  server/src/main/java/org/elasticsearch/common/lucene/MinimumScoreCollector.java
  server/src/main/java/org/elasticsearch/common/lucene/search/MultiPhrasePrefixQuery.java
  server/src/main/java/org/elasticsearch/common/lucene/search/Queries.java
  server/src/main/java/org/elasticsearch/index/IndexModule.java
  server/src/main/java/org/elasticsearch/index/codec/CodecService.java
  server/src/main/java/org/elasticsearch/index/codec/CrateCodec.java
  server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java
  server/src/main/java/org/elasticsearch/index/engine/RecoverySourcePruneMergePolicy.java
  server/src/main/java/org/elasticsearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/elasticsearch/index/query/RegexpFlag.java
  server/src/main/java/org/elasticsearch/index/search/MatchQuery.java
  server/src/main/java/org/elasticsearch/index/shard/ShardSplittingQuery.java
  server/src/main/java/org/elasticsearch/index/store/Store.java
  server/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/elasticsearch/search/profile/query/ProfileScorer.java
  server/src/main/java/org/elasticsearch/search/profile/query/ProfileWeight.java
  server/src/test/java/io/crate/execution/engine/collect/collectors/OptimizeQueryForSearchAfterTest.java
  server/src/test/java/io/crate/lucene/BitStringEqQueryTest.java
  server/src/test/java/io/crate/lucene/BooleanEqQueryTest.java
  server/src/test/java/io/crate/lucene/CharacterEqQueryTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/DoubleEqQueryTest.java
  server/src/test/java/io/crate/lucene/FloatEqQueryTest.java
  server/src/test/java/io/crate/lucene/IntEqQueryTest.java
  server/src/test/java/io/crate/lucene/IpEqQueryTest.java
  server/src/test/java/io/crate/lucene/LikeQueryBuilderTest.java
  server/src/test/java/io/crate/lucene/StringEqQueryTest.java
  server/src/test/java/io/crate/lucene/WithinQueryBuilderTest.java
  server/src/test/java/org/elasticsearch/index/IndexServiceTests.java
  server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/elasticsearch/index/store/FsDirectoryFactoryTests.java
  server/src/testFixtures/java/io/crate/lucene/PatchedAssertingLeafReader.java
  server/src/testFixtures/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/CorruptionUtils.java
  server/src/testFixtures/java/org/elasticsearch/test/engine/ThrowingLeafReaderWrapper.java
Labels: ready-to-merge, cla-signed

#17338 Add native access/vector flags to jvm settings in debug config
  .idea/runConfigurations/CrateDB.xml
  .vscode/launch.json
Labels: ready-to-merge, cla-signed

#17342 Remove lock objects from UpsertResultCollectors
  server/src/main/java/io/crate/execution/engine/indexing/UpsertResultCollectors.java
Labels: ready-to-merge, cla-signed

#17343 Fix SubQueryResults.merge(), result values of both sides must be used
  docs/appendices/release-notes/5.10.1.rst
  server/src/main/java/io/crate/planner/operators/SubQueryResults.java
  server/src/test/java/io/crate/integrationtests/CorrelatedSubqueryITest.java
  server/src/test/java/io/crate/planner/operators/SubQueryResultsTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17346 Add storage compat change to release notes
  docs/admin/system-information.rst
  docs/appendices/release-notes/6.0.0.rst
Labels: ready-to-merge, cla-signed

#17345 Add BWC code to blob tables resolution
  server/src/main/java/io/crate/metadata/blob/BlobTableInfoFactory.java
Labels: ready-to-merge, cla-signed

#17349 Fix BWC handling in MetadataDiff for schemas
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge, cla-signed

#17351 Deprecate usage of _version
  docs/appendices/release-notes/6.0.0.rst
  docs/general/ddl/system-columns.rst
  server/src/main/java/io/crate/analyze/relations/DocTableRelation.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/testFixtures/java/org/elasticsearch/test/ESTestCase.java
Labels: ready-to-merge, cla-signed

#17308 Return existing SharedShardContext if a FetchTask tries to create a new one with same shardId/readerId
  server/src/main/java/io/crate/execution/engine/fetch/FetchTask.java
  server/src/main/java/io/crate/execution/jobs/SharedShardContexts.java
  server/src/test/java/io/crate/execution/jobs/SharedShardContextsTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17359 Fix transport handshake, handshake response sent wrong version
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
  server/src/main/java/org/elasticsearch/transport/TransportHandshaker.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
Labels: ready-to-merge, cla-signed, v/5.10

#17365 Fix eval projection to support fewer outputs than its source
  docs/appendices/release-notes/5.10.1.rst
  server/src/main/java/io/crate/execution/dsl/projection/EvalProjection.java
  server/src/test/java/io/crate/execution/dsl/projection/EvalProjectionTest.java
  server/src/test/java/io/crate/planner/UnionPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17370 Add missing change entries for 5.9.10
  docs/appendices/release-notes/5.9.10.rst
Labels: ready-to-merge, cla-signed, v/5.10

#17371 Fix MIN/MAX for NUMERIC values
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/io/crate/execution/engine/aggregation/impl/Aggregations.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericMaxAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericMinAggregation.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/MinimumAggregationTest.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17382 Use default min/max implementations for numeric
  server/src/main/java/io/crate/execution/engine/aggregation/impl/Aggregations.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/MinimumAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericMaxAggregation.java
  server/src/main/java/io/crate/execution/engine/aggregation/impl/NumericMinAggregation.java
  server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java
Labels: ready-to-merge, cla-signed

#17386 Add default traversal for join, union and QS to AnalyzedRelationVisitor
  server/src/main/java/io/crate/analyze/RelationNames.java
  server/src/main/java/io/crate/analyze/Relations.java
  server/src/main/java/io/crate/analyze/relations/AnalyzedRelationVisitor.java
  server/src/main/java/io/crate/auth/AccessControlImpl.java
  server/src/main/java/io/crate/execution/dsl/projection/builder/SplitPointsBuilder.java
Labels: cla-signed

#17388 Avoid client node roundtrip during shards resize
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/TransportResizeAction.java
Labels: ready-to-merge, cla-signed

#17389 docs: Replace link for Google Service Account
  docs/sql/statements/create-repository.rst
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17392 Removed unused docvalues path for some type indexer
  server/src/main/java/io/crate/execution/dml/BitStringIndexer.java
  server/src/main/java/io/crate/execution/dml/BooleanIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoPointIndexer.java
  server/src/main/java/io/crate/execution/dml/GeoShapeIndexer.java
  server/src/main/java/io/crate/execution/dml/IpIndexer.java
Labels: ready-to-merge, cla-signed

#17369 TranslogIndexer must add dedicated fulltext indices to sub-columns
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.10.rst
  libs/shared/src/main/java/io/crate/common/collections/Lists.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17400 Fix Nullability for array_position
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/io/crate/expression/scalar/ArrayPositionFunction.java
  server/src/test/java/io/crate/lucene/ThreeValuedLogicQueryBuilderTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17397 Remove TransportCreateIndexAction
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/io/crate/planner/node/ddl/CreateBlobTablePlan.java
  server/src/main/java/org/elasticsearch/action/ActionModule.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexResponse.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeResponse.java
  server/src/main/java/org/elasticsearch/client/IndicesAdminClient.java
  server/src/main/java/org/elasticsearch/client/support/AbstractClient.java
  server/src/test/java/io/crate/integrationtests/DanglingIndicesIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/GCDanglingArtifactsITest.java
  server/src/test/java/io/crate/integrationtests/ResizeShardsITest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequestTest.java
  server/src/testFixtures/java/org/elasticsearch/test/IntegTestCase.java
  server/src/testFixtures/java/org/elasticsearch/test/hamcrest/ElasticsearchAssertions.java
Labels: cla-signed

#17405 Fix restore resolve indices logic to not include all templates
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/integrationtests/SnapshotRestoreIntegrationTest.java
  server/src/test/java/org/elasticsearch/snapshots/RestoreServiceTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17407 Add support for the array_overlap scalar and related && operator
  docs/appendices/release-notes/6.0.0.rst
  docs/general/builtins/array-comparisons.rst
  docs/general/builtins/scalar-functions.rst
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseLexer.g4
  libs/sql-parser/src/main/antlr/io/crate/sql/parser/antlr/SqlBaseParser.g4
  libs/sql-parser/src/main/java/io/crate/sql/parser/AstBuilder.java
  libs/sql-parser/src/test/java/io/crate/sql/parser/TestStatementBuilder.java
  server/src/main/java/io/crate/expression/scalar/ArrayOverlapFunction.java
  server/src/main/java/io/crate/expression/scalar/ScalarFunctions.java
  server/src/test/java/io/crate/expression/scalar/ArrayOverlapFunctionTest.java
Labels: ready-to-merge, cla-signed

#17413 Fix wrong join results for CASE in join condition
  docs/appendices/release-notes/5.10.1.rst
  docs/general/dql/joins.rst
  server/src/main/java/io/crate/planner/operators/EquiJoinDetector.java
  server/src/test/java/io/crate/planner/operators/EquiJoinDetectorTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17411 Fix thread safety of the translog indexer, remove shared state
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17417 Remove dropped column filter from ColumnFieldVisitor
  server/src/main/java/io/crate/expression/reference/doc/lucene/ColumnFieldVisitor.java
Labels: ready-to-merge, cla-signed

#17421 Release 5.9.10
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17412 Fix cross-join elimination
  server/src/main/java/io/crate/planner/operators/JoinPlan.java
  server/src/main/java/io/crate/planner/optimizer/joinorder/JoinGraph.java
  server/src/main/java/io/crate/planner/optimizer/rule/EliminateCrossJoin.java
  server/src/main/java/io/crate/planner/optimizer/rule/MoveConstantJoinConditionsBeneathJoin.java
  server/src/test/java/io/crate/planner/optimizer/rule/EliminateCrossJoinTest.java
Labels: ready-to-merge, cla-signed

#17425 Increase timeout for the resize action
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/test/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequestTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17426 Fix source matching of RewriteFilterOnCrossJoinToInnerJoin
  server/src/main/java/io/crate/planner/optimizer/rule/RewriteFilterOnCrossJoinToInnerJoin.java
  server/src/test/java/io/crate/planner/optimizer/rule/RewriteFilterOnCrossJoinToInnerJoinTest.java
Labels: ready-to-merge, cla-signed

#17430 Reflect release 5.9.10
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17432 Release 5.10.1
  docs/appendices/release-notes/5.10.1.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17434 Mute occasionally failing ShuffleForcedMergePolicy test
  server/src/test/java/io/crate/lucene/index/TestShuffleForcedMergePolicyTests.java
Labels: ready-to-merge, cla-signed

#17437 Fix inbound handler handshake tests, remove current version dep
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
Labels: ready-to-merge, cla-signed, v/5.10

#17440 Reflect 5.9.10 on 5.10
  docs/appendices/release-notes/5.9.10.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17435 Bump version to 5.10.2-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.2.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17436 Replace deprecated Regxp.Kind.REGEXP_DEPRECATED_COMPLEMENT
  server/src/main/java/io/crate/expression/operator/any/AnyNotLikeOperator.java
  server/src/main/java/org/elasticsearch/index/query/RegexpFlag.java
Labels: ready-to-merge, cla-signed

#17444 Adjust inbound handler handshake test to be correct with its versions
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
Labels: ready-to-merge, cla-signed

#17443 Double timeout and ack based on default values
  server/src/main/java/org/elasticsearch/action/admin/indices/shrink/ResizeRequest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17446 The root endpoint JSON response now reflects the actual HTTP status code
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/protocols/http/MainAndStaticFileHandler.java
Labels: ready-to-merge, cla-signed, v/5.10

#17448 Fix flaky testShrinkShardsOfTable
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
Labels: cla-signed

#17424 Encapsulate dropped cols skipping for SourceParser in lookupName function
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/ColumnFieldVisitor.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/SourceParser.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/expression/reference/doc/lucene/SourceParserTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
Labels: ready-to-merge, cla-signed

#17451 Update netty to 4.1.118
  pom.xml
Labels: ready-to-merge, cla-signed

#17127 Add RelationMetadata.Table
  server/src/main/java/io/crate/execution/ddl/SwapRelationsOperation.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportCreateTableAction.java
  server/src/main/java/io/crate/fdw/ForeignTable.java
  server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/DropTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/io/crate/metadata/cluster/RenameTableClusterStateExecutor.java
  server/src/main/java/io/crate/metadata/cluster/SwapAndDropIndexExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/RelationMetadata.java
  server/src/test/java/io/crate/execution/ddl/tables/DropColumnTaskTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/PgCatalogITest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/metadata/doc/DocSchemaInfoTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoTest.java
  server/src/testFixtures/java/io/crate/operation/aggregation/AggregationTestCase.java
  server/src/testFixtures/java/io/crate/testing/SQLExecutor.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
Labels: ready-to-merge, cla-signed

#17450 Remove no longer needed index_shrink settings
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
Labels: ready-to-merge, cla-signed

#17455 Reduce MockNode constructors
  app/src/main/java/org/elasticsearch/bootstrap/BootstrapProxy.java
  app/src/test/java/io/crate/node/NodeSettingsTest.java
  benchmarks/src/main/java/io/crate/analyze/PreExecutionBenchmark.java
  benchmarks/src/main/java/io/crate/execution/dml/IndexerBenchmark.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/org/elasticsearch/indices/IndicesServiceCloseTests.java
  server/src/testFixtures/java/org/elasticsearch/node/MockNode.java
  server/src/testFixtures/java/org/elasticsearch/test/TestCluster.java
Labels: ready-to-merge, cla-signed

#17453 Implement field retrieval for JoinRelation
  server/src/main/java/io/crate/analyze/JoinRelation.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/planner/operators/JoinTest.java
Labels: ready-to-merge, cla-signed

#17459 Re-enable indexer test for dynamic nested array creation
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
Labels: ready-to-merge, cla-signed

#17463 Clarify changes entry for `/` status property change
  docs/appendices/release-notes/5.10.2.rst
Labels: ready-to-merge, cla-signed, v/5.10

#17466 Start UDCService directly in node instead of via plugin
  app/src/main/java/org/elasticsearch/bootstrap/BootstrapProxy.java
  server/src/main/java/io/crate/udc/plugin/UDCPlugin.java
  server/src/main/java/io/crate/udc/service/UDCService.java
  server/src/main/java/org/elasticsearch/node/Node.java
Labels: ready-to-merge, cla-signed

#17139 Guess inner types for objects and unify list/union cast semantics
  server/src/main/java/io/crate/analyze/TableElementsAnalyzer.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/execution/dml/ArrayIndexer.java
  server/src/main/java/io/crate/execution/dml/ObjectIndexer.java
  server/src/main/java/io/crate/expression/symbol/Literal.java
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/test/java/io/crate/DataTypeTest.java
  server/src/test/java/io/crate/analyze/UpdateAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/geo/WithinFunctionTest.java
  server/src/test/java/io/crate/integrationtests/GeoShapeIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
  server/src/test/java/io/crate/integrationtests/TransportSQLActionTest.java
  server/src/test/java/io/crate/integrationtests/ViewsITest.java
  server/src/test/java/io/crate/types/TypeConversionTest.java
Labels: ready-to-merge, cla-signed

#17468 Remove redundant properties from RestoreSnapshotRequest
  docs/sql/statements/restore-snapshot.rst
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTest.java
Labels: ready-to-merge, cla-signed

#17471 tests: Cleanup RegexpIntegrationTest
  server/src/test/java/io/crate/integrationtests/RegexpIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17469 Change logical replication restore to also use TableOrPartition
  server/src/main/java/io/crate/planner/node/ddl/RestoreSnapshotPlan.java
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/io/crate/replication/logical/MetadataTracker.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TableOrPartition.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/io/crate/replication/logical/MetadataTrackerTest.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTest.java
  server/src/test/java/org/elasticsearch/snapshots/RestoreServiceTest.java
Labels: ready-to-merge, cla-signed

#17470 Fix filter pushdown for views when filtered column is aliased
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/planner/optimizer/rule/MoveFilterBeneathProjectSet.java
  server/src/test/java/io/crate/planner/ViewPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17474 Remove unused indexSettings from internal RestoreRequest
  server/src/main/java/io/crate/replication/logical/LogicalReplicationService.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/restore/TransportRestoreSnapshotAction.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/snapshots/RestoreServiceTest.java
Labels: cla-signed

#17465 Fix for unremoved empty partitions when DELETE condition contained nondeterministic functions
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/analyze/where/WhereClauseAnalyzer.java
  server/src/test/java/io/crate/analyze/where/WhereClauseAnalyzerTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17472 Fix `~` operator behavior regarding complement
  server/src/main/java/io/crate/expression/operator/RegexpMatchOperator.java
  server/src/test/java/io/crate/expression/operator/RegexpMatchOperatorTest.java
  server/src/test/java/io/crate/integrationtests/RegexpIntegrationTest.java
Labels: ready-to-merge, cla-signed

#17480 Fix NPE due to JobContext.stmt incorrectly set to null
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/session/Session.java
  server/src/test/java/io/crate/session/SessionTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17488 Allow comparing a non-boolean column to a boolean literal in WHERE clause
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/planner/optimizer/symbol/rule/SwapCastsInComparisonOperators.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17495 Add EqualityProxy (eq=true) for a standalone boolean column
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/io/crate/analyze/where/EqualityExtractor.java
  server/src/test/java/io/crate/analyze/where/EqualityExtractorTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17493 Avoid byte copy operations to decompress data for snapshots
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/org/elasticsearch/repositories/blobstore/ChecksumBlobStoreFormat.java
Labels: ready-to-merge, cla-signed, v/5.10

#17502 Reflect 5.8.6 5.9.10 releases
  docs/appendices/release-notes/5.8.7.rst
  docs/appendices/release-notes/5.9.11.rst
  docs/appendices/release-notes/index.rst
Labels: ready-to-merge, cla-signed

#17492 Ensure UDFs are available for generated col validations as part of node upgrade
  docs/appendices/release-notes/5.10.2.rst
  docs/appendices/release-notes/5.8.7.rst
  docs/appendices/release-notes/5.9.11.rst
  server/src/main/java/io/crate/metadata/cluster/OpenTableClusterStateTaskExecutor.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeService.java
  server/src/main/java/org/elasticsearch/gateway/GatewayMetaState.java
  server/src/main/java/org/elasticsearch/gateway/LocalAllocateDangledIndices.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexUpgradeServiceTest.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStateTests.java
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9, v/5.10

#17498 Bump version to 5.8.7
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.8.7.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17516 Run linkcheck/vale only on doc changes
  .github/workflows/docs.yml
  .github/workflows/skip-docs.yml
Labels: ready-to-merge, cla-signed

#17519 Don't treat warnings as errors during sphinx build
  blackbox/bin/sphinx
Labels: cla-signed

#17514 Restore RelationMetadata.Table from snapshots and use indexUUIDs to resolve indices
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/snapshots/RestoreService.java
Labels: ready-to-merge, cla-signed

#17517 Deprecate IndexNameExpressionResolver methods
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java
Labels: cla-signed

#17530 Release 5.8.7
  docs/appendices/release-notes/5.8.7.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17531 Release 5.9.11
  docs/appendices/release-notes/5.9.11.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17529 Try to use optimized subscript function with concrete return type
  extensions/lang-js/src/test/java/io/crate/operation/language/JavaScriptUDFIntegrationTest.java
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/expression/scalar/SubscriptFunction.java
  server/src/main/java/io/crate/expression/scalar/SubscriptObjectFunction.java
  server/src/main/java/io/crate/metadata/Scalar.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/main/java/io/crate/types/ObjectType.java
  server/src/main/java/io/crate/types/UndefinedType.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/expression/scalar/SubscriptFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/SubscriptObjectFunctionTest.java
  server/src/test/java/io/crate/expression/scalar/systeminformation/PgTypeofFunctionTest.java
  server/src/test/java/io/crate/integrationtests/CreateTableAsIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/ScalarIntegrationTest.java
  server/src/test/java/io/crate/types/DataTypesTest.java
  server/src/test/java/io/crate/types/ObjectTypeTest.java
  server/src/testFixtures/java/io/crate/expression/scalar/ScalarTestCase.java
  server/src/testFixtures/java/io/crate/testing/Asserts.java
  server/src/testFixtures/java/io/crate/testing/SymbolAssert.java
Labels: ready-to-merge, cla-signed

#17537 Bump version to 5.9.12-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.12.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17540 Release 5.10.2
  docs/appendices/release-notes/5.10.2.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17544 Reflect 5.10.2 release
  docs/appendices/release-notes/5.10.2.rst
  docs/appendices/release-notes/5.10.3.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17542 Bump version to 5.10.3-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.3.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed
