Repository crate/crate, pull requests merged in 2025-01, with the labels that each got.

#17182 Fix flaky rest bulk error test
  server/src/test/java/io/crate/integrationtests/RestSQLActionIntegrationTest.java
Labels: ready-to-merge

#17178 Fix `alter` from falsely updating table version created setting to latest
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java
  server/src/test/java/io/crate/metadata/cluster/AlterTableClusterStateExecutorTest.java
Labels: ready-to-merge, v/5.9

#17192 Update netty to 4.1.116
  pom.xml
Labels: ready-to-merge

#17193 Add docs for row type
  docs/general/ddl/data-types.rst
  docs/interfaces/http.rst
Labels: ready-to-merge

#17190 Set new partitions' version created setting to the smallest non-client node version
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsAction.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge

#17213 Fix flaky percentile test_custom_compression_setting_is_used
  server/src/test/java/io/crate/execution/engine/aggregation/impl/PercentileAggregationTest.java
Labels: cla-signed

#17205 Do not ignore uppercases in function names in a view's query body
  docs/appendices/release-notes/5.9.7.rst
  libs/sql-parser/src/main/java/io/crate/sql/ExpressionFormatter.java
  libs/sql-parser/src/main/java/io/crate/sql/Identifiers.java
  libs/sql-parser/src/test/java/io/crate/sql/IdentifiersTest.java
  server/src/test/java/io/crate/analyze/CreateViewAnalyzerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17220 Forward port numeric/double/BigDecimal class-cast-error changes entry
  docs/appendices/release-notes/5.9.7.rst
Labels: cla-signed

#17222 TranslogIndexer should use shard created version
  server/src/main/java/io/crate/execution/dml/TranslogIndexer.java
  server/src/main/java/org/elasticsearch/index/IndexService.java
  server/src/test/java/io/crate/execution/dml/IndexerTest.java
  server/src/test/java/io/crate/execution/dml/TranslogIndexerTest.java
  server/src/testFixtures/java/org/elasticsearch/index/engine/TranslogHandler.java
  server/src/testFixtures/java/org/elasticsearch/index/shard/IndexShardTestCase.java
Labels: ready-to-merge, cla-signed

#17225 Set new partitions' version created to the smallest non-client node version
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreatePartitionsActionTest.java
Labels: ready-to-merge

#17214 Add policy to column_details in info_schema.columns
  docs/appendices/release-notes/5.10.0.rst
  docs/general/information-schema.rst
  server/src/main/java/io/crate/metadata/information/InformationColumnsTableInfo.java
  server/src/test/java/io/crate/integrationtests/InformationSchemaTest.java
  server/src/test/java/io/crate/integrationtests/PrivilegesIntegrationTest.java
Labels: cla-signed

#17228 Mitigate wrong template createdVersion by inferring it from partitions
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/io/crate/analyze/AlterTableDropColumnAnalyzer.java
  server/src/main/java/io/crate/analyze/AlterTableRenameColumnAnalyzer.java
  server/src/main/java/io/crate/execution/ddl/tables/TransportAddColumnAction.java
  server/src/main/java/io/crate/execution/dml/Indexer.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfoFactory.java
  server/src/test/java/io/crate/analyze/AlterTableRenameColumnAnalyzerTest.java
  server/src/test/java/io/crate/metadata/doc/DocTableInfoFactoryTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17231 Fix pruning of CorrelatedJoin in combination with Eval
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/io/crate/planner/operators/CorrelatedJoin.java
  server/src/test/java/io/crate/planner/CorrelatedJoinPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17233 Add release entry for #17190
  docs/appendices/release-notes/5.9.7.rst
Labels: ready-to-merge, cla-signed, v/5.9

#17226 Fix distributed execution of window functions with partition on a sub-column
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/io/crate/planner/operators/WindowAgg.java
  server/src/test/java/io/crate/planner/operators/WindowAggTest.java
Labels: ready-to-merge, cla-signed, v/5.9

#17237 Docs: Fix `COPY FROM` Azure example
  docs/sql/statements/copy-from.rst
Labels: ready-to-merge, docs, cla-signed, v/5.9

#17240 Fix link to ISO ISO 19107:2003 used in `GEO` search docs
  docs/general/dql/geo.rst
Labels: ready-to-merge, cla-signed, v/5.9

#17230 Suspend row consumer once netty outbound buffers are full
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/io/crate/protocols/postgres/Messages.java
  server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java
  server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java
  server/src/main/java/io/crate/protocols/postgres/RowCountReceiver.java
  server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java
  server/src/main/java/io/crate/rest/action/RestResultSetReceiver.java
  server/src/main/java/io/crate/rest/action/RestRowCountReceiver.java
  server/src/main/java/io/crate/session/BaseResultReceiver.java
  server/src/main/java/io/crate/session/CollectingResultReceiver.java
  server/src/main/java/io/crate/session/ResultReceiver.java
  server/src/main/java/io/crate/session/RetryOnFailureResultReceiver.java
  server/src/main/java/io/crate/session/RowConsumerToResultReceiver.java
  server/src/test/java/io/crate/protocols/postgres/BatchPortalTest.java
  server/src/test/java/io/crate/protocols/postgres/ResultSetReceiverTest.java
  server/src/test/java/io/crate/session/RowConsumerToResultReceiverTest.java
  server/src/testFixtures/java/io/crate/testing/SQLTransportExecutor.java
Labels: ready-to-merge, cla-signed, v/5.9

#17239 Release 5.9.7
  docs/appendices/release-notes/5.9.7.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17242 Allow vector module and native access in surefire tests
  pom.xml
Labels: cla-signed

#17245 Bump version to 5.9.8-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.8.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17250 Release 5.9.8
  docs/appendices/release-notes/5.9.8.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17252 Bump version to 5.9.9-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.9.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17254 Release 5.10.0
  docs/appendices/release-notes/5.10.0.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17256 Bump version to 5.10.1-SNAPSHOT
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed

#17255 Bump version to 6.0.0-SNAPSHOT
  .mergify.yml
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/6.0.0.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
  server/src/test/java/io/crate/integrationtests/TablesNeedUpgradeSysCheckTest.java
  server/src/test/java/org/elasticsearch/VersionTest.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/elasticsearch/env/NodeMetadataTests.java
  server/src/test/java/org/elasticsearch/transport/InboundDecoderTests.java
Labels: ready-to-merge, cla-signed

#17244 Create RoutineInfos on-demand in InformationSchemaIterables
  server/src/main/java/io/crate/execution/engine/collect/sources/InformationSchemaIterables.java
  server/src/main/java/io/crate/metadata/RoutineInfos.java
Labels: ready-to-merge, cla-signed

#17221 Allow dynamic addition of nested array columns
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/execution/dml/DynamicIndexer.java
  server/src/main/java/io/crate/types/DataTypes.java
  server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java
  server/src/test/java/io/crate/integrationtests/DynamicMappingUpdateITest.java
  server/src/test/java/io/crate/integrationtests/SQLTypeMappingTest.java
Labels: ready-to-merge, cla-signed

#17259 Update maven plugins to their latest version
  pom.xml
Labels: ready-to-merge, cla-signed

#17257 Remove unused code from NotPredicate
  server/src/main/java/io/crate/expression/predicate/NotPredicate.java
Labels: ready-to-merge, cla-signed

#17260 Use shard created version in ColumnFieldVisitor
  server/src/main/java/io/crate/expression/reference/doc/lucene/ColumnFieldVisitor.java
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
Labels: ready-to-merge, cla-signed

#16502 Generate Lucene queries for AllEqOperator
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/expression/operator/all/AllEqOperator.java
  server/src/main/java/io/crate/expression/operator/any/AnyNeqOperator.java
  server/src/test/java/io/crate/expression/operator/AllOperatorTest.java
  server/src/test/java/io/crate/lucene/CommonQueryBuilderTest.java
Labels: ready-to-merge, cla-signed

#17268 Fix NPE in StoredRowLookup when _raw was requested before doc lookup
  server/src/main/java/io/crate/expression/reference/doc/lucene/StoredRowLookup.java
  server/src/test/java/io/crate/execution/dml/MixedVersionStorageTest.java
  server/src/testFixtures/java/io/crate/testing/IndexEnv.java
  server/src/testFixtures/java/io/crate/testing/QueryTester.java
Labels: ready-to-merge, cla-signed, v/5.10

#17275 Add support for lowercase patterns to the to_char scalar function
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/expression/scalar/formatting/DateTimeFormatter.java
  server/src/test/java/io/crate/expression/scalar/formatting/ToCharFunctionTest.java
Labels: ready-to-merge, cla-signed

#17280 Bump bundled JDK to 23.0.2
  pom.xml
Labels: ready-to-merge, cla-signed, v/5.10

#17281 Fix handling of unallocated shards during number_of_shards resize
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.9.rst
  server/src/main/java/io/crate/execution/ddl/tables/AlterTableClient.java
  server/src/main/java/io/crate/execution/support/ChainableAction.java
  server/src/main/java/io/crate/execution/support/ChainableActions.java
  server/src/main/java/io/crate/metadata/cluster/SwapAndDropIndexExecutor.java
  server/src/main/java/io/crate/metadata/doc/DocTableInfo.java
  server/src/test/java/io/crate/execution/support/ChainableActionsTest.java
  server/src/test/java/io/crate/integrationtests/AlterTableIntegrationTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17286 Allow precision=scale in NumericType; Fix avg aggregation errors
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.9.rst
  docs/general/ddl/data-types.rst
  server/src/main/java/io/crate/types/NumericType.java
  server/src/test/java/io/crate/execution/engine/aggregation/impl/average/numeric/NumericAverageStateTest.java
  server/src/test/java/io/crate/types/NumericTypeTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17264 Fixes a handshake issue between different major versions
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/6.0.0.rst
  server/src/main/java/io/crate/protocols/postgres/PgClient.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/transport/InboundDecoder.java
  server/src/main/java/org/elasticsearch/transport/OutboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TcpTransportChannel.java
  server/src/main/java/org/elasticsearch/transport/TransportHandshaker.java
  server/src/test/java/org/elasticsearch/VersionTest.java
  server/src/test/java/org/elasticsearch/transport/InboundDecoderTests.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/InboundPipelineTests.java
  server/src/test/java/org/elasticsearch/transport/OutboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportActionProxyTests.java
  server/src/test/java/org/elasticsearch/transport/TransportHandshakerTests.java
Labels: ready-to-merge, cla-signed, v/5.10

#17304 Remove v/5.6 from mergify backport rules
  .mergify.yml
Labels: ready-to-merge, cla-signed

#17298 Fix InputColumns resolution of the parametrized outputs in the Fetch operator
  docs/appendices/release-notes/5.10.1.rst
  docs/appendices/release-notes/5.9.9.rst
  server/src/main/java/io/crate/planner/operators/Fetch.java
  server/src/test/java/io/crate/planner/operators/LogicalPlannerTest.java
Labels: ready-to-merge, cla-signed, v/5.9, v/5.10

#17292 Do not throw missing key errors for object types with missing inner types
  docs/appendices/release-notes/5.10.1.rst
  server/src/main/java/io/crate/analyze/expressions/ExpressionAnalyzer.java
  server/src/main/java/io/crate/types/TypeSignature.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
Labels: ready-to-merge, cla-signed, v/5.10

#17309 Adds details to the repository rate limiter settings
  docs/sql/statements/create-repository.rst
Labels: ready-to-merge, v/5.8, cla-signed, v/5.9, v/5.10

#17316 Fix link to HLL++ publication, use archive, original starts failing
  docs/general/builtins/aggregation.rst
Labels: ready-to-merge, v/5.7, v/5.8, cla-signed, v/5.9, v/5.10

#17318 Fix BWC streaming of the Metadata
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
Labels: ready-to-merge, cla-signed

#17325 Release 5.7.6
  docs/appendices/release-notes/5.7.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17328 Release 5.8.6
  docs/appendices/release-notes/5.8.6.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17329 Reflect 5.7.6
  docs/appendices/release-notes/5.7.6.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17330 Release 5.9.9
  docs/appendices/release-notes/5.9.9.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17331 Bump version to 5.9.10
  app/pom.xml
  benchmarks/pom.xml
  docs/admin/system-information.rst
  docs/appendices/release-notes/5.9.10.rst
  docs/appendices/release-notes/index.rst
  extensions/functions/pom.xml
  extensions/jmx-monitoring/pom.xml
  extensions/lang-js/pom.xml
  jlink-jdk/pom.xml
  libs/azure-testing/pom.xml
  libs/cli/pom.xml
  libs/dex/pom.xml
  libs/es-x-content/pom.xml
  libs/guice/pom.xml
  libs/pgwire/pom.xml
  libs/shared/pom.xml
  libs/sql-parser/pom.xml
  plugins/cr8-copy-s3/pom.xml
  plugins/crate-copy-azure/pom.xml
  plugins/dns-discovery/pom.xml
  plugins/es-analysis-common/pom.xml
  plugins/es-analysis-phonetic/pom.xml
  plugins/es-discovery-ec2/pom.xml
  plugins/es-repository-azure/pom.xml
  plugins/es-repository-s3/pom.xml
  plugins/es-repository-url/pom.xml
  plugins/repository-gcs/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17332 Reflect 5.7.6 and 5.8.6 releases
  docs/appendices/release-notes/5.7.6.rst
  docs/appendices/release-notes/5.8.6.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge

#17333 Reflect 5.7.6, 5.8.6, 5.9.9 releases
  docs/appendices/release-notes/5.7.6.rst
  docs/appendices/release-notes/5.8.6.rst
  docs/appendices/release-notes/5.9.10.rst
  docs/appendices/release-notes/5.9.9.rst
  docs/appendices/release-notes/index.rst
  server/src/main/java/org/elasticsearch/Version.java
Labels: ready-to-merge, cla-signed, v/5.10

#17133 Support subscript access on unknown sub-column of virtual table
  server/src/main/java/io/crate/analyze/relations/AliasedAnalyzedRelation.java
  server/src/main/java/io/crate/analyze/relations/AnalyzedView.java
  server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java
  server/src/test/java/io/crate/integrationtests/ObjectColumnTest.java
Labels: ready-to-merge, cla-signed

#17336 Fix persistence of metadata's schemas
  server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java
  server/src/test/java/io/crate/integrationtests/BlobTableIntegrationTest.java
Labels: ready-to-merge, cla-signed
